In [1]:
import sqlite3
import pandas as pd
from datetime import datetime

conn = sqlite3.connect("student_course.db")
cursor = conn.cursor()

In [2]:
# Xóa bảng cũ nếu có
cursor.execute("DROP TABLE IF EXISTS student")
cursor.execute("DROP TABLE IF EXISTS course")

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INTEGER PRIMARY KEY,
    course_name TEXT
)
""")

# Tạo bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# Thêm dữ liệu course
courses = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]

cursor.executemany("INSERT INTO course VALUES (?, ?)", courses)

# Thêm dữ liệu student
students = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]

cursor.executemany("INSERT INTO student VALUES (?, ?, ?, ?, ?)", students)

conn.commit()
print("Đã tạo xong dữ liệu")

Đã tạo xong dữ liệu

In [3]:
print("Bảng student:")
display(pd.read_sql("SELECT * FROM student", conn))

print("Bảng course:")
display(pd.read_sql("SELECT * FROM course", conn))

Bảng student:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

Bảng course:

   id course_name
0  12   Giai tich
1  26     Tin hoc
2  34    Thong ke

In [4]:
query = """
SELECT *
FROM student s
CROSS JOIN course c
"""
display(pd.read_sql(query, conn))

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

In [5]:
query = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c
ON s.course_id = c.id
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

In [6]:
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [7]:
query = """
SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         NaN               None      None        NaN    NaN     Tin hoc
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke

In [8]:
query = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM course c
LEFT JOIN student s ON s.course_id = c.id
"""
display(pd.read_sql(query, conn))

    student_id               name     class  course_id  score course_name
0          NaN               None      None        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9        None
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2        None
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0        None
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5        None
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2        None
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [9]:
# Cập nhật các course_id bị thiếu
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
""")

# Xóa các bản ghi có course_id không tồn tại trong bảng course
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

conn.commit()

display(pd.read_sql("SELECT * FROM student", conn))

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

In [10]:
query = """
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score), 2) AS avg_score
FROM student
GROUP BY class
"""
display(pd.read_sql(query, conn))

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

In [11]:
query = """
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(s.score), 2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
display(pd.read_sql(query, conn))

  course_name  total_students  avg_score
0   Giai tich               1       6.70
1    Thong ke               2       9.20
2     Tin hoc               3       7.37

In [12]:
query = """
SELECT c.course_name,
       ROUND(AVG(s.score), 2) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6.0 AND AVG(s.score) <= 8.9 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
display(pd.read_sql(query, conn))

  course_name  avg_score classification
0   Giai tich       6.70            Tot
1    Thong ke       9.20       Xuat sac
2     Tin hoc       7.37            Tot

In [13]:
query = """
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS ranking
FROM student
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score  ranking
0           2       Tran Thi Lan   Kinh Te         34    9.2        1
1           7      Bui Tien Dung   Kinh Te         34    9.2        1
2           3       Pham Van Nam  Toan Tin         26    7.9        3
3           9     Duong Huu Phuc   Kinh Te         26    7.2        4
4          10       Cao Thi Hanh  May Tinh         26    7.0        5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7        6

In [14]:
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score DESC) AS ranking
    FROM student
)
WHERE ranking <= 3
"""
display(pd.read_sql(query, conn))

   student_id           name     class  course_id  score  ranking
0           2   Tran Thi Lan   Kinh Te         34    9.2        1
1           7  Bui Tien Dung   Kinh Te         34    9.2        1
2           3   Pham Van Nam  Toan Tin         26    7.9        3

In [15]:
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS ranking
    FROM student
)
WHERE ranking <= 3
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score  ranking
0           1  Nguyen Minh Hoang  May Tinh         12    6.7        1
1          10       Cao Thi Hanh  May Tinh         26    7.0        2
2           9     Duong Huu Phuc   Kinh Te         26    7.2        3

In [16]:
query = """
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS ranking_in_class
FROM student
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score  ranking_in_class
0           2       Tran Thi Lan   Kinh Te         34    9.2                 1
1           7      Bui Tien Dung   Kinh Te         34    9.2                 1
2           9     Duong Huu Phuc   Kinh Te         26    7.2                 3
3          10       Cao Thi Hanh  May Tinh         26    7.0                 1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7                 2
5           3       Pham Van Nam  Toan Tin         26    7.9                 1

In [17]:
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS ranking_in_class
    FROM student
)
WHERE ranking_in_class <= 3
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score  ranking_in_class
0           2       Tran Thi Lan   Kinh Te         34    9.2                 1
1           7      Bui Tien Dung   Kinh Te         34    9.2                 1
2           9     Duong Huu Phuc   Kinh Te         26    7.2                 3
3          10       Cao Thi Hanh  May Tinh         26    7.0                 1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7                 2
5           3       Pham Van Nam  Toan Tin         26    7.9                 1

In [18]:
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS ranking_in_class
    FROM student
)
WHERE ranking_in_class <= 3
"""
display(pd.read_sql(query, conn))

   student_id               name     class  course_id  score  ranking_in_class
0           9     Duong Huu Phuc   Kinh Te         26    7.2                 1
1           2       Tran Thi Lan   Kinh Te         34    9.2                 2
2           7      Bui Tien Dung   Kinh Te         34    9.2                 2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7                 1
4          10       Cao Thi Hanh  May Tinh         26    7.0                 2
5           3       Pham Van Nam  Toan Tin         26    7.9                 1

In [19]:
query = """
SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS ranking_in_course
FROM student
"""
display(pd.read_sql(query, conn))

,student_id,name,class,course_id,score,ranking_in_course
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,1
1,3,Pham Van Nam,Toan Tin,26,7.9,1
2,9,Duong Huu Phuc,Kinh Te,26,7.2,2
3,10,Cao Thi Hanh,May Tinh,26,7.0,3
4,2,Tran Thi Lan,Kinh Te,34,9.2,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,1

In [20]:
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS ranking_in_course
    FROM student
)
WHERE ranking_in_course <= 3
"""
display(pd.read_sql(query, conn))

,student_id,name,class,course_id,score,ranking_in_course
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,1
1,3,Pham Van Nam,Toan Tin,26,7.9,1
2,9,Duong Huu Phuc,Kinh Te,26,7.2,2
3,10,Cao Thi Hanh,May Tinh,26,7.0,3
4,2,Tran Thi Lan,Kinh Te,34,9.2,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,1

In [21]:
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS ranking_in_course
    FROM student
)
WHERE ranking_in_course <= 3
"""
display(pd.read_sql(query, conn))

,student_id,name,class,course_id,score,ranking_in_course
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,1
1,10,Cao Thi Hanh,May Tinh,26,7.0,1
2,9,Duong Huu Phuc,Kinh Te,26,7.2,2
3,3,Pham Van Nam,Toan Tin,26,7.9,3
4,2,Tran Thi Lan,Kinh Te,34,9.2,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,1

In [22]:
cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME")
conn.commit()

display(pd.read_sql("SELECT * FROM student", conn))

   student_id               name     class  course_id  score graduation_date
0           1  Nguyen Minh Hoang  May Tinh         12    6.7            None
1           2       Tran Thi Lan   Kinh Te         34    9.2            None
2           3       Pham Van Nam  Toan Tin         26    7.9            None
3           7      Bui Tien Dung   Kinh Te         34    9.2            None
4           9     Duong Huu Phuc   Kinh Te         26    7.2            None
5          10       Cao Thi Hanh  May Tinh         26    7.0            None

In [23]:
ranking_df = pd.read_sql("""
SELECT student_id,
       RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
""", conn)

ranking_df

   student_id  rank_score
0           2           1
1           7           1
2           3           3
3           9           4
4          10           5
5           1           6

##Kết luận##

- Đã thực hiện kết nối hai bảng `student` và `course` bằng các kiểu: CROSS JOIN, INNER JOIN, LEFT JOIN, RIGHT JOIN mô phỏng và FULL OUTER JOIN mô phỏng.
- Đã cập nhật các giá trị `course_id` còn thiếu bằng mã môn học hợp lệ trong bảng `course`.
- Đã loại bỏ các bản ghi có `course_id` không tồn tại trong bảng `course`.
- Đã thống kê tổng số sinh viên và điểm trung bình theo lớp, theo môn học.
- Đã phân loại thi đua của từng môn học dựa trên điểm trung bình.
- Đã xếp hạng sinh viên theo điểm toàn bộ, theo lớp và theo môn học; đồng thời tìm top 3 cao nhất và thấp nhất trong từng trường hợp.
- Đã bổ sung cột `graduation_date` và cập nhật dữ liệu dựa trên thứ hạng của sinh viên.