In [1]:
import sqlite3
import pandas as pd

In [2]:
connection = sqlite3.connect('oanh.db')
cursor = connection.cursor()

In [3]:
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

In [4]:
# Dữ liệu bảng student
students = [
    (1, "Nguyen Minh Hoang", "May Tinh", 12, 6.7),
    (2, "Tran Thi Lan", "Kinh Te", 34, 9.2),
    (3, "Pham Van Nam", "Toan Tin", None, 7.9),
    (4, "Le Thanh Huyen", "Toan Tin", 20, 7.2),
    (5, "Vu Quoc Anh", "May Tinh", 24, 8.0),
    (6, "Dang Thuy Linh", "May Tinh", 24, 5.5),
    (7, "Bui Tien Dung", "Kinh Te", 34, 9.2),
    (8, "Ho Ngoc Mai", "Toan Tin", 20, 8.8),
    (9, "Duong Huu Phuc", "Kinh Te", None, 7.2),
    (10, "Cao Thi Hanh", "May Tinh", None, 7.0)
]

cursor.executemany("INSERT INTO student VALUES (?, ?, ?, ?, ?)", students)

# Dữ liệu bảng course
courses = [
    (12, "Giai tich"),
    (34, "Thong ke"),
    (26, "Tin hoc")
]

cursor.executemany("INSERT INTO course VALUES (?, ?)", courses)

connection.commit()

In [5]:
# Kết hợp 
query_inner_join = """
SELECT student.student_id,
       student.name,
       student.class,
       student.course_id,
       student.score,
       course.course_name
FROM student
INNER JOIN course
ON student.course_id = course.id
"""

df_inner = pd.read_sql_query(query_inner_join, connection)
print("INNER JOIN:")
display(df_inner)

INNER JOIN:

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

In [6]:
query_left_join = """
SELECT student.student_id,
       student.name,
       student.class,
       student.course_id,
       student.score,
       course.course_name
FROM student
LEFT JOIN course
ON student.course_id = course.id
"""

df_left = pd.read_sql_query(query_left_join, connection)
print("LEFT JOIN:")
display(df_left)

LEFT JOIN:

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [7]:
query_right_join = """
SELECT student.student_id,
       student.name,
       student.class,
       student.course_id,
       student.score,
       course.course_name
FROM course
LEFT JOIN student
ON student.course_id = course.id
"""

df_right = pd.read_sql_query(query_right_join, connection)
print("RIGHT JOIN (giả lập):")
display(df_right)

RIGHT JOIN (giả lập):

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
2         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3         NaN               None      None        NaN    NaN     Tin hoc

In [8]:
query_full_join = """
SELECT student.student_id,
       student.name,
       student.class,
       student.course_id,
       student.score,
       course.course_name
FROM student
LEFT JOIN course
ON student.course_id = course.id

UNION

SELECT student.student_id,
       student.name,
       student.class,
       student.course_id,
       student.score,
       course.course_name
FROM course
LEFT JOIN student
ON student.course_id = course.id
"""

df_full = pd.read_sql_query(query_full_join, connection)
print("FULL OUTER JOIN (giả lập):")
display(df_full)

FULL OUTER JOIN (giả lập):

    student_id               name     class  course_id  score course_name
0          NaN               None      None        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9        None
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2        None
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0        None
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5        None
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2        None
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [9]:
cursor.execute("""
DELETE FROM student
WHERE course_id IS NOT NULL
AND course_id NOT IN (SELECT id FROM course)
""")

connection.commit()

In [10]:
cursor.execute("""
UPDATE student
SET course_id = 12
WHERE course_id IS NULL
""")

connection.commit()

In [11]:
query_a = """
SELECT class,
       COUNT(student_id) AS tong_sinh_vien,
       AVG(score) AS diem_trung_binh
FROM student
GROUP BY class
"""

df_a = pd.read_sql_query(query_a, connection)
display(df_a)

      class  tong_sinh_vien  diem_trung_binh
0   Kinh Te               3         8.533333
1  May Tinh               2         6.850000
2  Toan Tin               1         7.900000

In [12]:
query_b = """
SELECT course.course_name,
       COUNT(student.student_id) AS tong_sinh_vien,
       AVG(student.score) AS diem_trung_binh
FROM student
INNER JOIN course
ON student.course_id = course.id
GROUP BY course.course_name
"""

df_b = pd.read_sql_query(query_b, connection)
display(df_b)

  course_name  tong_sinh_vien  diem_trung_binh
0   Giai tich               4              7.2
1    Thong ke               2              9.2

In [13]:
query_c = """
SELECT course.course_name,
       AVG(student.score) AS diem_trung_binh,
       CASE
           WHEN AVG(student.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(student.score) >= 6.0 THEN 'Tot'
           ELSE 'Kem'
       END AS xep_loai
FROM student
INNER JOIN course
ON student.course_id = course.id
GROUP BY course.course_name
"""

df_c = pd.read_sql_query(query_c, connection)
display(df_c)

  course_name  diem_trung_binh  xep_loai
0   Giai tich              7.2       Tot
1    Thong ke              9.2  Xuat sac

In [14]:
# xếp theo điểm
query_rank_all = """
SELECT student_id,
       name,
       class,
       score,
       RANK() OVER (ORDER BY score DESC) AS thu_hang
FROM student
"""

df_rank_all = pd.read_sql_query(query_rank_all, connection)
display(df_rank_all)

   student_id               name     class  score  thu_hang
0           2       Tran Thi Lan   Kinh Te    9.2         1
1           7      Bui Tien Dung   Kinh Te    9.2         1
2           3       Pham Van Nam  Toan Tin    7.9         3
3           9     Duong Huu Phuc   Kinh Te    7.2         4
4          10       Cao Thi Hanh  May Tinh    7.0         5
5           1  Nguyen Minh Hoang  May Tinh    6.7         6

In [15]:
query_top3 = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           score,
           RANK() OVER (ORDER BY score DESC) AS thu_hang
    FROM student
)
WHERE thu_hang <= 3
"""

df_top3 = pd.read_sql_query(query_top3, connection)
display(df_top3)

   student_id           name     class  score  thu_hang
0           2   Tran Thi Lan   Kinh Te    9.2         1
1           7  Bui Tien Dung   Kinh Te    9.2         1
2           3   Pham Van Nam  Toan Tin    7.9         3

In [16]:
query_bottom3 = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           score,
           RANK() OVER (ORDER BY score ASC) AS thu_hang
    FROM student
)
WHERE thu_hang <= 3
"""

df_bottom3 = pd.read_sql_query(query_bottom3, connection)
display(df_bottom3)

   student_id               name     class  score  thu_hang
0           1  Nguyen Minh Hoang  May Tinh    6.7         1
1          10       Cao Thi Hanh  May Tinh    7.0         2
2           9     Duong Huu Phuc   Kinh Te    7.2         3

In [17]:
# xếp theo lớp
query_rank_class = """
SELECT student_id,
       name,
       class,
       score,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS thu_hang
FROM student
"""

df_rank_class = pd.read_sql_query(query_rank_class, connection)
display(df_rank_class)

   student_id               name     class  score  thu_hang
0           2       Tran Thi Lan   Kinh Te    9.2         1
1           7      Bui Tien Dung   Kinh Te    9.2         1
2           9     Duong Huu Phuc   Kinh Te    7.2         3
3          10       Cao Thi Hanh  May Tinh    7.0         1
4           1  Nguyen Minh Hoang  May Tinh    6.7         2
5           3       Pham Van Nam  Toan Tin    7.9         1

In [18]:
query_top3_class = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           score,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS thu_hang
    FROM student
)
WHERE thu_hang <= 3
"""

df_top3_class = pd.read_sql_query(query_top3_class, connection)
display(df_top3_class)

   student_id               name     class  score  thu_hang
0           2       Tran Thi Lan   Kinh Te    9.2         1
1           7      Bui Tien Dung   Kinh Te    9.2         1
2           9     Duong Huu Phuc   Kinh Te    7.2         3
3          10       Cao Thi Hanh  May Tinh    7.0         1
4           1  Nguyen Minh Hoang  May Tinh    6.7         2
5           3       Pham Van Nam  Toan Tin    7.9         1

In [19]:
# xếp theo mã
query_rank_course = """
SELECT student_id,
       name,
       course_id,
       score,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS thu_hang
FROM student
"""

df_rank_course = pd.read_sql_query(query_rank_course, connection)
display(df_rank_course)

   student_id               name  course_id  score  thu_hang
0           3       Pham Van Nam         12    7.9         1
1           9     Duong Huu Phuc         12    7.2         2
2          10       Cao Thi Hanh         12    7.0         3
3           1  Nguyen Minh Hoang         12    6.7         4
4           2       Tran Thi Lan         34    9.2         1
5           7      Bui Tien Dung         34    9.2         1

In [20]:
query_top3_course = """
SELECT *
FROM (
    SELECT student_id,
           name,
           course_id,
           score,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS thu_hang
    FROM student
)
WHERE thu_hang <= 3
"""

df_top3_course = pd.read_sql_query(query_top3_course, connection)
display(df_top3_course)

   student_id            name  course_id  score  thu_hang
0           3    Pham Van Nam         12    7.9         1
1           9  Duong Huu Phuc         12    7.2         2
2          10    Cao Thi Hanh         12    7.0         3
3           2    Tran Thi Lan         34    9.2         1
4           7   Bui Tien Dung         34    9.2         1

In [21]:
# bài 4
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

connection.commit()

In [22]:
cursor.execute("""
UPDATE student
SET graduation_date = date('2026-06-01', '+' || (
    SELECT RANK - 1
    FROM (
        SELECT student_id,
               RANK() OVER (ORDER BY score DESC) AS RANK
        FROM student
    ) AS temp
    WHERE temp.student_id = student.student_id
) || ' months')
""")

connection.commit()

In [23]:
df_final = pd.read_sql_query("SELECT * FROM student", connection)
display(df_final)

   student_id               name     class  course_id  score graduation_date
0           1  Nguyen Minh Hoang  May Tinh         12    6.7      2026-11-01
1           2       Tran Thi Lan   Kinh Te         34    9.2      2026-06-01
2           3       Pham Van Nam  Toan Tin         12    7.9      2026-08-01
3           7      Bui Tien Dung   Kinh Te         34    9.2      2026-06-01
4           9     Duong Huu Phuc   Kinh Te         12    7.2      2026-09-01
5          10       Cao Thi Hanh  May Tinh         12    7.0      2026-10-01