In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Tạo bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INT,
    name TEXT,
    class TEXT,
    course_id INT,
    score FLOAT
)
""")

# Insert dữ liệu
students = [
    (1,"Nguyen Minh Hoang","May Tinh",12,6.7),
    (2,"Tran Thi Lan","Kinh Te",34,9.2),
    (3,"Pham Van Nam","Toan Tin",None,7.9),
    (4,"Le Thanh Huyen","Toan Tin",20,7.2),
    (5,"Vu Quoc Anh","May Tinh",24,8.0),
    (6,"Dang Thuy Linh","May Tinh",24,5.5),
    (7,"Bui Tien Dung","Kinh Te",34,9.2),
    (8,"Ho Ngoc Mai","Toan Tin",20,8.8),
    (9,"Duong Huu Phuc","Kinh Te",None,7.2),
    (10,"Cao Thi Hanh","May Tinh",None,7.0)
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INT,
    course_name TEXT
)
""")

courses = [
    (12,"Giai tich"),
    (34,"Thong ke"),
    (26,"Tin hoc")
]

cursor.executemany("INSERT INTO course VALUES (?,?)", courses)

conn.commit()

In [10]:
# Yêu cầu 1: kết nối hai bảng 
#  tích Decartes
pd.read_sql("""
            SELECT *
            FROM student, course
            """, conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

In [ ]:
# Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.
# INNER JOIN
pd.read_sql("""
            SELECT *
            FROM student
            INNER JOIN course ON student.course_id = course.id
            """, conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

In [12]:
# LEFT JOIN
pd.read_sql("""
            SELECT *
            FROM student
            LEFT JOIN course ON student.course_id = course.id
            """, conn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

In [13]:
# RIGHT JOIN
pd.read_sql("""
            SELECT *
            FROM student
            RIGHT JOIN course ON student.course_id = course.id
            """, conn)

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN               None      None        NaN    NaN  26     Tin hoc

In [15]:
#FULL OUTER JOIN.
pd.read_sql("""
            SELECT *
            FROM student
            FULL OUTER JOIN course ON student.course_id = course.id
            """, conn)

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None
10,NaN,None,None,NaN,NaN,26.0,Tin hoc

In [17]:
#Yêu cầu 2:
# cập nhật những giá trị course_id còn thiếu trong bảng student
cursor.execute("""
            UPDATE student
            SET course_id = 26
            WHERE course_id IS NULL
            """)

In [ ]:
#  loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course
cursor.execute("""
            DELETE FROM student
            WHERE course_id NOT IN (SELECT id FROM course)
            """)

In [19]:
# Câu a: Tổng số sinh viên, điểm trung bình của từng lớp
pd.read_sql("""
            SELECT 
                class,
                COUNT(*) AS total_students, 
                AVG(score) AS avg_score 
            FROM student
            GROUP BY class
            """, conn)

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               4   6.800000
2  Toan Tin               3   7.966667

In [22]:
# b. Tổng số sinh viên, điểm trung bình của từng môn học.
pd.read_sql("""
            SELECT 
                c.course_name,
                COUNT(*) AS total_students,
                AVG(s.score) AS avg_score
            FROM student s
            INNER JOIN course c ON s.course_id = c.id
            GROUP BY c.course_name
            """, conn)

  course_name  total_students  avg_score
0   Giai tich               4        7.2
1    Thong ke               2        9.2

In [23]:
# c. Phân loại thi đua theo số điểm
pd.read_sql("""
            SELECT 
                c.course_name,
                AVG(s.score) AS avg_score,
                CASE 
                    WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
                    WHEN AVG(s.score) BETWEEN 6 AND 8.9 THEN 'Tot'
                    ELSE 'Kem'
                END AS classification
            FROM student s
            INNER JOIN course c ON s.course_id = c.id
            GROUP BY c.course_name
            """, conn)

  course_name  avg_score classification
0   Giai tich        7.2            Tot
1    Thong ke        9.2       Xuat sac

In [ ]:
#Câu 3
pd.read_sql("""
            SELECT 
                student_id,
                name,
                class,
                score,
                ROW_NUMBER() OVER (ORDER BY score DESC) AS rank_all
            FROM student
            """, conn)

   student_id               name     class  score  rank_all
0           2       Tran Thi Lan   Kinh Te    9.2         1
1           7      Bui Tien Dung   Kinh Te    9.2         2
2           8        Ho Ngoc Mai  Toan Tin    8.8         3
3           5        Vu Quoc Anh  May Tinh    8.0         4
4           3       Pham Van Nam  Toan Tin    7.9         5
5           4     Le Thanh Huyen  Toan Tin    7.2         6
6           9     Duong Huu Phuc   Kinh Te    7.2         7
7          10       Cao Thi Hanh  May Tinh    7.0         8
8           1  Nguyen Minh Hoang  May Tinh    6.7         9
9           6     Dang Thuy Linh  May Tinh    5.5        10

In [ ]:
# Top 3 sinh viên có điểm cao nhất trong mỗi môn học.
pd.read_sql("""
            SELECT * FROM (
                SELECT 
                    student_id,
                    name,
                    class,
                    score,
                    ROW_NUMBER() OVER (ORDER BY score DESC) AS rank_num
                FROM student
                ) AS ranked_students    
            WHERE rank_num <= 3
            """, conn)

   student_id           name     class  score  rank_num
0           2   Tran Thi Lan   Kinh Te    9.2         1
1           7  Bui Tien Dung   Kinh Te    9.2         2
2           8    Ho Ngoc Mai  Toan Tin    8.8         3

In [25]:
# Top 3 sinh viên có điểm thấp nhất trong mỗi môn học.
pd.read_sql("""
            SELECT * FROM (
                SELECT 
                    student_id,
                    name,
                    class,
                    score,
                    ROW_NUMBER() OVER (ORDER BY score ASC) AS rank_num
                FROM student
                ) AS ranked_students
            WHERE rank_num <= 3
            """, conn)

   student_id               name     class  score  rank_num
0           6     Dang Thuy Linh  May Tinh    5.5         1
1           1  Nguyen Minh Hoang  May Tinh    6.7         2
2          10       Cao Thi Hanh  May Tinh    7.0         3

In [ ]:
#b Lớp học
pd.read_sql("""
            SELECT 
                student_id,
                name,
                class,
                score,
                ROW_NUMBER() OVER (
                    PARTITION BY class 
                    ORDER BY score DESC
                ) AS rank_in_class
            FROM student
            """, conn)

   student_id               name     class  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te    9.2              1
1           7      Bui Tien Dung   Kinh Te    9.2              2
2           9     Duong Huu Phuc   Kinh Te    7.2              3
3           5        Vu Quoc Anh  May Tinh    8.0              1
4          10       Cao Thi Hanh  May Tinh    7.0              2
5           1  Nguyen Minh Hoang  May Tinh    6.7              3
6           6     Dang Thuy Linh  May Tinh    5.5              4
7           8        Ho Ngoc Mai  Toan Tin    8.8              1
8           3       Pham Van Nam  Toan Tin    7.9              2
9           4     Le Thanh Huyen  Toan Tin    7.2              3

In [ ]:
# Top 3 sinh viên có điểm cao nhất trong mỗi lớp.
pd.read_sql("""
            SELECT *
            FROM (
                SELECT 
                student_id,
                name,
                class,
                score,
                RANK() OVER (
                    PARTITION BY class 
                    ORDER BY score DESC
                ) AS rank_high
                FROM student
            ) AS ranked_students
            WHERE rank_high = 1
            """, conn)

   student_id           name     class  score  rank_high
0           2   Tran Thi Lan   Kinh Te    9.2          1
1           7  Bui Tien Dung   Kinh Te    9.2          1
2           5    Vu Quoc Anh  May Tinh    8.0          1
3           8    Ho Ngoc Mai  Toan Tin    8.8          1

In [42]:
#Top 3 sinh viên có điểm thấp nhất trong mỗi lớp.
pd.read_sql("""
            SELECT *
            FROM (
                SELECT 
                    student_id,
                    name,
                    class,
                    score,
                    RANK() OVER (
                        PARTITION BY class 
                        ORDER BY score ASC
                    ) AS rank_low
                FROM student
            ) AS ranked_students
            WHERE rank_low = 1
            """, conn)

   student_id            name     class  score  rank_low
0           9  Duong Huu Phuc   Kinh Te    7.2         1
1           6  Dang Thuy Linh  May Tinh    5.5         1
2           4  Le Thanh Huyen  Toan Tin    7.2         1

In [ ]:
#cĐiểm số theo mã môn học. 
pd.read_sql("""
            SELECT 
                s.student_id,
                s.name,
                s.course_id,
                s.score,
                ROW_NUMBER() OVER (
                    PARTITION BY s.course_id 
                    ORDER BY s.score DESC
                ) AS rank_in_course
            FROM student s
            """, conn)

   student_id               name  course_id  score  rank_in_course
0           3       Pham Van Nam         12    7.9               1
1           9     Duong Huu Phuc         12    7.2               2
2          10       Cao Thi Hanh         12    7.0               3
3           1  Nguyen Minh Hoang         12    6.7               4
4           8        Ho Ngoc Mai         20    8.8               1
5           4     Le Thanh Huyen         20    7.2               2
6           5        Vu Quoc Anh         24    8.0               1
7           6     Dang Thuy Linh         24    5.5               2
8           2       Tran Thi Lan         34    9.2               1
9           7      Bui Tien Dung         34    9.2               2

In [ ]:
#Top sinh viên có điểm cao nhất trong mỗi mã môn học.
pd.read_sql("""
            SELECT *
            FROM (
                SELECT 
                student_id,
                name,
                course_id,
                score,
                RANK() OVER (
                    PARTITION BY course_id 
                    ORDER BY score DESC
                    ) AS rank_high
                FROM student
                ) AS ranked_students
            WHERE rank_high = 1
            """, conn)

   student_id               name  course_id  score  rank_high
0           3       Pham Van Nam        NaN    7.9          1
1           1  Nguyen Minh Hoang       12.0    6.7          1
2           8        Ho Ngoc Mai       20.0    8.8          1
3           5        Vu Quoc Anh       24.0    8.0          1
4           2       Tran Thi Lan       34.0    9.2          1
5           7      Bui Tien Dung       34.0    9.2          1

In [ ]:
#Top sinh viên có điểm thấp nhất trong mỗi mã môn học.
pd.read_sql("""
            SELECT *
            FROM (
                SELECT 
                    student_id,
                    name,
                    course_id,
                    score,
                    RANK() OVER (
                        PARTITION BY course_id 
                        ORDER BY score ASC
                    ) AS rank_low
                FROM student
                ) AS ranked_students
            WHERE rank_low = 1
            """, conn)

   student_id               name  course_id  score  rank_low
0          10       Cao Thi Hanh        NaN    7.0         1
1           1  Nguyen Minh Hoang       12.0    6.7         1
2           4     Le Thanh Huyen       20.0    7.2         1
3           6     Dang Thuy Linh       24.0    5.5         1
4           2       Tran Thi Lan       34.0    9.2         1
5           7      Bui Tien Dung       34.0    9.2         1

In [ ]:
#Câu 4
# bổ sung thêm một trường graduation_date
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

conn.commit()

In [55]:
cursor.execute("""
UPDATE student
SET graduation_date = DATETIME('now', '+' || (
    SELECT r FROM (
        SELECT 
            student_id,
            RANK() OVER (ORDER BY score DESC) AS r
        FROM student
    ) tmp
    WHERE tmp.student_id = student.student_id
) || ' days')
""")

In [57]:
#Xem kết quả
pd.read_sql("SELECT * FROM student", conn)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,2026-04-12 04:15:48
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,2026-04-04 04:15:48
2,3,Pham Van Nam,Toan Tin,NaN,7.9,2026-04-08 04:15:48
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,2026-04-09 04:15:48
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,2026-04-07 04:15:48
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,2026-04-13 04:15:48
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,2026-04-04 04:15:48
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,2026-04-06 04:15:48
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2,2026-04-09 04:15:48
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,2026-04-11 04:15:48