In [5]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

In [6]:
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

In [7]:
students = [
(1,'Nguyen Minh Hoang','May Tinh',12,6.7),
(2,'Tran Thi Lan','Kinh Te',34,9.2),
(3,'Pham Van Nam','Toan Tin',None,7.9),
(4,'Le Thanh Huyen','Toan Tin',20,7.2),
(5,'Vu Quoc Anh','May Tinh',24,8.0),
(6,'Dang Thuy Linh','May Tinh',24,5.5),
(7,'Bui Tien Dung','Kinh Te',34,9.2),
(8,'Ho Ngoc Mai','Toan Tin',20,8.8),
(9,'Duong Huu Phuc','Kinh Te',None,7.2),
(10,'Cao Thi Hanh','May Tinh',None,7.0)
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)

courses = [
(12,'Giai tich'),
(34,'Thong ke'),
(26,'Tin hoc')
]

cursor.executemany("INSERT INTO course VALUES (?,?)", courses)

conn.commit()

# câu 1:

In [ ]:
query = """
SELECT *
FROM student
CROSS JOIN course
"""
df = pd.read_sql(query, conn)
df

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

In [10]:
# inter join
query = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c
ON s.course_id = c.id
"""
df = pd.read_sql(query, conn)
df

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

In [11]:
# left join
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
"""
df = pd.read_sql(query, conn)
df

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [12]:
# right join
query = """
SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
df = pd.read_sql(query, conn)
df

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         NaN               None      None        NaN    NaN     Tin hoc

In [13]:
# full outer join
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s ON s.course_id = c.id
"""
df = pd.read_sql(query, conn)
df

    student_id               name     class  course_id  score course_name
0          NaN               None      None        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9        None
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2        None
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0        None
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5        None
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2        None
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0        None

# câu 2:

In [15]:
cursor.execute("""
UPDATE student
SET course_id = 12
WHERE course_id IS NULL
""")

cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

conn.commit()

In [16]:
df = pd.read_sql("SELECT * FROM student", conn)
df

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         12    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         12    7.2
5          10       Cao Thi Hanh  May Tinh         12    7.0

In [17]:
# A
query = """
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score),2) AS avg_score
FROM student
GROUP BY class
"""
df = pd.read_sql(query, conn)
df

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

In [18]:
# B
query = """
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(s.score),2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
df = pd.read_sql(query, conn)
df

  course_name  total_students  avg_score
0   Giai tich               4        7.2
1    Thong ke               2        9.2

In [19]:
# C
query = """
SELECT c.course_name,
       ROUND(AVG(s.score),2) AS avg_score,
       CASE
           WHEN AVG(s.score) > 9 THEN 'Xuat sac'
           WHEN AVG(s.score) > 6 AND AVG(s.score) < 8.9 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
df = pd.read_sql(query, conn)
df

  course_name  avg_score classification
0   Giai tich        7.2            Tot
1    Thong ke        9.2       Xuat sac

# câu 3:

In [20]:
# A
query = """
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_high,
       RANK() OVER (ORDER BY score ASC) AS rank_low
FROM student
"""
df = pd.read_sql(query, conn)
df

,student_id,name,class,course_id,score,rank_high,rank_low
0,2,Tran Thi Lan,Kinh Te,34,9.2,1,5
1,7,Bui Tien Dung,Kinh Te,34,9.2,1,5
2,3,Pham Van Nam,Toan Tin,12,7.9,3,4
3,9,Duong Huu Phuc,Kinh Te,12,7.2,4,3
4,10,Cao Thi Hanh,May Tinh,12,7.0,5,2
5,1,Nguyen Minh Hoang,May Tinh,12,6.7,6,1

In [21]:
# top 3 cao nhất
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id           name     class  course_id  score  r
0           2   Tran Thi Lan   Kinh Te         34    9.2  1
1           7  Bui Tien Dung   Kinh Te         34    9.2  1
2           3   Pham Van Nam  Toan Tin         12    7.9  3

In [22]:
# top 3 thấp nhất
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         12    7.0  2
2           9     Duong Huu Phuc   Kinh Te         12    7.2  3

In [23]:
# B
query = """
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_in_class
FROM student
"""
df = pd.read_sql(query, conn)
df

   student_id               name     class  course_id  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te         34    9.2              1
1           7      Bui Tien Dung   Kinh Te         34    9.2              1
2           9     Duong Huu Phuc   Kinh Te         12    7.2              3
3          10       Cao Thi Hanh  May Tinh         12    7.0              1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7              2
5           3       Pham Van Nam  Toan Tin         12    7.9              1

In [ ]:
# top 3 mỗi lớp
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           2       Tran Thi Lan   Kinh Te         34    9.2  1
1           7      Bui Tien Dung   Kinh Te         34    9.2  1
2           9     Duong Huu Phuc   Kinh Te         12    7.2  3
3          10       Cao Thi Hanh  May Tinh         12    7.0  1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7  2
5           3       Pham Van Nam  Toan Tin         12    7.9  1

In [26]:
# top thấp mỗi lớp
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           9     Duong Huu Phuc   Kinh Te         12    7.2  1
1           2       Tran Thi Lan   Kinh Te         34    9.2  2
2           7      Bui Tien Dung   Kinh Te         34    9.2  2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
4          10       Cao Thi Hanh  May Tinh         12    7.0  2
5           3       Pham Van Nam  Toan Tin         12    7.9  1

In [27]:
# C
query = """
SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_in_course
FROM student
"""
df = pd.read_sql(query, conn)
df

   student_id               name     class  course_id  score  rank_in_course
0           3       Pham Van Nam  Toan Tin         12    7.9               1
1           9     Duong Huu Phuc   Kinh Te         12    7.2               2
2          10       Cao Thi Hanh  May Tinh         12    7.0               3
3           1  Nguyen Minh Hoang  May Tinh         12    6.7               4
4           2       Tran Thi Lan   Kinh Te         34    9.2               1
5           7      Bui Tien Dung   Kinh Te         34    9.2               1

In [28]:
# top 3 mỗi môn
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id            name     class  course_id  score  r
0           3    Pham Van Nam  Toan Tin         12    7.9  1
1           9  Duong Huu Phuc   Kinh Te         12    7.2  2
2          10    Cao Thi Hanh  May Tinh         12    7.0  3
3           2    Tran Thi Lan   Kinh Te         34    9.2  1
4           7   Bui Tien Dung   Kinh Te         34    9.2  1

In [29]:
# top thấp mỗi môn
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         12    7.0  2
2           9     Duong Huu Phuc   Kinh Te         12    7.2  3
3           2       Tran Thi Lan   Kinh Te         34    9.2  1
4           7      Bui Tien Dung   Kinh Te         34    9.2  1

# câu 4:

In [30]:
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

conn.commit()

In [31]:
query = """
WITH ranked AS (
    SELECT student_id,
           RANK() OVER (ORDER BY score DESC) AS r
    FROM student
)
UPDATE student
SET graduation_date = DATETIME('now', '+' || (
    SELECT r FROM ranked WHERE ranked.student_id = student.student_id
) || ' days')
"""
cursor.execute(query)
conn.commit()

In [32]:
df = pd.read_sql("""
SELECT student_id, name, score, graduation_date
FROM student
ORDER BY score DESC
""", conn)

df

   student_id               name  score      graduation_date
0           2       Tran Thi Lan    9.2  2026-04-04 11:59:59
1           7      Bui Tien Dung    9.2  2026-04-04 11:59:59
2           3       Pham Van Nam    7.9  2026-04-06 11:59:59
3           9     Duong Huu Phuc    7.2  2026-04-07 11:59:59
4          10       Cao Thi Hanh    7.0  2026-04-08 11:59:59
5           1  Nguyen Minh Hoang    6.7  2026-04-09 11:59:59