#Câu 1

In [3]:
import sqlite3
import pandas as pd

# 1. Tạo kết nối tới cơ sở dữ liệu SQLite trong bộ nhớ
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# 2. Tạo bảng course
cursor.execute('''
CREATE TABLE course (
    id INTEGER PRIMARY KEY,
    course_name TEXT
)
''')

# 3. Tạo bảng student
cursor.execute('''
CREATE TABLE student (
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
''')

# 4. Chèn dữ liệu vào bảng course
course_data = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]
cursor.executemany('INSERT INTO course VALUES (?, ?)', course_data)

# 5. Chèn dữ liệu vào bảng student
student_data = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]
cursor.executemany('INSERT INTO student VALUES (?, ?, ?, ?, ?)', student_data)
conn.commit()

# Hàm hỗ trợ hiển thị kết quả truy vấn SQL bằng Pandas
def run_query(query):
    return pd.read_sql_query(query, conn)

print("Đã khởi tạo dữ liệu thành công!")

Đã khởi tạo dữ liệu thành công!

In [4]:
# Tích Decartes (Cross Join) - Kết nối mọi dòng của bảng này với mọi dòng của bảng kia
query_cross = """
SELECT s.*, c.* FROM student s
CROSS JOIN course c;
"""
display(run_query(query_cross))

# INNER JOIN - Chỉ lấy những sinh viên có course_id tồn tại trong bảng course
query_inner = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c ON s.course_id = c.id;
"""
display(run_query(query_inner))

# LEFT JOIN - Lấy tất cả sinh viên, nếu không có môn học tương ứng thì để NULL
query_left = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id;
"""
display(run_query(query_left))

# RIGHT JOIN - Lấy tất cả môn học, môn nào chưa có sinh viên sẽ để NULL
query_right = """
SELECT s.*, c.course_name
FROM student s
RIGHT JOIN course c ON s.course_id = c.id;
"""
display(run_query(query_right))

# FULL OUTER JOIN - Lấy tất cả dữ liệu từ cả 2 bảng
query_full = """
SELECT s.*, c.course_name
FROM student s
FULL OUTER JOIN course c ON s.course_id = c.id;
"""
display(run_query(query_full))

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

DatabaseError: Execution failed on sql '
SELECT s.*, c.course_name
FROM student s
RIGHT JOIN course c ON s.course_id = c.id;
': RIGHT and FULL OUTER JOINs are not currently supported

#Câu 2

In [5]:
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL;
""")

# Xóa những bản ghi tham gia môn học không tồn tại trong bảng course
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course);
""")
conn.commit()

print("Dữ liệu bảng student sau khi Cập nhật và Xóa:")
display(run_query("SELECT * FROM student"))

Dữ liệu bảng student sau khi Cập nhật và Xóa:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

In [6]:
# a. Tổng số sinh viên, điểm trung bình của từng lớp
query_2a = """
SELECT class, COUNT(student_id) as total_students, ROUND(AVG(score), 2) as avg_score
FROM student
GROUP BY class;
"""
display(run_query(query_2a))

# b. Tổng số sinh viên, điểm trung bình của từng môn học
query_2b = """
SELECT c.course_name, COUNT(s.student_id) as total_students, ROUND(AVG(s.score), 2) as avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name;
"""
display(run_query(query_2b))

# c. Phân loại thi đua theo điểm số
query_2c = """
SELECT *,
    CASE
        WHEN score >= 9.0 THEN 'Xuất sắc'
        WHEN score >= 6.0 AND score <= 8.9 THEN 'Tốt'
        ELSE 'Kém'
    END as classification
FROM student;
"""
display(run_query(query_2c))

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

  course_name  total_students  avg_score
0   Giai tich               1       6.70
1    Thong ke               2       9.20
2     Tin hoc               3       7.37

   student_id               name     class  course_id  score classification
0           1  Nguyen Minh Hoang  May Tinh         12    6.7            Tốt
1           2       Tran Thi Lan   Kinh Te         34    9.2       Xuất sắc
2           3       Pham Van Nam  Toan Tin         26    7.9            Tốt
3           7      Bui Tien Dung   Kinh Te         34    9.2       Xuất sắc
4           9     Duong Huu Phuc   Kinh Te         26    7.2            Tốt
5          10       Cao Thi Hanh  May Tinh         26    7.0            Tốt

#Câu 3

In [7]:
# Xếp hạng tổng quát theo điểm số
query_rank_score = """
SELECT student_id, name, score,
       RANK() OVER(ORDER BY score DESC) as rank_by_score,
       RANK() OVER(PARTITION BY class ORDER BY score DESC) as rank_by_class,
       RANK() OVER(PARTITION BY course_id ORDER BY score DESC) as rank_by_course
FROM student;
"""
display(run_query(query_rank_score))

# Tìm TOP 3 cao nhất và TOP 3 thấp nhất (Ví dụ theo điểm số tổng quát)
query_top_bottom = """
WITH RankedStudents AS (
    SELECT student_id, name, score,
           RANK() OVER(ORDER BY score DESC) as rank_desc,
           RANK() OVER(ORDER BY score ASC) as rank_asc
    FROM student
)
SELECT name, score, 'Top 3 Cao Nhất' as category
FROM RankedStudents WHERE rank_desc <= 3
UNION ALL
SELECT name, score, 'Top 3 Thấp Nhất' as category
FROM RankedStudents WHERE rank_asc <= 3;
"""
display(run_query(query_top_bottom))

,student_id,name,score,rank_by_score,rank_by_class,rank_by_course
0,2,Tran Thi Lan,9.2,1,1,1
1,7,Bui Tien Dung,9.2,1,1,1
2,3,Pham Van Nam,7.9,3,1,1
3,9,Duong Huu Phuc,7.2,4,3,2
4,10,Cao Thi Hanh,7.0,5,1,3
5,1,Nguyen Minh Hoang,6.7,6,2,1

                name  score         category
0       Tran Thi Lan    9.2   Top 3 Cao Nhất
1      Bui Tien Dung    9.2   Top 3 Cao Nhất
2       Pham Van Nam    7.9   Top 3 Cao Nhất
3     Duong Huu Phuc    7.2  Top 3 Thấp Nhất
4       Cao Thi Hanh    7.0  Top 3 Thấp Nhất
5  Nguyen Minh Hoang    6.7  Top 3 Thấp Nhất

#Câu 4

In [8]:
# 1. Thêm cột graduation_date
try:
    cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME;")
except sqlite3.OperationalError:
    pass # Bỏ qua nếu cột đã tồn tại (chạy lại cell nhiều lần)

# 2. Cập nhật graduation_date = Thời gian hiện tại + X ngày (với X là thứ hạng điểm số)
cursor.execute("""
WITH Ranked AS (
    SELECT student_id, RANK() OVER(ORDER BY score DESC) as rank_val
    FROM student
)
UPDATE student
SET graduation_date = (
    SELECT datetime('now', '+' || r.rank_val || ' days')
    FROM Ranked r
    WHERE r.student_id = student.student_id
);
""")
conn.commit()

# Xem kết quả cuối cùng
display(run_query("SELECT student_id, name, score, graduation_date FROM student ORDER BY score DESC;"))

   student_id               name  score      graduation_date
0           2       Tran Thi Lan    9.2  2026-03-29 07:30:27
1           7      Bui Tien Dung    9.2  2026-03-29 07:30:27
2           3       Pham Van Nam    7.9  2026-03-31 07:30:27
3           9     Duong Huu Phuc    7.2  2026-04-01 07:30:27
4          10       Cao Thi Hanh    7.0  2026-04-02 07:30:27
5           1  Nguyen Minh Hoang    6.7  2026-04-03 07:30:27