In [4]:
import sqlite3
import pandas as pd

# Tạo database trong RAM
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

In [5]:
cursor.executescript("""
CREATE TABLE student (
    student_id INT,
    name TEXT,
    class TEXT,
    course_id INT,
    score FLOAT
);

INSERT INTO student VALUES
(1,'Nguyen Minh Hoang','May Tinh',12,6.7),
(2,'Tran Thi Lan','Kinh Te',34,9.2),
(3,'Pham Van Nam','Toan Tin',NULL,7.9),
(4,'Le Thanh Huyen','Toan Tin',20,7.2),
(5,'Vu Quoc Anh','May Tinh',24,8.0),
(6,'Dang Thuy Linh','May Tinh',24,5.5),
(7,'Bui Tien Dung','Kinh Te',34,9.2),
(8,'Ho Ngoc Mai','Toan Tin',20,8.8),
(9,'Duong Huu Phuc','Kinh Te',NULL,7.2),
(10,'Cao Thi Hanh','May Tinh',NULL,7.0);

CREATE TABLE course (
    id INT,
    course_name TEXT
);

INSERT INTO course VALUES
(12,'Giai tich'),
(34,'Thong ke'),
(26,'Tin hoc');
""")

In [6]:
print("Student:")
display(pd.read_sql_query("SELECT * FROM student", conn))

print("Course:")
display(pd.read_sql_query("SELECT * FROM course", conn))

Student:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

Course:

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

##1. Hãy kết nối hai bảng trên theo những cách sau:
- Sử dụng tích Decartes.
- Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.

In [7]:
df = pd.read_sql_query("""
SELECT * FROM student CROSS JOIN course
""", conn)
display(df)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

###INNER JOIN

In [8]:
df = pd.read_sql_query("""
SELECT * FROM student s
INNER JOIN course c ON s.course_id = c.id
""", conn)
display(df)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

###LEFT JOIN

In [9]:
df = pd.read_sql_query("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id
""", conn)
display(df)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

###RIGHT JOIN

In [11]:
df = pd.read_sql_query("""
SELECT * FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)
display(df)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin hoc         NaN               None      None        NaN    NaN

###FULL OUTER JOIN

In [12]:
df = pd.read_sql_query("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT * FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)
display(df)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

##2. Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL,
trong đó các giá trị được điền là những giá trị nằm trong bảng course  và loại bỏ những
bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết:

a. Tổng số sinh viên, điểm trung bình của từng lớp.

b. Tổng số sinh viên, điểm trung bình của từng môn học.

c. Phân loại thi đua theo số điểm của từng môn học biết:

i. Điểm TB ≥  9.0: Xuất sắc.

ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.

iii. Điểm TB < 6.0: Kém.

In [13]:
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
""")

In [14]:
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

In [15]:
display(pd.read_sql_query("SELECT * FROM student", conn))

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

###a. Tổng số sinh viên, điểm trung bình của từng lớp.

In [16]:
df = pd.read_sql_query("""
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score),2) AS avg_score
FROM student
GROUP BY class
""", conn)
display(df)

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

###b. Tổng số sinh viên, điểm trung bình của từng môn học.

In [17]:
df = pd.read_sql_query("""
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(score),2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)
display(df)

  course_name  total_students  avg_score
0   Giai tich               1       6.70
1    Thong ke               2       9.20
2     Tin hoc               3       7.37

###c. Phân loại thi đua theo số điểm của từng môn học

In [18]:
df = pd.read_sql_query("""
SELECT c.course_name,
       ROUND(AVG(score),2) AS avg_score,
       CASE
           WHEN AVG(score) >= 9 THEN 'Xuat sac'
           WHEN AVG(score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)
display(df)

  course_name  avg_score classification
0   Giai tich       6.70            Tot
1    Thong ke       9.20       Xuat sac
2     Tin hoc       7.37            Tot

##3. Hãy xếp hạng sinh viên

###a. Điểm số

In [19]:
df = pd.read_sql_query("""
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
""", conn)
display(df)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           3       Pham Van Nam  Toan Tin         26    7.9           3
3           9     Duong Huu Phuc   Kinh Te         26    7.2           4
4          10       Cao Thi Hanh  May Tinh         26    7.0           5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7           6

###b. Điểm số theo lớp học.

In [20]:
df = pd.read_sql_query("""
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
""", conn)
display(df)

   student_id               name     class  course_id  score  rank_class
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           9     Duong Huu Phuc   Kinh Te         26    7.2           3
3          10       Cao Thi Hanh  May Tinh         26    7.0           1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7           2
5           3       Pham Van Nam  Toan Tin         26    7.9           1

###c. Điểm số theo mã môn học.

In [21]:
df = pd.read_sql_query("""
SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_course
FROM student
""", conn)
display(df)

   student_id               name     class  course_id  score  rank_course
0           1  Nguyen Minh Hoang  May Tinh         12    6.7            1
1           3       Pham Van Nam  Toan Tin         26    7.9            1
2           9     Duong Huu Phuc   Kinh Te         26    7.2            2
3          10       Cao Thi Hanh  May Tinh         26    7.0            3
4           2       Tran Thi Lan   Kinh Te         34    9.2            1
5           7      Bui Tien Dung   Kinh Te         34    9.2            1

###Top 3 sinh viện đạt thứ hạng cao nhất

In [22]:
df = pd.read_sql_query("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
""", conn)
display(df)

   student_id           name     class  course_id  score  r
0           2   Tran Thi Lan   Kinh Te         34    9.2  1
1           7  Bui Tien Dung   Kinh Te         34    9.2  1
2           3   Pham Van Nam  Toan Tin         26    7.9  3

### Top 3 sinh viên đạt thứ hạng thấp nhất

In [23]:
df = pd.read_sql_query("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
""", conn)
display(df)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         26    7.0  2
2           9     Duong Huu Phuc   Kinh Te         26    7.2  3

##4. Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số.

In [24]:
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date TEXT
""")
cursor.execute("""
UPDATE student
SET graduation_date = DATETIME('now', '+' || (
    SELECT rnk FROM (
        SELECT student_id,
               RANK() OVER (ORDER BY score DESC) AS rnk
        FROM student
    ) tmp
    WHERE tmp.student_id = student.student_id
) || ' days')
""")
df = pd.read_sql_query("SELECT * FROM student", conn)
display(df)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-04-09 04:19:11
1,2,Tran Thi Lan,Kinh Te,34,9.2,2026-04-04 04:19:11
2,3,Pham Van Nam,Toan Tin,26,7.9,2026-04-06 04:19:11
3,7,Bui Tien Dung,Kinh Te,34,9.2,2026-04-04 04:19:11
4,9,Duong Huu Phuc,Kinh Te,26,7.2,2026-04-07 04:19:11
5,10,Cao Thi Hanh,May Tinh,26,7.0,2026-04-08 04:19:11