IMPORT THƯ VIỆN

In [21]:
import pandas as pd

TẠO BẢNG STUDENT

In [22]:
student = pd.DataFrame({
    "student_id": [1,2,3,4,5,6,7,8,9,10],
    "name": [
        "Nguyen Minh Hoang","Tran Thi Lan","Pham Van Nam","Le Thanh Huyen",
        "Vu Quoc Anh","Dang Thuy Linh","Bui Tien Dung","Ho Ngoc Mai",
        "Duong Huu Phuc","Cao Thi Hanh"
    ],
    "class": [
        "May Tinh","Kinh Te","Toan Tin","Toan Tin",
        "May Tinh","May Tinh","Kinh Te","Toan Tin",
        "Kinh Te","May Tinh"
    ],
    "course_id": [12,34,None,20,24,24,34,20,None,None],
    "score": [6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})

student

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

TẠO BẢNG COURSE

In [23]:
course = pd.DataFrame({
    "id": [12,34,26],
    "course_name": ["Giai tich","Thong ke","Tin hoc"]
})

course

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

BÀI 1

TÍCH DECARTES

In [24]:
cross_join = student.merge(course, how="cross")
cross_join

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

NHẬN XÉT:

Phép nối này tạo ra tất cả các tổ hợp có thể giữa hai bảng, nghĩa là mỗi sinh viên sẽ được ghép với tất cả các môn học. Điều này làm cho số lượng bản ghi tăng rất lớn (bằng tích số dòng của hai bảng).

INNER JOIN

In [25]:
inner_join = pd.merge(
    student, course,
    left_on="course_id",
    right_on="id",
    how="inner"
)
inner_join

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

NHẬN XÉT:

Chỉ giữ lại các bản ghi có sự khớp giữa course_id và id. Điều này đảm bảo rằng mọi dữ liệu sau khi nối đều hợp lệ.

→ Tuy nhiên, các sinh viên chưa có môn học hoặc có course_id không hợp lệ sẽ bị loại bỏ, dẫn đến mất dữ liệu.

LEFT JOIN

In [26]:
left_join = pd.merge(
    student, course,
    left_on="course_id",
    right_on="id",
    how="left"
)
left_join

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

NHẬN XÉT:

Giữ toàn bộ dữ liệu từ bảng student, kể cả khi không có thông tin môn học tương ứng.

→ Đây là phép nối phù hợp khi mục tiêu chính là phân tích sinh viên, vì không làm mất bất kỳ sinh viên nào.

RIGHT JOIN

In [27]:
right_join = pd.merge(
    student, course,
    left_on="course_id",
    right_on="id",
    how="right"
)
right_join

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

NHẬN XÉT:

Giữ toàn bộ dữ liệu từ bảng course, kể cả khi không có sinh viên đăng ký.

→ Giúp phát hiện các môn học chưa có sinh viên tham gia

FULL OUTER JOIN

In [28]:
outer_join = pd.merge(
    student, course,
    left_on="course_id",
    right_on="id",
    how="outer"
)
outer_join

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

NHẬN XÉT:

Kết hợp toàn bộ dữ liệu của cả hai bảng, bao gồm cả các bản ghi không khớp.

→ Đây là cách tổng quát nhất nhưng tạo ra nhiều giá trị NULL

BÀI 2

TẠO DATABASE VÀ BẢNG

In [29]:
import sqlite3
import pandas as pd

# Tạo kết nối
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Tạo bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

INSERT DỮ LIỆU

In [30]:
# Insert student
cursor.executemany("""
INSERT INTO student VALUES (?, ?, ?, ?, ?)
""", [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
])

# Insert course
cursor.executemany("""
INSERT INTO course VALUES (?, ?)
""", [
(12,"Giai tich"),
(34,"Thong ke"),
(26,"Tin hoc")
])

conn.commit()

CẬP NHẬT COURSE_ID CÒN THIẾU

In [31]:
import random

# Lấy danh sách course_id hợp lệ
course_ids = [12, 34, 26]

# Cập nhật từng dòng NULL
cursor.execute("SELECT student_id FROM student WHERE course_id IS NULL")
rows = cursor.fetchall()

for row in rows:
    random_id = random.choice(course_ids)
    cursor.execute("""
        UPDATE student
        SET course_id = ?
        WHERE student_id = ?
    """, (random_id, row[0]))

conn.commit()

XÓA CÁC BẢN GHI CÓ COURSE KO TỒN TẠI

In [32]:
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

conn.commit()

XEM BẢNG SAU KHI XỬ LÝ

In [33]:
df = pd.read_sql_query("SELECT * FROM student", conn)
df

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         34    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         34    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

NHẬN XÉT:

Sau khi thực hiện cập nhật và làm sạch dữ liệu:

Các giá trị course_id bị thiếu đã được bổ sung bằng các giá trị hợp lệ từ bảng course, đảm bảo không còn dữ liệu NULL.

Các bản ghi có course_id không tồn tại (20, 24) đã bị loại bỏ

TỔNG SỐ SV VÀ ĐIỂM TB THEO LỚP

In [34]:
query_a = """
SELECT class,
       COUNT(*) AS tong_sinh_vien,
       ROUND(AVG(score), 2) AS diem_trung_binh
FROM student
GROUP BY class
"""
pd.read_sql_query(query_a, conn)

      class  tong_sinh_vien  diem_trung_binh
0   Kinh Te               3             8.53
1  May Tinh               2             6.85
2  Toan Tin               1             7.90

NHẬN XÉT:

Kết quả cho thấy số lượng sinh viên phân bố không đồng đều giữa các lớp, gồm 6 sinh viên trong đó lớp Kinh Tế nhiều nhất với 3 sinh viên, lớp Máy Tính có 2 và ít nhất là lớp Toán Tin với 1 sinh viên

Điểm trung bình của từng lớp phản ánh chất lượng học tập:

Lớp có điểm trung bình cao nhất là lớp Kinh Tế với 8,53 điểm

Lớp có điểm trung bình thấp nhất là lớp Máy Tính với 6,85 điểm

TỔNG SỐ SV VÀ ĐIỂM TB THEO MÔN HỌC

In [35]:
query_b = """
SELECT c.course_name,
       COUNT(*) AS tong_sinh_vien,
       ROUND(AVG(s.score), 2) AS diem_trung_binh
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
pd.read_sql_query(query_b, conn)

  course_name  tong_sinh_vien  diem_trung_binh
0   Giai tich               1             6.70
1    Thong ke               4             8.38
2     Tin hoc               1             7.00

NHẬN XÉT:

Môn học có điểm trung bình cao nhất là môn Thống kê

Môn học có điểm trung bình thấp nhất là môn Tin học

PHÂN LOẠI THI ĐUA THEO MÔN HỌC

In [36]:
query_c = """
SELECT c.course_name,
       ROUND(AVG(s.score), 2) AS diem_trung_binh,
       CASE
           WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(s.score) BETWEEN 6.0 AND 8.9 THEN 'Tot'
           ELSE 'Kem'
       END AS xep_loai
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
pd.read_sql_query(query_c, conn)

  course_name  diem_trung_binh xep_loai
0   Giai tich             6.70      Tot
1    Thong ke             8.38      Tot
2     Tin hoc             7.00      Tot

NHẬN XÉT:

Môn Giải tích có điểm trung bình là 7,3 và xếp loại Tốt

Môn Thống kê có điểm trung bình là 8,53 và xếp loại Tốt

Môn Tin học có điểm trung bình là 7 và xếp loại Tốt

BÀI 3

XẾP HẠNG THEO TOÀN BỘ ĐIỂM SV

In [37]:
query_rank_all = """
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
"""
pd.read_sql_query(query_rank_all, conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           3       Pham Van Nam  Toan Tin         34    7.9           3
3           9     Duong Huu Phuc   Kinh Te         34    7.2           4
4          10       Cao Thi Hanh  May Tinh         26    7.0           5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7           6

NHẬN XÉT:

Có tất cả 7 sinh viên, trong đó:

Sinh viên Trần Thị Lan và Bùi Tiến Dũng đều có điểm trung bình là 9,2 và xếp thứ nhất

Sinh viên Nguyễn Minh Hoàng có điểm trung bình thấp nhất là 6,7 và xếp cuối cùng

TOP 3 CAO NHẤT

In [38]:
query_top3_high = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score DESC) AS rank_score
    FROM student
)
WHERE rank_score <= 3
"""
pd.read_sql_query(query_top3_high, conn)

   student_id           name     class  course_id  score  rank_score
0           2   Tran Thi Lan   Kinh Te         34    9.2           1
1           7  Bui Tien Dung   Kinh Te         34    9.2           1
2           3   Pham Van Nam  Toan Tin         34    7.9           3

NHẬN XÉT:

Top 3 sinh viên có điểm cao nhất gồm Trần Thị Lan, Bùi Tiến Dũng và Phạm Văn Nam

TOP 3 THẤP NHẤT

In [39]:
query_top3_low = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS rank_score
    FROM student
)
WHERE rank_score <= 3
"""
pd.read_sql_query(query_top3_low, conn)

   student_id               name     class  course_id  score  rank_score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7           1
1          10       Cao Thi Hanh  May Tinh         26    7.0           2
2           9     Duong Huu Phuc   Kinh Te         34    7.2           3

NHẬN XÉT:

Top 3 sinh viên coa điểm thấp nhất là Nguyễn Minh Hoàng, Cao Thị Hạnh, Dương Hữu Phúc

XẾP HẠNG THEO TỪNG LỚP HỌC

In [40]:
query_rank_class = """
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_in_class
FROM student
"""
pd.read_sql_query(query_rank_class, conn)

   student_id               name     class  course_id  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te         34    9.2              1
1           7      Bui Tien Dung   Kinh Te         34    9.2              1
2           9     Duong Huu Phuc   Kinh Te         34    7.2              3
3          10       Cao Thi Hanh  May Tinh         26    7.0              1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7              2
5           3       Pham Van Nam  Toan Tin         34    7.9              1

NHẬN XÉT:

Lớp Kinh tế gồm 3 sinh viên trong đó sinh viên Trần Thị Lan và Bùi Tiến Dũng xếp thứ 1 với điểm 9,2

Lớp Máy Tinh gồm 2 sinh viên và Cao Thị Hạnh xếp thứ 1 với điểm 7

Lớp Toán Tin chỉ có 1 sinh viên là Phạm Văn Nam và xếp thứ 1

TOP 3 CAO NHẤT MỖI LỚP

In [41]:
query_top3_class_high = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_in_class
    FROM student
)
WHERE rank_in_class <= 3
"""
pd.read_sql_query(query_top3_class_high, conn)

   student_id               name     class  course_id  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te         34    9.2              1
1           7      Bui Tien Dung   Kinh Te         34    9.2              1
2           9     Duong Huu Phuc   Kinh Te         34    7.2              3
3          10       Cao Thi Hanh  May Tinh         26    7.0              1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7              2
5           3       Pham Van Nam  Toan Tin         34    7.9              1

NHẬN XÉT:

Lớp Kinh Tế gồm 3 sinh viên theo thứ tự cao xuống thấp là Trần Thị Lan, Bùi Tiến Dũng cùng xếp thứ 1, Dương Hữu Phúc

Lớp Máy Tính gồm 2 sinh viên theo thứ tự cao xuống thấp là Cao Thị Hạnh, Nguyễn Minh Hoàng

Lớp Toán Tin có 1 sinh viên là Phạm Văn Nam

TOP 3 THẤP NHẤT MỖI LỚP

In [42]:
query_top3_class_low = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS rank_in_class
    FROM student
)
WHERE rank_in_class <= 3
"""
pd.read_sql_query(query_top3_class_low, conn)

   student_id               name     class  course_id  score  rank_in_class
0           9     Duong Huu Phuc   Kinh Te         34    7.2              1
1           2       Tran Thi Lan   Kinh Te         34    9.2              2
2           7      Bui Tien Dung   Kinh Te         34    9.2              2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7              1
4          10       Cao Thi Hanh  May Tinh         26    7.0              2
5           3       Pham Van Nam  Toan Tin         34    7.9              1

NHẬN XÉT:

Top 3 thấp nhất lớp Kinh Tế đầu tiên là Dương Hữu Phúc với 7,2. Tiếp đến là Trần Thị Lan và Bùi Tiến Dũng

Top 3 thấp nhất lớp Máy Tính là Nguyễn Minhh Hoàng và Cao Thị Hạnh

Top 3 thấp nhất Toán Tin chỉ có Phạm Văn Nam

XẾP HẠNG THEO TỪNG MÔN HỌC

In [43]:
query_rank_course = """
SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_in_course
FROM student
"""
pd.read_sql_query(query_rank_course, conn)

   student_id               name     class  course_id  score  rank_in_course
0           1  Nguyen Minh Hoang  May Tinh         12    6.7               1
1          10       Cao Thi Hanh  May Tinh         26    7.0               1
2           2       Tran Thi Lan   Kinh Te         34    9.2               1
3           7      Bui Tien Dung   Kinh Te         34    9.2               1
4           3       Pham Van Nam  Toan Tin         34    7.9               3
5           9     Duong Huu Phuc   Kinh Te         34    7.2               4

NHẬN XÉT:

Ở môn Giả tích thì Phạm Văn Nam xếp thứ 1

Môn Tin học chỉ có 1 sinh viên là Cao Thị Hạnh

Môn Thông kê cao nhất với 9,2 điểm gồm Trần Thị Lan và Bùi Tiến Dũng cùng xếp thứ 1

TOP 3 CAO NHẤT MỖI MÔN

In [44]:
query_top3_course_high = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_in_course
    FROM student
)
WHERE rank_in_course <= 3
"""
pd.read_sql_query(query_top3_course_high, conn)

   student_id               name     class  course_id  score  rank_in_course
0           1  Nguyen Minh Hoang  May Tinh         12    6.7               1
1          10       Cao Thi Hanh  May Tinh         26    7.0               1
2           2       Tran Thi Lan   Kinh Te         34    9.2               1
3           7      Bui Tien Dung   Kinh Te         34    9.2               1
4           3       Pham Van Nam  Toan Tin         34    7.9               3

NHẬN XÉT:

Môn Giải thích top 3 cao nhất đầu tiên là Phạm Văn Nam rồi tới Nguyễn Minh Hoàng

Môn Tin học chỉ có Cao Thị Hạnh

Môn Thống kê cao nhất là Trần Thị Lan và Bùi Tiến Dũng

TOP 3 THẤP NHẤT MỖI MÔN

In [45]:
query_top3_course_low = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS rank_in_course
    FROM student
)
WHERE rank_in_course <= 3
"""
pd.read_sql_query(query_top3_course_low, conn)

   student_id               name     class  course_id  score  rank_in_course
0           1  Nguyen Minh Hoang  May Tinh         12    6.7               1
1          10       Cao Thi Hanh  May Tinh         26    7.0               1
2           9     Duong Huu Phuc   Kinh Te         34    7.2               1
3           3       Pham Van Nam  Toan Tin         34    7.9               2
4           2       Tran Thi Lan   Kinh Te         34    9.2               3
5           7      Bui Tien Dung   Kinh Te         34    9.2               3

NHẬN XÉT:

Top 3 thấp nhất môn Giải tích đầu tiên là Nguyễn Minh Hoàng sau đó là Phạm Văn Nam

Môn Tin học chỉ có Cao Thị Hạnh

Môn Thống kê thấp nhất là Dương Hữu Phúc xếp thứ 1 tiếp theo là Trần Thị Lan và Bùi Tiến Dũng

BÀI 4

CHẠY LẠI BẢNG CŨ

In [46]:
pd.read_sql_query("SELECT * FROM student", conn)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         34    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         34    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

THÊM CỘT GRADUATION_DATE

In [47]:
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")
conn.commit()

CẬP NHẬT GRADUATION_DATE THEO RANK

In [48]:
cursor.execute("""
UPDATE student
SET graduation_date = DATETIME(
    'now',
    '+' || (
        SELECT rank_score
        FROM (
            SELECT student_id,
                   RANK() OVER (ORDER BY score DESC) AS rank_score
            FROM student
        ) r
        WHERE r.student_id = student.student_id
    ) || ' days'
)
""")
conn.commit()

XEM KẾT QUẢ

In [49]:
df = pd.read_sql_query("""
SELECT student_id, name, score, graduation_date
FROM student
ORDER BY score DESC
""", conn)

df

   student_id               name  score      graduation_date
0           2       Tran Thi Lan    9.2  2026-04-04 14:26:49
1           7      Bui Tien Dung    9.2  2026-04-04 14:26:49
2           3       Pham Van Nam    7.9  2026-04-06 14:26:49
3           9     Duong Huu Phuc    7.2  2026-04-07 14:26:49
4          10       Cao Thi Hanh    7.0  2026-04-08 14:26:49
5           1  Nguyen Minh Hoang    6.7  2026-04-09 14:26:49

NHẬN XÉT:

Thời gian tốt nghiệp được tính dựa trên thứ hạng điểm số là một cách mô phỏng hợp lý:

Sinh viên có điểm cao → tốt nghiệp sớm hơn ( trong đó Trần Thị Lan và Bùi Tiến Dũng là tốt nghiệp sớm nhất)

Sinh viên có điểm thấp → tốt nghiệp muộn hơn ( Nguyễn Minh Hoàng tốt nghiệp muộn nhất)