In [2]:
import sqlite3
import pandas as pd

**Câu 1**

In [3]:
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE student (
    student_id INT,
    name TEXT,
    class TEXT,
    course_id INT,
    score REAL
)
""")

cursor.execute("""
CREATE TABLE course (
    id INT,
    course_name TEXT
)
""")

Thêm dữ liệu

In [5]:
cursor.executemany("""
INSERT INTO student VALUES (?, ?, ?, ?, ?)
""", [
(1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
(2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
(3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
(4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
(5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
(6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
(7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
(8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
(9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
(10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
])

cursor.executemany("""
INSERT INTO course VALUES (?, ?)
""", [
(12, 'Giai tich'),
(34, 'Thong ke'),
(26, 'Tin hoc')
])

conn.commit()

INNER JOIN

In [8]:
pd.read_sql_query("""
SELECT *
FROM student s
INNER JOIN course c
ON s.course_id = c.id
""", conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
2            2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
3            2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
4            7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke
5            7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke
6            1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
7            1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
8            2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
9            2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
10           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke
11           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

LEFT JOIN

In [9]:
pd.read_sql_query("""
SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
2,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
3,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
4,3,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
5,4,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
6,5,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
7,6,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
8,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
9,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
10,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
11,9,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
12,10,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None
13,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
14,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
15,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
16,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
17,3,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
18,4,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
19,5,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
20,6,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
21,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
22,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
23,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
24,9,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
25,10,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None

RIGHT JOIN

In [10]:
pd.read_sql_query("""
SELECT *
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
""", conn)

    id course_name  student_id               name     class  course_id  score
0   12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1   12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
2   34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
3   34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
4   34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
5   34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
6   26     Tin hoc         NaN               None      None        NaN    NaN
7   12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
8   12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
9   34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
10  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
11  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
12  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
13  26     Tin hoc         NaN               None      None        NaN    NaN

FULL OUTER JOIN

In [11]:
pd.read_sql_query("""
SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id

UNION

SELECT *
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

**Kết luận**

- Các phép JOIN giúp kết nối dữ liệu giữa hai bảng student và course.
- INNER JOIN chỉ giữ các bản ghi khớp giữa hai bảng.
- LEFT JOIN giữ toàn bộ sinh viên kể cả khi chưa có môn học.
- RIGHT JOIN và FULL OUTER JOIN (mô phỏng trong SQLite) giúp quan sát đầy đủ dữ liệu từ cả hai bảng.
- Tích Descartes tạo ra tất cả các tổ hợp dữ liệu, thường dùng cho mục đích kiểm thử hoặc phân tích.

# Câu 2 : Cập nhật và làm sạch dữ liệu

In [12]:
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
""")
conn.commit()

In [13]:
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")
conn.commit()

**a.Tổng sinh viên và điểm trung bình theo lớp**

In [14]:
pd.read_sql_query("""
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score),2) AS avg_score
FROM student
GROUP BY class
""", conn)

      class  total_students  avg_score
0   Kinh Te               6       8.53
1  May Tinh               4       6.85
2  Toan Tin               2       7.90

**b.Tổng sinh viên và điểm trung bình theo môn**

In [15]:
pd.read_sql_query("""
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(s.score),2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  total_students  avg_score
0   Giai tich               4       6.70
1    Thong ke               8       9.20
2     Tin hoc              12       7.37

**c.Phân loại theo điểm**

In [16]:
pd.read_sql_query("""
SELECT c.course_name,
       ROUND(AVG(s.score),2) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  avg_score classification
0   Giai tich       6.70            Tot
1    Thong ke       9.20       Xuat sac
2     Tin hoc       7.37            Tot

- Dữ liệu đã được làm sạch bằng cách cập nhật các giá trị course_id còn thiếu bằng các giá trị hợp lệ từ bảng course và loại bỏ các bản ghi không thỏa mãn ràng buộc khóa ngoại.

- Sau khi chuẩn hóa dữ liệu, việc thống kê cho thấy:
  + Có sự khác biệt về số lượng sinh viên và điểm trung bình giữa các lớp.
  + Mỗi môn học có mức điểm trung bình riêng phản ánh chất lượng học tập.

- Dựa trên điểm trung bình, các môn học được phân loại thành:
  + ≥ 9.0: Xuất sắc
  + 6.0 – 8.9: Tốt
  + < 6.0: Kém

- Việc xử lý và phân tích đảm bảo tính toàn vẹn dữ liệu và hỗ trợ đánh giá kết quả học tập một cách rõ ràng, nhất quán.

# Câu 3

**a.Xếp hạng sinh viên qua điểm số**

In [18]:
pd.read_sql_query("""
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
""", conn)

    student_id               name     class  course_id  score  rank_score
0            2       Tran Thi Lan   Kinh Te         34    9.2           1
1            7      Bui Tien Dung   Kinh Te         34    9.2           1
2            2       Tran Thi Lan   Kinh Te         34    9.2           1
3            7      Bui Tien Dung   Kinh Te         34    9.2           1
4            3       Pham Van Nam  Toan Tin         26    7.9           5
5            3       Pham Van Nam  Toan Tin         26    7.9           5
6            9     Duong Huu Phuc   Kinh Te         26    7.2           7
7            9     Duong Huu Phuc   Kinh Te         26    7.2           7
8           10       Cao Thi Hanh  May Tinh         26    7.0           9
9           10       Cao Thi Hanh  May Tinh         26    7.0           9
10           1  Nguyen Minh Hoang  May Tinh         12    6.7          11
11           1  Nguyen Minh Hoang  May Tinh         12    6.7          11

**b.Xếp hạng sinh viên qua điểm số theo lớp học**

In [19]:
pd.read_sql_query("""
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
""", conn)

    student_id               name     class  course_id  score  rank_class
0            2       Tran Thi Lan   Kinh Te         34    9.2           1
1            7      Bui Tien Dung   Kinh Te         34    9.2           1
2            2       Tran Thi Lan   Kinh Te         34    9.2           1
3            7      Bui Tien Dung   Kinh Te         34    9.2           1
4            9     Duong Huu Phuc   Kinh Te         26    7.2           5
5            9     Duong Huu Phuc   Kinh Te         26    7.2           5
6           10       Cao Thi Hanh  May Tinh         26    7.0           1
7           10       Cao Thi Hanh  May Tinh         26    7.0           1
8            1  Nguyen Minh Hoang  May Tinh         12    6.7           3
9            1  Nguyen Minh Hoang  May Tinh         12    6.7           3
10           3       Pham Van Nam  Toan Tin         26    7.9           1
11           3       Pham Van Nam  Toan Tin         26    7.9           1

**c.Xếp hạng sinh viên qua điểm số theo mã môn học**

In [20]:
pd.read_sql_query("""
SELECT s.*, c.course_name,
       RANK() OVER (PARTITION BY s.course_id ORDER BY score DESC) AS rank_course
FROM student s
JOIN course c ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,course_name,rank_course
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,Giai tich,1
1,1,Nguyen Minh Hoang,May Tinh,12,6.7,Giai tich,1
2,1,Nguyen Minh Hoang,May Tinh,12,6.7,Giai tich,1
3,1,Nguyen Minh Hoang,May Tinh,12,6.7,Giai tich,1
4,3,Pham Van Nam,Toan Tin,26,7.9,Tin hoc,1
5,3,Pham Van Nam,Toan Tin,26,7.9,Tin hoc,1
6,3,Pham Van Nam,Toan Tin,26,7.9,Tin hoc,1
7,3,Pham Van Nam,Toan Tin,26,7.9,Tin hoc,1
8,9,Duong Huu Phuc,Kinh Te,26,7.2,Tin hoc,5
9,9,Duong Huu Phuc,Kinh Te,26,7.2,Tin hoc,5
10,9,Duong Huu Phuc,Kinh Te,26,7.2,Tin hoc,5
11,9,Duong Huu Phuc,Kinh Te,26,7.2,Tin hoc,5
12,10,Cao Thi Hanh,May Tinh,26,7.0,Tin hoc,9
13,10,Cao Thi Hanh,May Tinh,26,7.0,Tin hoc,9
14,10,Cao Thi Hanh,May Tinh,26,7.0,Tin hoc,9
15,10,Cao Thi Hanh,May Tinh,26,7.0,Tin hoc,9
16,2,Tran Thi Lan,Kinh Te,34,9.2,Thong ke,1
17,2,Tran Thi Lan,Kinh Te,34,9.2,Thong ke,1
18,7,Bui Tien Dung,Kinh Te,34,9.2,Thong ke,1
19,7,Bui Tien Dung,Kinh Te,34,9.2,Thong ke,1
20,2,Tran Thi Lan,Kinh Te,34,9.2,Thong ke,1
21,2,Tran Thi Lan,Kinh Te,34,9.2,Thong ke,1
22,7,Bui Tien Dung,Kinh Te,34,9.2,Thong ke,1
23,7,Bui Tien Dung,Kinh Te,34,9.2,Thong ke,1

**Top 3 sinh viên hạng cao nhất**

In [21]:
pd.read_sql_query("""
SELECT *
FROM student
ORDER BY score DESC
LIMIT 3
""", conn)

   student_id           name    class  course_id  score
0           2   Tran Thi Lan  Kinh Te         34    9.2
1           7  Bui Tien Dung  Kinh Te         34    9.2
2           2   Tran Thi Lan  Kinh Te         34    9.2

**Top 3 sinh viên hạng thấp nhất**

In [22]:
pd.read_sql_query("""
SELECT *
FROM student
ORDER BY score ASC
LIMIT 3
""", conn)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           1  Nguyen Minh Hoang  May Tinh         12    6.7
2          10       Cao Thi Hanh  May Tinh         26    7.0

**Kết luận**

- Sử dụng hàm RANK() cho phép xếp hạng sinh viên theo điểm một cách linh hoạt.
- Có thể xếp hạng theo toàn bộ dữ liệu, theo lớp hoặc theo từng môn học.
- Việc lấy top 3 cao nhất và thấp nhất giúp nhanh chóng xác định sinh viên nổi bật và sinh viên cần cải thiện.
- Kết quả xếp hạng hỗ trợ đánh giá và so sánh hiệu quả học tập một cách rõ ràng.

# Câu 4

In [23]:
cursor.execute("""
ALTER TABLE student ADD COLUMN graduation_date TEXT
""")

In [24]:
cursor.execute("""
UPDATE student
SET graduation_date = DATE('now', '+' || (
    SELECT rank_score
    FROM (
        SELECT student_id,
               RANK() OVER (ORDER BY score DESC) AS rank_score
        FROM student
    ) r
    WHERE r.student_id = student.student_id
) || ' days')
""")
conn.commit()

In [25]:
pd.read_sql_query("SELECT * FROM student", conn)

    student_id               name     class  course_id  score graduation_date
0            1  Nguyen Minh Hoang  May Tinh         12    6.7      2026-04-14
1            2       Tran Thi Lan   Kinh Te         34    9.2      2026-04-04
2            3       Pham Van Nam  Toan Tin         26    7.9      2026-04-08
3            7      Bui Tien Dung   Kinh Te         34    9.2      2026-04-04
4            9     Duong Huu Phuc   Kinh Te         26    7.2      2026-04-10
5           10       Cao Thi Hanh  May Tinh         26    7.0      2026-04-12
6            1  Nguyen Minh Hoang  May Tinh         12    6.7      2026-04-14
7            2       Tran Thi Lan   Kinh Te         34    9.2      2026-04-04
8            3       Pham Van Nam  Toan Tin         26    7.9      2026-04-08
9            7      Bui Tien Dung   Kinh Te         34    9.2      2026-04-04
10           9     Duong Huu Phuc   Kinh Te         26    7.2      2026-04-10
11          10       Cao Thi Hanh  May Tinh         26    7.0      2026-04-12

**Kết luận**

- Việc bổ sung cột graduation_date giúp mô phỏng thời gian tốt nghiệp của sinh viên.
- Thời gian tốt nghiệp được tính dựa trên thời điểm hiện tại và thứ hạng học tập.
- Sinh viên có thứ hạng cao sẽ có thời gian tốt nghiệp sớm hơn.
- Cách tiếp cận này thể hiện khả năng áp dụng dữ liệu để xây dựng các mô hình tính toán thực tế.