# Bài Tập: Kết Hợp Hai Bảng student và course
Cho hai bảng **student(student_id, name, class, course_id, score)** và **course(id, course_name)**

In [1]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# Tạo bảng Student
student_data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name': ['Nguyen Minh Hoang', 'Tran Thi Lan', 'Pham Van Nam', 'Le Thanh Huyen',
             'Vu Quoc Anh', 'Dang Thuy Linh', 'Bui Tien Dung', 'Ho Ngoc Mai',
             'Duong Huu Phuc', 'Cao Thi Hanh'],
    'class': ['May Tinh', 'Kinh Te', 'Toan Tin', 'Toan Tin', 'May Tinh',
              'May Tinh', 'Kinh Te', 'Toan Tin', 'Kinh Te', 'May Tinh'],
    'course_id': [12, 34, None, 20, 24, 24, 34, 20, None, None],
    'score': [6.7, 9.2, 7.9, 7.2, 8.0, 5.5, 9.2, 8.8, 7.2, 7.0]
}

# Tạo bảng Course
course_data = {
    'id': [12, 34, 26],
    'course_name': ['Giai tich', 'Thong ke', 'Tin hoc']
}

student = pd.DataFrame(student_data)
course = pd.DataFrame(course_data)

print("=== Bảng Student ===")
display(student)
print("\n=== Bảng Course ===")
display(course)

=== Bảng Student ===

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

=== Bảng Course ===

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

---
## Câu 1: Kết nối hai bảng theo các cách khác nhau

### 1a. Tích Descartes (Cross Join)

In [2]:
# Tích Descartes: kết hợp mọi hàng của student với mọi hàng của course
student['_key'] = 1
course['_key'] = 1
cross_join = pd.merge(student, course, on='_key').drop('_key', axis=1)
student.drop('_key', axis=1, inplace=True)
course.drop('_key', axis=1, inplace=True)

print(f"Tích Descartes: {len(student)} hàng x {len(course)} hàng = {len(cross_join)} hàng")
display(cross_join.head(10))

Tích Descartes: 10 hàng x 3 hàng = 30 hàng

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3           2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5           2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6           3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7           3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8           3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9           4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich

### 1b. INNER JOIN

In [3]:
# INNER JOIN: chỉ lấy các hàng có course_id khớp với id trong bảng course
inner_join = pd.merge(student, course, left_on='course_id', right_on='id', how='inner')

print(f"INNER JOIN: {len(inner_join)} hàng (chỉ sinh viên có course_id tồn tại trong bảng course)")
display(inner_join)

INNER JOIN: 3 hàng (chỉ sinh viên có course_id tồn tại trong bảng course)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

### 1c. LEFT JOIN

In [4]:
# LEFT JOIN: giữ tất cả hàng của student, course_name = NaN nếu không khớp
left_join = pd.merge(student, course, left_on='course_id', right_on='id', how='left')

print(f"LEFT JOIN: {len(left_join)} hàng (tất cả sinh viên, course_name NaN nếu không có môn)")
display(left_join)

LEFT JOIN: 10 hàng (tất cả sinh viên, course_name NaN nếu không có môn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

### 1d. RIGHT JOIN

In [5]:
# RIGHT JOIN: giữ tất cả hàng của course, student info = NaN nếu không khớp
right_join = pd.merge(student, course, left_on='course_id', right_on='id', how='right')

print(f"RIGHT JOIN: {len(right_join)} hàng (tất cả môn học, kể cả môn chưa có sinh viên đăng ký)")
display(right_join)

RIGHT JOIN: 4 hàng (tất cả môn học, kể cả môn chưa có sinh viên đăng ký)

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

### 1e. FULL OUTER JOIN

In [6]:
# FULL OUTER JOIN: giữ tất cả hàng của cả hai bảng
full_outer_join = pd.merge(student, course, left_on='course_id', right_on='id', how='outer')

print(f"FULL OUTER JOIN: {len(full_outer_join)} hàng (tất cả sinh viên + tất cả môn học)")
display(full_outer_join)

FULL OUTER JOIN: 11 hàng (tất cả sinh viên + tất cả môn học)

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

---
## Câu 2: Cập nhật course_id còn thiếu và phân tích dữ liệu

### 2a. Cập nhật course_id bằng câu lệnh SQL tương đương
Cập nhật các giá trị course_id còn thiếu = giá trị nằm trong bảng course (random trong [12, 34, 26]),  
sau đó loại bỏ sinh viên tham gia môn học không tồn tại trong bảng course.

In [7]:
import sqlite3

# Tạo database SQLite in-memory và thực hiện SQL
conn = sqlite3.connect(':memory:')

# Đưa DataFrame vào SQLite
student.to_sql('student', conn, index=False, if_exists='replace')
course.to_sql('course', conn, index=False, if_exists='replace')

# Câu lệnh SQL: Cập nhật course_id còn thiếu bằng một giá trị hợp lệ từ bảng course
# Ở đây ta dùng id nhỏ nhất trong course làm giá trị mặc định (12)
update_sql = """
UPDATE student
SET course_id = (SELECT MIN(id) FROM course)
WHERE course_id IS NULL
"""
conn.execute(update_sql)
conn.commit()

# Loại bỏ sinh viên có course_id không tồn tại trong bảng course
delete_sql = """
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
"""
conn.execute(delete_sql)
conn.commit()

# Đọc lại dữ liệu đã cập nhật
student_updated = pd.read_sql('SELECT * FROM student', conn)

print("=== Bảng Student sau khi cập nhật ===")
print(f"Số bản ghi: {len(student_updated)}")
display(student_updated)

=== Bảng Student sau khi cập nhật ===
Số bản ghi: 6

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       12.0    7.9
3           7      Bui Tien Dung   Kinh Te       34.0    9.2
4           9     Duong Huu Phuc   Kinh Te       12.0    7.2
5          10       Cao Thi Hanh  May Tinh       12.0    7.0

### 2b. Tổng số sinh viên, điểm trung bình của từng lớp

In [8]:
sql_class = """
SELECT 
    class AS Lop,
    COUNT(*) AS Tong_SV,
    ROUND(AVG(score), 2) AS Diem_TB
FROM student
GROUP BY class
ORDER BY class
"""
result_class = pd.read_sql(sql_class, conn)
print("=== Tổng số sinh viên và điểm trung bình theo từng lớp ===")
display(result_class)

=== Tổng số sinh viên và điểm trung bình theo từng lớp ===

        Lop  Tong_SV  Diem_TB
0   Kinh Te        3     8.53
1  May Tinh        2     6.85
2  Toan Tin        1     7.90

### 2c. Tổng số sinh viên, điểm trung bình của từng môn học

In [9]:
sql_course = """
SELECT 
    c.course_name AS Mon_Hoc,
    COUNT(s.student_id) AS Tong_SV,
    ROUND(AVG(s.score), 2) AS Diem_TB
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
ORDER BY c.course_name
"""
result_course = pd.read_sql(sql_course, conn)
print("=== Tổng số sinh viên và điểm trung bình theo từng môn học ===")
display(result_course)

=== Tổng số sinh viên và điểm trung bình theo từng môn học ===

     Mon_Hoc  Tong_SV  Diem_TB
0  Giai tich        4      7.2
1   Thong ke        2      9.2

### 2d. Phân loại thi đua theo số điểm từng môn học

In [10]:
sql_phanloai = """
SELECT 
    c.course_name AS Mon_Hoc,
    ROUND(AVG(s.score), 2) AS Diem_TB,
    CASE
        WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
        WHEN AVG(s.score) >= 6.0 THEN 'Tot'
        ELSE 'Kem'
    END AS Phan_Loai
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
ORDER BY Diem_TB DESC
"""
result_phanloai = pd.read_sql(sql_phanloai, conn)
print("=== Phân loại thi đua theo điểm trung bình từng môn học ===")
print("  Điểm TB ≥ 9.0: Xuất sắc")
print("  6.0 ≤ Điểm TB ≤ 8.9: Tốt")
print("  Điểm TB < 6.0: Kém")
display(result_phanloai)

=== Phân loại thi đua theo điểm trung bình từng môn học ===
  Điểm TB ≥ 9.0: Xuất sắc
  6.0 ≤ Điểm TB ≤ 8.9: Tốt
  Điểm TB < 6.0: Kém

     Mon_Hoc  Diem_TB Phan_Loai
0   Thong ke      9.2  Xuat sac
1  Giai tich      7.2       Tot

---
## Câu 3: Xếp hạng sinh viên

### 3a. Xếp hạng theo điểm số (toàn trường)

In [11]:
# SQLite không hỗ trợ RANK() trực tiếp theo cách chuẩn, dùng pandas
df = student_updated.copy()
df = df.merge(course, left_on='course_id', right_on='id', how='left')

# Xếp hạng toàn trường theo điểm số
df['Hang_Toan_Truong'] = df['score'].rank(method='min', ascending=False).astype(int)
rank_score = df[['student_id','name','class','course_name','score','Hang_Toan_Truong']].sort_values('Hang_Toan_Truong')

print("=== Xếp hạng sinh viên theo điểm số (toàn trường) ===")
display(rank_score)

top3_cao = rank_score.head(3)
top3_thap = rank_score.tail(3)
print("\n>>> Top 3 sinh viên đạt thứ hạng CAO NHẤT:")
display(top3_cao[['student_id','name','score','Hang_Toan_Truong']])
print("\n>>> Top 3 sinh viên đạt thứ hạng THẤP NHẤT:")
display(top3_thap[['student_id','name','score','Hang_Toan_Truong']])

=== Xếp hạng sinh viên theo điểm số (toàn trường) ===

,student_id,name,class,course_name,score,Hang_Toan_Truong
1,2,Tran Thi Lan,Kinh Te,Thong ke,9.2,1
3,7,Bui Tien Dung,Kinh Te,Thong ke,9.2,1
2,3,Pham Van Nam,Toan Tin,Giai tich,7.9,3
4,9,Duong Huu Phuc,Kinh Te,Giai tich,7.2,4
5,10,Cao Thi Hanh,May Tinh,Giai tich,7.0,5
0,1,Nguyen Minh Hoang,May Tinh,Giai tich,6.7,6

>>> Top 3 sinh viên đạt thứ hạng CAO NHẤT:

   student_id           name  score  Hang_Toan_Truong
1           2   Tran Thi Lan    9.2                 1
3           7  Bui Tien Dung    9.2                 1
2           3   Pham Van Nam    7.9                 3

>>> Top 3 sinh viên đạt thứ hạng THẤP NHẤT:

   student_id               name  score  Hang_Toan_Truong
4           9     Duong Huu Phuc    7.2                 4
5          10       Cao Thi Hanh    7.0                 5
0           1  Nguyen Minh Hoang    6.7                 6

### 3b. Xếp hạng theo điểm số trong từng lớp học

In [12]:
# Xếp hạng trong từng lớp
df['Hang_Trong_Lop'] = df.groupby('class')['score'].rank(method='min', ascending=False).astype(int)
rank_class = df[['student_id','name','class','score','Hang_Trong_Lop']].sort_values(['class','Hang_Trong_Lop'])

print("=== Xếp hạng sinh viên theo điểm số trong từng lớp ===")
display(rank_class)

# Top 3 cao nhất / thấp nhất theo lớp
print("\n>>> Top 3 sinh viên thứ hạng CAO NHẤT theo lớp:")
top3_lop_cao = rank_class.groupby('class').head(3)
display(top3_lop_cao)

print("\n>>> Top 3 sinh viên thứ hạng THẤP NHẤT theo lớp:")
top3_lop_thap = rank_class.groupby('class').tail(3).sort_values(['class','Hang_Trong_Lop'], ascending=[True,False])
display(top3_lop_thap)

=== Xếp hạng sinh viên theo điểm số trong từng lớp ===

   student_id               name     class  score  Hang_Trong_Lop
1           2       Tran Thi Lan   Kinh Te    9.2               1
3           7      Bui Tien Dung   Kinh Te    9.2               1
4           9     Duong Huu Phuc   Kinh Te    7.2               3
5          10       Cao Thi Hanh  May Tinh    7.0               1
0           1  Nguyen Minh Hoang  May Tinh    6.7               2
2           3       Pham Van Nam  Toan Tin    7.9               1

>>> Top 3 sinh viên thứ hạng CAO NHẤT theo lớp:

   student_id               name     class  score  Hang_Trong_Lop
1           2       Tran Thi Lan   Kinh Te    9.2               1
3           7      Bui Tien Dung   Kinh Te    9.2               1
4           9     Duong Huu Phuc   Kinh Te    7.2               3
5          10       Cao Thi Hanh  May Tinh    7.0               1
0           1  Nguyen Minh Hoang  May Tinh    6.7               2
2           3       Pham Van Nam  Toan Tin    7.9               1

>>> Top 3 sinh viên thứ hạng THẤP NHẤT theo lớp:

   student_id               name     class  score  Hang_Trong_Lop
4           9     Duong Huu Phuc   Kinh Te    7.2               3
1           2       Tran Thi Lan   Kinh Te    9.2               1
3           7      Bui Tien Dung   Kinh Te    9.2               1
0           1  Nguyen Minh Hoang  May Tinh    6.7               2
5          10       Cao Thi Hanh  May Tinh    7.0               1
2           3       Pham Van Nam  Toan Tin    7.9               1

### 3c. Xếp hạng theo điểm số trong từng môn học

In [13]:
# Xếp hạng trong từng môn học
df['Hang_Trong_Mon'] = df.groupby('course_id')['score'].rank(method='min', ascending=False).astype(int)
rank_mon = df[['student_id','name','course_name','score','Hang_Trong_Mon']].sort_values(['course_name','Hang_Trong_Mon'])

print("=== Xếp hạng sinh viên theo điểm số trong từng môn học ===")
display(rank_mon)

print("\n>>> Top 3 sinh viên thứ hạng CAO NHẤT theo môn:")
top3_mon_cao = rank_mon.groupby('course_name').head(3)
display(top3_mon_cao)

print("\n>>> Top 3 sinh viên thứ hạng THẤP NHẤT theo môn:")
top3_mon_thap = rank_mon.groupby('course_name').tail(3).sort_values(['course_name','Hang_Trong_Mon'], ascending=[True,False])
display(top3_mon_thap)

=== Xếp hạng sinh viên theo điểm số trong từng môn học ===

   student_id               name course_name  score  Hang_Trong_Mon
2           3       Pham Van Nam   Giai tich    7.9               1
4           9     Duong Huu Phuc   Giai tich    7.2               2
5          10       Cao Thi Hanh   Giai tich    7.0               3
0           1  Nguyen Minh Hoang   Giai tich    6.7               4
1           2       Tran Thi Lan    Thong ke    9.2               1
3           7      Bui Tien Dung    Thong ke    9.2               1

>>> Top 3 sinh viên thứ hạng CAO NHẤT theo môn:

   student_id            name course_name  score  Hang_Trong_Mon
2           3    Pham Van Nam   Giai tich    7.9               1
4           9  Duong Huu Phuc   Giai tich    7.2               2
5          10    Cao Thi Hanh   Giai tich    7.0               3
1           2    Tran Thi Lan    Thong ke    9.2               1
3           7   Bui Tien Dung    Thong ke    9.2               1

>>> Top 3 sinh viên thứ hạng THẤP NHẤT theo môn:

   student_id               name course_name  score  Hang_Trong_Mon
0           1  Nguyen Minh Hoang   Giai tich    6.7               4
5          10       Cao Thi Hanh   Giai tich    7.0               3
4           9     Duong Huu Phuc   Giai tich    7.2               2
1           2       Tran Thi Lan    Thong ke    9.2               1
3           7      Bui Tien Dung    Thong ke    9.2               1

---
## Câu 4: Bổ sung trường graduation_date
Thêm trường **graduation_date** kiểu DATETIME vào bảng student.  
Thời gian tốt nghiệp = thời gian hiện tại + số ngày tính theo hạng điểm số:
- Hạng càng cao (điểm càng cao) → tốt nghiệp sớm hơn
- Công thức: graduation_date = NOW() + (rank - 1) * 30 ngày

In [14]:
now = datetime.now()

# graduation_date = thời gian hiện tại + (hạng - 1) * 30 ngày
# Hạng 1 (điểm cao nhất) tốt nghiệp sớm nhất = now + 0 ngày
df['graduation_date'] = df['Hang_Toan_Truong'].apply(
    lambda rank: now + timedelta(days=(rank - 1) * 30)
)
df['graduation_date'] = df['graduation_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

# Cập nhật vào SQLite
conn.execute("ALTER TABLE student ADD COLUMN graduation_date TEXT")
for _, row in df.iterrows():
    conn.execute(
        "UPDATE student SET graduation_date = ? WHERE student_id = ?",
        (row['graduation_date'], row['student_id'])
    )
conn.commit()

final_df = pd.read_sql('SELECT * FROM student', conn)
# Thêm hạng và graduation_date từ df
final_df = final_df.merge(df[['student_id','Hang_Toan_Truong','graduation_date']], on='student_id')
final_df = final_df.rename(columns={'graduation_date_y': 'graduation_date'}).drop(columns=['graduation_date_x'], errors='ignore')

print("=== Bảng Student sau khi bổ sung graduation_date ===")
print("Quy tắc: graduation_date = thời điểm hiện tại + (hạng - 1) × 30 ngày")
print(f"Thời điểm hiện tại: {now.strftime('%Y-%m-%d %H:%M:%S')}")
display(final_df[['student_id','name','class','score','Hang_Toan_Truong','graduation_date']].sort_values('Hang_Toan_Truong'))

print("\n=== Kết luận ===")
print("- Sinh viên xếp hạng 1 (điểm cao nhất) tốt nghiệp sớm nhất.")
print("- Mỗi bậc hạng cách nhau 30 ngày.")
print("- Sinh viên xếp hạng thấp nhất sẽ tốt nghiệp muộn nhất.")

conn.close()

=== Bảng Student sau khi bổ sung graduation_date ===
Quy tắc: graduation_date = thời điểm hiện tại + (hạng - 1) × 30 ngày
Thời điểm hiện tại: 2026-04-03 07:28:36

,student_id,name,class,score,Hang_Toan_Truong,graduation_date
1,2,Tran Thi Lan,Kinh Te,9.2,1,2026-04-03 07:28:36
3,7,Bui Tien Dung,Kinh Te,9.2,1,2026-04-03 07:28:36
2,3,Pham Van Nam,Toan Tin,7.9,3,2026-06-02 07:28:36
4,9,Duong Huu Phuc,Kinh Te,7.2,4,2026-07-02 07:28:36
5,10,Cao Thi Hanh,May Tinh,7.0,5,2026-08-01 07:28:36
0,1,Nguyen Minh Hoang,May Tinh,6.7,6,2026-08-31 07:28:36

=== Kết luận ===
- Sinh viên xếp hạng 1 (điểm cao nhất) tốt nghiệp sớm nhất.
- Mỗi bậc hạng cách nhau 30 ngày.
- Sinh viên xếp hạng thấp nhất sẽ tốt nghiệp muộn nhất.