Câu 1: Kết nối hai bảng

In [ ]:
import pandas as pd

# Dữ liệu
student = pd.DataFrame({
    "student_id": [1,2,3,4,5,6,7,8,9,10],
    "name": ["Nguyen Minh Hoang","Tran Thi Lan","Pham Van Nam","Le Thanh Huyen",
             "Vu Quoc Anh","Dang Thuy Linh","Bui Tien Dung","Ho Ngoc Mai",
             "Duong Huu Phuc","Cao Thi Hanh"],
    "class": ["May Tinh","Kinh Te","Toan Tin","Toan Tin","May Tinh",
              "May Tinh","Kinh Te","Toan Tin","Kinh Te","May Tinh"],
    "course_id": [12,34,None,20,24,24,34,20,None,None],
    "score": [6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})

course = pd.DataFrame({
    "id": [12,34,26],
    "course_name": ["Giai tich","Thong ke","Tin hoc"]
})

# CROSS JOIN
cross = student.merge(course, how='cross')
display(cross)

# INNER JOIN
inner = student.merge(course, left_on='course_id', right_on='id', how='inner')
display(inner)

# LEFT JOIN
left = student.merge(course, left_on='course_id', right_on='id', how='left')
display(left)

# RIGHT JOIN
right = student.merge(course, left_on='course_id', right_on='id', how='right')
display(right)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

Kết luận : 
- CROSS JOIN tạo ra rất nhiều bản ghi và không phù hợp cho phân tích thực tế.
- INNER JOIN là cách tốt nhất để lấy dữ liệu chính xác giữa hai bảng.
- LEFT JOIN phù hợp khi cần giữ toàn bộ danh sách sinh viên.
- RIGHT JOIN giúp kiểm tra các môn học chưa có sinh viên đăng ký.

Câu 2: Làm sạch dữ liệu và thống kê

In [2]:
# Điền course_id thiếu
student['course_id'] = student['course_id'].fillna(26)

# Xóa dữ liệu không hợp lệ
student = student[student['course_id'].isin(course['id'])]

display(student)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       26.0    7.9
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
8           9     Duong Huu Phuc   Kinh Te       26.0    7.2
9          10       Cao Thi Hanh  May Tinh       26.0    7.0

In [7]:
#A, Theo lớp 
class_stats = student.groupby('class').agg(
    total_students=('student_id','count'),
    avg_score=('score','mean')
)

display(class_stats)

          total_students  avg_score
class
Kinh Te                3   8.533333
May Tinh               2   6.850000
Toan Tin               1   7.900000

Nhận xét : 
- Có sự khác biệt về điểm trung bình giữa các lớp
- Một số lớp có số lượng sinh viên nhiều hơn

In [6]:
#B, Theo môn 
merged = student.merge(course, left_on='course_id', right_on='id')

course_stats = merged.groupby('course_name').agg(
    total_students=('student_id','count'),
    avg_score=('score','mean')
)

display(course_stats)

             total_students  avg_score
course_name
Giai tich                 1   6.700000
Thong ke                  2   9.200000
Tin hoc                   3   7.366667

Kết luận

- Một số môn có nhiều sinh viên tham gia hơn các môn khác.
- Điểm trung bình giữa các môn có sự chênh lệch, phản ánh độ khó hoặc mức độ tiếp thu của sinh viên.

In [17]:
#C , Phân loại 
def classify(x):
    if x >= 9:
        return "Xuat sac"
    elif x >= 6:
        return "Tot"
    else:
        return "Kem"

course_stats['classification'] = course_stats['avg_score'].apply(classify)

display(course_stats)

             total_students  avg_score classification
course_name
Giai tich                 1   6.700000            Tot
Thong ke                  2   9.200000       Xuat sac
Tin hoc                   3   7.366667            Tot

Kết luận

- Các môn học được phân loại chủ yếu ở mức "Tốt".
- Không có nhiều môn đạt mức "Xuất sắc", cho thấy vẫn còn dư địa để cải thiện kết quả học tập.

Câu 3 : Xếp hạng sinh viên

In [ ]:
# Điểm số 
student['rank_all'] = student['score'].rank(ascending=False)

# Điểm số theo lớp
student['rank_class'] = student.groupby('class')['score'].rank(ascending=False)

# Điểm số theo môn
student['rank_course'] = student.groupby('course_id')['score'].rank(ascending=False)

display(student)

,student_id,name,class,course_id,score,rank_all,rank_class,rank_course
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,9.0,3.0,1.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,1.5,1.5,1.5
2,3,Pham Van Nam,Toan Tin,NaN,7.9,5.0,2.0,NaN
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,6.5,3.0,2.0
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,4.0,1.0,1.0
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,10.0,4.0,2.0
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,1.5,1.5,1.5
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,3.0,1.0,1.0
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2,6.5,3.0,NaN
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,8.0,2.0,NaN

Kết luận

- Việc xếp hạng theo điểm số giúp đánh giá tổng thể năng lực học tập của sinh viên.
- Khi xét theo lớp và theo môn học, có thể thấy rõ sự phân hóa về kết quả học tập trong từng nhóm.
- Mỗi lớp và mỗi môn đều có những sinh viên nổi bật với điểm số cao, đồng thời cũng tồn tại nhóm sinh viên có kết quả thấp hơn.
- Điều này cho thấy sự khác biệt về năng lực học tập giữa các sinh viên cũng như giữa các nhóm học.

In [11]:
#Top 3 cao nhất
top3 = student.sort_values(by='score', ascending=False).head(3)
display(top3)

,student_id,name,class,course_id,score,rank_all,rank_class,rank_course
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,1.5,1.5,1.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,1.5,1.5,1.5
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,3.0,1.0,1.0

Kết luận

- Top 3 sinh viên có điểm số vượt trội, thể hiện năng lực học tập tốt.
- Đây là nhóm sinh viên có thành tích nổi bật nhất.

In [12]:
#Top 3 thấp nhất
bottom3 = student.sort_values(by='score').head(3)
display(bottom3)

,student_id,name,class,course_id,score,rank_all,rank_class,rank_course
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,10.0,4.0,2.0
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,9.0,3.0,1.0
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,8.0,2.0,NaN

Kết luận

- Nhóm sinh viên điểm thấp cần cải thiện kết quả học tập.
- Có sự chênh lệch đáng kể so với nhóm điểm cao.

Câu 4 : Thêm cột

In [13]:
student['graduation_date'] = pd.Timestamp.now() + pd.to_timedelta((10 - student['score']), unit='D')

display(student)

,student_id,name,class,course_id,score,rank_all,rank_class,rank_course,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,9.0,3.0,1.0,2026-04-04 07:38:33.421799
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,1.5,1.5,1.5,2026-04-01 19:38:33.421799
2,3,Pham Van Nam,Toan Tin,NaN,7.9,5.0,2.0,NaN,2026-04-03 02:50:33.421799
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,6.5,3.0,2.0,2026-04-03 19:38:33.421799
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,4.0,1.0,1.0,2026-04-03 00:26:33.421799
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,10.0,4.0,2.0,2026-04-05 12:26:33.421799
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,1.5,1.5,1.5,2026-04-01 19:38:33.421799
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,3.0,1.0,1.0,2026-04-02 05:14:33.421799
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2,6.5,3.0,NaN,2026-04-03 19:38:33.421799
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,8.0,2.0,NaN,2026-04-04 00:26:33.421799

Kết luận

- Thời gian tốt nghiệp phụ thuộc vào điểm số của sinh viên.
- Sinh viên có điểm cao sẽ tốt nghiệp sớm hơn.
- Sinh viên có điểm thấp cần thêm thời gian để hoàn thành chương trình.