### 1.

In [ ]:
import sqlite3
import pandas as pd
conn = sqlite3.connect(':memory:')
# Create sample data for student and course tables
student_data = pd.DataFrame({
    'student_id': [1,2,3,4,5,6,7,8,9,10],
    'name': ['Nguyen Minh Hoang','Tran Thi Lan','Pham Van Nam','Le Thanh Huyen',
             'Vu Quoc Anh','Dang Thuy Linh','Bui Tien Dung','Ho Ngoc Mai',
             'Duong Huu Phuc','Cao Thi Hanh'],
    'class': ['May Tinh','Kinh Te','Toan Tin','Toan Tin','May Tinh',
              'May Tinh','Kinh Te','Toan Tin','Kinh Te','May Tinh'],
    'course_id': [12,34,None,20,24,24,34,20,None,None],
    'score': [6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})
course_data = pd.DataFrame({
    'id': [12,34,26],
    'course_name': ['Giai tich','Thong ke','Tin hoc']
})
# Create tables and insert data into the in-memory SQLite database
# Note: We use 'replace' to ensure that if the tables already exist, they will be overwritten with the new data.
student_data.to_sql('student', conn, index=False, if_exists='replace')
course_data.to_sql('course', conn, index=False, if_exists='replace')

3

#### CROSS JOIN

In [ ]:
# Perform a cross join between student and course tables
query = """
SELECT *
FROM student, course
"""
# Execute the query and display the results
pd.read_sql(query, conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

#### INNER JOIN

In [ ]:
# Perform an inner join between student and course tables
query = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c
ON s.course_id = c.id
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke

#### LEFT JOIN

In [ ]:
# Perform a left join between student and course tables
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0         NaN

#### RIGHT JOIN

In [ ]:
# Perform a right join between student and course tables (SQLite does not support RIGHT JOIN, so we can simulate it using LEFT JOIN and swapping the tables)
query = """
SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         NaN                NaN       NaN        NaN    NaN     Tin hoc

#### FULL OUTER JOIN

In [ ]:
# Perform a full outer join between student and course tables (SQLite does not support FULL OUTER JOIN, so we can simulate it using UNION of LEFT JOIN and RIGHT JOIN)
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s ON s.course_id = c.id
"""
pd.read_sql(query, conn)

    student_id               name     class  course_id  score course_name
0          NaN                NaN       NaN        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9         NaN
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2         NaN
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0         NaN
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5         NaN
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8         NaN
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2         NaN
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0         NaN

### 2.

In [7]:
# Cập nhật course_id bị thiếu
query = """
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
"""
conn.execute(query)
conn.commit()

In [8]:
# Xóa course không tồn tại
query = """
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
"""
conn.execute(query)
conn.commit()

In [9]:
# Kiểm tra lại
pd.read_sql("SELECT * FROM student", conn)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       26.0    7.9
3           7      Bui Tien Dung   Kinh Te       34.0    9.2
4           9     Duong Huu Phuc   Kinh Te       26.0    7.2
5          10       Cao Thi Hanh  May Tinh       26.0    7.0

In [10]:
# a. Tổng số sinh viên + điểm TB theo lớp
query = """
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score), 2) AS avg_score
FROM student
GROUP BY class
"""
pd.read_sql(query, conn)

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

In [11]:
# b. Tổng số sinh viên + điểm TB theo môn
query = """
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(s.score), 2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
pd.read_sql(query, conn)

  course_name  total_students  avg_score
0   Giai tich               1       6.70
1    Thong ke               2       9.20
2     Tin hoc               3       7.37

In [12]:
# c. Phân loại thi đua
query = """
SELECT c.course_name,
       ROUND(AVG(s.score), 2) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6.0 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
pd.read_sql(query, conn)

  course_name  avg_score classification
0   Giai tich       6.70            Tot
1    Thong ke       9.20       Xuat sac
2     Tin hoc       7.37            Tot

### 3.

In [13]:
# a. Xếp hạng theo điểm (toàn bộ)
query = """
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te       34.0    9.2           1
1           7      Bui Tien Dung   Kinh Te       34.0    9.2           1
2           3       Pham Van Nam  Toan Tin       26.0    7.9           3
3           9     Duong Huu Phuc   Kinh Te       26.0    7.2           4
4          10       Cao Thi Hanh  May Tinh       26.0    7.0           5
5           1  Nguyen Minh Hoang  May Tinh       12.0    6.7           6

In [14]:
# Top 3 cao nhất
query = """
SELECT *
FROM (
    SELECT *, RANK() OVER (ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id           name     class  course_id  score  r
0           2   Tran Thi Lan   Kinh Te       34.0    9.2  1
1           7  Bui Tien Dung   Kinh Te       34.0    9.2  1
2           3   Pham Van Nam  Toan Tin       26.0    7.9  3

In [15]:
# Top 3 thấp nhất
query = """
SELECT *
FROM (
    SELECT *, RANK() OVER (ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  1
1          10       Cao Thi Hanh  May Tinh       26.0    7.0  2
2           9     Duong Huu Phuc   Kinh Te       26.0    7.2  3

In [16]:
# b. Xếp hạng theo lớp
query = """
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_in_class
FROM student
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te       34.0    9.2              1
1           7      Bui Tien Dung   Kinh Te       34.0    9.2              1
2           9     Duong Huu Phuc   Kinh Te       26.0    7.2              3
3          10       Cao Thi Hanh  May Tinh       26.0    7.0              1
4           1  Nguyen Minh Hoang  May Tinh       12.0    6.7              2
5           3       Pham Van Nam  Toan Tin       26.0    7.9              1

In [17]:
# Top 3 mỗi lớp 
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           2       Tran Thi Lan   Kinh Te       34.0    9.2  1
1           7      Bui Tien Dung   Kinh Te       34.0    9.2  1
2           9     Duong Huu Phuc   Kinh Te       26.0    7.2  3
3          10       Cao Thi Hanh  May Tinh       26.0    7.0  1
4           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  2
5           3       Pham Van Nam  Toan Tin       26.0    7.9  1

In [18]:
# Bottom 3 mỗi lớp
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           9     Duong Huu Phuc   Kinh Te       26.0    7.2  1
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  2
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  2
3           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  1
4          10       Cao Thi Hanh  May Tinh       26.0    7.0  2
5           3       Pham Van Nam  Toan Tin       26.0    7.9  1

In [19]:
# c. Xếp hạng theo môn học
query = """
SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_in_course
FROM student
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  rank_in_course
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7               1
1           3       Pham Van Nam  Toan Tin       26.0    7.9               1
2           9     Duong Huu Phuc   Kinh Te       26.0    7.2               2
3          10       Cao Thi Hanh  May Tinh       26.0    7.0               3
4           2       Tran Thi Lan   Kinh Te       34.0    9.2               1
5           7      Bui Tien Dung   Kinh Te       34.0    9.2               1

In [20]:
# Top 3 mỗi môn
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  1
1           3       Pham Van Nam  Toan Tin       26.0    7.9  1
2           9     Duong Huu Phuc   Kinh Te       26.0    7.2  2
3          10       Cao Thi Hanh  May Tinh       26.0    7.0  3
4           2       Tran Thi Lan   Kinh Te       34.0    9.2  1
5           7      Bui Tien Dung   Kinh Te       34.0    9.2  1

In [21]:
# Bottom 3 mỗi môn
query = """
SELECT *
FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
"""
pd.read_sql(query, conn)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  1
1          10       Cao Thi Hanh  May Tinh       26.0    7.0  1
2           9     Duong Huu Phuc   Kinh Te       26.0    7.2  2
3           3       Pham Van Nam  Toan Tin       26.0    7.9  3
4           2       Tran Thi Lan   Kinh Te       34.0    9.2  1
5           7      Bui Tien Dung   Kinh Te       34.0    9.2  1

### 4.

In [22]:
# Thêm cột graduation_date
query = """
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
"""
conn.execute(query)
conn.commit()

In [23]:
query = """
UPDATE student
SET graduation_date = datetime('now', '+' || rank_days || ' days')
FROM (
    SELECT student_id,
           RANK() OVER (ORDER BY score DESC) AS rank_days
    FROM student
) AS temp
WHERE student.student_id = temp.student_id
"""
conn.execute(query)
conn.commit()

In [24]:
pd.read_sql("SELECT * FROM student", conn)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,2026-04-05 01:43:35
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,2026-03-31 01:43:35
2,3,Pham Van Nam,Toan Tin,26.0,7.9,2026-04-02 01:43:35
3,7,Bui Tien Dung,Kinh Te,34.0,9.2,2026-03-31 01:43:35
4,9,Duong Huu Phuc,Kinh Te,26.0,7.2,2026-04-03 01:43:35
5,10,Cao Thi Hanh,May Tinh,26.0,7.0,2026-04-04 01:43:35