TẠO 2 BẢNG ĐÃ CHO

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

students = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]

courses = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]

cursor.executemany("INSERT INTO student VALUES (?, ?, ?, ?, ?)", students)
cursor.executemany("INSERT INTO course VALUES (?, ?)", courses)
conn.commit()
display(pd.read_sql_query("SELECT * FROM student", conn))
display(pd.read_sql_query("SELECT * FROM course", conn))
print("Đã tạo xong 2 bảng")

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

Đã tạo xong 2 bảng

Sử dụng tích Dercartes

In [2]:
query = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score,
       c.id AS course_table_id, c.course_name
FROM student s
CROSS JOIN course c
"""

df_cross = pd.read_sql_query(query, conn)
display(df_cross)

print("Tổng số dòng:", len(df_cross))

,student_id,name,class,course_id,score,course_table_id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich
1,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,34,Thong ke
2,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,26,Tin hoc
3,2,Tran Thi Lan,Kinh Te,34.0,9.2,12,Giai tich
4,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke
5,2,Tran Thi Lan,Kinh Te,34.0,9.2,26,Tin hoc
6,3,Pham Van Nam,Toan Tin,NaN,7.9,12,Giai tich
7,3,Pham Van Nam,Toan Tin,NaN,7.9,34,Thong ke
8,3,Pham Van Nam,Toan Tin,NaN,7.9,26,Tin hoc
9,4,Le Thanh Huyen,Toan Tin,20.0,7.2,12,Giai tich
10,4,Le Thanh Huyen,Toan Tin,20.0,7.2,34,Thong ke
11,4,Le Thanh Huyen,Toan Tin,20.0,7.2,26,Tin hoc
12,5,Vu Quoc Anh,May Tinh,24.0,8.0,12,Giai tich
13,5,Vu Quoc Anh,May Tinh,24.0,8.0,34,Thong ke
14,5,Vu Quoc Anh,May Tinh,24.0,8.0,26,Tin hoc
15,6,Dang Thuy Linh,May Tinh,24.0,5.5,12,Giai tich
16,6,Dang Thuy Linh,May Tinh,24.0,5.5,34,Thong ke
17,6,Dang Thuy Linh,May Tinh,24.0,5.5,26,Tin hoc
18,7,Bui Tien Dung,Kinh Te,34.0,9.2,12,Giai tich
19,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke
20,7,Bui Tien Dung,Kinh Te,34.0,9.2,26,Tin hoc
21,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,12,Giai tich
22,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,34,Thong ke
23,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,26,Tin hoc
24,9,Duong Huu Phuc,Kinh Te,NaN,7.2,12,Giai tich
25,9,Duong Huu Phuc,Kinh Te,NaN,7.2,34,Thong ke
26,9,Duong Huu Phuc,Kinh Te,NaN,7.2,26,Tin hoc
27,10,Cao Thi Hanh,May Tinh,NaN,7.0,12,Giai tich
28,10,Cao Thi Hanh,May Tinh,NaN,7.0,34,Thong ke
29,10,Cao Thi Hanh,May Tinh,NaN,7.0,26,Tin hoc

Tổng số dòng: 30

SỬ DỤNG JOIN:

In [3]:
# INNER JOIN
query = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM student s
INNER JOIN course c
ON s.course_id = c.id
"""

df_inner = pd.read_sql_query(query, conn)
display(df_inner)
print("Tổng số dòng:", len(df_inner))

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

Tổng số dòng: 3

In [4]:
# LEFT JOIN
query = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
"""

df_left = pd.read_sql_query(query, conn)
display(df_left)

print("Tổng số dòng:", len(df_left))

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0         NaN

Tổng số dòng: 10

In [5]:
# RIGHT JOIN
query = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""

df_right = pd.read_sql_query(query, conn)
display(df_right)

print("Tổng số dòng:", len(df_right))

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         NaN                NaN       NaN        NaN    NaN     Tin hoc

Tổng số dòng: 4

In [6]:
# FULL OUTER JOIN
query = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id

UNION

SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""

df_full = pd.read_sql_query(query, conn)
display(df_full)
print("Tổng số dòng:", len(df_full))

    student_id               name     class  course_id  score course_name
0          NaN                NaN       NaN        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9         NaN
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2         NaN
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0         NaN
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5         NaN
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8         NaN
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2         NaN
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0         NaN

Tổng số dòng: 11

2.CẬP NHẬT NHỮNG GIÁ TRỊ CORSE_ID CÒN THIẾU TRONG BẢNG STUDENT BẰNG SQL

In [7]:
# Hiển thị dữ liệu từ 2 bảng
import pandas as pd

print("Bảng student:")
display(pd.read_sql_query("SELECT * FROM student", conn))

print("Bảng course:")
display(pd.read_sql_query("SELECT * FROM course", conn))

Bảng student:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

Bảng course:

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

In [8]:
# Cập nhật dữ liệu thiếu
cursor.execute("UPDATE student SET course_id = 26 WHERE student_id = 3")
cursor.execute("UPDATE student SET course_id = 12 WHERE student_id = 9")
cursor.execute("UPDATE student SET course_id = 26 WHERE student_id = 10")
conn.commit()

display(pd.read_sql_query("SELECT * FROM student", conn))

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           4     Le Thanh Huyen  Toan Tin         20    7.2
4           5        Vu Quoc Anh  May Tinh         24    8.0
5           6     Dang Thuy Linh  May Tinh         24    5.5
6           7      Bui Tien Dung   Kinh Te         34    9.2
7           8        Ho Ngoc Mai  Toan Tin         20    8.8
8           9     Duong Huu Phuc   Kinh Te         12    7.2
9          10       Cao Thi Hanh  May Tinh         26    7.0

In [ ]:
# Loại bỏ bản ghi không tồn tại
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")
conn.commit()

display(pd.read_sql_query("SELECT * FROM student", conn))

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         12    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

2.a TỔNG SỐ SINH VIÊN, ĐIỂM TRUNG BÌNH CỦA TỪNG LỚP

In [11]:
query = """
SELECT class,
       COUNT(*) AS tong_sinh_vien,
       ROUND(AVG(score), 2) AS diem_trung_binh
FROM student
GROUP BY class
"""

df_class = pd.read_sql_query(query, conn)
display(df_class)
print(f"Tổng số sinh viên và điểm trung bình theo lớp: {len(df_class)}")

      class  tong_sinh_vien  diem_trung_binh
0   Kinh Te               3             8.53
1  May Tinh               2             6.85
2  Toan Tin               1             7.90

Tổng số sinh viên và điểm trung bình theo lớp: 3

2.b TỔNG SỐ SINH VIÊN, ĐIỂM TRUNG BÌNH TỪNG MÔN HỌC

In [12]:
query = """
SELECT c.course_name,
       COUNT(s.student_id) AS tong_sinh_vien,
       ROUND(AVG(s.score), 2) AS diem_trung_binh
FROM student s
JOIN course c
ON s.course_id = c.id
GROUP BY c.course_name
"""

df_course = pd.read_sql_query(query, conn)
display(df_course)
print(f"Tổng số sinh viên và điểm trung bình theo môn học: {len(df_course)}")

  course_name  tong_sinh_vien  diem_trung_binh
0   Giai tich               2             6.95
1    Thong ke               2             9.20
2     Tin hoc               2             7.45

Tổng số sinh viên và điểm trung bình theo môn học: 3

2.c PHÂN LOẠI THI ĐUA THEO SỐ ĐIỂM CỦA TỪNG MÔN HỌC

In [13]:
query = """
SELECT c.course_name AS mon_hoc,
       ROUND(AVG(s.score), 2) AS diem_tb,
       CASE
           WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6.0 AND AVG(s.score) <= 8.9 THEN 'Tot'
           ELSE 'Kem'
       END AS xep_loai
FROM student s
JOIN course c
ON s.course_id = c.id
GROUP BY c.course_name
"""

df_thidua = pd.read_sql_query(query, conn)
display(df_thidua)
print(f"Tổng số môn học và xếp loại thi đua: {len(df_thidua)}")

     mon_hoc  diem_tb  xep_loai
0  Giai tich     6.95       Tot
1   Thong ke     9.20  Xuat sac
2    Tin hoc     7.45       Tot

Tổng số môn học và xếp loại thi đua: 3

3. XẾP HẠNG SINH VIÊN

In [14]:
#Bảng xếp hạng toàn bộ sinh viên
query = """
SELECT student_id,
       name,
       class,
       course_id,
       score,
       RANK() OVER (ORDER BY score DESC) AS xep_hang
FROM student
"""

df_rank_score = pd.read_sql_query(query, conn)
display(df_rank_score)

   student_id               name     class  course_id  score  xep_hang
0           2       Tran Thi Lan   Kinh Te         34    9.2         1
1           7      Bui Tien Dung   Kinh Te         34    9.2         1
2           3       Pham Van Nam  Toan Tin         26    7.9         3
3           9     Duong Huu Phuc   Kinh Te         12    7.2         4
4          10       Cao Thi Hanh  May Tinh         26    7.0         5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7         6

In [15]:
# Top 3 sinh viên có thứ hạng cao nhất theo điểm số
query = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           course_id,
           score,
           RANK() OVER (ORDER BY score DESC) AS xep_hang
    FROM student
)
WHERE xep_hang <= 3
"""

top3_high_score = pd.read_sql_query(query, conn)
display(top3_high_score)

   student_id           name     class  course_id  score  xep_hang
0           2   Tran Thi Lan   Kinh Te         34    9.2         1
1           7  Bui Tien Dung   Kinh Te         34    9.2         1
2           3   Pham Van Nam  Toan Tin         26    7.9         3

In [16]:
# Top 3 sinh viên có thứ hạng thấp nhất theo điểm số
query = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           course_id,
           score,
           RANK() OVER (ORDER BY score ASC) AS xep_hang_thap
    FROM student
)
WHERE xep_hang_thap <= 3
"""

top3_low_score = pd.read_sql_query(query, conn)
display(top3_low_score)

   student_id               name     class  course_id  score  xep_hang_thap
0           1  Nguyen Minh Hoang  May Tinh         12    6.7              1
1          10       Cao Thi Hanh  May Tinh         26    7.0              2
2           9     Duong Huu Phuc   Kinh Te         12    7.2              3

3.b ĐIỂM SỐ THEO LỚP HỌC

In [17]:
# Bảng xếp hạng theo lớp
query = """
SELECT student_id,
       name,
       class,
       course_id,
       score,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS xep_hang_trong_lop
FROM student
ORDER BY class, xep_hang_trong_lop
"""

df_rank_class = pd.read_sql_query(query, conn)
display(df_rank_class)

,student_id,name,class,course_id,score,xep_hang_trong_lop
0,2,Tran Thi Lan,Kinh Te,34,9.2,1
1,7,Bui Tien Dung,Kinh Te,34,9.2,1
2,9,Duong Huu Phuc,Kinh Te,12,7.2,3
3,10,Cao Thi Hanh,May Tinh,26,7.0,1
4,1,Nguyen Minh Hoang,May Tinh,12,6.7,2
5,3,Pham Van Nam,Toan Tin,26,7.9,1

In [18]:
# Top 3 sinh viên có thứ hạng cao nhất theo từng lớp
query = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           course_id,
           score,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS xep_hang
    FROM student
)
WHERE xep_hang <= 3
ORDER BY class, xep_hang
"""

top3_high_class = pd.read_sql_query(query, conn)
display(top3_high_class)

   student_id               name     class  course_id  score  xep_hang
0           2       Tran Thi Lan   Kinh Te         34    9.2         1
1           7      Bui Tien Dung   Kinh Te         34    9.2         1
2           9     Duong Huu Phuc   Kinh Te         12    7.2         3
3          10       Cao Thi Hanh  May Tinh         26    7.0         1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7         2
5           3       Pham Van Nam  Toan Tin         26    7.9         1

In [19]:
# Top 3 sinh viên có thứ hạng thấp nhất theo từng lớp
query = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           course_id,
           score,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS xep_hang
    FROM student
)
WHERE xep_hang <= 3
ORDER BY class, xep_hang
"""

top3_low_class = pd.read_sql_query(query, conn)
display(top3_low_class)

   student_id               name     class  course_id  score  xep_hang
0           9     Duong Huu Phuc   Kinh Te         12    7.2         1
1           2       Tran Thi Lan   Kinh Te         34    9.2         2
2           7      Bui Tien Dung   Kinh Te         34    9.2         2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7         1
4          10       Cao Thi Hanh  May Tinh         26    7.0         2
5           3       Pham Van Nam  Toan Tin         26    7.9         1

3.c ĐIỂM SỐ THEO MÃ MÔN HỌC

In [20]:
# Bảng xếp hạng theo mã môn học
query = """
SELECT student_id,
       name,
       class,
       course_id,
       score,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS xep_hang_trong_mon
FROM student
ORDER BY course_id, xep_hang_trong_mon
"""

df_rank_course = pd.read_sql_query(query, conn)
display(df_rank_course)

,student_id,name,class,course_id,score,xep_hang_trong_mon
0,9,Duong Huu Phuc,Kinh Te,12,7.2,1
1,1,Nguyen Minh Hoang,May Tinh,12,6.7,2
2,3,Pham Van Nam,Toan Tin,26,7.9,1
3,10,Cao Thi Hanh,May Tinh,26,7.0,2
4,2,Tran Thi Lan,Kinh Te,34,9.2,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,1

In [21]:
# Top 3 sinh viên có thứ hạng cao nhất theo từng mã môn học
query = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           course_id,
           score,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS xep_hang
    FROM student
)
WHERE xep_hang <= 3
ORDER BY course_id, xep_hang
"""

top3_high_course = pd.read_sql_query(query, conn)
display(top3_high_course)

   student_id               name     class  course_id  score  xep_hang
0           9     Duong Huu Phuc   Kinh Te         12    7.2         1
1           1  Nguyen Minh Hoang  May Tinh         12    6.7         2
2           3       Pham Van Nam  Toan Tin         26    7.9         1
3          10       Cao Thi Hanh  May Tinh         26    7.0         2
4           2       Tran Thi Lan   Kinh Te         34    9.2         1
5           7      Bui Tien Dung   Kinh Te         34    9.2         1

In [22]:
# Top 3 sinh viên có thứ hạng thấp nhất theo từng mã môn học
query = """
SELECT *
FROM (
    SELECT student_id,
           name,
           class,
           course_id,
           score,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS xep_hang
    FROM student
)
WHERE xep_hang <= 3
ORDER BY course_id, xep_hang
"""

top3_low_course = pd.read_sql_query(query, conn)
display(top3_low_course)

   student_id               name     class  course_id  score  xep_hang
0           1  Nguyen Minh Hoang  May Tinh         12    6.7         1
1           9     Duong Huu Phuc   Kinh Te         12    7.2         2
2          10       Cao Thi Hanh  May Tinh         26    7.0         1
3           3       Pham Van Nam  Toan Tin         26    7.9         2
4           2       Tran Thi Lan   Kinh Te         34    9.2         1
5           7      Bui Tien Dung   Kinh Te         34    9.2         1

4. BỔ SUNG TRƯỜNG graduation_date

In [ ]:
from datetime import datetime, timedelta
# Thêm graduation_date
cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME")
current_time = datetime.now()
cursor.execute("SELECT student_id, score FROM student")
for student_id, score in cursor.fetchall():
    grad_date = current_time + timedelta(days=int(score * 30))
    cursor.execute("UPDATE student SET graduation_date = ? WHERE student_id = ?", (grad_date, student_id))
conn.commit()

cursor.execute("SELECT student_id, name, graduation_date FROM student")
df_graduation = pd.DataFrame(cursor.fetchall(), columns=["student_id", "name", "graduation_date"])
print(df_graduation)

   student_id               name             graduation_date
0           1  Nguyen Minh Hoang  2026-10-21 09:09:01.112126
1           2       Tran Thi Lan  2027-01-04 09:09:01.112126
2           3       Pham Van Nam  2026-11-26 09:09:01.112126
3           7      Bui Tien Dung  2027-01-04 09:09:01.112126
4           9     Duong Huu Phuc  2026-11-05 09:09:01.112126
5          10       Cao Thi Hanh  2026-10-30 09:09:01.112126

C:\Users\admin\AppData\Local\Temp\ipykernel_856\4195370594.py:8: DeprecationWarning: The default datetime adapter is deprecated as of Python 3.12; see the sqlite3 documentation for suggested replacement recipes
  cursor.execute("UPDATE student SET graduation_date = ? WHERE student_id = ?", (grad_date, student_id))