In [1]:
import pandas as pd

# Tạo bảng student
student = pd.DataFrame({
    "student_id": [1,2,3,4,5,6,7,8,9,10],
    "name": [
        "Nguyen Minh Hoang","Tran Thi Lan","Pham Van Nam",
        "Le Thanh Huyen","Vu Quoc Anh","Dang Thuy Linh",
        "Bui Tien Dung","Ho Ngoc Mai","Duong Huu Phuc","Cao Thi Hanh"
    ],
    "class": ["May Tinh","Kinh Te","Toan Tin","Toan Tin","May Tinh","May Tinh","Kinh Te","Toan Tin","Kinh Te","May Tinh"],
    "course_id": [12,34,None,20,24,24,34,20,None,None],
    "score": [6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})

# Tạo bảng course
course = pd.DataFrame({
    "id": [12,34,26],
    "course_name": ["Giai tich","Thong ke","Tin hoc"]
})

student, course

(   student_id               name     class  course_id  score
 0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
 1           2       Tran Thi Lan   Kinh Te       34.0    9.2
 2           3       Pham Van Nam  Toan Tin        NaN    7.9
 3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
 4           5        Vu Quoc Anh  May Tinh       24.0    8.0
 5           6     Dang Thuy Linh  May Tinh       24.0    5.5
 6           7      Bui Tien Dung   Kinh Te       34.0    9.2
 7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
 8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
 9          10       Cao Thi Hanh  May Tinh        NaN    7.0,
    id course_name
 0  12   Giai tich
 1  34    Thong ke
 2  26     Tin hoc)

INNER, LEFT, RIGHT, FULL, DECARTES

In [2]:
inner_join = pd.merge(student, course, left_on="course_id", right_on="id", how="inner")
inner_join

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

In [3]:
left_join = pd.merge(student, course, left_on="course_id", right_on="id", how="left")
left_join

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

In [4]:
right_join = pd.merge(student, course, left_on="course_id", right_on="id", how="right")
right_join

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

In [5]:
full_join = pd.merge(student, course, left_on="course_id", right_on="id", how="outer")
full_join

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

In [6]:
cross_join = student.merge(course, how="cross")
cross_join

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

LOẠI BỎ COURSE ID KO NẰM TRONG BẢNG COURSE

In [17]:
valid_ids = course["id"].tolist()

student_clean = student[student["course_id"].isin(valid_ids)].copy()
student_clean

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
6           7      Bui Tien Dung   Kinh Te       34.0    9.2

In [8]:
# Tổng số sinh viên, điểm TB của từng lớp
class_stats = student_clean.groupby("class").agg(
    total_students=("student_id","count"),
    avg_score=("score","mean")
)
class_stats

          total_students  avg_score
class
Kinh Te                2        9.2
May Tinh               1        6.7

In [18]:
# Tổng số sinh viên điểm TB của từng môn
course_stats = pd.merge(student_clean, course, left_on="course_id", right_on="id")

course_stats = course_stats.groupby("course_name").agg(
    total_students=("student_id","count"),
    avg_score=("score","mean")
)
course_stats

             total_students  avg_score
course_name
Giai tich                 1        6.7
Thong ke                  2        9.2

In [19]:
# Phân loại học lực
def classify(score):
    if score >= 9:
        return "Xuat sac"
    elif score >= 6:
        return "Tot"
    else:
        return "Kem"

student_clean["rank"] = student_clean["score"].apply(classify)
student_clean

   student_id               name     class  course_id  score      rank
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7       Tot
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  Xuat sac
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  Xuat sac

XẾP HẠNG SINH VIÊN

In [20]:
student_clean["rank_all"] = student_clean["score"].rank(ascending=False)
student_clean.sort_values("score", ascending=False)

,student_id,name,class,course_id,score,rank,rank_all
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.5
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,3.0

In [12]:
# Top 3 cao nhất
student_clean.sort_values("score", ascending=False).head(3)

,student_id,name,class,course_id,score,rank,rank_all
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.5
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,3.0

In [13]:
# Top 3 thấp nhất
student_clean.sort_values("score").head(3)

,student_id,name,class,course_id,score,rank,rank_all
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,3.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.5

In [21]:
# Điểm số theo lớp
student_clean["rank_class"] = student_clean.groupby("class")["score"].rank(ascending=False)
student_clean.sort_values(["class","rank_class"])

,student_id,name,class,course_id,score,rank,rank_all,rank_class
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.5,1.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.5,1.5
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,3.0,1.0

In [22]:
# Điểm số theo môn học
student_clean["rank_course"] = student_clean.groupby("course_id")["score"].rank(ascending=False)
student_clean.sort_values(["course_id","rank_course"])

,student_id,name,class,course_id,score,rank,rank_all,rank_class,rank_course
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,3.0,1.0,1.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.5,1.5,1.5
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.5,1.5,1.5

GRADUATION DATE

In [23]:
from datetime import datetime, timedelta

current_time = datetime.now()

student_clean["graduation_date"] = student_clean["rank_all"].apply(
    lambda x: current_time + timedelta(days=int(x*30))
)

student_clean

,student_id,name,class,course_id,score,rank,rank_all,rank_class,rank_course,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,3.0,1.0,1.0,2026-06-28 10:29:22.469050
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.5,1.5,1.5,2026-05-14 10:29:22.469050
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.5,1.5,1.5,2026-05-14 10:29:22.469050