In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

def run_query(query, description=""):
    if description:
        print(f"{description}")
    try:
        display(pd.read_sql_query(query, conn))
    except Exception as e:
        print("Lỗi hoặc không có dữ liệu trả về:", e)
    print("\n")

# 1. Tạo bảng 
cursor.execute('''
    CREATE TABLE course (
        id INTEGER PRIMARY KEY,
        course_name TEXT
    )
''')

# 2. Tạo bảng student
cursor.execute('''
    CREATE TABLE student (
        student_id INTEGER PRIMARY KEY,
        name TEXT,
        class TEXT,
        course_id INTEGER,
        score REAL
    )
''')

# 3. Chèn dữ liệu vào bảng course 
course_data = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]
cursor.executemany('INSERT INTO course VALUES (?, ?)', course_data)

# 4. Chèn dữ liệu vào bảng student 
student_data = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]
cursor.executemany('INSERT INTO student VALUES (?, ?, ?, ?, ?)', student_data)
conn.commit()

run_query("SELECT * FROM student", "Dữ liệu bảng Student")
run_query("SELECT * FROM course", "Dữ liệu bảng Course")

Dữ liệu bảng Student

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

Dữ liệu bảng Course

   id course_name
0  12   Giai tich
1  26     Tin hoc
2  34    Thong ke

In [7]:
# Tích Decartes 
run_query('''
SELECT * FROM student CROSS JOIN course;
''', "Tích Decartes")

# INNER JOIN 
run_query('''
SELECT * FROM student 
INNER JOIN course ON student.course_id = course.id;
''', "INNER JOIN")

# LEFT JOIN 
run_query('''
SELECT * FROM student 
LEFT JOIN course ON student.course_id = course.id;
''', "LEFT JOIN")

# RIGHT JOIN 
run_query('''
SELECT * FROM student 
RIGHT JOIN course ON student.course_id = course.id;
''', "RIGHT JOIN")

# FULL OUTER JOIN 
run_query('''
SELECT * FROM student 
FULL OUTER JOIN course ON student.course_id = course.id;
''', "FULL OUTER JOIN")

Tích Decartes

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

INNER JOIN

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

LEFT JOIN

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

RIGHT JOIN

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN               None      None        NaN    NaN  26     Tin hoc

FULL OUTER JOIN

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None
10,NaN,None,None,NaN,NaN,26.0,Tin hoc

In [ ]:
# Cập nhật course_id còn thiếu bằng một giá trị có trong bảng course 
cursor.execute('''
UPDATE student 
SET course_id = 26 
WHERE course_id IS NULL;
''')

# Loại bỏ các bản ghi có course_id không tồn tại 
cursor.execute('''
DELETE FROM student 
WHERE course_id NOT IN (SELECT id FROM course);
''')
conn.commit()

run_query("SELECT * FROM student", "Bảng student sau khi Cập nhật và Xóa")

# a. Tổng số sinh viên, điểm trung bình của từng lớp 
run_query('''
SELECT class, COUNT(student_id) as tong_sv, AVG(score) as diem_tb 
FROM student 
GROUP BY class;
''', "2a. Thống kê theo lớp")

# b. Tổng số sinh viên, điểm trung bình của từng môn học 
run_query('''
SELECT c.course_name, COUNT(s.student_id) as tong_sv, AVG(s.score) as diem_tb 
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name;
''', "2b. Thống kê theo môn học")

# c. Phân loại thi đua theo điểm số môn học 
run_query('''
SELECT name, score, c.course_name,
    CASE 
        WHEN score >= 9.0 THEN 'Xuất sắc'
        WHEN score >= 6.0 AND score <= 8.9 THEN 'Tốt'
        WHEN score < 6.0 THEN 'Kém'
    END as xep_loai
FROM student s
JOIN course c ON s.course_id = c.id;
''', "2c. Phân loại thi đua (Xuất sắc, Tốt, Kém)")

Bảng student sau khi Cập nhật và Xóa

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

2a. Thống kê theo lớp

      class  tong_sv   diem_tb
0   Kinh Te        3  8.533333
1  May Tinh        2  6.850000
2  Toan Tin        1  7.900000

2b. Thống kê theo môn học

  course_name  tong_sv   diem_tb
0   Giai tich        1  6.700000
1    Thong ke        2  9.200000
2     Tin hoc        3  7.366667

2c. Phân loại thi đua (Xuất sắc [cite: 15], Tốt [cite: 16], Kém [cite: 17])

                name  score course_name  xep_loai
0  Nguyen Minh Hoang    6.7   Giai tich       Tốt
1       Tran Thi Lan    9.2    Thong ke  Xuất sắc
2       Pham Van Nam    7.9     Tin hoc       Tốt
3      Bui Tien Dung    9.2    Thong ke  Xuất sắc
4     Duong Huu Phuc    7.2     Tin hoc       Tốt
5       Cao Thi Hanh    7.0     Tin hoc       Tốt

In [ ]:
# a. Xếp hạng tổng thể theo Điểm số 
run_query('''
WITH Ranked AS (
    SELECT student_id, name, score, 
           RANK() OVER (ORDER BY score DESC) as rank_cao_nhat,
           RANK() OVER (ORDER BY score ASC) as rank_thap_nhat
    FROM student
)
SELECT * FROM Ranked WHERE rank_cao_nhat <= 3 OR rank_thap_nhat <= 3
ORDER BY score DESC;
''', "3a. Top 3 cao nhất và thấp nhất theo toàn bộ điểm số")

# b. Xếp hạng theo lớp học  
run_query('''
WITH RankedClass AS (
    SELECT student_id, name, class, score,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_cao_nhat,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) as rank_thap_nhat
    FROM student
)
SELECT * FROM RankedClass WHERE rank_cao_nhat <= 3 OR rank_thap_nhat <= 3
ORDER BY class, score DESC;
''', "3b. Top 3 cao nhất/thấp nhất trong từng Lớp")

# c. Xếp hạng theo môn học  
run_query('''
WITH RankedCourse AS (
    SELECT student_id, name, course_id, score,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_cao_nhat,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) as rank_thap_nhat
    FROM student
)
SELECT * FROM RankedCourse WHERE rank_cao_nhat <= 3 OR rank_thap_nhat <= 3
ORDER BY course_id, score DESC;
''', "3c. Top 3 cao nhất/thấp nhất trong từng Môn học")

3a. Top 3 cao nhất và thấp nhất theo toàn bộ điểm số

   student_id               name  score  rank_cao_nhat  rank_thap_nhat
0           2       Tran Thi Lan    9.2              1               5
1           7      Bui Tien Dung    9.2              1               5
2           3       Pham Van Nam    7.9              3               4
3           9     Duong Huu Phuc    7.2              4               3
4          10       Cao Thi Hanh    7.0              5               2
5           1  Nguyen Minh Hoang    6.7              6               1

3b. Top 3 cao nhất/thấp nhất trong từng Lớp

,student_id,name,class,score,rank_cao_nhat,rank_thap_nhat
0,2,Tran Thi Lan,Kinh Te,9.2,1,2
1,7,Bui Tien Dung,Kinh Te,9.2,1,2
2,9,Duong Huu Phuc,Kinh Te,7.2,3,1
3,10,Cao Thi Hanh,May Tinh,7.0,1,2
4,1,Nguyen Minh Hoang,May Tinh,6.7,2,1
5,3,Pham Van Nam,Toan Tin,7.9,1,1

3c. Top 3 cao nhất/thấp nhất trong từng Môn học

,student_id,name,course_id,score,rank_cao_nhat,rank_thap_nhat
0,1,Nguyen Minh Hoang,12,6.7,1,1
1,3,Pham Van Nam,26,7.9,1,3
2,9,Duong Huu Phuc,26,7.2,2,2
3,10,Cao Thi Hanh,26,7.0,3,1
4,2,Tran Thi Lan,34,9.2,1,1
5,7,Bui Tien Dung,34,9.2,1,1

In [10]:
# Bổ sung trường graduation_date với kiểu DATETIME 
cursor.execute('''
ALTER TABLE student ADD COLUMN graduation_date DATETIME;
''')

# Cập nhật thời gian
cursor.execute('''
WITH RankData AS (
    SELECT student_id, RANK() OVER (ORDER BY score DESC) as rnk 
    FROM student
)
UPDATE student
SET graduation_date = datetime('now', '+' || (SELECT rnk FROM RankData WHERE RankData.student_id = student.student_id) || ' days');
''')
conn.commit()

run_query("SELECT student_id, name, score, graduation_date FROM student ORDER BY score DESC;", "4. Cập nhật ngày tốt nghiệp theo thứ hạng")

conn.close()

4. Cập nhật ngày tốt nghiệp theo thứ hạng

   student_id               name  score      graduation_date
0           2       Tran Thi Lan    9.2  2026-03-31 14:14:45
1           7      Bui Tien Dung    9.2  2026-03-31 14:14:45
2           3       Pham Van Nam    7.9  2026-04-02 14:14:45
3           9     Duong Huu Phuc    7.2  2026-04-03 14:14:45
4          10       Cao Thi Hanh    7.0  2026-04-04 14:14:45
5           1  Nguyen Minh Hoang    6.7  2026-04-05 14:14:45