## Tạo bảng

### Tạo bảng student

In [ ]:
import sqlite3
import pandas as pd

conn = sqlite3.connect('student.db')
cursor = conn.cursor()

cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

### Tạo bảng course

In [ ]:
cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

### Insert dữ liệu

In [ ]:
cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", [
(1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
(2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
(3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
(4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
(5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
(6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
(7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
(8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
(9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
(10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
])

cursor.executemany("INSERT INTO course VALUES (?,?)", [
(12, 'Giai tich'),
(34, 'Thong ke'),
(26, 'Tin hoc')
])

conn.commit()

## 1. JOIN & DECARTES

### Tích Descartes

In [ ]:
pd.read_sql_query("SELECT * FROM student, course", conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

### INNER JOIN

In [ ]:
pd.read_sql_query("""
SELECT * FROM student
INNER JOIN course
ON student.course_id = course.id
""", conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

### LEFT JOIN

In [ ]:
pd.read_sql_query("""
SELECT * FROM student
LEFT JOIN course
ON student.course_id = course.id
""", conn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

### RIGHT JOIN (giả lập)

In [ ]:
pd.read_sql_query("""
SELECT * FROM course
LEFT JOIN student
ON student.course_id = course.id
""", conn)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin hoc         NaN               None      None        NaN    NaN

### FULL OUTER JOIN (SQLite giả lập)

In [ ]:
pd.read_sql_query("""
SELECT * FROM student
LEFT JOIN course ON student.course_id = course.id
UNION
SELECT * FROM course
LEFT JOIN student ON student.course_id = course.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

**Nhận xét JOIN & Tích Descartes**

Tích Descartes (CROSS JOIN) tạo ra tất cả các tổ hợp có thể giữa hai bảng, dẫn đến số lượng bản ghi rất lớn và thường không có ý nghĩa thực tế.

INNER JOIN chỉ lấy các bản ghi có khóa khớp giữa hai bảng, đảm bảo tính chính xác của dữ liệu liên kết.

LEFT JOIN giữ lại toàn bộ dữ liệu từ bảng student, kể cả khi không có thông tin tương ứng trong bảng course.

RIGHT JOIN (giả lập trong SQLite) giữ lại toàn bộ dữ liệu từ bảng course.

FULL OUTER JOIN kết hợp cả hai bảng, đảm bảo không mất dữ liệu ở bất kỳ phía nào.

## 2. Xử lý dữ liệu

### Xóa các course_id không tồn tại (20, 24)

In [ ]:
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

### Cập nhật NULL

In [ ]:
cursor.execute("""
UPDATE student
SET course_id = 12
WHERE course_id IS NULL
""")

conn.commit()

### Theo lớp

In [ ]:
pd.read_sql_query("""
SELECT class,
COUNT(*) AS total_students,
AVG(score) AS avg_score
FROM student
GROUP BY class
""", conn)

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               2   6.850000
2  Toan Tin               1   7.900000

### Theo môn học

In [ ]:
pd.read_sql_query("""
SELECT course_name,
COUNT(*) AS total_students,
AVG(score) AS avg_score
FROM student
JOIN course ON student.course_id = course.id
GROUP BY course_name
""", conn)

  course_name  total_students  avg_score
0   Giai tich               4        7.2
1    Thong ke               2        9.2

### Phân loại

In [ ]:
pd.read_sql_query("""
SELECT name, score,
CASE
    WHEN score >= 9 THEN 'Xuất sắc'
    WHEN score >= 6 THEN 'Tốt'
    ELSE 'Kém'
END AS classification
FROM student
""", conn)

                name  score classification
0  Nguyen Minh Hoang    6.7            Tốt
1       Tran Thi Lan    9.2       Xuất sắc
2       Pham Van Nam    7.9            Tốt
3      Bui Tien Dung    9.2       Xuất sắc
4     Duong Huu Phuc    7.2            Tốt
5       Cao Thi Hanh    7.0            Tốt

Nhận xét xử lý dữ liệu

Dữ liệu ban đầu tồn tại các giá trị course_id không hợp lệ (không có trong bảng course) và giá trị NULL.

Việc loại bỏ các bản ghi không hợp lệ giúp đảm bảo tính toàn vẹn dữ liệu.
Việc cập nhật các giá trị NULL giúp dữ liệu đầy đủ hơn để phục vụ cho phân tích.
Sau khi xử lý, dữ liệu đã sạch và sẵn sàng cho các phép tính thống kê.

## 3. Xếp hạng

### Toàn bộ

In [ ]:
pd.read_sql_query("""
SELECT name, score,
RANK() OVER (ORDER BY score DESC) AS rank
FROM student
""", conn)

                name  score  rank
0       Tran Thi Lan    9.2     1
1      Bui Tien Dung    9.2     1
2       Pham Van Nam    7.9     3
3     Duong Huu Phuc    7.2     4
4       Cao Thi Hanh    7.0     5
5  Nguyen Minh Hoang    6.7     6

### Theo lớp

In [ ]:
pd.read_sql_query("""
SELECT name, class, score,
RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank
FROM student
""", conn)

                name     class  score  rank
0       Tran Thi Lan   Kinh Te    9.2     1
1      Bui Tien Dung   Kinh Te    9.2     1
2     Duong Huu Phuc   Kinh Te    7.2     3
3       Cao Thi Hanh  May Tinh    7.0     1
4  Nguyen Minh Hoang  May Tinh    6.7     2
5       Pham Van Nam  Toan Tin    7.9     1

### Theo môn

In [ ]:
pd.read_sql_query("""
SELECT name, course_id, score,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank
FROM student
""", conn)

                name  course_id  score  rank
0       Pham Van Nam         12    7.9     1
1     Duong Huu Phuc         12    7.2     2
2       Cao Thi Hanh         12    7.0     3
3  Nguyen Minh Hoang         12    6.7     4
4       Tran Thi Lan         34    9.2     1
5      Bui Tien Dung         34    9.2     1

### Top 3 cao nhất

In [ ]:
pd.read_sql_query("""
SELECT * FROM (
    SELECT name, score,
    RANK() OVER (ORDER BY score DESC) as rank
    FROM student
)
WHERE rank <= 3
""", conn)

            name  score  rank
0   Tran Thi Lan    9.2     1
1  Bui Tien Dung    9.2     1
2   Pham Van Nam    7.9     3

### Top 3 thấp nhất

In [ ]:
pd.read_sql_query("""
SELECT * FROM (
    SELECT name, score,
    RANK() OVER (ORDER BY score ASC) as rank
    FROM student
)
WHERE rank <= 3
""", conn)

                name  score  rank
0  Nguyen Minh Hoang    6.7     1
1       Cao Thi Hanh    7.0     2
2     Duong Huu Phuc    7.2     3

## 4. graduation_date

### Thêm cột

In [30]:
columns = pd.read_sql_query("PRAGMA table_info(student)", conn)

if 'graduation_date' not in columns['name'].values:
    cursor.execute("""
    ALTER TABLE student ADD COLUMN graduation_date DATETIME
    """)

### Update theo rank

In [31]:
pd.read_sql_query("""
SELECT name, score,
RANK() OVER (ORDER BY score DESC) as rank,
graduation_date
FROM student
""", conn)

                name  score  rank      graduation_date
0       Tran Thi Lan    9.2     1  2026-04-03 11:16:51
1      Bui Tien Dung    9.2     1  2026-04-03 11:16:51
2       Pham Van Nam    7.9     3  2026-04-04 11:16:51
3     Duong Huu Phuc    7.2     4  2026-04-05 11:16:51
4       Cao Thi Hanh    7.0     5  2026-04-06 11:16:51
5  Nguyen Minh Hoang    6.7     6  2026-04-07 11:16:51

**Nhận xét graduation_date**

Thời gian tốt nghiệp được xác định dựa trên thứ hạng điểm số của sinh viên.
Sinh viên có điểm cao hơn sẽ có thứ hạng cao hơn và tốt nghiệp sớm hơn.
Các sinh viên có cùng điểm số sẽ có cùng thời gian tốt nghiệp.
Sinh viên có điểm thấp hơn sẽ tốt nghiệp muộn hơn tương ứng với thứ hạng của mình.