In [1]:
import sqlite3 
import pandas as pd 

conn = sqlite3.connect(":memory:")
cur = conn.cursor()

cur.execute("""
CREATE TABLE student(
    student_id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    class TEXT NOT NULL,
    course_id INTEGER,
    score REAL
)            
""")

cur.execute("""
CREATE TABLE course(
    id INTEGER PRIMARY KEY,
    course_name TEXT NOT NULL
)
""")

students = [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
]

courses = [
(12,"Giai tich"),
(34,"Thong ke"),
(26,"Tin hoc")
]

cur.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)
cur.executemany("INSERT INTO course VALUES (?,?)", courses)
conn.commit()
display(pd.read_sql_query('SELECT * FROM student;', conn))
display(pd.read_sql_query('SELECT * FROM course;', conn))

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

   id course_name
0  12   Giai tich
1  26     Tin hoc
2  34    Thong ke

1. Hãy kết nối hai bảng trên theo những cách sau: 
- Sử dụng tích Decartes. 
- Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.

In [4]:
# Tích decartes
decartes = """
SELECT *
FROM student, course
"""
df_decartes = pd.read_sql_query(decartes, conn)
print(df_decartes)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

In [5]:
# inner join
query_inner = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM student s
INNER JOIN course c
    ON s.course_id = c.id
"""
df_inner = pd.read_sql_query(query_inner, conn)
print(df_inner)

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

In [6]:
# left join
query_left = """
SELECT s.student_id, s.name, s.class, s.course_id,s.score, c.course_name
FROM student s
LEFT JOIN course c
    ON s.course_id = c.id
"""
df_left = pd.read_sql_query(query_left, conn)
print(df_left)

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [7]:
# right join
query_right = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.course_name
FROM course c
LEFT JOIN student s
    ON s.course_id = c.id
"""
df_right = pd.read_sql_query(query_right, conn)
print(df_right)

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         NaN               None      None        NaN    NaN     Tin hoc
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke

In [8]:
# full join
query_full = """
SELECT s.student_id, s.name, s.class, s.course_id, s.score, c.id AS course_table_id, c.course_name
FROM student s
LEFT JOIN course c
    ON s.course_id = c.id

UNION

SELECT  s.student_id, s.name, s.class, s.course_id, s.score, c.id AS course_table_id, c.course_name
FROM course c
LEFT JOIN student s
    ON s.course_id = c.id
"""
df_full = pd.read_sql_query(query_full, conn)
print(df_full)

    student_id               name     class  course_id  score  \
0          NaN               None      None        NaN    NaN
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0

    course_table_id course_name
0              26.0     Tin hoc
1              12.0   Giai tich
2              34.0    Thong ke
3               NaN        None
4               NaN        None
5               NaN        None
6               NaN        None
7              34.0    Thong ke
8               NaN        None
9               NaN        None
10              NaN        None

2. Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL, 
trong đó các giá trị được điền là những giá trị nằm trong bảng course  và loại bỏ những 
bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết: 

a. Tổng số sinh viên, điểm trung bình của từng lớp. 

b. Tổng số sinh viên, điểm trung bình của từng môn học. 

c. Phân loại thi đua theo số điểm của từng môn học biết: 
- Điểm TB ≥  9.0: Xuất sắc. 
- 6.0 ≤ Điểm TB ≤ 8.9: Tốt. 
- Điểm TB < 6.0: Kém.

In [14]:
# 1. Cập nhật course_id còn thiếu
cur.execute("""
UPDATE student
SET course_id = (SELECT MIN(id) FROM course)
WHERE course_id IS NULL
""")

# 2. Xóa những bản ghi có môn học không tồn tại
cur.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")
conn.commit()

In [ ]:
# a. Tổng số sinh viên, điểm trung bình từng lớp
query_a = """
SELECT  class,
    COUNT(*) AS tong_so_sinh_vien,
    ROUND(AVG(score), 2) AS diem_trung_binh
FROM student
GROUP BY class
"""
print("Tổng số sinh viên và điểm trung bình theo từng lớp: ")
print(pd.read_sql_query(query_a, conn))

Tổng số sinh viên và điểm trung bình theo từng lớp:
      class  tong_so_sinh_vien  diem_trung_binh
0   Kinh Te                  3             8.53
1  May Tinh                  2             6.85
2  Toan Tin                  1             7.90

In [17]:
# b. Tổng số sinh viên, điểm trung bình của từng môn học
query_b = """
SELECT c.course_name,
    COUNT(s.student_id) AS tong_so_sinh_vien,
    ROUND(AVG(s.score), 2) AS diem_trung_binh
FROM course c
LEFT JOIN student s
    ON s.course_id = c.id
GROUP BY c.id, c.course_name
"""
print("\n Tổng số sinh viên, điểm trung bình của từng môn học: ")
print(pd.read_sql_query(query_b, conn))

 Tổng số sinh viên, điểm trung bình của từng môn học:
  course_name  tong_so_sinh_vien  diem_trung_binh
0   Giai tich                  2             7.30
1     Tin hoc                  1             7.20
2    Thong ke                  3             8.47

In [18]:
# c. Phân loại thi đua
query_c = """
SELECT c.course_name,
    COUNT(s.student_id) AS tong_so_sinh_vien,
    ROUND(AVG(s.score), 2) AS diem_trung_binh,
    CASE
        WHEN AVG(s.score) >= 9.0 THEN 'Xuất sắc'
        WHEN AVG(s.score) >= 6.0 AND AVG(s.score) <= 8.9 THEN 'Tốt'
        WHEN AVG(s.score) < 6.0 THEN 'Kém'
        ELSE 'Chưa có dữ liệu'
    END AS xep_loai
FROM course c
LEFT JOIN student s
    ON s.course_id = c.id
GROUP BY c.id, c.course_name
"""
print("\nPhân loại thi đua: ")
print(pd.read_sql_query(query_c, conn))

Phân loại thi đua:
  course_name  tong_so_sinh_vien  diem_trung_binh xep_loai
0   Giai tich                  2             7.30      Tốt
1     Tin hoc                  1             7.20      Tốt
2    Thong ke                  3             8.47      Tốt

3. Hãy xếp hạng sinh viên thông qua: 

a. Điểm số. 

b. Điểm số theo lớp học. 

c. Điểm số theo mã môn học. 

và cho biết top 3 sinh viện đạt thứ hạng cao nhất, top 3 sinh viên đạt thứ hạng thấp nhất theo 
từng trường hợp trên.

In [24]:
# Xếp hạng điểm số
rank_diem_so = """
SELECT *
FROM (
    SELECT
        student_id,
        name,
        class,
        course_id,
        score,
        ROW_NUMBER() OVER (ORDER BY score DESC) AS rank_high
    FROM student
)
"""

df_diem_so = pd.read_sql_query(rank_diem_so, conn)
print(df_diem_so)

   student_id               name     class  course_id  score  rank_high
0           2       Tran Thi Lan   Kinh Te         34    9.2          1
1           7      Bui Tien Dung   Kinh Te         34    9.2          2
2           3       Pham Van Nam  Toan Tin         12    7.9          3
3           9     Duong Huu Phuc   Kinh Te         26    7.2          4
4          10       Cao Thi Hanh  May Tinh         34    7.0          5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7          6

In [23]:
query_a_top3_high = """
SELECT *
FROM (
    SELECT
        student_id,
        name,
        class,
        course_id,
        score,
        ROW_NUMBER() OVER (ORDER BY score DESC) AS rank_high
    FROM student
)
WHERE rank_high <= 3
"""

df_a_top3_high = pd.read_sql_query(query_a_top3_high, conn)
print(df_a_top3_high)

   student_id           name     class  course_id  score  rank_high
0           2   Tran Thi Lan   Kinh Te         34    9.2          1
1           7  Bui Tien Dung   Kinh Te         34    9.2          2
2           3   Pham Van Nam  Toan Tin         12    7.9          3

In [32]:
# Xếp hạng điểm số theo lớp học
lop_hoc =(""" 
SELECT
    student_id,
    name,
    class,
    course_id,
    score,
    DENSE_RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_in_class_high
FROM student;
""")
df_lop_hoc = pd.read_sql_query(lop_hoc, conn)
print(df_lop_hoc)

   student_id               name     class  course_id  score  \
0           2       Tran Thi Lan   Kinh Te         34    9.2
1           7      Bui Tien Dung   Kinh Te         34    9.2
2           9     Duong Huu Phuc   Kinh Te         26    7.2
3          10       Cao Thi Hanh  May Tinh         34    7.0
4           1  Nguyen Minh Hoang  May Tinh         12    6.7
5           3       Pham Van Nam  Toan Tin         12    7.9

   rank_in_class_high
0                   1
1                   1
2                   2
3                   1
4                   2
5                   1

In [31]:
query_b_high = """
SELECT *
FROM (
    SELECT
        student_id, name, class, course_id, score,
        ROW_NUMBER() OVER (PARTITION BY class ORDER BY score DESC) AS ranking
    FROM student
)
WHERE ranking <= 3
ORDER BY class, ranking
"""
print("\nTop 3 cao nhất theo lớp:")
print(pd.read_sql_query(query_b_high, conn))

Top 3 cao nhất theo lớp:
   student_id               name     class  course_id  score  ranking
0           2       Tran Thi Lan   Kinh Te         34    9.2        1
1           7      Bui Tien Dung   Kinh Te         34    9.2        2
2           9     Duong Huu Phuc   Kinh Te         26    7.2        3
3          10       Cao Thi Hanh  May Tinh         34    7.0        1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7        2
5           3       Pham Van Nam  Toan Tin         12    7.9        1

In [34]:
# Xếp hạng điểm số theo mã môn học
ma_mon_hoc = """
SELECT *
FROM (
    SELECT
        student_id, name, class, course_id, score,
        DENSE_RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS ranking
    FROM student
)
WHERE ranking <= 3
ORDER BY course_id, ranking
"""
df_ma_mon_hoc = pd.read_sql_query(ma_mon_hoc, conn)
print(df_ma_mon_hoc)

   student_id               name     class  course_id  score  ranking
0           3       Pham Van Nam  Toan Tin         12    7.9        1
1           1  Nguyen Minh Hoang  May Tinh         12    6.7        2
2           9     Duong Huu Phuc   Kinh Te         26    7.2        1
3           2       Tran Thi Lan   Kinh Te         34    9.2        1
4           7      Bui Tien Dung   Kinh Te         34    9.2        1
5          10       Cao Thi Hanh  May Tinh         34    7.0        2

In [35]:
query_c_top3_high = """
SELECT *
FROM (
    SELECT
        student_id,
        name,
        class,
        course_id,
        score,
        RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_in_course_high
    FROM student
)
WHERE rank_in_course_high <= 3
ORDER BY course_id, rank_in_course_high, score DESC
"""

df_c_top3_high = pd.read_sql_query(query_c_top3_high, conn)
print(df_c_top3_high)

   student_id               name     class  course_id  score  \
0           3       Pham Van Nam  Toan Tin         12    7.9
1           1  Nguyen Minh Hoang  May Tinh         12    6.7
2           9     Duong Huu Phuc   Kinh Te         26    7.2
3           2       Tran Thi Lan   Kinh Te         34    9.2
4           7      Bui Tien Dung   Kinh Te         34    9.2
5          10       Cao Thi Hanh  May Tinh         34    7.0

   rank_in_course_high
0                    1
1                    2
2                    1
3                    1
4                    1
5                    3

4. Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng 
student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được 
xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số.

In [36]:
cur.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME")

cur.execute("""
UPDATE student
SET graduation_date = datetime('now', '+' || CAST(score AS INTEGER) || ' days')
""")

conn.commit()

print("\n--- STUDENT SAU KHI THÊM GRADUATION DATE ---")
print(pd.read_sql("SELECT * FROM student", conn))

--- STUDENT SAU KHI THÊM GRADUATION DATE ---
   student_id               name     class  course_id  score  \
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         12    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         34    7.0

       graduation_date
0  2026-04-09 15:32:46
1  2026-04-12 15:32:46
2  2026-04-10 15:32:46
3  2026-04-12 15:32:46
4  2026-04-10 15:32:46
5  2026-04-10 15:32:46