# BÀI TẬP CHƯƠNG 2

## 1.Hãy kết nối hai bảng trên theo những cách sau:

Chuẩn bị dữ liệu

In [42]:
import sqlite3
import pandas as pd

# ==============================
# Tạo database in-memory
# ==============================
conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# ==============================
# Tạo bảng (có IF NOT EXISTS)
# ==============================
cursor.execute("""
CREATE TABLE IF NOT EXISTS course(
    id INTEGER PRIMARY KEY,
    course_name TEXT
)
""")

cursor.execute("""
CREATE TABLE IF NOT EXISTS student(
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# ==============================
# Thêm dữ liệu bảng course
# ==============================
courses = [
    (12, "Giai tich"),
    (34, "Thong ke"),
    (26, "Tin hoc")
]

cursor.executemany(
    "INSERT INTO course VALUES (?, ?)",
    courses
)

# ==============================
# Thêm dữ liệu bảng student
# ==============================
students = [
    [1,"Nguyen Minh Hoang","May Tinh",12,6.7],
    [2,"Tran Thi Lan","Kinh Te",34,9.2],
    [3,"Pham Van Nam","Toan Tin",None,7.9],
    [4,"Le Thanh Huyen","Toan Tin",20,7.2],
    [5,"Vu Quoc Anh","May Tinh",24,8.0],
    [6,"Dang Thuy Linh","May Tinh",24,5.5],
    [7,"Bui Tien Dung","Kinh Te",34,9.2],
    [8,"Ho Ngoc Mai","Toan Tin",20,8.8],
    [9,"Duong Huu Phuc","Kinh Te",None,7.2],
    [10,"Cao Thi Hanh","May Tinh",None,7.0]
]

cursor.executemany("""
INSERT INTO student(student_id, name, class, course_id, score)
VALUES (?, ?, ?, ?, ?)
""", students)

conn.commit()

# ==============================
# Hiển thị dữ liệu (có sort)
# ==============================
df_course = pd.read_sql("SELECT * FROM course ORDER BY id", conn)
df_student = pd.read_sql("SELECT * FROM student ORDER BY student_id", conn)

print("=== BANG COURSE ===")
print(df_course.to_string(index=False))

print("\n=== BANG STUDENT ===")
print(df_student.to_string(index=False))

=== BANG COURSE ===
 id course_name
 12   Giai tich
 26     Tin hoc
 34    Thong ke

=== BANG STUDENT ===
 student_id              name    class  course_id  score
          1 Nguyen Minh Hoang May Tinh       12.0    6.7
          2      Tran Thi Lan  Kinh Te       34.0    9.2
          3      Pham Van Nam Toan Tin        NaN    7.9
          4    Le Thanh Huyen Toan Tin       20.0    7.2
          5       Vu Quoc Anh May Tinh       24.0    8.0
          6    Dang Thuy Linh May Tinh       24.0    5.5
          7     Bui Tien Dung  Kinh Te       34.0    9.2
          8       Ho Ngoc Mai Toan Tin       20.0    8.8
          9    Duong Huu Phuc  Kinh Te        NaN    7.2
         10      Cao Thi Hanh May Tinh        NaN    7.0

### Sử dụng tích Decartes.

In [44]:
print(" Tích Descartes")

sql_cartesian = """
SELECT
    st.student_id,
    st.name,
    st.class,
    cr.course_name,
    cr.id AS course_id,
    st.score
FROM student st, course cr
"""

cartesian_result = pd.read_sql(sql_cartesian, conn)
print(cartesian_result)

 Tích Descartes
    student_id               name     class course_name  course_id  score
0            1  Nguyen Minh Hoang  May Tinh   Giai tich         12    6.7
1            1  Nguyen Minh Hoang  May Tinh     Tin hoc         26    6.7
2            1  Nguyen Minh Hoang  May Tinh    Thong ke         34    6.7
3            2       Tran Thi Lan   Kinh Te   Giai tich         12    9.2
4            2       Tran Thi Lan   Kinh Te     Tin hoc         26    9.2
5            2       Tran Thi Lan   Kinh Te    Thong ke         34    9.2
6            3       Pham Van Nam  Toan Tin   Giai tich         12    7.9
7            3       Pham Van Nam  Toan Tin     Tin hoc         26    7.9
8            3       Pham Van Nam  Toan Tin    Thong ke         34    7.9
9            4     Le Thanh Huyen  Toan Tin   Giai tich         12    7.2
10           4     Le Thanh Huyen  Toan Tin     Tin hoc         26    7.2
11           4     Le Thanh Huyen  Toan Tin    Thong ke         34    7.2
12           5        Vu Quoc Anh  May Tinh   Giai tich         12    8.0
13           5        Vu Quoc Anh  May Tinh     Tin hoc         26    8.0
14           5        Vu Quoc Anh  May Tinh    Thong ke         34    8.0
15           6     Dang Thuy Linh  May Tinh   Giai tich         12    5.5
16           6     Dang Thuy Linh  May Tinh     Tin hoc         26    5.5
17           6     Dang Thuy Linh  May Tinh    Thong ke         34    5.5
18           7      Bui Tien Dung   Kinh Te   Giai tich         12    9.2
19           7      Bui Tien Dung   Kinh Te     Tin hoc         26    9.2
20           7      Bui Tien Dung   Kinh Te    Thong ke         34    9.2
21           8        Ho Ngoc Mai  Toan Tin   Giai tich         12    8.8
22           8        Ho Ngoc Mai  Toan Tin     Tin hoc         26    8.8
23           8        Ho Ngoc Mai  Toan Tin    Thong ke         34    8.8
24           9     Duong Huu Phuc   Kinh Te   Giai tich         12    7.2
25           9     Duong Huu Phuc   Kinh Te     Tin hoc         26    7.2
26           9     Duong Huu Phuc   Kinh Te    Thong ke         34    7.2
27          10       Cao Thi Hanh  May Tinh   Giai tich         12    7.0
28          10       Cao Thi Hanh  May Tinh     Tin hoc         26    7.0
29          10       Cao Thi Hanh  May Tinh    Thong ke         34    7.0

Kết luận:

Qua phép nối bằng tích Descartes, ta thấy mỗi sinh viên được kết hợp với tất cả các môn học trong bảng course, không phụ thuộc vào việc sinh viên đó thực sự có đăng ký môn học hay không. Điều này làm cho số lượng bản ghi tăng lên rất lớn và thường chỉ được sử dụng trong các trường hợp đặc biệt. Vì vậy, tích Descartes không phản ánh đúng mối quan hệ thực tế giữa hai bảng mà chỉ mang tính chất kết hợp toàn bộ dữ liệu để phục vụ các mục đích xử lý hoặc kiểm tra.

### Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.

#### INNER JOIN

In [45]:
query = """
SELECT *
FROM Student
INNER JOIN course
ON Student.course_id = course.id
"""
df = pd.read_sql(query, conn)

display(df)
print("Số dòng:", len(df))

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

Số dòng: 3

Kết luận:

Chỉ giữ các bản ghi course_id trùng với id

Loại bỏ:

course_id = NULL

course_id không tồn tại (20, 24)

#### LEFT JOIN

In [10]:
query = """
SELECT *
FROM Student
LEFT JOIN course
ON Student.course_id = course.id
"""
df = pd.read_sql(query, conn)

display(df)
print("Số dòng:", len(df))

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

Số dòng: 10

Kết luận:
Giữ toàn bộ bảng Student
Nếu không có khóa học → course_name = NULL
Thấy rõ sinh viên chưa có hoặc sai course_id

#### RIGHT JOIN

In [47]:
sql_right = """
SELECT
    cr.id AS course_id,
    cr.course_name,
    st.student_id,
    st.name,
    st.class,
    st.score
FROM course cr
LEFT JOIN student st
ON cr.id = st.course_id
"""

right_result = pd.read_sql(sql_right, conn)
print(right_result)

   course_id course_name  student_id               name     class  score
0         12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh    6.7
1         26     Tin hoc         NaN               None      None    NaN
2         34    Thong ke         7.0      Bui Tien Dung   Kinh Te    9.2
3         34    Thong ke         2.0       Tran Thi Lan   Kinh Te    9.2

Nhận xét:

Phép nối này thực chất tương đương với RIGHT JOIN (do lấy bảng course làm bên trái trong LEFT JOIN), nên toàn bộ các môn học đều được giữ lại. Những môn học có sinh viên đăng ký sẽ hiển thị đầy đủ thông tin sinh viên tương ứng, trong khi môn học không có sinh viên (như Tin học) sẽ có các giá trị NULL ở phía bảng student. Điều này cho thấy phép nối giúp phát hiện các dữ liệu chưa có liên kết giữa hai bảng.

#### FULL OUTER JOIN

In [48]:
query = """
SELECT
    Student.student_id,
    Student.name,
    Student.class,
    Student.course_id,
    Student.score,
    course.id,
    course.course_name
FROM Student
LEFT JOIN course
ON Student.course_id = course.id

UNION

SELECT
    Student.student_id,
    Student.name,
    Student.class,
    Student.course_id,
    Student.score,
    course.id,
    course.course_name
FROM course
LEFT JOIN Student
ON Student.course_id = course.id
"""
df = pd.read_sql(query, conn)

display(df)
print("Số dòng:", len(df))

,student_id,name,class,course_id,score,id,course_name
0,NaN,None,None,NaN,NaN,26.0,Tin hoc
1,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
2,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
3,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
4,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
5,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
6,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None

Số dòng: 11

## 2.Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL, trong đó các giá trị được điền là những giá trị nằm trong bảng course và loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết:

In [74]:
# 1. UPDATE
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
""")

# 2. DELETE
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

conn.commit()

# 👉 3. THÊM Ở ĐÂY (ngay sau khi làm sạch)
cursor.execute("""
INSERT INTO student (student_id, name, class, course_id, score)
VALUES (11, 'Nguyen Van A', 'May Tinh', 26, 8.5)
""")

conn.commit()

Kết luận:


Sau khi thực hiện cập nhật và làm sạch dữ liệu, các giá trị course_id bị thiếu đã được bổ sung bằng những giá trị hợp lệ từ bảng course, đồng thời các bản ghi có course_id không tồn tại cũng đã được loại bỏ. Nhờ đó, bảng student chỉ còn các dữ liệu có liên kết hợp lệ với bảng course, đảm bảo tính toàn vẹn và nhất quán của cơ sở dữ liệu. Điều này giúp cho các phép nối bảng và các truy vấn phân tích sau đó cho kết quả chính xác và đáng tin cậy hơn.

### a. Tổng số sinh viên, điểm trung bình của từng lớp.

In [69]:
sql_a = """
SELECT
    class,
    COUNT(student_id) AS tong_sinh_vien,
    ROUND(AVG(score), 2) AS diem_trung_binh
FROM student
GROUP BY class
ORDER BY class
"""

result_a = pd.read_sql(sql_a, conn)
print(result_a)

      class  tong_sinh_vien  diem_trung_binh
0   Kinh Te               3             8.53
1  May Tinh               2             6.85
2  Toan Tin               1             7.90

Kết luận

Kết quả cho thấy mỗi lớp có số lượng sinh viên và mức điểm trung bình khác nhau, phản ánh sự chênh lệch về quy mô và chất lượng học tập giữa các lớp. Thông qua đó, có thể đánh giá tổng quan hiệu quả học tập của từng lớp, từ đó hỗ trợ việc so sánh và đưa ra các biện pháp cải thiện phù hợp.

### b. Tổng số sinh viên, điểm trung bình theo môn học

In [75]:
df_course = pd.read_sql_query("""
SELECT c.course_name,
       COUNT(s.student_id) AS total_students,
       AVG(s.score) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

print(df_course)

  course_name  total_students  avg_score
0   Giai tich               4        7.2
1    Thong ke               2        9.2
2     Tin hoc               1        8.5

Kết luận

Kết quả cho thấy mỗi môn học có số lượng sinh viên tham gia và điểm trung bình khác nhau. Điều này phản ánh mức độ phân bổ sinh viên giữa các môn học cũng như kết quả học tập tương ứng. Những môn có điểm trung bình cao cho thấy sinh viên nắm vững kiến thức hơn, trong khi các môn có điểm thấp hơn có thể cần được xem xét để cải thiện phương pháp giảng dạy hoặc hỗ trợ học tập.

### c. Phân loại theo điểm trung bình từng môn

i. Điểm TB ≥ 9.0: Xuất sắc.

ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.

iii. Điểm TB < 6.0: Kém.

In [76]:
print("=== PHAN LOAI MON HOC ===")

sql_c = """
SELECT
    c.course_name,
    ROUND(AVG(s.score), 2) AS diem_trung_binh,
    CASE
        WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
        WHEN AVG(s.score) BETWEEN 6.0 AND 8.9 THEN 'Tot'
        ELSE 'Kem'
    END AS xep_loai
FROM course c
LEFT JOIN student s ON c.id = s.course_id
GROUP BY c.course_name
ORDER BY c.course_name
"""

result_c = pd.read_sql(sql_c, conn)
print(result_c)

=== PHAN LOAI MON HOC ===
  course_name  diem_trung_binh  xep_loai
0   Giai tich              7.2       Tot
1    Thong ke              9.2  Xuat sac
2     Tin hoc              8.5       Tot

Kết luận

Kết quả phân loại cho thấy mỗi môn học được xếp loại dựa trên điểm trung bình của sinh viên tham gia. Những môn có điểm trung bình cao được xếp loại “Xuất sắc”, các môn ở mức trung bình được xếp loại “Tốt”, và các môn có điểm thấp được xếp loại “Kém”. Việc phân loại này giúp đánh giá chất lượng học tập của từng môn học một cách trực quan, từ đó hỗ trợ việc cải thiện nội dung giảng dạy và nâng cao hiệu quả học tập của sinh viên.

##3.Hãy xếp hạng sinh viên thông qua:

### a. Điểm số

#### Xếp hạng

In [78]:
sql_rank_all = """
SELECT
    student_id,
    name,
    class,
    course_id,
    score,
    RANK() OVER (ORDER BY score DESC) AS ranking
FROM student
"""

df_rank_all = pd.read_sql_query(sql_rank_all, conn)
print(df_rank_all)

   student_id               name     class  course_id  score  ranking
0           2       Tran Thi Lan   Kinh Te         34    9.2        1
1           7      Bui Tien Dung   Kinh Te         34    9.2        1
2          11       Nguyen Van A  May Tinh         26    8.5        3
3           3       Pham Van Nam  Toan Tin         12    7.9        4
4           9     Duong Huu Phuc   Kinh Te         12    7.2        5
5          10       Cao Thi Hanh  May Tinh         12    7.0        6
6           1  Nguyen Minh Hoang  May Tinh         12    6.7        7

Nhận xét:

Kết quả cho thấy bảng xếp hạng sinh viên được sắp theo điểm số giảm dần, trong đó hai sinh viên có điểm cao nhất (9.2) cùng đứng hạng 1. Do sử dụng hàm RANK(), các trường hợp bằng điểm sẽ nhận cùng thứ hạng và thứ hạng tiếp theo bị bỏ qua (ví dụ không có hạng 2 mà nhảy xuống hạng 3). Các sinh viên còn lại được xếp hạng lần lượt theo mức điểm giảm dần, phản ánh rõ sự chênh lệch về kết quả học tập. Điều này giúp dễ dàng nhận diện nhóm sinh viên có thành tích cao và đánh giá tổng quan chất lượng lớp học.

#### Top 3 cao nhất

In [80]:
query_a_top3 = """
SELECT *
FROM (
    SELECT *, RANK() OVER (ORDER BY score DESC) as r
    FROM student
)
WHERE r <= 3
"""

print(pd.read_sql_query(query_a_top3, conn))

   student_id           name     class  course_id  score  r
0           2   Tran Thi Lan   Kinh Te         34    9.2  1
1           7  Bui Tien Dung   Kinh Te         34    9.2  1
2          11   Nguyen Van A  May Tinh         26    8.5  3

Kết luận:
Top 3 sinh viên cao nhất bao gồm những người có điểm số cao nhất trong toàn bộ bảng. Do có trường hợp đồng điểm (9.2), có thể xuất hiện nhiều hơn 3 sinh viên nếu cùng hạng.

#### Top 3 thấp nhất

In [81]:
query_a_bottom3 = """
SELECT *
FROM (
    SELECT *, RANK() OVER (ORDER BY score ASC) as r
    FROM student
)
WHERE r <= 3
"""

print(pd.read_sql_query(query_a_bottom3, conn))

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         12    7.0  2
2           9     Duong Huu Phuc   Kinh Te         12    7.2  3

Kết luận:
Top 3 sinh viên thấp nhất là những người có điểm thấp nhất toàn bộ dữ liệu. Điều này giúp dễ dàng xác định nhóm sinh viên cần cải thiện kết quả học tập.

### b. Điểm số theo lớp học.

#### Xếp hạng

In [82]:
query_b = """
SELECT *,
RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_in_class
FROM student
"""

print(pd.read_sql_query(query_b, conn))

   student_id               name     class  course_id  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te         34    9.2              1
1           7      Bui Tien Dung   Kinh Te         34    9.2              1
2           9     Duong Huu Phuc   Kinh Te         12    7.2              3
3          11       Nguyen Van A  May Tinh         26    8.5              1
4          10       Cao Thi Hanh  May Tinh         12    7.0              2
5           1  Nguyen Minh Hoang  May Tinh         12    6.7              3
6           3       Pham Van Nam  Toan Tin         12    7.9              1

Kết luận:
Mỗi lớp học có một bảng xếp hạng riêng. Sinh viên chỉ được so sánh với các bạn cùng lớp, giúp đánh giá chính xác hơn năng lực trong từng môi trường học tập.

#### Top 3 cao nhất mỗi lớp

In [84]:
query_b_top3 = """
SELECT *
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY class ORDER BY score DESC) as r
    FROM student
)
WHERE r <= 3
"""

print(pd.read_sql_query(query_b_top3, conn))

   student_id               name     class  course_id  score  r
0           2       Tran Thi Lan   Kinh Te         34    9.2  1
1           7      Bui Tien Dung   Kinh Te         34    9.2  1
2           9     Duong Huu Phuc   Kinh Te         12    7.2  3
3          11       Nguyen Van A  May Tinh         26    8.5  1
4          10       Cao Thi Hanh  May Tinh         12    7.0  2
5           1  Nguyen Minh Hoang  May Tinh         12    6.7  3
6           3       Pham Van Nam  Toan Tin         12    7.9  1

Kết luận:
Mỗi lớp sẽ có tối đa 3 sinh viên đứng đầu. Kết quả giúp xác định những học sinh xuất sắc nhất trong từng lớp học.

#### Top 3 thấp nhất mỗi lớp

In [85]:
query_b_bottom3 = """
SELECT *
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY class ORDER BY score ASC) as r
    FROM student
)
WHERE r <= 3
"""

print(pd.read_sql_query(query_b_bottom3, conn))

   student_id               name     class  course_id  score  r
0           9     Duong Huu Phuc   Kinh Te         12    7.2  1
1           2       Tran Thi Lan   Kinh Te         34    9.2  2
2           7      Bui Tien Dung   Kinh Te         34    9.2  2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
4          10       Cao Thi Hanh  May Tinh         12    7.0  2
5          11       Nguyen Van A  May Tinh         26    8.5  3
6           3       Pham Van Nam  Toan Tin         12    7.9  1

Kết luận:
Kết quả cho thấy nhóm sinh viên có điểm thấp nhất trong từng lớp. Điều này hỗ trợ giáo viên dễ dàng nhận diện những trường hợp cần hỗ trợ học tập.

### c. Điểm số theo mã môn học.

#### Xếp hạng

In [86]:
query_c = """
SELECT *,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_in_course
FROM student
"""

print(pd.read_sql_query(query_c, conn))

   student_id               name     class  course_id  score  rank_in_course
0           3       Pham Van Nam  Toan Tin         12    7.9               1
1           9     Duong Huu Phuc   Kinh Te         12    7.2               2
2          10       Cao Thi Hanh  May Tinh         12    7.0               3
3           1  Nguyen Minh Hoang  May Tinh         12    6.7               4
4          11       Nguyen Van A  May Tinh         26    8.5               1
5           2       Tran Thi Lan   Kinh Te         34    9.2               1
6           7      Bui Tien Dung   Kinh Te         34    9.2               1

Kết luận:
Sinh viên được xếp hạng trong từng môn học riêng biệt. Điều này cho phép đánh giá hiệu quả học tập theo từng môn thay vì toàn bộ chương trình.

#### Top 3 cao nhất mỗi môn

In [87]:
query_c_top3 = """
SELECT *
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as r
    FROM student
)
WHERE r <= 3
"""

print(pd.read_sql_query(query_c_top3, conn))

   student_id            name     class  course_id  score  r
0           3    Pham Van Nam  Toan Tin         12    7.9  1
1           9  Duong Huu Phuc   Kinh Te         12    7.2  2
2          10    Cao Thi Hanh  May Tinh         12    7.0  3
3          11    Nguyen Van A  May Tinh         26    8.5  1
4           2    Tran Thi Lan   Kinh Te         34    9.2  1
5           7   Bui Tien Dung   Kinh Te         34    9.2  1

Kết luận:
Kết quả xác định những sinh viên có thành tích tốt nhất trong từng môn học. Đây là cơ sở để đánh giá năng lực chuyên môn của sinh viên.

#### Top 3 thấp nhất mỗi môn

In [88]:
query_c_bottom3 = """
SELECT *
FROM (
    SELECT *,
    RANK() OVER (PARTITION BY course_id ORDER BY score ASC) as r
    FROM student
)
WHERE r <= 3
"""

print(pd.read_sql_query(query_c_bottom3, conn))

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         12    7.0  2
2           9     Duong Huu Phuc   Kinh Te         12    7.2  3
3          11       Nguyen Van A  May Tinh         26    8.5  1
4           2       Tran Thi Lan   Kinh Te         34    9.2  1
5           7      Bui Tien Dung   Kinh Te         34    9.2  1

Kết luận:
Các sinh viên có điểm thấp nhất trong từng môn được xác định rõ ràng. Điều này giúp phát hiện các môn học mà sinh viên gặp khó khăn để có hướng cải thiện phù hợp.

## 4.Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số.

In [89]:
import sqlite3
import pandas as pd

# Kết nối database
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# 1. Tạo bảng
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# 2. Thêm dữ liệu
cursor.executemany("""
INSERT INTO student VALUES (?, ?, ?, ?, ?)
""", [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
])

# 3. Thêm cột graduation_date
cursor.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

# 4. Cập nhật graduation_date theo rank
cursor.execute("""
WITH ranked AS (
    SELECT student_id,
           RANK() OVER (ORDER BY score DESC) as r
    FROM student
)
UPDATE student
SET graduation_date = datetime('now', '+' || (
    SELECT r FROM ranked WHERE ranked.student_id = student.student_id
) || ' days')
""")

conn.commit()

# 5. Hiển thị kết quả cuối cùng
query = """
SELECT student_id, name, score, graduation_date
FROM student
ORDER BY score DESC
"""

df = pd.read_sql_query(query, conn)
print(df)

   student_id               name  score      graduation_date
0           2       Tran Thi Lan    9.2  2026-04-04 15:21:05
1           7      Bui Tien Dung    9.2  2026-04-04 15:21:05
2           8        Ho Ngoc Mai    8.8  2026-04-06 15:21:05
3           5        Vu Quoc Anh    8.0  2026-04-07 15:21:05
4           3       Pham Van Nam    7.9  2026-04-08 15:21:05
5           4     Le Thanh Huyen    7.2  2026-04-09 15:21:05
6           9     Duong Huu Phuc    7.2  2026-04-09 15:21:05
7          10       Cao Thi Hanh    7.0  2026-04-11 15:21:05
8           1  Nguyen Minh Hoang    6.7  2026-04-12 15:21:05
9           6     Dang Thuy Linh    5.5  2026-04-13 15:21:05

Kết luận

Đoạn code trên đã thực hiện đầy đủ các bước từ tạo bảng dữ liệu sinh viên, thêm cột mới graduation_date, đến việc tính toán và cập nhật thời gian tốt nghiệp dựa trên thứ hạng điểm số. Kết quả cho thấy sinh viên có điểm cao hơn sẽ có thứ hạng nhỏ hơn và do đó ngày tốt nghiệp gần với thời điểm hiện tại hơn, trong khi sinh viên có điểm thấp hơn sẽ có ngày tốt nghiệp muộn hơn. Cách tiếp cận này minh họa rõ mối quan hệ giữa thành tích học tập và tiến độ hoàn thành chương trình.