bài 1

In [1]:
import pandas as pd
import numpy as np

# Bảng student
student = pd.DataFrame({
    'student_id': [1,2,3,4,5,6,7,8,9,10],
    'name': ['Nguyen Minh Hoang','Tran Thi Lan','Pham Van Nam','Le Thanh Huyen',
             'Vu Quoc Anh','Dang Thuy Linh','Bui Tien Dung','Ho Ngoc Mai',
             'Duong Huu Phuc','Cao Thi Hanh'],
    'class': ['May Tinh','Kinh Te','Toan Tin','Toan Tin','May Tinh',
              'May Tinh','Kinh Te','Toan Tin','Kinh Te','May Tinh'],
    'course_id': [12,34,None,20,24,24,34,20,None,None],
    'score': [6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})

# Bảng course
course = pd.DataFrame({
    'id': [12,34,26],
    'course_name': ['Giai tich','Thong ke','Tin hoc']
})

student, course

(   student_id               name     class  course_id  score
 0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
 1           2       Tran Thi Lan   Kinh Te       34.0    9.2
 2           3       Pham Van Nam  Toan Tin        NaN    7.9
 3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
 4           5        Vu Quoc Anh  May Tinh       24.0    8.0
 5           6     Dang Thuy Linh  May Tinh       24.0    5.5
 6           7      Bui Tien Dung   Kinh Te       34.0    9.2
 7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
 8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
 9          10       Cao Thi Hanh  May Tinh        NaN    7.0,
    id course_name
 0  12   Giai tich
 1  34    Thong ke
 2  26     Tin hoc)

INNER JOIN

In [3]:
inner_join = student.merge(course, left_on='course_id', right_on='id', how='inner')
inner_join

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

LEFT JOIN

In [4]:
left_join = student.merge(course, left_on='course_id', right_on='id', how='left')
left_join

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

RIGHT JOIN

In [5]:
right_join = student.merge(course, left_on='course_id', right_on='id', how='right')
right_join

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

FULL OUTER JOIN

In [6]:
full_join = student.merge(course, left_on='course_id', right_on='id', how='outer')
full_join

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

bài 2

In [7]:
student['course_id'] = student['course_id'].fillna(26)

In [8]:
student = student[student['course_id'].isin(course['id'])]

In [9]:
avg_class = student.groupby('class')['score'].mean()
avg_class

class
Kinh Te     8.533333
May Tinh    6.850000
Toan Tin    7.900000
Name: score, dtype: float64

In [10]:
df = student.merge(course, left_on='course_id', right_on='id')

stats_course = df.groupby('course_name').agg(
    total_students=('student_id','count'),
    avg_score=('score','mean')
)

stats_course

             total_students  avg_score
course_name
Giai tich                 1   6.700000
Thong ke                  2   9.200000
Tin hoc                   3   7.366667

In [11]:
def rank(score):
    if score >= 9:
        return 'Xuat sac'
    elif score >= 6:
        return 'Tot'
    else:
        return 'Kem'

student['rank'] = student['score'].apply(rank)
student

/tmp/ipykernel_1023/3223060408.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student['rank'] = student['score'].apply(rank)

   student_id               name     class  course_id  score      rank
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7       Tot
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  Xuat sac
2           3       Pham Van Nam  Toan Tin       26.0    7.9       Tot
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  Xuat sac
8           9     Duong Huu Phuc   Kinh Te       26.0    7.2       Tot
9          10       Cao Thi Hanh  May Tinh       26.0    7.0       Tot

bài 3

In [12]:
student['rank_score'] = student['score'].rank(ascending=False, method='min')
student.sort_values('rank_score')

/tmp/ipykernel_1023/3675856930.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student['rank_score'] = student['score'].rank(ascending=False, method='min')

,student_id,name,class,course_id,score,rank,rank_score
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.0
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.0
2,3,Pham Van Nam,Toan Tin,26.0,7.9,Tot,3.0
8,9,Duong Huu Phuc,Kinh Te,26.0,7.2,Tot,4.0
9,10,Cao Thi Hanh,May Tinh,26.0,7.0,Tot,5.0
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,6.0

In [13]:
student['rank_class'] = student.groupby('class')['score'].rank(ascending=False, method='min')
student.sort_values(['class','rank_class'])

/tmp/ipykernel_1023/3307165110.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student['rank_class'] = student.groupby('class')['score'].rank(ascending=False, method='min')

,student_id,name,class,course_id,score,rank,rank_score,rank_class
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0
8,9,Duong Huu Phuc,Kinh Te,26.0,7.2,Tot,4.0,3.0
9,10,Cao Thi Hanh,May Tinh,26.0,7.0,Tot,5.0,1.0
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,6.0,2.0
2,3,Pham Van Nam,Toan Tin,26.0,7.9,Tot,3.0,1.0

In [14]:
student['rank_course'] = student.groupby('course_id')['score'].rank(ascending=False, method='min')
student.sort_values(['course_id','rank_course'])

/tmp/ipykernel_1023/1545660654.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student['rank_course'] = student.groupby('course_id')['score'].rank(ascending=False, method='min')

,student_id,name,class,course_id,score,rank,rank_score,rank_class,rank_course
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,6.0,2.0,1.0
2,3,Pham Van Nam,Toan Tin,26.0,7.9,Tot,3.0,1.0,1.0
8,9,Duong Huu Phuc,Kinh Te,26.0,7.2,Tot,4.0,3.0,2.0
9,10,Cao Thi Hanh,May Tinh,26.0,7.0,Tot,5.0,1.0,3.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0,1.0

In [15]:
top3 = student.sort_values('score', ascending=False).head(3)
top3

,student_id,name,class,course_id,score,rank,rank_score,rank_class,rank_course
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0,1.0
2,3,Pham Van Nam,Toan Tin,26.0,7.9,Tot,3.0,1.0,1.0

In [16]:
bottom3 = student.sort_values('score', ascending=True).head(3)
bottom3

,student_id,name,class,course_id,score,rank,rank_score,rank_class,rank_course
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,6.0,2.0,1.0
9,10,Cao Thi Hanh,May Tinh,26.0,7.0,Tot,5.0,1.0,3.0
8,9,Duong Huu Phuc,Kinh Te,26.0,7.2,Tot,4.0,3.0,2.0

bài 4

In [17]:
student['graduation_date'] = None

/tmp/ipykernel_1023/3191238514.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student['graduation_date'] = None

In [18]:
from datetime import datetime, timedelta

today = datetime.now()

student['graduation_date'] = student['score'].apply(
    lambda x: today + timedelta(days=(10 - x)*30)
)

student

/tmp/ipykernel_1023/1021653542.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  student['graduation_date'] = student['score'].apply(

,student_id,name,class,course_id,score,rank,rank_score,rank_class,rank_course,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,Tot,6.0,2.0,1.0,2026-07-08 07:17:36.892177
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0,1.0,2026-04-24 07:17:36.892177
2,3,Pham Van Nam,Toan Tin,26.0,7.9,Tot,3.0,1.0,1.0,2026-06-02 07:17:36.892177
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,Xuat sac,1.0,1.0,1.0,2026-04-24 07:17:36.892177
8,9,Duong Huu Phuc,Kinh Te,26.0,7.2,Tot,4.0,3.0,2.0,2026-06-23 07:17:36.892177
9,10,Cao Thi Hanh,May Tinh,26.0,7.0,Tot,5.0,1.0,3.0,2026-06-29 07:17:36.892177