# THIẾT LẬP DỮ LIỆU BAN ĐẦU
Tạo database trong bộ nhớ (in-memory) và khởi tạo 2 bảng `student` và `course` theo đề bài.

In [1]:
import sqlite3
import pandas as pd

# Kết nối với database chạy trên RAM
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Tạo bảng course [cite: 2, 4]
cursor.executescript('''
CREATE TABLE course (
    id INTEGER PRIMARY KEY,
    course_name TEXT
);

INSERT INTO course VALUES
(12, 'Giai tich'),
(34, 'Thong ke'),
(26, 'Tin hoc');
''')

# Tạo bảng student [cite: 2, 3]
cursor.executescript('''
CREATE TABLE student (
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
);

INSERT INTO student VALUES
(1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
(2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
(3, 'Pham Van Nam', 'Toan Tin', NULL, 7.9),
(4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
(5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
(6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
(7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
(8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
(9, 'Duong Huu Phuc', 'Kinh Te', NULL, 7.2),
(10, 'Cao Thi Hanh', 'May Tinh', NULL, 7.0);
''')

print("Thiết lập dữ liệu thành công!")
# Hiển thị thử dữ liệu bảng student
display(pd.read_sql_query("SELECT * FROM student;", conn))

Thiết lập dữ liệu thành công!

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

# CÂU 1: KẾT NỐI HAI BẢNG
[cite_start]Sử dụng tích Decartes và các loại JOIN: INNER, LEFT, RIGHT, FULL OUTER[cite: 7, 8, 9]. 
*(Lưu ý: SQLite hỗ trợ RIGHT JOIN và FULL OUTER JOIN từ bản 3.39.0 trở lên)*

In [2]:
print("1. Tích Descartes (CROSS JOIN)")
display(pd.read_sql_query("SELECT * FROM student CROSS JOIN course;", conn))

print("\n2. INNER JOIN")
display(pd.read_sql_query("SELECT * FROM student INNER JOIN course ON student.course_id = course.id;", conn))

print("\n3. LEFT JOIN")
display(pd.read_sql_query("SELECT * FROM student LEFT JOIN course ON student.course_id = course.id;", conn))

print("\n4. RIGHT JOIN")
try:
    display(pd.read_sql_query("SELECT * FROM student RIGHT JOIN course ON student.course_id = course.id;", conn))
except Exception as e:
    print("Phiên bản SQLite của bạn không hỗ trợ RIGHT JOIN trực tiếp. Thay thế bằng cách đổi chỗ LEFT JOIN:")
    display(pd.read_sql_query("SELECT * FROM course LEFT JOIN student ON student.course_id = course.id;", conn))

print("\n5. FULL OUTER JOIN")
try:
    display(pd.read_sql_query("SELECT * FROM student FULL OUTER JOIN course ON student.course_id = course.id;", conn))
except Exception as e:
    print("Phiên bản SQLite không hỗ trợ FULL OUTER JOIN.")

1. Tích Descartes (CROSS JOIN)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

2. INNER JOIN

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

3. LEFT JOIN

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

4. RIGHT JOIN

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN               None      None        NaN    NaN  26     Tin hoc

5. FULL OUTER JOIN

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None
10,NaN,None,None,NaN,NaN,26.0,Tin hoc

# CÂU 2: CẬP NHẬT & THỐNG KÊ
- [cite_start]Điền giá trị `course_id` (chọn môn Tin học id=26 làm ví dụ) cho các sinh viên bị thiếu.
- [cite_start]Loại bỏ các sinh viên có `course_id` không tồn tại trong bảng `course` (id 20, 24)[cite: 10, 11].
- [cite_start]Thống kê sinh viên, điểm trung bình theo lớp, môn học và phân loại[cite: 12, 13, 14].

In [3]:
# Cập nhật giá trị NULL bằng một giá trị có trong bảng course (chọn id=26)
cursor.execute("UPDATE student SET course_id = 26 WHERE course_id IS NULL;")

# Xóa bản ghi có course_id không tồn tại trong bảng course
cursor.execute("DELETE FROM student WHERE course_id NOT IN (SELECT id FROM course);")
conn.commit()

print("Dữ liệu bảng student sau khi Cập nhật & Xóa:")
display(pd.read_sql_query("SELECT * FROM student;", conn))

print("\n2a. Tổng số sinh viên, điểm trung bình của từng lớp")
q2a = "SELECT class, COUNT(student_id) as total_students, AVG(score) as avg_score FROM student GROUP BY class;"
display(pd.read_sql_query(q2a, conn))

print("\n2b. Tổng số sinh viên, điểm trung bình của từng môn học")
q2b = "SELECT course_id, COUNT(student_id) as total_students, AVG(score) as avg_score FROM student GROUP BY course_id;"
display(pd.read_sql_query(q2b, conn))

print("\n2c. Phân loại thi đua theo điểm trung bình từng môn học")
# Điều kiện: >= 9.0: Xuất sắc, 6.0 <= TB <= 8.9: Tốt, < 6.0: Kém
q2c = '''
SELECT course_id, AVG(score) as avg_score,
       CASE 
           WHEN AVG(score) >= 9.0 THEN 'Xuất sắc'
           WHEN AVG(score) >= 6.0 AND AVG(score) <= 8.9 THEN 'Tốt'
           ELSE 'Kém'
       END as phan_loai
FROM student
GROUP BY course_id;
'''
display(pd.read_sql_query(q2c, conn))

Dữ liệu bảng student sau khi Cập nhật & Xóa:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

2a. Tổng số sinh viên, điểm trung bình của từng lớp

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               2   6.850000
2  Toan Tin               1   7.900000

2b. Tổng số sinh viên, điểm trung bình của từng môn học

   course_id  total_students  avg_score
0         12               1   6.700000
1         26               3   7.366667
2         34               2   9.200000

2c. Phân loại thi đua theo điểm trung bình từng môn học

   course_id  avg_score phan_loai
0         12   6.700000       Tốt
1         26   7.366667       Tốt
2         34   9.200000  Xuất sắc

# CÂU 3: XẾP HẠNG SINH VIÊN
[cite_start]Xếp hạng thông qua điểm số chung, theo lớp, theo môn học[cite: 18, 19, 20, 21].
[cite_start]Đồng thời truy xuất ra Top 3 cao nhất và Top 3 thấp nhất của từng hạng mục[cite: 22].

In [4]:
print("3a. Xếp hạng theo Điểm số tổng (Top 3 Cao nhất và Thấp nhất)")
q3a = '''
WITH Ranked AS (
    SELECT student_id, name, score,
           RANK() OVER (ORDER BY score DESC) as rank_desc,
           RANK() OVER (ORDER BY score ASC) as rank_asc
    FROM student
)
SELECT student_id, name, score, 'Top 3 Cao Nhat' as Loai FROM Ranked WHERE rank_desc <= 3
UNION ALL
SELECT student_id, name, score, 'Top 3 Thap Nhat' as Loai FROM Ranked WHERE rank_asc <= 3;
'''
display(pd.read_sql_query(q3a, conn))


print("\n3b. Xếp hạng theo Lớp học (Hiển thị Rank để dễ đối chiếu)")
q3b = '''
SELECT student_id, name, class, score,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_trong_lop
FROM student;
'''
display(pd.read_sql_query(q3b, conn))


print("\n3c. Xếp hạng theo Môn học (Hiển thị Rank để dễ đối chiếu)")
q3c = '''
SELECT student_id, name, course_id, score,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_trong_mon
FROM student;
'''
display(pd.read_sql_query(q3c, conn))

3a. Xếp hạng theo Điểm số tổng (Top 3 Cao nhất và Thấp nhất)

   student_id               name  score             Loai
0           2       Tran Thi Lan    9.2   Top 3 Cao Nhat
1           7      Bui Tien Dung    9.2   Top 3 Cao Nhat
2           3       Pham Van Nam    7.9   Top 3 Cao Nhat
3           9     Duong Huu Phuc    7.2  Top 3 Thap Nhat
4          10       Cao Thi Hanh    7.0  Top 3 Thap Nhat
5           1  Nguyen Minh Hoang    6.7  Top 3 Thap Nhat

3b. Xếp hạng theo Lớp học (Hiển thị Rank để dễ đối chiếu)

   student_id               name     class  score  rank_trong_lop
0           2       Tran Thi Lan   Kinh Te    9.2               1
1           7      Bui Tien Dung   Kinh Te    9.2               1
2           9     Duong Huu Phuc   Kinh Te    7.2               3
3          10       Cao Thi Hanh  May Tinh    7.0               1
4           1  Nguyen Minh Hoang  May Tinh    6.7               2
5           3       Pham Van Nam  Toan Tin    7.9               1

3c. Xếp hạng theo Môn học (Hiển thị Rank để dễ đối chiếu)

   student_id               name  course_id  score  rank_trong_mon
0           1  Nguyen Minh Hoang         12    6.7               1
1           3       Pham Van Nam         26    7.9               1
2           9     Duong Huu Phuc         26    7.2               2
3          10       Cao Thi Hanh         26    7.0               3
4           2       Tran Thi Lan         34    9.2               1
5           7      Bui Tien Dung         34    9.2               1

# CÂU 4: BỔ SUNG TRƯỜNG `graduation_date`
Thêm cột `graduation_date` kiểu DATETIME. [cite_start]Thời gian tốt nghiệp = Thời gian hiện tại + số hạng của bạn đó (được quy đổi thành số *ngày* để minh hoạ)[cite: 23].

In [5]:
# Thêm trường graduation_date
try:
    cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME;")
except:
    pass # Bỏ qua lỗi nếu cột đã được tạo khi chạy lại cell

# Cập nhật thời gian: Ngày hiện tại + số ngày bằng đúng hạng (rank) điểm số
cursor.execute('''
WITH RankedStudents AS (
    SELECT student_id, RANK() OVER (ORDER BY score DESC) as rank_score
    FROM student
)
UPDATE student
SET graduation_date = date('now', '+' || 
    (SELECT rank_score FROM RankedStudents WHERE RankedStudents.student_id = student.student_id) 
    || ' days');
''')
conn.commit()

print("Bảng student sau khi thêm trường graduation_date (cộng thêm ngày theo rank):")
display(pd.read_sql_query("SELECT student_id, name, score, graduation_date FROM student ORDER BY score DESC;", conn))

# Đóng kết nối
conn.close()

Bảng student sau khi thêm trường graduation_date (cộng thêm ngày theo rank):

   student_id               name  score graduation_date
0           2       Tran Thi Lan    9.2      2026-03-29
1           7      Bui Tien Dung    9.2      2026-03-29
2           3       Pham Van Nam    7.9      2026-03-31
3           9     Duong Huu Phuc    7.2      2026-04-01
4          10       Cao Thi Hanh    7.0      2026-04-02
5           1  Nguyen Minh Hoang    6.7      2026-04-03