In [1]:
import pandas as pd
import sqlite3
import datetime

# Tạo kết nối đến database ảo trong RAM
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# 1. Tạo bảng và chèn dữ liệu Student
student_data = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]
student_df = pd.DataFrame(student_data, columns=['student_id', 'name', 'class', 'course_id', 'score'])
student_df.to_sql('student', conn, index=False)

# 2. Tạo bảng và chèn dữ liệu Course
course_data = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]
course_df = pd.DataFrame(course_data, columns=['id', 'course_name'])
course_df.to_sql('course', conn, index=False)

print("Đã khởi tạo xong Database!")

Đã khởi tạo xong Database!

### Bài 1: Kết nối 2 bảng

In [ ]:
print("1. TÍCH DECARTES (CROSS JOIN)")
q_cross = "SELECT * FROM student CROSS JOIN course;"
display(pd.read_sql(q_cross, conn).head(3)) # Hiển thị 3 dòng đầu cho gọn

print("2. INNER JOIN")
q_inner = "SELECT s.*, c.course_name FROM student s INNER JOIN course c ON s.course_id = c.id;"
display(pd.read_sql(q_inner, conn))

print("3. LEFT JOIN")
q_left = "SELECT s.*, c.course_name FROM student s LEFT JOIN course c ON s.course_id = c.id;"
display(pd.read_sql(q_left, conn))

print("\4. RIGHT JOIN")
# SQLite không hỗ trợ RIGHT JOIN trực tiếp, ta đảo bảng course lên trước LEFT JOIN
q_right = "SELECT s.*, c.course_name FROM course c LEFT JOIN student s ON c.id = s.course_id;"
display(pd.read_sql(q_right, conn))

print("5. FULL OUTER JOIN")
q_full = "SELECT s.*, c.course_name FROM student s FULL OUTER JOIN course c ON s.course_id = c.id;"
display(pd.read_sql(q_full, conn))

--- 1. TÍCH DECARTES (CROSS JOIN) ---

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc

--- 2. INNER JOIN ---

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke

--- 3. LEFT JOIN ---

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0         NaN

--- 4. RIGHT JOIN ---

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         NaN                NaN       NaN        NaN    NaN     Tin hoc

--- 5. FULL OUTER JOIN ---

    student_id               name     class  course_id  score course_name
0          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2          3.0       Pham Van Nam  Toan Tin        NaN    7.9         NaN
3          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2         NaN
4          5.0        Vu Quoc Anh  May Tinh       24.0    8.0         NaN
5          6.0     Dang Thuy Linh  May Tinh       24.0    5.5         NaN
6          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8         NaN
8          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2         NaN
9         10.0       Cao Thi Hanh  May Tinh        NaN    7.0         NaN
10         NaN                NaN       NaN        NaN    NaN     Tin hoc

Kết luận Câu 1:

INNER JOIN chỉ giữ lại các bạn có course_id khớp với bảng course (id: 12, 34).

LEFT JOIN giữ lại toàn bộ sinh viên, môn nào không có sẽ bị NaN.

FULL OUTER JOIN giữ lại toàn bộ sinh viên và toàn bộ môn học, nếu không khớp sẽ ghép với NaN.

### Câu 2: Cập nhật, xóa dữ liệu và Thống kê

In [ ]:
# 1. Cập nhật mã môn học còn thiếu (Điền mã 26 - Tin học)
cursor.execute("UPDATE student SET course_id = 26 WHERE course_id IS NULL;")

# 2. Xóa các bản ghi có môn học không tồn tại trong bảng course
cursor.execute("DELETE FROM student WHERE course_id NOT IN (SELECT id FROM course);")
conn.commit()

print("Dữ liệu bảng Student sau khi Cập nhật và Xóa:")
display(pd.read_sql("SELECT * FROM student", conn))

# 2a. Tổng số sinh viên, điểm trung bình của từng lớp
print("2a. Thống kê theo Lớp")
q_2a = """
SELECT class, COUNT(student_id) as tong_sv, ROUND(AVG(score), 2) as diem_tb
FROM student GROUP BY class;
"""
display(pd.read_sql(q_2a, conn))

# 2b & 2c. Tổng số sinh viên, điểm trung bình và phân loại từng môn học
print("\n--- 2b & 2c. Thống kê và Phân loại theo Môn học ---")
q_2bc = """
SELECT c.course_name, 
       COUNT(s.student_id) as tong_sv, 
       ROUND(AVG(s.score), 2) as diem_tb,
       CASE 
           WHEN AVG(s.score) >= 9.0 THEN 'Xuất sắc'
           WHEN AVG(s.score) >= 6.0 AND AVG(s.score) < 9.0 THEN 'Tốt'
           ELSE 'Kém'
       END as xep_loai_thi_dua
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name;
"""
display(pd.read_sql(q_2bc, conn))

Dữ liệu bảng Student sau khi Cập nhật và Xóa:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       26.0    7.9
3           7      Bui Tien Dung   Kinh Te       34.0    9.2
4           9     Duong Huu Phuc   Kinh Te       26.0    7.2
5          10       Cao Thi Hanh  May Tinh       26.0    7.0

--- 2a. Thống kê theo Lớp ---

      class  tong_sv  diem_tb
0   Kinh Te        3     8.53
1  May Tinh        2     6.85
2  Toan Tin        1     7.90

--- 2b & 2c. Thống kê và Phân loại theo Môn học ---

  course_name  tong_sv  diem_tb xep_loai_thi_dua
0   Giai tich        1     6.70              Tốt
1    Thong ke        2     9.20         Xuất sắc
2     Tin hoc        3     7.37              Tốt

### Câu 3: Xếp hạng sinh viên (RANK)

Sau khi làm sạch dữ liệu, chỉ còn lại 6 sinh viên hợp lệ. Dựa vào kết quả (2c), môn Thống kê đạt danh hiệu xuất sắc (Điểm TB > 9.0), còn Giải tích và Tin học đạt loại Tốt.

In [ ]:
print("3a. Xếp hạng theo Điểm số tổng")
q_3a = "SELECT name, class, score, RANK() OVER (ORDER BY score DESC) as rank_tong FROM student;"
display(pd.read_sql(q_3a, conn))

print("3b. Xếp hạng theo Lớp học")
q_3b = "SELECT name, class, score, RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_lop FROM student;"
display(pd.read_sql(q_3b, conn))

print("3c. Xếp hạng theo Môn học")
q_3c = "SELECT s.name, c.course_name, s.score, RANK() OVER (PARTITION BY s.course_id ORDER BY s.score DESC) as rank_mon FROM student s JOIN course c ON s.course_id = c.id;"
display(pd.read_sql(q_3c, conn))

print("Top 3 cao nhất và thấp nhất (Theo điểm tổng)")
q_top_bottom = """
WITH Ranked AS (
    SELECT name, score, 
           RANK() OVER (ORDER BY score DESC) as rank_cao_nhat,
           RANK() OVER (ORDER BY score ASC) as rank_thap_nhat
    FROM student
)
SELECT name, score, 'Top 3 Cao nhat' as Loai FROM Ranked WHERE rank_cao_nhat <= 3
UNION ALL
SELECT name, score, 'Top 3 Thap nhat' as Loai FROM Ranked WHERE rank_thap_nhat <= 3;
"""
display(pd.read_sql(q_top_bottom, conn))

--- 3a. Xếp hạng theo Điểm số tổng ---

                name     class  score  rank_tong
0       Tran Thi Lan   Kinh Te    9.2          1
1      Bui Tien Dung   Kinh Te    9.2          1
2       Pham Van Nam  Toan Tin    7.9          3
3     Duong Huu Phuc   Kinh Te    7.2          4
4       Cao Thi Hanh  May Tinh    7.0          5
5  Nguyen Minh Hoang  May Tinh    6.7          6

--- 3b. Xếp hạng theo Lớp học ---

                name     class  score  rank_lop
0       Tran Thi Lan   Kinh Te    9.2         1
1      Bui Tien Dung   Kinh Te    9.2         1
2     Duong Huu Phuc   Kinh Te    7.2         3
3       Cao Thi Hanh  May Tinh    7.0         1
4  Nguyen Minh Hoang  May Tinh    6.7         2
5       Pham Van Nam  Toan Tin    7.9         1

--- 3c. Xếp hạng theo Môn học ---

                name course_name  score  rank_mon
0  Nguyen Minh Hoang   Giai tich    6.7         1
1       Pham Van Nam     Tin hoc    7.9         1
2     Duong Huu Phuc     Tin hoc    7.2         2
3       Cao Thi Hanh     Tin hoc    7.0         3
4       Tran Thi Lan    Thong ke    9.2         1
5      Bui Tien Dung    Thong ke    9.2         1

--- Top 3 cao nhất và thấp nhất (Theo điểm tổng) ---

                name  score             Loai
0       Tran Thi Lan    9.2   Top 3 Cao nhat
1      Bui Tien Dung    9.2   Top 3 Cao nhat
2       Pham Van Nam    7.9   Top 3 Cao nhat
3     Duong Huu Phuc    7.2  Top 3 Thap nhat
4       Cao Thi Hanh    7.0  Top 3 Thap nhat
5  Nguyen Minh Hoang    6.7  Top 3 Thap nhat

Kết luận Câu 3:

Trần Thị Lan và Bùi Tiến Dũng (cùng 9.2) dẫn đầu bảng xếp hạng tổng. Nguyễn Minh Hoàng (6.7) ở vị trí cuối cùng. Tính năng PARTITION BY giúp reset lại thứ hạng khi đổi sang lớp hoặc môn khác.

### Câu 4: Bổ sung trường graduation_date

In [5]:
# 1. Thêm cột graduation_date
cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME;")

# 2. Cập nhật giá trị dựa trên rank
q_update_date = """
WITH CTE_Rank AS (
    SELECT student_id, RANK() OVER (ORDER BY score DESC) as rank_num
    FROM student
)
UPDATE student 
SET graduation_date = datetime('now', 'localtime', '+' || (SELECT rank_num FROM CTE_Rank WHERE CTE_Rank.student_id = student.student_id) || ' days');
"""
cursor.execute(q_update_date)
conn.commit()

print("--- Bảng Student sau khi có Ngày Tốt Nghiệp ---")
q_final = "SELECT name, score, graduation_date FROM student ORDER BY score DESC;"
display(pd.read_sql(q_final, conn))

# Đóng kết nối khi làm xong
conn.close()

--- Bảng Student sau khi có Ngày Tốt Nghiệp ---

                name  score      graduation_date
0       Tran Thi Lan    9.2  2026-04-04 01:18:21
1      Bui Tien Dung    9.2  2026-04-04 01:18:21
2       Pham Van Nam    7.9  2026-04-06 01:18:21
3     Duong Huu Phuc    7.2  2026-04-07 01:18:21
4       Cao Thi Hanh    7.0  2026-04-08 01:18:21
5  Nguyen Minh Hoang    6.7  2026-04-09 01:18:21