##BÀI TẬP CHƯƠNG 2

In [2]:
import sqlite3
import pandas as pd

# Tạo kết nối tới database student.db
conn = sqlite3.connect("student.db")

# Tạo con trỏ để thực thi các câu lệnh SQL
cur = conn.cursor()

In [3]:
# Tạo bảng student
sql = """
CREATE TABLE student(
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
"""
cur.execute(sql)

In [4]:
# Tạo bảng course
sql = """
CREATE TABLE course(
    id INTEGER,
    course_name TEXT
)
"""
cur.execute(sql)

In [5]:
# Thêm dữ liệu cho bảng student
students = [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
]

for s in students:
    cur.execute("INSERT INTO student VALUES (?,?,?,?,?)",s)

# Thêm dữ liệu cho bảng course
courses = [
(12,"Giai tich"),
(34,"Thong ke"),
(26,"Tin hoc")
]

for c in courses:
    cur.execute("INSERT INTO course VALUES (?,?)",c)

conn.commit()

In [6]:
# Tích Decartes
query = """
SELECT *
FROM student, course
"""

df = pd.read_sql_query(query, conn)
df

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

In [7]:
# INNER JOIN
query = """
SELECT *
FROM student
INNER JOIN course
ON student.course_id = course.id
"""

df = pd.read_sql_query(query, conn)
df

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

In [8]:
# LEFT JOIN
query = """
SELECT *
FROM student
LEFT JOIN course
ON student.course_id = course.id
"""

df = pd.read_sql_query(query, conn)
df

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

In [9]:
# SQLite không hỗ trợ RIGHT JOIN nên đổi vị trí hai bảng và sử dụng LEFT JOIN
query = """
SELECT *
FROM course
LEFT JOIN student
ON student.course_id = course.id
"""

df = pd.read_sql_query(query, conn)
df

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin hoc         NaN               None      None        NaN    NaN

In [10]:
# SQLite không hỗ trợ FULL OUTER JOIN nên sử dụng UNION của LEFT JOIN hai chiều
query = """
SELECT *
FROM student
LEFT JOIN course
ON student.course_id = course.id

UNION

SELECT *
FROM course
LEFT JOIN student
ON student.course_id = course.id
"""

df = pd.read_sql_query(query, conn)
df

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

In [11]:
# Xóa các sinh viên có course_id không tồn tại trong bảng course
sql = """
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
"""
cur.execute(sql)
conn.commit()

In [12]:
# Cập nhật các sinh viên chưa có course_id (NULL) thành 26
sql = """
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
"""

cur.execute(sql)
conn.commit()

In [13]:
# Thống kê số sinh viên và điểm trung bình theo từng lớp
query = """
SELECT class,
COUNT(*) as tong_sv,
AVG(score) as diem_tb
FROM student
GROUP BY class
"""

df = pd.read_sql_query(query, conn)
df

      class  tong_sv   diem_tb
0   Kinh Te        3  8.533333
1  May Tinh        2  6.850000
2  Toan Tin        1  7.900000

In [14]:
# Thống kê số sinh viên và điểm trung bình theo từng môn học
query = """
SELECT course_name,
COUNT(student_id) as tong_sv,
AVG(score) as diem_tb
FROM student
JOIN course
ON student.course_id = course.id
GROUP BY course_name
"""

df = pd.read_sql_query(query, conn)
df

  course_name  tong_sv   diem_tb
0   Giai tich        1  6.700000
1    Thong ke        2  9.200000
2     Tin hoc        3  7.366667

In [15]:
# Phân loại thi đua dựa trên điểm trung bình của từng môn học
query = """
SELECT course_name,
AVG(score) as diem_tb,

CASE
WHEN AVG(score) >= 9 THEN 'Xuat sac'
WHEN AVG(score) >= 6 THEN 'Tot'
ELSE 'Kem'
END as xep_loai

FROM student
JOIN course
ON student.course_id = course.id

GROUP BY course_name
"""

df = pd.read_sql_query(query, conn)
df

  course_name   diem_tb  xep_loai
0   Giai tich  6.700000       Tot
1    Thong ke  9.200000  Xuat sac
2     Tin hoc  7.366667       Tot

In [16]:
# Xếp hạng sinh viên theo điểm số từ cao xuống thấp
query = """
SELECT *,
RANK() OVER (ORDER BY score DESC) as rank_score
FROM student
"""

df = pd.read_sql_query(query, conn)
df

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           3       Pham Van Nam  Toan Tin         26    7.9           3
3           9     Duong Huu Phuc   Kinh Te         26    7.2           4
4          10       Cao Thi Hanh  May Tinh         26    7.0           5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7           6

In [17]:
# Xếp hạng sinh viên trong từng lớp
query = """
SELECT *,
RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_class
FROM student
"""

df = pd.read_sql_query(query, conn)
df

   student_id               name     class  course_id  score  rank_class
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           9     Duong Huu Phuc   Kinh Te         26    7.2           3
3          10       Cao Thi Hanh  May Tinh         26    7.0           1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7           2
5           3       Pham Van Nam  Toan Tin         26    7.9           1

In [18]:
# Xếp hạng sinh viên theo mã môn học
query = """
SELECT *,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_course
FROM student
"""

df = pd.read_sql_query(query, conn)
df

   student_id               name     class  course_id  score  rank_course
0           1  Nguyen Minh Hoang  May Tinh         12    6.7            1
1           3       Pham Van Nam  Toan Tin         26    7.9            1
2           9     Duong Huu Phuc   Kinh Te         26    7.2            2
3          10       Cao Thi Hanh  May Tinh         26    7.0            3
4           2       Tran Thi Lan   Kinh Te         34    9.2            1
5           7      Bui Tien Dung   Kinh Te         34    9.2            1

In [19]:
# Thêm cột graduation_date vào bảng student
sql = """
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
"""

cur.execute(sql)

In [20]:
# Thời gian tốt nghiệp
sql = """
UPDATE student
SET graduation_date = datetime('now','+' || score || ' days')
"""

cur.execute(sql)
conn.commit()

In [21]:
# Hiển thị bảng student sau khi thêm cột graduation_date
df = pd.read_sql_query("SELECT * FROM student",conn)
df

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-04-10 07:42:37
1,2,Tran Thi Lan,Kinh Te,34,9.2,2026-04-12 19:42:37
2,3,Pham Van Nam,Toan Tin,26,7.9,2026-04-11 12:30:37
3,7,Bui Tien Dung,Kinh Te,34,9.2,2026-04-12 19:42:37
4,9,Duong Huu Phuc,Kinh Te,26,7.2,2026-04-10 19:42:37
5,10,Cao Thi Hanh,May Tinh,26,7.0,2026-04-10 14:54:37