1

In [1]:
import pandas as pd
import numpy as np

# Tạo bảng Student
student_data = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name': ['Nguyen Minh Hoang', 'Tran Thi Lan', 'Pham Van Nam', 'Le Thanh Huyen', 
             'Vu Quoc Anh', 'Dang Thuy Linh', 'Bui Tien Dung', 'Ho Ngoc Mai', 
             'Duong Huu Phuc', 'Cao Thi Hanh'],
    'class': ['May Tinh', 'Kinh Te', 'Toan Tin', 'Toan Tin', 'May Tinh', 
              'May Tinh', 'Kinh Te', 'Toan Tin', 'Kinh Te', 'May Tinh'],
    'course_id': [12, 34, np.nan, 20, 24, 24, 34, 20, np.nan, np.nan],
    'score': [6.7, 9.2, 7.9, 7.2, 8.0, 5.5, 9.2, 8.8, 7.2, 7.0]
}
df_student = pd.DataFrame(student_data)

# Tạo bảng Course
course_data = {
    'id': [12, 34, 26],
    'course_name': ['Giai tich', 'Thong ke', 'Tin hoc']
}
df_course = pd.DataFrame(course_data)

In [2]:
cartesian_product = df_student.merge(df_course, how='cross')
print("Tích Descartes (30 dòng):")
display(cartesian_product.head())

Tích Descartes (30 dòng):

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3           2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke

In [3]:
inner_join = pd.merge(df_student, df_course, left_on='course_id', right_on='id', how='inner')
print("Inner Join:")
display(inner_join)

Inner Join:

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

In [4]:
left_join = pd.merge(df_student, df_course, left_on='course_id', right_on='id', how='left')
print("Left Join:")
display(left_join)

Left Join:

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

In [5]:
right_join = pd.merge(df_student, df_course, left_on='course_id', right_on='id', how='right')
print("Right Join:")
display(right_join)

Right Join:

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

In [6]:
full_join = pd.merge(df_student, df_course, left_on='course_id', right_on='id', how='outer')
print("Full Outer Join:")
display(full_join)

Full Outer Join:

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

# 2

In [14]:
# 1. Cập nhật course_id còn thiếu (NaN) bằng một mã tồn tại trong bảng course (chọn mã 26)
df_student['course_id'] = df_student['course_id'].fillna(26)

# 2. Loại bỏ các bản ghi học môn không tồn tại trong bảng course (mã 20, 24)
# Lấy danh sách ID hợp lệ từ bảng course
valid_ids = df_course['id'].values
df_student_clean = df_student[df_student['course_id'].isin(valid_ids)].copy()

print("Dữ liệu sau khi làm sạch:")
display(df_student_clean)

Dữ liệu sau khi làm sạch:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       26.0    7.9
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
8           9     Duong Huu Phuc   Kinh Te       26.0    7.2
9          10       Cao Thi Hanh  May Tinh       26.0    7.0

a. Tổng số sinh viên và điểm trung bình từng lớp

In [15]:
stats_class = df_student_clean.groupby('class').agg(
    tong_sinh_vien=('student_id', 'count'),
    diem_trung_binh=('score', 'mean')
).reset_index()

print("Thống kê theo lớp:")
display(stats_class)

Thống kê theo lớp:

      class  tong_sinh_vien  diem_trung_binh
0   Kinh Te               3         8.533333
1  May Tinh               2         6.850000
2  Toan Tin               1         7.900000

b. Tổng số sinh viên và điểm trung bình từng môn học

In [16]:
# Join hai bảng
df_merged = pd.merge(df_student_clean, df_course, left_on='course_id', right_on='id')

stats_course = df_merged.groupby('course_name').agg(
    tong_sinh_vien=('student_id', 'count'),
    diem_trung_binh=('score', 'mean')
).reset_index()

print("Thống kê theo môn học:")
display(stats_course)

Thống kê theo môn học:

  course_name  tong_sinh_vien  diem_trung_binh
0   Giai tich               1         6.700000
1    Thong ke               2         9.200000
2     Tin hoc               3         7.366667

c. Phân loại thi đua theo môn học

In [17]:
def phan_loai(dtb):
    if dtb >= 9.0:
        return 'Xuất sắc'
    elif 6.0 <= dtb <= 8.9:
        return 'Tốt'
    else:
        return 'Kém'

# Áp dụng hàm phân loại vào kết quả thống kê môn học
stats_course['phan_loai'] = stats_course['diem_trung_binh'].apply(phan_loai)

print("Kết quả phân loại thi đua môn học:")
display(stats_course[['course_name', 'diem_trung_binh', 'phan_loai']])

Kết quả phân loại thi đua môn học:

  course_name  diem_trung_binh phan_loai
0   Giai tich         6.700000       Tốt
1    Thong ke         9.200000  Xuất sắc
2     Tin hoc         7.366667       Tốt

# 3

a. Điểm số

In [21]:
# Tính hạng toàn trường
df_student_clean['rank_all'] = df_student_clean['score'].rank(ascending=False, method='min')

# Top 3 cao nhất
top_3_high = df_student_clean.nsmallest(3, 'rank_all')

# Top 3 thấp nhất
top_3_low = df_student_clean.nlargest(3, 'rank_all')

print("--- TOÀN TRƯỜNG ---")
print("Top 3 cao nhất:")
display(top_3_high[['name', 'score', 'rank_all']])
print("Top 3 thấp nhất:")
display(top_3_low[['name', 'score', 'rank_all']])

--- TOÀN TRƯỜNG ---
Top 3 cao nhất:

            name  score  rank_all
1   Tran Thi Lan    9.2       1.0
6  Bui Tien Dung    9.2       1.0
2   Pham Van Nam    7.9       3.0

Top 3 thấp nhất:

                name  score  rank_all
0  Nguyen Minh Hoang    6.7       6.0
9       Cao Thi Hanh    7.0       5.0
8     Duong Huu Phuc    7.2       4.0

b. Điểm số theo lớp học

In [22]:
# Tính hạng theo lớp
df_student_clean['rank_class'] = df_student_clean.groupby('class')['score'].rank(ascending=False, method='min')

# Sắp xếp để dễ quan sát
df_sorted_class = df_student_clean.sort_values(['class', 'rank_class'])

# Top 3 cao nhất mỗi lớp
top_3_class_high = df_sorted_class.groupby('class').head(3)

# Top 3 thấp nhất mỗi lớp
top_3_class_low = df_sorted_class.groupby('class').tail(3)

print("--- THEO TỪNG LỚP ---")
print("Top 3 cao nhất mỗi lớp:")
display(top_3_class_high[['class', 'name', 'score', 'rank_class']])
print("Top 3 thấp nhất mỗi lớp:")
display(top_3_class_low[['class', 'name', 'score', 'rank_class']])

--- THEO TỪNG LỚP ---
Top 3 cao nhất mỗi lớp:

      class               name  score  rank_class
1   Kinh Te       Tran Thi Lan    9.2         1.0
6   Kinh Te      Bui Tien Dung    9.2         1.0
8   Kinh Te     Duong Huu Phuc    7.2         3.0
9  May Tinh       Cao Thi Hanh    7.0         1.0
0  May Tinh  Nguyen Minh Hoang    6.7         2.0
2  Toan Tin       Pham Van Nam    7.9         1.0

Top 3 thấp nhất mỗi lớp:

      class               name  score  rank_class
1   Kinh Te       Tran Thi Lan    9.2         1.0
6   Kinh Te      Bui Tien Dung    9.2         1.0
8   Kinh Te     Duong Huu Phuc    7.2         3.0
9  May Tinh       Cao Thi Hanh    7.0         1.0
0  May Tinh  Nguyen Minh Hoang    6.7         2.0
2  Toan Tin       Pham Van Nam    7.9         1.0

c. Điểm số theo mã môn học

In [23]:
# Tính hạng theo môn học
df_student_clean['rank_course'] = df_student_clean.groupby('course_id')['score'].rank(ascending=False, method='min')

# Sắp xếp theo môn và hạng
df_sorted_course = df_student_clean.sort_values(['course_id', 'rank_course'])

# Top 3 cao nhất mỗi môn
top_3_course_high = df_sorted_course.groupby('course_id').head(3)

# Top 3 thấp nhất mỗi môn
top_3_course_low = df_sorted_course.groupby('course_id').tail(3)

print("--- THEO MÃ MÔN HỌC ---")
print("Top 3 cao nhất mỗi môn:")
display(top_3_course_high[['course_id', 'name', 'score', 'rank_course']])
print("Top 3 thấp nhất mỗi môn:")
display(top_3_course_low[['course_id', 'name', 'score', 'rank_course']])

--- THEO MÃ MÔN HỌC ---
Top 3 cao nhất mỗi môn:

   course_id               name  score  rank_course
0       12.0  Nguyen Minh Hoang    6.7          1.0
2       26.0       Pham Van Nam    7.9          1.0
8       26.0     Duong Huu Phuc    7.2          2.0
9       26.0       Cao Thi Hanh    7.0          3.0
1       34.0       Tran Thi Lan    9.2          1.0
6       34.0      Bui Tien Dung    9.2          1.0

Top 3 thấp nhất mỗi môn:

   course_id               name  score  rank_course
0       12.0  Nguyen Minh Hoang    6.7          1.0
2       26.0       Pham Van Nam    7.9          1.0
8       26.0     Duong Huu Phuc    7.2          2.0
9       26.0       Cao Thi Hanh    7.0          3.0
1       34.0       Tran Thi Lan    9.2          1.0
6       34.0      Bui Tien Dung    9.2          1.0

# 4

In [24]:
from datetime import datetime

# 1. Lấy thời gian hiện tại (ngày, giờ, phút, giây)
current_time = datetime.now()

# 2. Tính toán ngày tốt nghiệp:
# Công thức: Thời gian hiện tại + (Số hạng toàn trường) ngày
# Ở đây mình dùng 'rank_all' đã tính từ câu 3a.
# Chúng ta dùng pd.to_timedelta để cộng đơn vị thời gian vào datetime
df_student_clean['graduation_date'] = current_time + pd.to_timedelta(df_student_clean['rank_all'], unit='D')

# 3. Hiển thị kết quả để kiểm tra
print(f"Thời gian hiện tại làm mốc: {current_time.strftime('%Y-%m-%d %H:%M:%S')}")
display(df_student_clean[['name', 'score', 'rank_all', 'graduation_date']].sort_values('rank_all'))

Thời gian hiện tại làm mốc: 2026-04-03 09:02:30

                name  score  rank_all            graduation_date
1       Tran Thi Lan    9.2       1.0 2026-04-04 09:02:30.348086
6      Bui Tien Dung    9.2       1.0 2026-04-04 09:02:30.348086
2       Pham Van Nam    7.9       3.0 2026-04-06 09:02:30.348086
8     Duong Huu Phuc    7.2       4.0 2026-04-07 09:02:30.348086
9       Cao Thi Hanh    7.0       5.0 2026-04-08 09:02:30.348086
0  Nguyen Minh Hoang    6.7       6.0 2026-04-09 09:02:30.348086