# Tạo database + bảng

In [198]:
import sqlite3

conn = sqlite3.connect(":memory:")
cursor = conn.cursor()

# Tạo bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

In [199]:
import pandas as pd
from IPython.display import display

def show(cursor):
    """Hien thi ket qua query dang bang dep voi pandas."""
    rows = cursor.fetchall()
    if not rows:
        print("(Khong co du lieu)")
        return
    cols = [desc[0] for desc in cursor.description]
    df = pd.DataFrame(rows, columns=cols)
    display(df)

# Insert dữ liệu

In [200]:
# Insert student
students = [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)

# Insert course
courses = [
(12,"Giai tich"),
(34,"Thong ke"),
(26,"Tin hoc")
]

cursor.executemany("INSERT INTO course VALUES (?,?)", courses)

conn.commit()

# Câu 1

nối 2 bảng theo tích decarts

In [202]:
# nối 2 bảng theo tích decarts
cursor.execute("""
SELECT * FROM student, course
""")
show(cursor)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

INNER JOIN

In [203]:
# INNER JOIN
cursor.execute("""
SELECT * FROM student s
INNER JOIN course c
ON s.course_id = c.id
""")
show(cursor)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

LEFT JOIN

In [204]:
# LEFT JOIN
cursor.execute("""
SELECT * FROM student s
LEFT JOIN course c
ON s.course_id = c.id
""")
show(cursor)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

Right JOIN

In [205]:
# Right JOIN
cursor.execute("""
SELECT * FROM course c
RIGHT JOIN student s
ON s.course_id = c.id
""")
show(cursor)

     id course_name  student_id               name     class  course_id  score
0  12.0   Giai tich           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34.0    Thong ke           2       Tran Thi Lan   Kinh Te       34.0    9.2
2  34.0    Thong ke           7      Bui Tien Dung   Kinh Te       34.0    9.2
3   NaN        None           3       Pham Van Nam  Toan Tin        NaN    7.9
4   NaN        None           4     Le Thanh Huyen  Toan Tin       20.0    7.2
5   NaN        None           5        Vu Quoc Anh  May Tinh       24.0    8.0
6   NaN        None           6     Dang Thuy Linh  May Tinh       24.0    5.5
7   NaN        None           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8   NaN        None           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9   NaN        None          10       Cao Thi Hanh  May Tinh        NaN    7.0

FULL OUTER JOIN

In [206]:
# FULL OUTER JOIN
cursor.execute("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT * FROM student s
RIGHT JOIN course c ON s.course_id = c.id
""")

show(cursor)

,student_id,name,class,course_id,score,id,course_name
0,NaN,None,None,NaN,NaN,26.0,Tin hoc
1,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
2,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
3,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
4,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
5,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
6,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None

# Câu 2

Cập nhật giá trị thiếu và loại bỏ bản ghi không tồn tại

In [207]:
# 1. UPDATE trước
cursor.execute("""
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
""")

# 2. DELETE sau
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
""")

conn.commit()

a. Tổng số sinh viên, điểm trung bình của từng lớp

In [208]:
cursor.execute("""
SELECT class,
       COUNT(*) AS total_students,
       AVG(score) AS avg_score
FROM student
GROUP BY class
""")
show(cursor)

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               2   6.850000
2  Toan Tin               1   7.900000

b. Tổng số sinh viên, điểm trung bình của từng môn học.

In [209]:
cursor.execute("""
SELECT c.course_name,
       COUNT(*) AS total_students,
       AVG(s.score) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""")
show(cursor)

  course_name  total_students  avg_score
0   Giai tich               1   6.700000
1    Thong ke               2   9.200000
2     Tin hoc               3   7.366667

c. Phân loại thi đua theo số điểm của từng môn học biết:

In [210]:
cursor.execute("""
SELECT c.course_name,
       AVG(s.score) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""")
show(cursor)

  course_name  avg_score classification
0   Giai tich   6.700000            Tot
1    Thong ke   9.200000       Xuat sac
2     Tin hoc   7.366667            Tot

# BÀI 3: Xếp hạng

# xếp hạng qua điểm số

In [211]:
# xếp hạng qua điểm số
cursor.execute("""
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_overall
FROM student
""")

In [212]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng cao nhất theo điểm số")
show(cursor)

top 3 sinh viên đạt thứ hạng cao nhất theo điểm số

   student_id           name     class  course_id  score  r
0           2   Tran Thi Lan   Kinh Te         34    9.2  1
1           7  Bui Tien Dung   Kinh Te         34    9.2  1
2           3   Pham Van Nam  Toan Tin         26    7.9  3

In [213]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng thấp nhất theo điểm số")
show(cursor)

top 3 sinh viên đạt thứ hạng thấp nhất theo điểm số

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         26    7.0  2
2           9     Duong Huu Phuc   Kinh Te         26    7.2  3

Theo lớp

In [214]:
cursor.execute("""
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
""")

Top 3 CAO NHẤT trong từng lớp

In [215]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng cao nhất theo điểm lớp")
show(cursor)

top 3 sinh viên đạt thứ hạng cao nhất theo điểm lớp

   student_id               name     class  course_id  score  r
0           2       Tran Thi Lan   Kinh Te         34    9.2  1
1           7      Bui Tien Dung   Kinh Te         34    9.2  1
2           9     Duong Huu Phuc   Kinh Te         26    7.2  3
3          10       Cao Thi Hanh  May Tinh         26    7.0  1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7  2
5           3       Pham Van Nam  Toan Tin         26    7.9  1

Top 3 THẤP NHẤT trong từng lớp

In [216]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng cao thấp nhất theo lớp")
show(cursor)

top 3 sinh viên đạt thứ hạng cao thấp nhất theo lớp

   student_id               name     class  course_id  score  r
0           9     Duong Huu Phuc   Kinh Te         26    7.2  1
1           2       Tran Thi Lan   Kinh Te         34    9.2  2
2           7      Bui Tien Dung   Kinh Te         34    9.2  2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
4          10       Cao Thi Hanh  May Tinh         26    7.0  2
5           3       Pham Van Nam  Toan Tin         26    7.9  1

c. Theo môn học

In [217]:
cursor.execute("""
SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_course
FROM student
""")

Top 3 CAO NHẤT theo từng môn

In [218]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng cao nhất theo môn học")
show(cursor)

top 3 sinh viên đạt thứ hạng cao nhất theo môn học

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1           3       Pham Van Nam  Toan Tin         26    7.9  1
2           9     Duong Huu Phuc   Kinh Te         26    7.2  2
3          10       Cao Thi Hanh  May Tinh         26    7.0  3
4           2       Tran Thi Lan   Kinh Te         34    9.2  1
5           7      Bui Tien Dung   Kinh Te         34    9.2  1

In [219]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng thấp nhất theo môn học")
show(cursor)

top 3 sinh viên đạt thứ hạng thấp nhất theo môn học

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1          10       Cao Thi Hanh  May Tinh         26    7.0  1
2           9     Duong Huu Phuc   Kinh Te         26    7.2  2
3           3       Pham Van Nam  Toan Tin         26    7.9  3
4           2       Tran Thi Lan   Kinh Te         34    9.2  1
5           7      Bui Tien Dung   Kinh Te         34    9.2  1

# BÀI 4: bổ sung graduation_date

In [220]:
cursor.execute("""
ALTER TABLE student ADD COLUMN graduation_date TEXT
""")

Cập nhật theo rank

In [221]:
cursor.execute("""
UPDATE student
SET graduation_date = datetime('now', '+' || 
    (SELECT RANK() OVER (ORDER BY score DESC)
     FROM student s2
     WHERE s2.student_id = student.student_id
    ) || ' days')
""")

conn.commit()

In [222]:
cursor.execute("""
SELECT * FROM student
""")
show(cursor)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-03-31 15:30:11
1,2,Tran Thi Lan,Kinh Te,34,9.2,2026-03-31 15:30:11
2,3,Pham Van Nam,Toan Tin,26,7.9,2026-03-31 15:30:11
3,7,Bui Tien Dung,Kinh Te,34,9.2,2026-03-31 15:30:11
4,9,Duong Huu Phuc,Kinh Te,26,7.2,2026-03-31 15:30:11
5,10,Cao Thi Hanh,May Tinh,26,7.0,2026-03-31 15:30:11