#1.Hãy kết nối hai bảng trên theo những cách sau:
- Sử dụng tích Decartes.
- Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN

In [10]:
import pandas as pd
import numpy as np

# 1. Khởi tạo dữ liệu bảng student theo đúng ảnh
data_student = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name': ['Nguyen Minh Hoang', 'Tran Thi Lan', 'Pham Van Nam', 'Le Thanh Huyen', 'Vu Quoc Anh',
             'Dang Thuy Linh', 'Bui Tien Dung', 'Ho Ngoc Mai', 'Duong Huu Phuc', 'Cao Thi Hanh'],
    'class': ['May Tinh', 'Kinh Te', 'Toan Tin', 'Toan Tin', 'May Tinh',
              'May Tinh', 'Kinh Te', 'Toan Tin', 'Kinh Te', 'May Tinh'],
    'course_id': [12, 34, None, 20, 24, 24, 34, 20, None, None],
    'score': [6.7, 9.2, 7.9, 7.2, 8.0, 5.5, 9.2, 8.8, 7.2, 7.0]
}
student = pd.DataFrame(data_student)

# Chuyển đổi cột course_id sang kiểu Int64 để hiển thị số nguyên thay vì số thập phân (do có chứa None)
student['course_id'] = student['course_id'].astype('Int64')

# 2. Khởi tạo dữ liệu bảng course theo đúng ảnh
data_course = {
    'id': [12, 34, 26],
    'course_name': ['Giai tich', 'Thong ke', 'Tin hoc']
}
course = pd.DataFrame(data_course)

# 3. Hiển thị kết quả
print("--- Bảng Student ---")
display(student)

print("\n--- Bảng Course ---")
display(course)

--- Bảng Student ---

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin       <NA>    7.9
3           4     Le Thanh Huyen  Toan Tin         20    7.2
4           5        Vu Quoc Anh  May Tinh         24    8.0
5           6     Dang Thuy Linh  May Tinh         24    5.5
6           7      Bui Tien Dung   Kinh Te         34    9.2
7           8        Ho Ngoc Mai  Toan Tin         20    8.8
8           9     Duong Huu Phuc   Kinh Te       <NA>    7.2
9          10       Cao Thi Hanh  May Tinh       <NA>    7.0

--- Bảng Course ---

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

In [12]:
# 2. Thực hiện Tích Decartes bằng tham số how='cross'
cross_join_df = pd.merge(student, course, how='cross')

# 3. Hiển thị kết quả
print(f"Tổng số bản ghi sau khi Cross Join: {len(cross_join_df)}")
display(cross_join_df.head(10)) # Hiển thị 10 dòng đầu để dễ quan sát

Tổng số bản ghi sau khi Cross Join: 30

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           1  Nguyen Minh Hoang  May Tinh         12    6.7  34    Thong ke
2           1  Nguyen Minh Hoang  May Tinh         12    6.7  26     Tin hoc
3           2       Tran Thi Lan   Kinh Te         34    9.2  12   Giai tich
4           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
5           2       Tran Thi Lan   Kinh Te         34    9.2  26     Tin hoc
6           3       Pham Van Nam  Toan Tin       <NA>    7.9  12   Giai tich
7           3       Pham Van Nam  Toan Tin       <NA>    7.9  34    Thong ke
8           3       Pham Van Nam  Toan Tin       <NA>    7.9  26     Tin hoc
9           4     Le Thanh Huyen  Toan Tin         20    7.2  12   Giai tich

1. Tích Decartes (Cross Join)
+ Bản chất: Đây là phép nhân chéo. Mỗi dòng của bảng 1 (Sinh viên) sẽ được ghép với tất cả các dòng của bảng 2 (Điểm). Ví dụ: Bảng 1 có 10 sinh viên, bảng 2 có 8 mốc điểm $\rightarrow$ Kết quả sẽ tạo ra một bảng mới có $10 \times 8 = 80$ dòng.
+ Trong Pandas: Cú pháp thường dùng là pd.merge(df_student, df_score, how='cross').
+ Nhận xét: Phép kết nối này sinh ra mọi tổ hợp có thể có, nhưng đa số là các dữ liệu "vô nghĩa" (ghép râu ông nọ cắm cằm bà kia). Trong thực tế phân tích dữ liệu, phép này hiếm khi được sử dụng trừ khi bạn thực sự cần tạo một ma trận kết hợp toàn bộ các khả năng.

In [13]:
# Thực hiện Inner Join dựa trên student.course_id và course.id
inner_join_df = pd.merge(student, course, left_on='course_id', right_on='id', how='inner')

print(f"Số lượng bản ghi: {len(inner_join_df)}")
display(inner_join_df)

Số lượng bản ghi: 3

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

2. INNER JOIN (Kết nối trong)
+ Bản chất: Chỉ giữ lại những dòng mà khóa kết nối (ở đây là student_id) xuất hiện ở cả hai bảng.
+ Trong Pandas: Cú pháp pd.merge(df_student, df_score, on='student_id', how='inner').
+ Nhận xét: Nếu một sinh viên có trong danh sách lớp nhưng chưa có điểm (không có trong bảng điểm), hoặc có một cột điểm bị sai mã sinh viên (không có trong bảng danh sách lớp), thì những dòng đó sẽ bị loại bỏ hoàn toàn. Đây là cách an toàn nhất nếu bạn chỉ muốn phân tích những người "có đầy đủ thông tin trọn vẹn".

In [14]:
# Thực hiện Left Join
left_join_df = pd.merge(student, course, left_on='course_id', right_on='id', how='left')

print(f"Số lượng bản ghi: {len(left_join_df)}")
display(left_join_df)

Số lượng bản ghi: 10

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin       <NA>    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin         20    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh         24    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh         24    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te         34    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin         20    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te       <NA>    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh       <NA>    7.0   NaN         NaN

3. LEFT JOIN (Kết nối trái)
+ Bản chất: Lấy toàn bộ dữ liệu của bảng bên trái (ví dụ: df_student), và cố gắng tìm dữ liệu tương ứng ở bảng bên phải (điểm) để đắp vào.
+ Trong Pandas: Cú pháp pd.merge(df_student, df_score, on='student_id', how='left').
+ Nhận xét: Đây là loại Join được sử dụng nhiều nhất trong thực tế. Khi dùng Left Join, bạn bảo toàn được danh sách gốc của mình. Những sinh viên nào không có điểm ở bảng bên phải thì các cột điểm sẽ tự động được gán giá trị rỗng (NaN).

In [15]:
#Thực hiện RIGHT JOIN
# Tham số: left_on và right_on do tên cột khóa ở 2 bảng khác nhau
right_join_df = pd.merge(student, course, left_on='course_id', right_on='id', how='right')

print(f"Số lượng bản ghi sau Right Join: {len(right_join_df)}")
display(right_join_df)

Số lượng bản ghi sau Right Join: 4

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke
3         NaN                NaN       NaN       <NA>    NaN  26     Tin hoc

4. RIGHT JOIN (Kết nối phải)
+ Bản chất: Ngược lại với Left Join. Giữ lại toàn bộ dữ liệu của bảng bên phải (bảng điểm), sau đó tìm tên sinh viên ở bảng trái đắp sang.
+ Trong Pandas: Cú pháp pd.merge(df_student, df_score, on='student_id', how='right').
+ Nhận xét: Trong bài toán này, Right Join sẽ bảo toàn mọi bản ghi điểm số. Nếu có một mã student_id lạ trong bảng điểm mà không tồn tại trong danh sách sinh viên ban đầu, dữ liệu về tên/lớp của người đó sẽ bị trống (NaN).

In [16]:
# Thực hiện Full Outer Join
outer_join_df = pd.merge(student, course, left_on='course_id', right_on='id', how='outer')

print(f"Số lượng bản ghi: {len(outer_join_df)}")
display(outer_join_df)

Số lượng bản ghi: 11

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24,5.5,NaN,NaN
5,NaN,NaN,NaN,<NA>,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,<NA>,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,<NA>,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,<NA>,7.0,NaN,NaN

5. FULL OUTER JOIN (Kết nối ngoài đầy đủ)
+ Bản chất: Giữ lại tất cả dữ liệu từ cả hai bảng, bất kể có khớp nhau hay không. Đây là sự kết hợp của cả Left Join và Right Join.
+ Trong Pandas: Cú pháp pd.merge(df_student, df_score, on='student_id', how='outer').
+ Nhận xét: Cách này đảm bảo bạn không bị mất bất kỳ một mẩu thông tin nào của cả 2 bảng. Những chỗ không khớp nhau giữa 2 bảng sẽ đều được điền giá trị NaN. Sau khi Full Outer Join, bạn có thể lọc các giá trị NaN để tìm ra những sinh viên "chỉ có tên mà không có điểm" hoặc "có điểm mà không có tên".

#2.Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL,trong đó các giá trị được điền là những giá trị nằm trong bảng course và loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết:
- a. Tổng số sinh viên, điểm trung bình của từng lớp.
- b. Tổng số sinh viên, điểm trung bình của từng môn học.
- c. Phân loại thi đua theo số điểm của từng môn học biết:
i. Điểm TB ≥ 9.0: Xuất sắc.
ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.
iii. Điểm TB < 6.0: Kém.

In [29]:
# 1. Cập nhật giá trị course_id còn thiếu (Tương đương: UPDATE student SET course_id = 26 WHERE course_id IS NULL)
# Vì bảng course có mã 26 (Tin học) chưa ai đăng ký, ta sẽ điền 26 cho các bạn bị thiếu mã môn.
student['course_id'] = student['course_id'].fillna(26)

# 2. Loại bỏ bản ghi có course_id không nằm trong bảng course (Tương đương: DELETE FROM student WHERE course_id NOT IN (12, 34, 26))
valid_course_ids = course['id'].tolist()
student_cleaned = student[student['course_id'].isin(valid_course_ids)].copy()

print(f"Số sinh viên hợp lệ sau khi làm sạch: {len(student_cleaned)}")

Số sinh viên hợp lệ sau khi làm sạch: 6

In [30]:
# Lấy giá trị course_id nhỏ nhất từ bảng course
min_course_id = course['id'].min()

# Cập nhật các giá trị course_id còn thiếu (NaN) trong bảng student
student.loc[student['course_id'].isna(), 'course_id'] = min_course_id

# Hiển thị DataFrame student sau khi cập nhật để kiểm tra
display(student)

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,7.0,3.0,4.0,2026-04-10 00:33:35.558565
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0,2026-04-04 00:33:35.558565
2,3,Pham Van Nam,Toan Tin,12,7.9,4.0,2.0,1.0,2026-04-07 00:33:35.558565
3,4,Le Thanh Huyen,Toan Tin,20,7.2,5.0,3.0,2.0,2026-04-08 00:33:35.558565
4,5,Vu Quoc Anh,May Tinh,24,8.0,3.0,1.0,1.0,2026-04-06 00:33:35.558565
5,6,Dang Thuy Linh,May Tinh,24,5.5,8.0,4.0,2.0,2026-04-11 00:33:35.558565
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0,2026-04-04 00:33:35.558565
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0,2026-04-05 00:33:35.558565
8,9,Duong Huu Phuc,Kinh Te,12,7.2,5.0,2.0,2.0,2026-04-08 00:33:35.558565
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0,2026-04-09 00:33:35.558565

In [31]:
# a. Tổng số sinh viên, điểm trung bình của từng lớp
df_class = student_cleaned.groupby('class').agg(
    Tong_SV=('student_id', 'count'),
    Diem_TB=('score', 'mean')
).reset_index()

# Làm tròn điểm TB đến 2 chữ số thập phân cho đẹp
df_class['Diem_TB'] = df_class['Diem_TB'].round(2)

print("\n--- a. Thống kê theo Lớp ---")
display(df_class)

--- a. Thống kê theo Lớp ---

      class  Tong_SV  Diem_TB
0   Kinh Te        3     8.53
1  May Tinh        2     6.85
2  Toan Tin        1     7.90

In [32]:
# b. Tổng số sinh viên, điểm trung bình của từng môn học
# Kết nối với bảng course để lấy tên môn học cho trực quan
merged_df = pd.merge(student_cleaned, course, left_on='course_id', right_on='id', how='inner')

df_course = merged_df.groupby(['course_id', 'course_name']).agg(
    Tong_SV=('student_id', 'count'),
    Diem_TB=('score', 'mean')
).reset_index()

df_course['Diem_TB'] = df_course['Diem_TB'].round(2)

print("\n--- b. Thống kê theo Môn học ---")
display(df_course[['course_name', 'Tong_SV', 'Diem_TB']])

--- b. Thống kê theo Môn học ---

  course_name  Tong_SV  Diem_TB
0   Giai tich        4      7.2
1    Thong ke        2      9.2

In [33]:
# c. Phân loại thi đua theo số điểm của từng môn học
def phan_loai_thi_dua(diem):
    if diem >= 9.0:
        return 'Xuất sắc'
    elif diem >= 6.0:
        return 'Tốt'
    else:
        return 'Kém'

# Áp dụng hàm phân loại vào cột Diem_TB
df_course['Phan_Loai'] = df_course['Diem_TB'].apply(phan_loai_thi_dua)

print("\n--- c. Phân loại thi đua từng môn học ---")
display(df_course[['course_name', 'Diem_TB', 'Phan_Loai']])

--- c. Phân loại thi đua từng môn học ---

  course_name  Diem_TB Phan_Loai
0   Giai tich      7.2       Tốt
1    Thong ke      9.2  Xuất sắc

1. Kỹ năng Làm sạch dữ liệu (Data Cleaning)
Đề bài không yêu cầu bạn tính toán ngay lập tức mà bắt buộc bạn phải qua 2 bước dọn dẹp dữ liệu:
+ Xử lý giá trị khuyết thiếu (Missing Values): Cập nhật các course_id bị trống. Trong thực tế, dữ liệu thu thập về thường xuyên bị thiếu hụt. Việc điền bù một mã hợp lệ (như mã 26) giúp ta giữ lại được bản ghi của sinh viên đó thay vì xóa đi một cách lãng phí.
+ Đảm bảo tính toàn vẹn tham chiếu (Referential Integrity): Loại bỏ các sinh viên học mã môn "ảo" (20 và 24). Rõ ràng trường chỉ đào tạo 3 môn (12, 34, 26) mà sinh viên lại có điểm ở môn 20 và 24, chứng tỏ lỗi do người nhập liệu hoặc hệ thống lưu trữ sai. Việc xóa bỏ các dòng này giúp báo cáo không bị rác.
2. Bài học về nguyên tắc "Garbage In, Garbage Out" (Rác vào thì rác ra)
Câu 2 ngầm dạy một nguyên tắc cốt lõi: Tuyệt đối không được thống kê, báo cáo khi dữ liệu chưa sạch.
+ Nếu bạn vội vàng tính điểm trung bình (các ý a, b, c) ngay trên bảng gốc 10 người, bạn sẽ tính nhầm cả điểm của những môn học không tồn tại, khiến quỹ điểm của lớp/môn bị sai lệch hoàn toàn.
+ Đề bài ép bạn phải làm sạch rồi mới được tính toán, đây là một tư duy rất chuẩn xác.
3. Nhận xét về kết quả cuối cùng
+ Sự hao hụt dữ liệu là bình thường: Như chúng ta đã thấy, từ 10 sinh viên ban đầu chỉ còn 6 sinh viên được đưa vào báo cáo thống kê (mất đi 40% dữ liệu). Trong thực tế, việc loại bỏ các dữ liệu nhiễu/sai logic để bảo vệ tính chính xác của toàn bộ file báo cáo là một quyết định đánh đổi bắt buộc.
+ Tính bao quát: Các ý a, b, c kiểm tra đầy đủ khả năng sử dụng hàm gom nhóm (GROUP BY), hàm tổng hợp (COUNT, AVG) và cả khả năng viết điều kiện phân loại (CASE WHEN trong SQL hoặc hàm IF/ELSE trong Python).

#3. Hãy xếp hạng sinh viên thông qua:
- a. Điểm số.
- b. Điểm số theo lớp học.
- c. Điểm số theo mã môn học

In [23]:
# a. Xếp hạng tổng thể theo điểm số (Từ cao xuống thấp)
student['rank_overall'] = student['score'].rank(method='dense', ascending=False)

# b. Xếp hạng theo lớp học (Mỗi lớp xếp hạng riêng)
student['rank_by_class'] = student.groupby('class')['score'].rank(method='dense', ascending=False)

# c. Xếp hạng theo mã môn học (Mỗi môn xếp hạng riêng)
student['rank_by_course'] = student.groupby('course_id')['score'].rank(method='dense', ascending=False)

# In kết quả, sắp xếp theo Lớp và Thứ hạng để dễ quan sát
display(student.sort_values(by=['class', 'rank_by_class']))

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0
8,9,Duong Huu Phuc,Kinh Te,12,7.2,5.0,2.0,2.0
4,5,Vu Quoc Anh,May Tinh,24,8.0,3.0,1.0,1.0
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,7.0,3.0,4.0
5,6,Dang Thuy Linh,May Tinh,24,5.5,8.0,4.0,2.0
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0
2,3,Pham Van Nam,Toan Tin,12,7.9,4.0,2.0,1.0
3,4,Le Thanh Huyen,Toan Tin,20,7.2,5.0,3.0,2.0

In [24]:
# Trước tiên, đảm bảo bảng student được sắp xếp theo điểm số từ cao xuống thấp
student_sorted = student.sort_values(by='score', ascending=False)

print("=== a. THEO ĐIỂM SỐ TỔNG THỂ ===")
print("--- Top 3 cao nhất ---")
display(student_sorted.head(3))
print("--- Top 3 thấp nhất ---")
display(student_sorted.tail(3))


print("\n=== b. THEO LỚP HỌC ===")
# Dùng groupby theo 'class', sau đó lấy 3 người đứng đầu/cuối của mỗi lớp
print("--- Top 3 cao nhất mỗi lớp ---")
display(student_sorted.groupby('class').head(3).sort_values(by=['class', 'score'], ascending=[True, False]))

print("--- Top 3 thấp nhất mỗi lớp ---")
display(student_sorted.groupby('class').tail(3).sort_values(by=['class', 'score'], ascending=[True, True]))


print("\n=== c. THEO MÃ MÔN HỌC ===")
# Dùng groupby theo 'course_id', sau đó lấy 3 người đứng đầu/cuối của mỗi môn
print("--- Top 3 cao nhất mỗi môn ---")
display(student_sorted.groupby('course_id').head(3).sort_values(by=['course_id', 'score'], ascending=[True, False]))

print("--- Top 3 thấp nhất mỗi môn ---")
display(student_sorted.groupby('course_id').tail(3).sort_values(by=['course_id', 'score'], ascending=[True, True]))

=== a. THEO ĐIỂM SỐ TỔNG THỂ ===
--- Top 3 cao nhất ---

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0

--- Top 3 thấp nhất ---

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,7.0,3.0,4.0
5,6,Dang Thuy Linh,May Tinh,24,5.5,8.0,4.0,2.0

=== b. THEO LỚP HỌC ===
--- Top 3 cao nhất mỗi lớp ---

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0
8,9,Duong Huu Phuc,Kinh Te,12,7.2,5.0,2.0,2.0
4,5,Vu Quoc Anh,May Tinh,24,8.0,3.0,1.0,1.0
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,7.0,3.0,4.0
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0
2,3,Pham Van Nam,Toan Tin,12,7.9,4.0,2.0,1.0
3,4,Le Thanh Huyen,Toan Tin,20,7.2,5.0,3.0,2.0

--- Top 3 thấp nhất mỗi lớp ---

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
8,9,Duong Huu Phuc,Kinh Te,12,7.2,5.0,2.0,2.0
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0
5,6,Dang Thuy Linh,May Tinh,24,5.5,8.0,4.0,2.0
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,7.0,3.0,4.0
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0
3,4,Le Thanh Huyen,Toan Tin,20,7.2,5.0,3.0,2.0
2,3,Pham Van Nam,Toan Tin,12,7.9,4.0,2.0,1.0
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0

=== c. THEO MÃ MÔN HỌC ===
--- Top 3 cao nhất mỗi môn ---

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
2,3,Pham Van Nam,Toan Tin,12,7.9,4.0,2.0,1.0
8,9,Duong Huu Phuc,Kinh Te,12,7.2,5.0,2.0,2.0
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0
3,4,Le Thanh Huyen,Toan Tin,20,7.2,5.0,3.0,2.0
4,5,Vu Quoc Anh,May Tinh,24,8.0,3.0,1.0,1.0
5,6,Dang Thuy Linh,May Tinh,24,5.5,8.0,4.0,2.0
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0

--- Top 3 thấp nhất mỗi môn ---

,student_id,name,class,course_id,score,rank_overall,rank_by_class,rank_by_course
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,7.0,3.0,4.0
9,10,Cao Thi Hanh,May Tinh,12,7.0,6.0,2.0,3.0
8,9,Duong Huu Phuc,Kinh Te,12,7.2,5.0,2.0,2.0
3,4,Le Thanh Huyen,Toan Tin,20,7.2,5.0,3.0,2.0
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,2.0,1.0,1.0
5,6,Dang Thuy Linh,May Tinh,24,5.5,8.0,4.0,2.0
4,5,Vu Quoc Anh,May Tinh,24,8.0,3.0,1.0,1.0
1,2,Tran Thi Lan,Kinh Te,34,9.2,1.0,1.0,1.0
6,7,Bui Tien Dung,Kinh Te,34,9.2,1.0,1.0,1.0

1. Trọng tâm kỹ năng: Kỹ thuật phân vùng dữ liệu (Window/Partitioning)
Nếu Câu 2 yêu cầu bạn dùng GROUP BY để gom nhóm và tính ra một giá trị duy nhất (tổng số, trung bình) cho cả nhóm, thì Câu 3 lại đòi hỏi một kỹ năng cao cấp hơn: Vẫn chia nhóm nhưng phải giữ nguyên từng bản ghi cá nhân để so sánh.
+ Ý a (Toàn cục): Xếp hạng trên toàn bộ sinh viên (dễ nhất).
+ Ý b & c (Phân vùng): Xếp hạng riêng trong nội bộ từng lớp hoặc từng môn học. Điều này đòi hỏi bạn phải biết dùng Window Functions (như RANK() OVER (PARTITION BY...) trong SQL) hoặc kết hợp groupby().rank() trong Pandas.
2. Điểm "bẫy" số 1:Xử lý các trường hợp đồng điểm (Ties)
+Đề bài yêu cầu xếp hạng theo điểm số nhưng lại không nói rõ: Nếu 2 sinh viên có cùng điểm thì xếp hạng như thế nào? * Ví dụ: Nếu có hai điểm 9.2 (như bạn Trần Thị Lan và Bùi Tiến Dũng trong dữ liệu), thì cả hai xếp hạng 1, người tiếp theo xếp hạng 2 (Dense Rank)? Hay người tiếp theo xếp hạng 3 (Standard Rank)? Việc chọn phương pháp xếp hạng nào sẽ ảnh hưởng trực tiếp đến kết quả "Top 3" mà đề bài yêu cầu tìm kiếm.

3. Điểm "bẫy" số 2: Số lượng dữ liệu không đủ (Hệ quả từ Câu 2)
Đây là một điểm cực kỳ thực tế mà người làm Data Analyst hay gặp phải:
+ Ở Câu 2, chúng ta đã thanh lọc dữ liệu và chỉ còn lại 6 sinh viên hợp lệ.
+ Khi bạn chia 6 sinh viên này vào các Lớp học (Ý b) hoặc Môn học (Ý c), có thể một lớp/môn chỉ có 1 đến 2 sinh viên.
+ Khi đó, yêu cầu "Tìm Top 3 cao nhất và Top 3 thấp nhất" sẽ trở nên khá buồn cười, vì danh sách Top 3 và Bottom 3 bị trùng lặp nhau (cả lớp có 2 người thì người hạng nhất cũng nằm trong top 3 thấp nhất). Đề bài cố tình đưa ra yêu cầu này để xem người phân tích có nhận ra sự mâu thuẫn về mặt số lượng (Sample size) sau khi đã cắt gọt dữ liệu hay không.
4. Tính ứng dụng thực tế: Tư duy làm Dashboard Báo cáo
Trong công việc thực tế, logic của Câu 3 chính là logic để xây dựng các bảng xếp hạng (Leaderboards) trên Dashboard:
+ Ý a: Bảng vàng toàn công ty.
+ Ý b, c: Top nhân viên xuất sắc nhất của từng Phòng ban / Từng khu vực.

#4.Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được

In [25]:
import pandas as pd

# 1. Đảm bảo bạn đã có cột thứ hạng tổng thể (nếu chưa có thì tính lại)
student['rank_overall'] = student['score'].rank(method='dense', ascending=False)

# 2. Lấy thời gian hiện tại
current_time = pd.Timestamp.now()

# 3. Tạo cột graduation_date (Kiểu DATETIME)
# Cộng thời gian hiện tại với thứ hạng (đơn vị: D = Days/Ngày)
student['graduation_date'] = current_time + pd.to_timedelta(student['rank_overall'], unit='D')

# In kết quả kiểm tra
print(f"Thời gian hiện tại được hệ thống ghi nhận: {current_time.strftime('%Y-%m-%d %H:%M:%S')}")
display(student[['student_id', 'name', 'score', 'rank_overall', 'graduation_date']].sort_values(by='rank_overall'))

Thời gian hiện tại được hệ thống ghi nhận: 2026-04-03 00:33:35

,student_id,name,score,rank_overall,graduation_date
1,2,Tran Thi Lan,9.2,1.0,2026-04-04 00:33:35.558565
6,7,Bui Tien Dung,9.2,1.0,2026-04-04 00:33:35.558565
7,8,Ho Ngoc Mai,8.8,2.0,2026-04-05 00:33:35.558565
4,5,Vu Quoc Anh,8.0,3.0,2026-04-06 00:33:35.558565
2,3,Pham Van Nam,7.9,4.0,2026-04-07 00:33:35.558565
3,4,Le Thanh Huyen,7.2,5.0,2026-04-08 00:33:35.558565
8,9,Duong Huu Phuc,7.2,5.0,2026-04-08 00:33:35.558565
9,10,Cao Thi Hanh,7.0,6.0,2026-04-09 00:33:35.558565
0,1,Nguyen Minh Hoang,6.7,7.0,2026-04-10 00:33:35.558565
5,6,Dang Thuy Linh,5.5,8.0,2026-04-11 00:33:35.558565

1. Kiểm tra kỹ năng xử lý Datetime: Đánh giá khả năng lấy mốc thời gian thực tế và thực hiện phép cộng/trừ trên dữ liệu thời gian.
2. Tính kế thừa (Data Pipeline): Câu 4 phụ thuộc hoàn toàn vào kết quả của Câu 3. Nếu bạn xếp hạng sai ở Câu 3, ngày tốt nghiệp ở Câu 4 sẽ sai theo.
3. Logic thực tế rất hay: Điểm cao $\rightarrow$ Hạng nhỏ (hạng 1, hạng 2) $\rightarrow$ Bị cộng ít thời gian $\rightarrow$ Tốt nghiệp sớm. Và ngược lại.
4. Điểm thiếu sót cần tự quy ước: Đề không nói rõ cộng số hạng vào đơn vị thời gian nào, nên khi code bạn cần tự ngầm hiểu và quy ước (ví dụ: lấy thời gian hiện tại cộng thêm số ngày hoặc số tháng tương ứng với hạng).