##### Kết nối database

In [47]:
import sqlite3
import pandas as pd
from datetime import datetime, timedelta

In [ ]:
# kết nối
conn = sqlite3.connect("tanh.db")

In [49]:
cursor = conn.cursor()

##### Tạo bảng

In [50]:
students = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngọc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]

courses = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]

# 3. Tạo bảng và chèn dữ liệu
cursor.execute('CREATE TABLE course (id INTEGER PRIMARY KEY, course_name TEXT)')
cursor.execute('CREATE TABLE student (student_id INTEGER, name TEXT, class TEXT, course_id INTEGER, score REAL)')

cursor.executemany('INSERT INTO course VALUES (?, ?)', courses)
cursor.executemany('INSERT INTO student VALUES (?, ?, ?, ?, ?)', students)

print("Đã khởi tạo database và chèn dữ liệu thành công")

Đã khởi tạo database và chèn dữ liệu thành công

##### Câu 1

In [52]:
# Tích Descartes
query_cartesian = "SELECT * FROM student CROSS JOIN course"
df_cartesian = pd.read_sql_query(query_cartesian, conn)
print("--- Tích Descartes ---")
display(df_cartesian)

--- Tích Descartes ---

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngọc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngọc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngọc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

In [60]:
query_inner = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c ON s.course_id = c.id
"""
df_inner = pd.read_sql_query(query_inner, conn)
print("--- INNER JOIN ---")
display(df_inner)

--- INNER JOIN ---

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

In [59]:
query_left = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id
"""
df_left = pd.read_sql_query(query_left, conn)
print("--- LEFT JOIN ---")
display(df_left)

--- LEFT JOIN ---

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngọc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

In [ ]:
query_right = """
SELECT c.course_name, s.*
FROM course c
LEFT JOIN student s ON c.id = s.course_id
"""
df_right = pd.read_sql_query(query_right, conn)
print("--- RIGHT JOIN ---")
display(df_right)

--- RIGHT JOIN (Mô phỏng) ---

  course_name  student_id               name     class  course_id  score
0   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1     Tin hoc         NaN               None      None        NaN    NaN
2    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
3    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2

In [61]:
query_full = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id
UNION
SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s ON c.id = s.course_id
"""
df_full = pd.read_sql_query(query_full, conn)
print("--- FULL OUTER JOIN ---")
display(df_full)

--- FULL OUTER JOIN ---

    student_id               name     class  course_id  score course_name
0          NaN               None      None        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9        None
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2        None
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0        None
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5        None
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngọc Mai  Toan Tin       20.0    8.8        None
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2        None
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0        None

> Nhận xét:
- Tích Descartes: Phù hợp để tạo tổ hợp nhưng dữ liệu thường bị nhiễu 

- INNER JOIN: Giúp dữ liệu sạch nhưng làm mất đi các sinh viên chưa có mã môn hợp lệ.

- LEFT/RIGHT JOIN: Dùng khi muốn giữ lại các đối tượng chưa có dữ liệu

##### Câu 2

In [ ]:
# 1. Cập nhật course_id còn thiếu 
cursor.execute("UPDATE student SET course_id = 12 WHERE course_id IS NULL")

# 2. Loại bỏ các bản ghi có course_id không tồn tại trong bảng course
cursor.execute("DELETE FROM student WHERE course_id NOT IN (SELECT id FROM course)")

print("Đã làm sạch dữ liệu thành công!")

Đã làm sạch dữ liệu thành công!

In [63]:
query_a = """
SELECT class, COUNT(student_id) as total_students, AVG(score) as average_score
FROM student
GROUP BY class
"""
print("--- Kết quả câu a ---")
display(pd.read_sql_query(query_a, conn))

--- Kết quả câu a ---

      class  total_students  average_score
0   Kinh Te               3       8.533333
1  May Tinh               2       6.850000
2  Toan Tin               1       7.900000

In [64]:
query_b = """
SELECT c.course_name, COUNT(s.student_id) as total_students, AVG(s.score) as average_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
print("--- Kết quả câu b ---")
display(pd.read_sql_query(query_b, conn))

--- Kết quả câu b ---

  course_name  total_students  average_score
0   Giai tich               4            7.2
1    Thong ke               2            9.2

In [65]:
query_c = """
SELECT c.course_name, 
       AVG(s.score) as score_avg,
       CASE 
           WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6.0 THEN 'Tot'
           ELSE 'Kem'
       END as classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
print("--- Kết quả câu c ---")
display(pd.read_sql_query(query_c, conn))

--- Kết quả câu c ---

  course_name  score_avg classification
0   Giai tich        7.2            Tot
1    Thong ke        9.2       Xuat sac

> Nhận xét:
-  Sau khi xóa các mã không tồn tại (20, 24), số lượng sinh viên tham gia tính toán giảm xuống (chỉ còn các sinh viên học môn 12 và 34).

- Chất lượng học tập:  Môn Thong ke đạt kết quả cực tốt với điểm trung bình 9.2, xếp loại Xuat sac.

- Môn Giai tich có điểm trung bình ở mức 7.2, xếp loại Tot.

- Phân bổ lớp: Lớp Kinh Te và Toan Tin cho thấy sự ổn định về mặt điểm số sau khi dữ liệu đã được chuẩn hóa.

##### Câu 3

In [66]:
query_3a = """
SELECT name, score, 
       RANK() OVER (ORDER BY score DESC) as rank
FROM student
"""
df_3a = pd.read_sql_query(query_3a, conn)

print("--- Xếp hạng theo điểm số toàn trường ---")
display(df_3a)

# Top 3 cao nhất và thấp nhất
print("Top 3 điểm cao nhất:")
display(df_3a.head(3))
print("Top 3 điểm thấp nhất:")
display(df_3a.tail(3))

--- Xếp hạng theo điểm số toàn trường ---

                name  score  rank
0       Tran Thi Lan    9.2     1
1      Bui Tien Dung    9.2     1
2       Pham Van Nam    7.9     3
3     Duong Huu Phuc    7.2     4
4       Cao Thi Hanh    7.0     5
5  Nguyen Minh Hoang    6.7     6

Top 3 điểm cao nhất:

            name  score  rank
0   Tran Thi Lan    9.2     1
1  Bui Tien Dung    9.2     1
2   Pham Van Nam    7.9     3

Top 3 điểm thấp nhất:

                name  score  rank
3     Duong Huu Phuc    7.2     4
4       Cao Thi Hanh    7.0     5
5  Nguyen Minh Hoang    6.7     6

In [ ]:
query_3b = """
SELECT name, class, score,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_in_class
FROM student
"""
df_3b = pd.read_sql_query(query_3b, conn)

print("--- Xếp hạng theo lớp học ---")
display(df_3b)

# Lấy Top 3 mỗi lớp 
top3_class = pd.read_sql_query(f"SELECT * FROM ({query_3b}) WHERE rank_in_class <= 3", conn)
print("Top 3 sinh viên của mỗi lớp:")
display(top3_class)

--- Xếp hạng theo lớp học ---

                name     class  score  rank_in_class
0       Tran Thi Lan   Kinh Te    9.2              1
1      Bui Tien Dung   Kinh Te    9.2              1
2     Duong Huu Phuc   Kinh Te    7.2              3
3       Cao Thi Hanh  May Tinh    7.0              1
4  Nguyen Minh Hoang  May Tinh    6.7              2
5       Pham Van Nam  Toan Tin    7.9              1

Top 3 sinh viên của mỗi lớp:

                name     class  score  rank_in_class
0       Tran Thi Lan   Kinh Te    9.2              1
1      Bui Tien Dung   Kinh Te    9.2              1
2     Duong Huu Phuc   Kinh Te    7.2              3
3       Cao Thi Hanh  May Tinh    7.0              1
4  Nguyen Minh Hoang  May Tinh    6.7              2
5       Pham Van Nam  Toan Tin    7.9              1

In [68]:
query_3c = """
SELECT s.name, c.course_name, s.score,
       RANK() OVER (PARTITION BY s.course_id ORDER BY s.score DESC) as rank_in_course
FROM student s
JOIN course c ON s.course_id = c.id
"""
df_3c = pd.read_sql_query(query_3c, conn)

print("--- Xếp hạng theo môn học ---")
display(df_3c)

# Lấy Top 3 mỗi môn học
top3_course = pd.read_sql_query(f"SELECT * FROM ({query_3c}) WHERE rank_in_course <= 3", conn)
print("Top 3 sinh viên của mỗi môn học:")
display(top3_course)

--- Xếp hạng theo môn học ---

                name course_name  score  rank_in_course
0       Pham Van Nam   Giai tich    7.9               1
1     Duong Huu Phuc   Giai tich    7.2               2
2       Cao Thi Hanh   Giai tich    7.0               3
3  Nguyen Minh Hoang   Giai tich    6.7               4
4       Tran Thi Lan    Thong ke    9.2               1
5      Bui Tien Dung    Thong ke    9.2               1

Top 3 sinh viên của mỗi môn học:

             name course_name  score  rank_in_course
0    Pham Van Nam   Giai tich    7.9               1
1  Duong Huu Phuc   Giai tich    7.2               2
2    Cao Thi Hanh   Giai tich    7.0               3
3    Tran Thi Lan    Thong ke    9.2               1
4   Bui Tien Dung    Thong ke    9.2               1

> Nhận xét:
- Toàn trường: Những bạn học lớp Kinh Te đang chiếm giữ các vị trí đầu bảng với mức điểm tuyệt đối trong bộ dữ liệu (9.2).

- Theo lớp: Xếp hạng theo lớp giúp nhận ra các sinh viên nổi bật trong từng chuyên ngành (như bạn Vu Quoc Anh đứng đầu lớp Máy Tính dù điểm tổng quát có thể thấp hơn các bạn lớp Kinh Tế).

- Theo môn học: Thấy sự cạnh tranh trong từng học phần. Môn Giai tich có sự cạnh tranh cao hơn do số lượng sinh viên sau khi cập nhật dữ liệu tập trung khá đông ở đây.

##### Câu 4

In [69]:
# Thêm cột graduation_date vào bảng student
cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME")
print("Đã thêm cột graduation_date thành công!")

Đã thêm cột graduation_date thành công!

In [70]:
# Sử dụng subquery để tính rank và cập nhật vào bảng chính
update_query = """
WITH student_ranks AS (
    SELECT student_id, 
           RANK() OVER (ORDER BY score DESC) as st_rank
    FROM student
)
UPDATE student
SET graduation_date = (
    SELECT date('now', '+' || st_rank || ' years')
    FROM student_ranks
    WHERE student_ranks.student_id = student.student_id
)
"""

cursor.execute(update_query)
conn.commit()

# Hiển thị kết quả kiểm tra
df_final = pd.read_sql_query("SELECT name, score, graduation_date FROM student ORDER BY score DESC", conn)
print("--- Kết quả cập nhật ngày tốt nghiệp ---")
display(df_final)

--- Kết quả cập nhật ngày tốt nghiệp ---

                name  score graduation_date
0       Tran Thi Lan    9.2      2027-04-03
1      Bui Tien Dung    9.2      2027-04-03
2       Pham Van Nam    7.9      2029-04-03
3     Duong Huu Phuc    7.2      2030-04-03
4       Cao Thi Hanh    7.0      2031-04-03
5  Nguyen Minh Hoang    6.7      2032-04-03

> Nhận xét:
- Bằng cách này, những sinh viên có kết quả học tập tốt hơn (thứ hạng thấp hơn như 1, 2) sẽ có ngày tốt nghiệp sớm hơn so với các bạn có thứ hạng cao (3, 4, 5...)