# Tạo database và bảng

In [1]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Tạo bảng student
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# Tạo bảng course
cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

# Insert dữ liệu

In [2]:
students = [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lai","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",34,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
]

courses = [
(12,"Giai tich"),
(34,"Thong ke"),
(20,"Tin hoc")
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)
cursor.executemany("INSERT INTO course VALUES (?,?)", courses)

conn.commit()

# JOINS

## CROSS JOIN

In [3]:
pd.read_sql_query("""
SELECT * 
FROM student CROSS JOIN course
""", conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  20     Tin hoc
3            2       Tran Thi Lai   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lai   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lai   Kinh Te       34.0    9.2  20     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  20     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  20     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  20     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  20     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  20     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  20     Tin hoc
24           9     Duong Huu Phuc   Kinh Te       34.0    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te       34.0    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te       34.0    7.2  20     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  20     Tin hoc

## INNER JOIN

In [4]:
pd.read_sql_query("""
SELECT * 
FROM student s
INNER JOIN course c ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lai   Kinh Te         34    9.2  34    Thong ke
2           4     Le Thanh Huyen  Toan Tin         20    7.2  20     Tin hoc
3           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke
4           8        Ho Ngoc Mai  Toan Tin         20    8.8  20     Tin hoc
5           9     Duong Huu Phuc   Kinh Te         34    7.2  34    Thong ke

## LEFT JOIN

In [5]:
pd.read_sql_query("""
SELECT * 
FROM student s
LEFT JOIN course c ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lai   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2  20.0     Tin hoc
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  20.0     Tin hoc
8           9     Duong Huu Phuc   Kinh Te       34.0    7.2  34.0    Thong ke
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

## RIGHT JOIN

In [6]:
pd.read_sql_query("""
SELECT * 
FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich           1  Nguyen Minh Hoang  May Tinh         12    6.7
1  34    Thong ke           2       Tran Thi Lai   Kinh Te         34    9.2
2  34    Thong ke           7      Bui Tien Dung   Kinh Te         34    9.2
3  34    Thong ke           9     Duong Huu Phuc   Kinh Te         34    7.2
4  20     Tin hoc           4     Le Thanh Huyen  Toan Tin         20    7.2
5  20     Tin hoc           8        Ho Ngoc Mai  Toan Tin         20    8.8

## FULL OUTER JOIN

In [7]:
pd.read_sql_query("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT * FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lai,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,20.0,Tin hoc
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,20.0,Tin hoc
8,9,Duong Huu Phuc,Kinh Te,34,7.2,34.0,Thong ke
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,20,Tin hoc,4,Le Thanh Huyen,Toan Tin,20.0,7.2
12,20,Tin hoc,8,Ho Ngoc Mai,Toan Tin,20.0,8.8
13,34,Thong ke,2,Tran Thi Lai,Kinh Te,34.0,9.2
14,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2
15,34,Thong ke,9,Duong Huu Phuc,Kinh Te,34.0,7.2

# Làm sạch dữ liệu

In [8]:
clean_df = pd.read_sql_query("""
SELECT *
FROM student
WHERE course_id IN (SELECT id FROM course)
""", conn)

clean_df

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lai   Kinh Te         34    9.2
2           4     Le Thanh Huyen  Toan Tin         20    7.2
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           8        Ho Ngoc Mai  Toan Tin         20    8.8
5           9     Duong Huu Phuc   Kinh Te         34    7.2

# Thống kê theo lớp

In [9]:
pd.read_sql_query("""
SELECT class, 
       COUNT(*) AS total_students,
       ROUND(AVG(score),2) AS avg_score
FROM student
WHERE course_id IN (SELECT id FROM course)
GROUP BY class
""", conn)

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               1       6.70
2  Toan Tin               2       8.00

# Thống kê theo môn

In [10]:
pd.read_sql_query("""
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(s.score),2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  total_students  avg_score
0   Giai tich               1       6.70
1    Thong ke               3       8.53
2     Tin hoc               2       8.00

# Phân loại

In [11]:
pd.read_sql_query("""
SELECT c.course_name,
       ROUND(AVG(s.score),2) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS ranking
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  avg_score ranking
0   Giai tich       6.70     Tot
1    Thong ke       8.53     Tot
2     Tin hoc       8.00     Tot

# Xếp hạng toàn bộ

In [12]:
pd.read_sql_query("""
SELECT *,
RANK() OVER (ORDER BY score DESC) AS rank_all
FROM student
WHERE course_id IN (SELECT id FROM course)
""", conn)

   student_id               name     class  course_id  score  rank_all
0           2       Tran Thi Lai   Kinh Te         34    9.2         1
1           7      Bui Tien Dung   Kinh Te         34    9.2         1
2           8        Ho Ngoc Mai  Toan Tin         20    8.8         3
3           4     Le Thanh Huyen  Toan Tin         20    7.2         4
4           9     Duong Huu Phuc   Kinh Te         34    7.2         4
5           1  Nguyen Minh Hoang  May Tinh         12    6.7         6

# Xếp hạng theo lớp

In [13]:
pd.read_sql_query("""
SELECT *,
RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
WHERE course_id IN (SELECT id FROM course)
""", conn)

   student_id               name     class  course_id  score  rank_class
0           2       Tran Thi Lai   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           9     Duong Huu Phuc   Kinh Te         34    7.2           3
3           1  Nguyen Minh Hoang  May Tinh         12    6.7           1
4           8        Ho Ngoc Mai  Toan Tin         20    8.8           1
5           4     Le Thanh Huyen  Toan Tin         20    7.2           2

# Xếp hạng theo môn

In [14]:
pd.read_sql_query("""
SELECT *,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_course
FROM student
WHERE course_id IN (SELECT id FROM course)
""", conn)

   student_id               name     class  course_id  score  rank_course
0           1  Nguyen Minh Hoang  May Tinh         12    6.7            1
1           8        Ho Ngoc Mai  Toan Tin         20    8.8            1
2           4     Le Thanh Huyen  Toan Tin         20    7.2            2
3           2       Tran Thi Lai   Kinh Te         34    9.2            1
4           7      Bui Tien Dung   Kinh Te         34    9.2            1
5           9     Duong Huu Phuc   Kinh Te         34    7.2            3

# Top 3 cao & thấp

In [ ]:
# Top 3 sinh viên có điểm cao nhất
pd.read_sql_query("""
SELECT *
FROM student
WHERE course_id IN (SELECT id FROM course)
ORDER BY score DESC
LIMIT 3
""", conn)

   student_id           name     class  course_id  score
0           2   Tran Thi Lai   Kinh Te         34    9.2
1           7  Bui Tien Dung   Kinh Te         34    9.2
2           8    Ho Ngoc Mai  Toan Tin         20    8.8

In [ ]:
# Top3 sinh viên có điểm thấp nhất
pd.read_sql_query("""
SELECT *
FROM student
WHERE course_id IN (SELECT id FROM course)
ORDER BY score ASC
LIMIT 3
""", conn)

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           4     Le Thanh Huyen  Toan Tin         20    7.2
2           9     Duong Huu Phuc   Kinh Te         34    7.2

# Thêm cột graduation_date

In [17]:
cursor.execute("""
ALTER TABLE student ADD COLUMN graduation_date DATETIME
""")

# Cập nhật graduation_date theo rank

In [18]:
pd.read_sql_query("""
SELECT student_id, name, score,
DATETIME('now', '+' || 
        RANK() OVER (ORDER BY score DESC) || ' days') AS graduation_date
FROM student
WHERE course_id IN (SELECT id FROM course)
""", conn)

   student_id               name  score      graduation_date
0           2       Tran Thi Lai    9.2  2026-03-29 01:58:44
1           7      Bui Tien Dung    9.2  2026-03-29 01:58:44
2           8        Ho Ngoc Mai    8.8  2026-03-31 01:58:44
3           4     Le Thanh Huyen    7.2  2026-04-01 01:58:44
4           9     Duong Huu Phuc    7.2  2026-04-01 01:58:44
5           1  Nguyen Minh Hoang    6.7  2026-04-03 01:58:44