### PHẦN 1

In [141]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

cursor.execute('''
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
''')

students_data = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]
cursor.executemany('INSERT INTO student VALUES (?,?,?,?,?)', students_data)

cursor.execute('''
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
''')

courses_data = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]
cursor.executemany('INSERT INTO course VALUES (?,?)', courses_data)
def query(sql):
    df = pd.read_sql_query(sql, conn)
    print(f"Tổng số dòng: {len(df)}") 
    return df

df_student = pd.read_sql_query("SELECT * FROM student", conn)
print(f"Tổng số dòng student: {len(df_student)}")
display(df_student)

df_course = pd.read_sql_query("SELECT * FROM course", conn)
print(f"Tổng số dòng course: {len(df_course)}")
display(df_course)

print("Đã tạo xong 2 bảng")

Tổng số dòng student: 10

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

Tổng số dòng course: 3

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

Đã tạo xong 2 bảng

In [142]:
# Tích Descartes
sql_descartes = """
SELECT 
    student.*, 
    course.id AS course_table_id, 
    course.course_name 
FROM student 
CROSS JOIN course
"""

display(query(sql_descartes))

Tổng số dòng: 30

,student_id,name,class,course_id,score,course_table_id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich
1,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,34,Thong ke
2,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,26,Tin hoc
3,2,Tran Thi Lan,Kinh Te,34.0,9.2,12,Giai tich
4,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke
5,2,Tran Thi Lan,Kinh Te,34.0,9.2,26,Tin hoc
6,3,Pham Van Nam,Toan Tin,NaN,7.9,12,Giai tich
7,3,Pham Van Nam,Toan Tin,NaN,7.9,34,Thong ke
8,3,Pham Van Nam,Toan Tin,NaN,7.9,26,Tin hoc
9,4,Le Thanh Huyen,Toan Tin,20.0,7.2,12,Giai tich
10,4,Le Thanh Huyen,Toan Tin,20.0,7.2,34,Thong ke
11,4,Le Thanh Huyen,Toan Tin,20.0,7.2,26,Tin hoc
12,5,Vu Quoc Anh,May Tinh,24.0,8.0,12,Giai tich
13,5,Vu Quoc Anh,May Tinh,24.0,8.0,34,Thong ke
14,5,Vu Quoc Anh,May Tinh,24.0,8.0,26,Tin hoc
15,6,Dang Thuy Linh,May Tinh,24.0,5.5,12,Giai tich
16,6,Dang Thuy Linh,May Tinh,24.0,5.5,34,Thong ke
17,6,Dang Thuy Linh,May Tinh,24.0,5.5,26,Tin hoc
18,7,Bui Tien Dung,Kinh Te,34.0,9.2,12,Giai tich
19,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke
20,7,Bui Tien Dung,Kinh Te,34.0,9.2,26,Tin hoc
21,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,12,Giai tich
22,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,34,Thong ke
23,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,26,Tin hoc
24,9,Duong Huu Phuc,Kinh Te,NaN,7.2,12,Giai tich
25,9,Duong Huu Phuc,Kinh Te,NaN,7.2,34,Thong ke
26,9,Duong Huu Phuc,Kinh Te,NaN,7.2,26,Tin hoc
27,10,Cao Thi Hanh,May Tinh,NaN,7.0,12,Giai tich
28,10,Cao Thi Hanh,May Tinh,NaN,7.0,34,Thong ke
29,10,Cao Thi Hanh,May Tinh,NaN,7.0,26,Tin hoc

In [143]:
# INNER JOIN
sql_inner = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c ON s.course_id = c.id
"""
display(query(sql_inner))

Tổng số dòng: 3

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

In [144]:
# LEFT JOIN 
sql_left = """
SELECT student.*, course.id AS course_table_id, course.course_name 
FROM student 
LEFT JOIN course ON student.course_id = course.id
"""
display(query(sql_left))

Tổng số dòng: 10

,student_id,name,class,course_id,score,course_table_id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None

In [145]:
# RIGHT JOIN 
sql_right = """
SELECT student.*, course.id AS course_table_id, course.course_name 
FROM course 
LEFT JOIN student ON student.course_id = course.id
"""
display(query(sql_right))

Tổng số dòng: 4

,student_id,name,class,course_id,score,course_table_id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke
2,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke
3,NaN,None,None,NaN,NaN,26,Tin hoc

In [146]:
# FULL OUTER JOIN 
sql_full = """
SELECT student.*, course.id AS course_table_id, course.course_name 
FROM student 
LEFT JOIN course ON student.course_id = course.id
UNION
SELECT student.*, course.id AS course_table_id, course.course_name 
FROM course 
LEFT JOIN student ON student.course_id = course.id
"""
display(query(sql_full))

Tổng số dòng: 11

,student_id,name,class,course_id,score,course_table_id,course_name
0,NaN,None,None,NaN,NaN,26.0,Tin hoc
1,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
2,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
3,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
4,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
5,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
6,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None

### PHẦN 2

In [147]:
# 1. Cập nhật các giá trị course_id còn thiếu trong bảng
cursor.execute("UPDATE student SET course_id = 26 WHERE student_id = 3")
cursor.execute("UPDATE student SET course_id = 12 WHERE student_id = 9")
cursor.execute("UPDATE student SET course_id = 26 WHERE student_id = 10")
conn.commit()

# 2. Loại bỏ các bản ghi không tồn tại trong bảng course
cursor.execute('''
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
''')

conn.commit()
print(" Dữ liệu sau khi làm sạch ")
sql_select = "SELECT student_id, name, class, course_id, score FROM student"
display(query(sql_select))

 Dữ liệu sau khi làm sạch
Tổng số dòng: 6

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         12    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

In [148]:
# a. Tổng số sinh viên và điểm trung bình từng lớp
sql_2a = """
SELECT class,
       COUNT(student_id) AS total_students,
       ROUND(AVG(score), 2) AS average_score
FROM student
GROUP BY class
"""
print(" Thống kê theo Lớp ")
display(query(sql_2a))

 Thống kê theo Lớp
Tổng số dòng: 3

      class  total_students  average_score
0   Kinh Te               3           8.53
1  May Tinh               2           6.85
2  Toan Tin               1           7.90

In [149]:
# b. Tổng số sinh viên và điểm trung bình từng môn học
sql_2b = """
SELECT c.course_name, 
       COUNT(s.student_id) AS total_students, 
       ROUND(AVG(s.score), 2) AS average_score
FROM course c                       -- Đổi course lên trước
LEFT JOIN student s ON c.id = s.course_id  -- Dùng LEFT JOIN để lấy hết các môn
GROUP BY c.course_name
"""

print(" Thống kê theo Môn học (Đầy đủ các môn) ")
display(query(sql_2b))

 Thống kê theo Môn học (Đầy đủ các môn)
Tổng số dòng: 3

  course_name  total_students  average_score
0   Giai tich               2           6.95
1    Thong ke               2           9.20
2     Tin hoc               2           7.45

In [150]:
# c. Phân loại thi đua
sql_2c = """
SELECT c.course_name,
       ROUND(AVG(s.score), 2) AS avg_score,
       CASE
            WHEN AVG(s.score) >= 9.0 THEN 'Xuất sắc'
            WHEN AVG(s.score) >= 6.0 THEN 'Tốt'
            ELSE 'Kém'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
print(" Phân loại thi đua theo môn học ")
display(query(sql_2c))

 Phân loại thi đua theo môn học
Tổng số dòng: 3

  course_name  avg_score classification
0   Giai tich       6.95            Tốt
1    Thong ke       9.20       Xuất sắc
2     Tin hoc       7.45            Tốt

### PHẦN 3

A. Xếp hạng sinh viên theo điểm số toàn trường

In [151]:
# Xếp hạng sinh viên điểm cao nhất toàn trường
sql_3a = """
WITH RankedStudents AS (
    SELECT 
        student_id, 
        name, 
        class, 
        course_id, 
        score,
        RANK() OVER (ORDER BY score DESC) as rank_high
    FROM student
)
SELECT 
    student_id, 
    name, 
    class, 
    course_id, 
    score, 
    rank_high 
FROM RankedStudents
WHERE rank_high <= 6
ORDER BY score DESC
"""

print(" Top sinh viên điểm cao nhất toàn trường ")
display(query(sql_3a))

 Top sinh viên điểm cao nhất toàn trường
Tổng số dòng: 6

   student_id               name     class  course_id  score  rank_high
0           2       Tran Thi Lan   Kinh Te         34    9.2          1
1           7      Bui Tien Dung   Kinh Te         34    9.2          1
2           3       Pham Van Nam  Toan Tin         26    7.9          3
3           9     Duong Huu Phuc   Kinh Te         12    7.2          4
4          10       Cao Thi Hanh  May Tinh         26    7.0          5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7          6

In [152]:
# Xếp hạng sinh viên điểm thấp nhất toàn trường
sql_3a_low = """
WITH RankedLowStudents AS (
    SELECT 
        student_id, 
        name, 
        class, 
        course_id, 
        score,
        RANK() OVER (ORDER BY score ASC) as rank_low
    FROM student
)
SELECT 
    student_id, 
    name, 
    class, 
    course_id, 
    score, 
    rank_low 
FROM RankedLowStudents
WHERE rank_low <= 6
ORDER BY score ASC
"""

print(" Top sinh viên có điểm thấp nhất toàn trường ")
display(query(sql_3a_low))

 Top sinh viên có điểm thấp nhất toàn trường
Tổng số dòng: 6

   student_id               name     class  course_id  score  rank_low
0           1  Nguyen Minh Hoang  May Tinh         12    6.7         1
1          10       Cao Thi Hanh  May Tinh         26    7.0         2
2           9     Duong Huu Phuc   Kinh Te         12    7.2         3
3           3       Pham Van Nam  Toan Tin         26    7.9         4
4           2       Tran Thi Lan   Kinh Te         34    9.2         5
5           7      Bui Tien Dung   Kinh Te         34    9.2         5

B. Xếp hạng sinh viên theo điểm số lớp học

In [153]:
# Xếp hạng sinh viên điểm cao nhất theo lớp học
sql_3b = """
WITH ClassRank AS (
    SELECT 
        student_id, 
        name, 
        class, 
        course_id, 
        score,
        RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_high
    FROM student
)
SELECT 
    student_id, 
    name, 
    class, 
    course_id, 
    score, 
    rank_high 
FROM ClassRank
WHERE rank_high <= 5
ORDER BY class, rank_high
"""

print(" Top sinh viên điểm cao nhất theo Lớp ")
display(query(sql_3b))

 Top sinh viên điểm cao nhất theo Lớp
Tổng số dòng: 6

   student_id               name     class  course_id  score  rank_high
0           2       Tran Thi Lan   Kinh Te         34    9.2          1
1           7      Bui Tien Dung   Kinh Te         34    9.2          1
2           9     Duong Huu Phuc   Kinh Te         12    7.2          3
3          10       Cao Thi Hanh  May Tinh         26    7.0          1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7          2
5           3       Pham Van Nam  Toan Tin         26    7.9          1

In [154]:
# Xếp hạng sinh viên điểm thấp nhất theo lớp học
sql_3b_low = """
WITH ClassLowRank AS (
    SELECT 
        student_id, 
        name, 
        class, 
        course_id, 
        score,
        RANK() OVER (PARTITION BY class ORDER BY score ASC) as rank_low
    FROM student
)
SELECT 
    student_id, 
    name, 
    class, 
    course_id, 
    score, 
    rank_low 
FROM ClassLowRank
WHERE rank_low <= 5
ORDER BY class, rank_low
"""

print(" Top sinh viên có điểm thấp nhất theo từng Lớp ")
display(query(sql_3b_low))

 Top sinh viên có điểm thấp nhất theo từng Lớp
Tổng số dòng: 6

   student_id               name     class  course_id  score  rank_low
0           9     Duong Huu Phuc   Kinh Te         12    7.2         1
1           2       Tran Thi Lan   Kinh Te         34    9.2         2
2           7      Bui Tien Dung   Kinh Te         34    9.2         2
3           1  Nguyen Minh Hoang  May Tinh         12    6.7         1
4          10       Cao Thi Hanh  May Tinh         26    7.0         2
5           3       Pham Van Nam  Toan Tin         26    7.9         1

C. Xếp hạng sinh viên theo điểm số môn học

In [155]:
# Xếp hạng sinh viên điểm cao nhất theo môn học 
sql_3c = """
WITH CourseRank AS (
    SELECT 
        s.student_id, 
        s.name, 
        s.class, 
        s.course_id, 
        s.score, 
        c.course_name,
        ROW_NUMBER() OVER (PARTITION BY s.course_id ORDER BY s.score DESC) as rank_high
    FROM student s
    JOIN course c ON s.course_id = c.id
)
SELECT 
    student_id, 
    name, 
    class, 
    course_id, 
    course_name, 
    score, 
    rank_high
FROM CourseRank
WHERE rank_high <= 5
ORDER BY course_name, rank_high
"""

print(" Top sinh viên điểm cao nhất theo Môn học ")
display(query(sql_3c))

 Top sinh viên điểm cao nhất theo Môn học
Tổng số dòng: 6

,student_id,name,class,course_id,course_name,score,rank_high
0,9,Duong Huu Phuc,Kinh Te,12,Giai tich,7.2,1
1,1,Nguyen Minh Hoang,May Tinh,12,Giai tich,6.7,2
2,2,Tran Thi Lan,Kinh Te,34,Thong ke,9.2,1
3,7,Bui Tien Dung,Kinh Te,34,Thong ke,9.2,2
4,3,Pham Van Nam,Toan Tin,26,Tin hoc,7.9,1
5,10,Cao Thi Hanh,May Tinh,26,Tin hoc,7.0,2

In [156]:
#  Xếp hạng sinh viên điểm thấp nhất theo môn học 
sql_3c_low = """
WITH CourseLowRank AS (
    SELECT 
        s.student_id, 
        s.name, 
        s.class, 
        s.course_id, 
        s.score, 
        c.course_name,
        -- Sử dụng ASC để điểm thấp nhất trong mỗi môn đứng hạng 1
        RANK() OVER (PARTITION BY s.course_id ORDER BY s.score ASC) as rank_low
    FROM student s
    JOIN course c ON s.course_id = c.id
)
SELECT 
    student_id, 
    name, 
    class, 
    course_id, 
    course_name, 
    score, 
    rank_low
FROM CourseLowRank
WHERE rank_low <= 5
ORDER BY course_name, rank_low
"""

print(" Top sinh viên có điểm thấp nhất theo Môn học ")
display(query(sql_3c_low))

 Top sinh viên có điểm thấp nhất theo Môn học
Tổng số dòng: 6

,student_id,name,class,course_id,course_name,score,rank_low
0,1,Nguyen Minh Hoang,May Tinh,12,Giai tich,6.7,1
1,9,Duong Huu Phuc,Kinh Te,12,Giai tich,7.2,2
2,2,Tran Thi Lan,Kinh Te,34,Thong ke,9.2,1
3,7,Bui Tien Dung,Kinh Te,34,Thong ke,9.2,1
4,10,Cao Thi Hanh,May Tinh,26,Tin hoc,7.0,1
5,3,Pham Van Nam,Toan Tin,26,Tin hoc,7.9,2

### PHẦN 4

In [157]:
# 1. Thêm cột mới với kiểu dữ liệu DATETIME
try:
    cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME")
    conn.commit()
    print(" Đã thêm cột graduation_date thành công ")
except sqlite3.OperationalError:
    print("Cột đã tồn tại.")

 Đã thêm cột graduation_date thành công

In [158]:
# 2. Cập nhật ngày tốt nghiệp: Ngày hiện tại + (Xếp hạng theo điểm số) ngày
sql_update_date = """
WITH Ranked AS (
    SELECT student_id,
           RANK() OVER (ORDER BY score DESC) as rnk
    FROM student
)
UPDATE student
SET graduation_date = (
    SELECT date('now', '+' || rnk || ' days')
    FROM Ranked
    WHERE Ranked.student_id = student.student_id
)
"""

cursor.execute(sql_update_date)
conn.commit()

print("Kết quả bảng Student sau khi cập nhật ngày tốt nghiệp")
display(query("SELECT student_id, name, score, graduation_date FROM student ORDER BY score DESC"))

Kết quả bảng Student sau khi cập nhật ngày tốt nghiệp
Tổng số dòng: 6

   student_id               name  score graduation_date
0           2       Tran Thi Lan    9.2      2026-04-04
1           7      Bui Tien Dung    9.2      2026-04-04
2           3       Pham Van Nam    7.9      2026-04-06
3           9     Duong Huu Phuc    7.2      2026-04-07
4          10       Cao Thi Hanh    7.0      2026-04-08
5           1  Nguyen Minh Hoang    6.7      2026-04-09