In [5]:
#CELL 1: Import & tạo database
import sqlite3
import pandas as pd

conn = sqlite3.connect("du_lieu_dantri.db")
cursor = conn.cursor()

# Xóa bảng cũ nếu có
cursor.execute("DROP TABLE IF EXISTS student")
cursor.execute("DROP TABLE IF EXISTS course")

# Tạo bảng
cursor.execute("""
CREATE TABLE student(
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

cursor.execute("""
CREATE TABLE course(
    id INTEGER,
    course_name TEXT
)
""")

# Dữ liệu
student_data = [
    (1, "Nguyen Minh Hoang", "May Tinh", 12, 6.7),
    (2, "Tran Thi Lan", "Kinh Te", 34, 9.2),
    (3, "Pham Van Nam", "Toan Tin", None, 7.9),
    (4, "Le Thanh Huyen", "Toan Tin", 20, 7.2),
    (5, "Vu Quoc Anh", "May Tinh", 24, 8.0),
    (6, "Dang Thuy Linh", "May Tinh", 24, 5.5),
    (7, "Bui Tien Dung", "Kinh Te", 34, 9.2),
    (8, "Ho Ngoc Mai", "Toan Tin", 20, 8.8),
    (9, "Duong Huu Phuc", "Kinh Te", None, 7.2),
    (10, "Cao Thi Hanh", "May Tinh", None, 7.0),
]

course_data = [
    (12, "Giai tich"),
    (34, "Thong ke"),
    (26, "Tin hoc"),
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", student_data)
cursor.executemany("INSERT INTO course VALUES (?,?)", course_data)

conn.commit()

In [6]:
#CELL 2: Tích Descartes
df = pd.read_sql("SELECT * FROM student, course;", conn)
df

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

In [7]:
#CELL 3: JOIN
pd.read_sql("""
SELECT *
FROM student s
INNER JOIN course c
ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

In [8]:
#LEFT JOIN
pd.read_sql("""
SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
""", conn)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

In [9]:
#RIGHT JOIN (giả lập)
pd.read_sql("""
SELECT *
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
""", conn)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2
2  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
3  26     Tin hoc         NaN               None      None        NaN    NaN

In [10]:
#FULL JOIN (giả lập)
pd.read_sql("""
SELECT * FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT * FROM course c
LEFT JOIN student s ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

In [11]:
#CELL 4: Cập nhật course_id NULL
cursor.execute("""
UPDATE student
SET course_id = (
    SELECT id FROM course ORDER BY RANDOM() LIMIT 1
)
WHERE course_id IS NULL
""")
conn.commit()

In [12]:
#CELL 5: Thống kê theo lớp
pd.read_sql("""
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score),2) AS avg_score
FROM student
GROUP BY class
""", conn)

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               4       6.80
2  Toan Tin               3       7.97

In [13]:
#CELL 6: Thống kê theo môn
pd.read_sql("""
SELECT c.course_name,
       COUNT(*) AS total_students,
       ROUND(AVG(s.score),2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  total_students  avg_score
0   Giai tich               4        7.2
1    Thong ke               2        9.2

In [14]:
#CELL 7: Phân loại môn
pd.read_sql("""
SELECT c.course_name,
       ROUND(AVG(s.score),2) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS rank
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""", conn)

  course_name  avg_score      rank
0   Giai tich        7.2       Tot
1    Thong ke        9.2  Xuat sac

In [15]:
#CELL 8: Xếp hạng
#Theo điểm
pd.read_sql("""
SELECT *,
RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
""", conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           8        Ho Ngoc Mai  Toan Tin         20    8.8           3
3           5        Vu Quoc Anh  May Tinh         24    8.0           4
4           3       Pham Van Nam  Toan Tin         12    7.9           5
5           4     Le Thanh Huyen  Toan Tin         20    7.2           6
6           9     Duong Huu Phuc   Kinh Te         12    7.2           6
7          10       Cao Thi Hanh  May Tinh         12    7.0           8
8           1  Nguyen Minh Hoang  May Tinh         12    6.7           9
9           6     Dang Thuy Linh  May Tinh         24    5.5          10

In [16]:
#Theo lớp
pd.read_sql("""
SELECT *,
RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
""", conn)

   student_id               name     class  course_id  score  rank_class
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           9     Duong Huu Phuc   Kinh Te         12    7.2           3
3           5        Vu Quoc Anh  May Tinh         24    8.0           1
4          10       Cao Thi Hanh  May Tinh         12    7.0           2
5           1  Nguyen Minh Hoang  May Tinh         12    6.7           3
6           6     Dang Thuy Linh  May Tinh         24    5.5           4
7           8        Ho Ngoc Mai  Toan Tin         20    8.8           1
8           3       Pham Van Nam  Toan Tin         12    7.9           2
9           4     Le Thanh Huyen  Toan Tin         20    7.2           3

In [17]:
#Theo môn
pd.read_sql("""
SELECT s.*, c.course_name,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_course
FROM student s
JOIN course c ON s.course_id = c.id
""", conn)

,student_id,name,class,course_id,score,course_name,rank_course
0,3,Pham Van Nam,Toan Tin,12,7.9,Giai tich,1
1,9,Duong Huu Phuc,Kinh Te,12,7.2,Giai tich,2
2,10,Cao Thi Hanh,May Tinh,12,7.0,Giai tich,3
3,1,Nguyen Minh Hoang,May Tinh,12,6.7,Giai tich,4
4,2,Tran Thi Lan,Kinh Te,34,9.2,Thong ke,1
5,7,Bui Tien Dung,Kinh Te,34,9.2,Thong ke,1

In [18]:
#CELL 9: Top 3 cao nhất & thấp nhất
#Top cao
pd.read_sql("""
SELECT * FROM (
    SELECT *, RANK() OVER (ORDER BY score DESC) r
    FROM student
) WHERE r <= 3
""", conn)

   student_id           name     class  course_id  score  r
0           2   Tran Thi Lan   Kinh Te         34    9.2  1
1           7  Bui Tien Dung   Kinh Te         34    9.2  1
2           8    Ho Ngoc Mai  Toan Tin         20    8.8  3

In [19]:
#Top thấp
pd.read_sql("""
SELECT * FROM (
    SELECT *, RANK() OVER (ORDER BY score ASC) r
    FROM student
) WHERE r <= 3
""", conn)

   student_id               name     class  course_id  score  r
0           6     Dang Thuy Linh  May Tinh         24    5.5  1
1           1  Nguyen Minh Hoang  May Tinh         12    6.7  2
2          10       Cao Thi Hanh  May Tinh         12    7.0  3

In [20]:
#CELL 10: Thêm graduation_date
cursor.execute("ALTER TABLE student ADD COLUMN graduation_date TEXT")
conn.commit()

In [21]:
#CELL 11: Cập nhật ngày tốt nghiệp
cursor.execute("""
UPDATE student
SET graduation_date = DATE('now', '+' || (
    SELECT COUNT(*)
    FROM student s2
    WHERE s2.score > student.score
) || ' days')
""")
conn.commit()

In [22]:
#CELL 12: Xem kết quả cuối
pd.read_sql("SELECT * FROM student", conn)

   student_id               name     class  course_id  score graduation_date
0           1  Nguyen Minh Hoang  May Tinh         12    6.7      2026-04-11
1           2       Tran Thi Lan   Kinh Te         34    9.2      2026-04-03
2           3       Pham Van Nam  Toan Tin         12    7.9      2026-04-07
3           4     Le Thanh Huyen  Toan Tin         20    7.2      2026-04-08
4           5        Vu Quoc Anh  May Tinh         24    8.0      2026-04-06
5           6     Dang Thuy Linh  May Tinh         24    5.5      2026-04-12
6           7      Bui Tien Dung   Kinh Te         34    9.2      2026-04-03
7           8        Ho Ngoc Mai  Toan Tin         20    8.8      2026-04-05
8           9     Duong Huu Phuc   Kinh Te         12    7.2      2026-04-08
9          10       Cao Thi Hanh  May Tinh         12    7.0      2026-04-10