1.Tạo bảng và dữ liệu

In [2]:
import sqlite3

# Kết nối đến cơ sở dữ liệu SQLite (hoặc tạo mới nếu chưa tồn tại)
conn = sqlite3.connect('university.db')
cursor = conn.cursor()

# Tạo bảng course
cursor.execute('''
CREATE TABLE IF NOT EXISTS course (
    id INT PRIMARY KEY,
    course_name VARCHAR(50)
);
''')

# Thêm dữ liệu vào bảng course
cursor.execute("INSERT OR IGNORE INTO course VALUES (12, 'Giai tich');")
cursor.execute("INSERT OR IGNORE INTO course VALUES (34, 'Thong ke');")
cursor.execute("INSERT OR IGNORE INTO course VALUES (26, 'Tin hoc');")

# Tạo bảng student
cursor.execute('''
CREATE TABLE IF NOT EXISTS student (
    student_id INT PRIMARY KEY,
    name VARCHAR(100),
    class VARCHAR(50),
    course_id INT,
    score FLOAT
);
''')

# Thêm dữ liệu vào bảng student
cursor.execute("INSERT OR IGNORE INTO student VALUES (1,'Nguyen Minh Hoang','May Tinh',12,6.7);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (2,'Tran Thi Lan','Kinh Te',34,9.2);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (3,'Pham Van Nam','Toan Tin',NULL,7.9);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (4,'Le Thanh Huyen','Toan Tin',20,7.2);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (5,'Vu Quoc Anh','May Tinh',24,8.0);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (6,'Dang Thuy Linh','May Tinh',24,5.5);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (7,'Bui Tien Dung','Kinh Te',34,9.2);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (8,'Ho Ngoc Mai','Toan Tin',20,8.8);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (9,'Duong Huu Phuc','Kinh Te',NULL,7.2);")
cursor.execute("INSERT OR IGNORE INTO student VALUES (10,'Cao Thi Hanh','May Tinh',NULL,7.0);")

# Lưu các thay đổi và đóng kết nối
conn.commit()
conn.close()

print("Database 'university.db' created and populated successfully.")

Database 'university.db' created and populated successfully.

1. Kết nối bảng
a. Tích Descartes (CROSS JOIN)

In [4]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query
query = "SELECT * FROM student s CROSS JOIN course c;"
df = pd.read_sql_query(query, conn)

# Display the results
display(df)

# Close the connection
conn.close()

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

b. INNER JOIN

In [5]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query
query = """SELECT *
FROM student s
INNER JOIN course c
ON s.course_id = c.id;"""
df_inner_join = pd.read_sql_query(query, conn)

# Display the results
display(df_inner_join)

# Close the connection
conn.close()

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

c. LEFT JOIN

In [6]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query with LEFT JOIN
query = """SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id;"""
df_left_join = pd.read_sql_query(query, conn)

# Display the results
display(df_left_join)

# Close the connection
conn.close()

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

d. RIGHT JOIN

In [7]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query with RIGHT JOIN
query = """SELECT *
FROM student s
RIGHT JOIN course c
ON s.course_id = c.id;"""

# Rewriting the RIGHT JOIN as a LEFT JOIN by swapping tables
query_rewritten = """SELECT 
    s.student_id, s.name, s.class, s.course_id, s.score,
    c.id, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id;"""

df_right_join = pd.read_sql_query(query_rewritten, conn)

# Display the results
display(df_right_join)

# Close the connection
conn.close()

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN               None      None        NaN    NaN  26     Tin hoc

e. FULL OUTER JOIN

In [8]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Query for the LEFT JOIN part
# Explicitly select and alias columns for consistency when using UNION
query_left_join = """
SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id AS student_course_id, -- Alias to distinguish from course.id
    s.score,
    c.id AS course_id,
    c.course_name
FROM student s
LEFT JOIN course c ON s.course_id = c.id;
"""
df_left = pd.read_sql_query(query_left_join, conn)

# Query for the RIGHT JOIN part (rewritten as a LEFT JOIN from the 'right' table to the 'left' table)
# Ensure columns are selected and aliased in the same order as the LEFT JOIN query for UNION compatibility
query_right_join_rewritten = """
SELECT
    s.student_id,
    s.name,
    s.class,
    s.course_id AS student_course_id,
    s.score,
    c.id AS course_id,
    c.course_name
FROM course c
LEFT JOIN student s ON c.id = s.course_id;
"""
df_right = pd.read_sql_query(query_right_join_rewritten, conn)

# Combine the results of both joins using pd.concat and drop_duplicates to simulate UNION
df_full_outer_join = pd.concat([df_left, df_right]).drop_duplicates().reset_index(drop=True)

# Display the results
display(df_full_outer_join)

# Close the connection
conn.close()

,student_id,name,class,student_course_id,score,course_id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None
10,NaN,None,None,NaN,NaN,26.0,Tin hoc

2. Cập nhật course_id & loại bỏ dữ liệu sai
a. Gán course_id hợp lệ

In [9]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('university.db')
c = conn.cursor()

#2. Cập nhật course_id & loại bỏ dữ liệu sai
#a. Gán course_id hợp lệ
c.execute('''
UPDATE student
SET course_id = 26
WHERE course_id IS NULL;
''')

# Commit the changes and close the connection
conn.commit()
conn.close()

print("Students with NULL course_id updated to course_id 26.")

Students with NULL course_id updated to course_id 26.

b. Xóa bản ghi course_id không tồn tại

In [10]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('university.db')
c = conn.cursor()

# DELETE FROM student where course_id not in course
c.execute('''
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course);
''')

# Commit the changes and close the connection
conn.commit()
conn.close()

print("Students with invalid course_id deleted successfully.")

Students with invalid course_id deleted successfully.

a. Tổng SV + điểm TB theo lớp

In [11]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to get class-wise statistics
query = """SELECT class,
       COUNT(*) AS total_students,
       AVG(score) AS avg_score
FROM student
GROUP BY class;"""
df_class_stats = pd.read_sql_query(query, conn)

# Display the results
display(df_class_stats)

# Close the connection
conn.close()

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               2   6.850000
2  Toan Tin               1   7.900000

b. Tổng SV + điểm TB theo môn

In [12]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to get course-wise statistics
query = """SELECT c.course_name,
       COUNT(s.student_id) AS total_students,
       AVG(s.score) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name;"""
df_course_stats = pd.read_sql_query(query, conn)

# Display the results
display(df_course_stats)

# Close the connection
conn.close()

  course_name  total_students  avg_score
0   Giai tich               1   6.700000
1    Thong ke               2   9.200000
2     Tin hoc               3   7.366667

c. Phân loại theo điểm TB môn học

In [13]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to get course-wise classification
query = """SELECT c.course_name,
       AVG(s.score) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name;"""
df_course_classification = pd.read_sql_query(query, conn)

# Display the results
display(df_course_classification)

# Close the connection
conn.close()

  course_name  avg_score classification
0   Giai tich   6.700000            Tot
1    Thong ke   9.200000       Xuat sac
2     Tin hoc   7.366667            Tot

3. Xếp hạng sinh viên
a. Theo điểm toàn bộ

In [14]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to rank students by score
query = """SELECT *,
       RANK() OVER (ORDER BY score DESC) AS ranking
FROM student;"""
df_student_ranking = pd.read_sql_query(query, conn)

# Display the results
display(df_student_ranking)

# Close the connection
conn.close()

   student_id               name     class  course_id  score  ranking
0           2       Tran Thi Lan   Kinh Te         34    9.2        1
1           7      Bui Tien Dung   Kinh Te         34    9.2        1
2           3       Pham Van Nam  Toan Tin         26    7.9        3
3           9     Duong Huu Phuc   Kinh Te         26    7.2        4
4          10       Cao Thi Hanh  May Tinh         26    7.0        5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7        6

b. Theo lớp

In [15]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to rank students by score within each class
query = """SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS ranking
FROM student;"""
df_class_ranking = pd.read_sql_query(query, conn)

# Display the results
display(df_class_ranking)

# Close the connection
conn.close()

   student_id               name     class  course_id  score  ranking
0           2       Tran Thi Lan   Kinh Te         34    9.2        1
1           7      Bui Tien Dung   Kinh Te         34    9.2        1
2           9     Duong Huu Phuc   Kinh Te         26    7.2        3
3          10       Cao Thi Hanh  May Tinh         26    7.0        1
4           1  Nguyen Minh Hoang  May Tinh         12    6.7        2
5           3       Pham Van Nam  Toan Tin         26    7.9        1

c. Theo môn học

In [16]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to rank students by score within each course_id
query = """SELECT *,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS ranking
FROM student;"""
df_course_id_ranking = pd.read_sql_query(query, conn)

# Display the results
display(df_course_id_ranking)

# Close the connection
conn.close()

   student_id               name     class  course_id  score  ranking
0           1  Nguyen Minh Hoang  May Tinh         12    6.7        1
1           3       Pham Van Nam  Toan Tin         26    7.9        1
2           9     Duong Huu Phuc   Kinh Te         26    7.2        2
3          10       Cao Thi Hanh  May Tinh         26    7.0        3
4           2       Tran Thi Lan   Kinh Te         34    9.2        1
5           7      Bui Tien Dung   Kinh Te         34    9.2        1

Top 3 cao nhất

In [17]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to select the top 3 students
query = """SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score DESC) AS rnk
    FROM student
) t
WHERE rnk <= 3;"""
df_top_students = pd.read_sql_query(query, conn)

# Display the results
display(df_top_students)

# Close the connection
conn.close()

   student_id           name     class  course_id  score  rnk
0           2   Tran Thi Lan   Kinh Te         34    9.2    1
1           7  Bui Tien Dung   Kinh Te         34    9.2    1
2           3   Pham Van Nam  Toan Tin         26    7.9    3

Top 3 thấp nhất

In [18]:
import sqlite3
import pandas as pd

# Connect to the database
conn = sqlite3.connect('university.db')

# Execute the SQL query to select the bottom 3 students
query = """SELECT *
FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS rnk
    FROM student
) t
WHERE rnk <= 3;"""
df_bottom_students = pd.read_sql_query(query, conn)

# Display the results
display(df_bottom_students)

# Close the connection
conn.close()

   student_id               name     class  course_id  score  rnk
0           1  Nguyen Minh Hoang  May Tinh         12    6.7    1
1          10       Cao Thi Hanh  May Tinh         26    7.0    2
2           9     Duong Huu Phuc   Kinh Te         26    7.2    3

4. Thêm graduation_date

In [19]:
import sqlite3

# Connect to the database
conn = sqlite3.connect('university.db')
c = conn.cursor()

# Add graduation_date column
c.execute('ALTER TABLE student ADD COLUMN graduation_date DATETIME;')

# Commit the changes and close the connection
conn.commit()
conn.close()

print("Column 'graduation_date' added to 'student' table successfully.")

Column 'graduation_date' added to 'student' table successfully.

Cập nhật theo thứ hạng

In [20]:
import sqlite3
import pandas as pd
from datetime import datetime, timedelta

# Connect to the database
conn = sqlite3.connect('university.db')
cursor = conn.cursor()

# Get students with their ranks
query_ranked_students = """
SELECT student_id, score, RANK() OVER (ORDER BY score DESC) AS rnk
FROM student;
"""
ranked_students_df = pd.read_sql_query(query_ranked_students, conn)

# Calculate graduation dates
current_date = datetime.now()
updates = []
for index, row in ranked_students_df.iterrows():
    student_id = row['student_id']
    rank = row['rnk']
    # Add rank days to the current date
    # SQLite datetime format is 'YYYY-MM-DD HH:MM:SS'
    graduation_date = current_date + timedelta(days=int(rank))
    updates.append((graduation_date.strftime('%Y-%m-%d %H:%M:%S'), student_id))

# Update the graduation_date column for each student
update_query = "UPDATE student SET graduation_date = ? WHERE student_id = ?;"
cursor.executemany(update_query, updates)

# Commit the changes and close the connection
conn.commit()
conn.close()

print("Graduation dates updated successfully based on student rankings.")

Graduation dates updated successfully based on student rankings.