In [ ]:
import sqlite3
import pandas as pd

# tạo database
conn = sqlite3.connect(":memory:")
cur = conn.cursor()

# tạo bảng course
cur.execute("""
CREATE TABLE course(
    id INTEGER PRIMARY KEY,
    course_name TEXT
)
""")

# tạo bảng student
cur.execute("""
CREATE TABLE student(
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")

# dữ liệu course
courses = [
    (12, "Giai tich"),
    (34, "Thong ke"),
    (26, "Tin hoc"),
    (20, "Tin hoc"),
    (24, "Tin hoc")
]

cur.executemany("INSERT INTO course VALUES (?,?)", courses)

# dữ liệu student
students = [
    (1,"Nguyen Minh Hoang","May Tinh",12,6.7),
    (2,"Tran Thi Lan","Kinh Te",34,9.2),
    (3,"Pham Van Nam","Toan Tin",None,7.9),
    (4,"Le Thanh Huyen","Toan Tin",20,7.2),
    (5,"Vu Quoc Anh","May Tinh",24,8.0),
    (6,"Dang Thuy Linh","May Tinh",24,5.5),
    (7,"Bui Tien Dung","Kinh Te",34,9.2),
    (8,"Ho Ngoc Mai","Toan Tin",20,8.8),
    (9,"Duong Huu Phuc","Kinh Te",None,7.2),
    (10,"Cao Thi Hanh","May Tinh",None,7.0)
]

cur.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)

conn.commit()

print("Database created!")

Database created!

In [ ]:
# Decartes product
query = "SELECT * FROM student, course"
print("DECARTES PRODUCT")
display(pd.read_sql(query, conn))


# INNER JOIN
query = """
SELECT *
FROM student
INNER JOIN course
ON student.course_id = course.id
"""
print("INNER JOIN")
display(pd.read_sql(query, conn))


# LEFT JOIN
query = """
SELECT *
FROM student
LEFT JOIN course
ON student.course_id = course.id
"""
print("LEFT JOIN")
display(pd.read_sql(query, conn))


# 4. RIGHT JOIN #do sqlite không hỗ trợ nên em mô phỏng bằng left join , bằng cách đảo vị trí bảng
query = """
SELECT *
FROM course
LEFT JOIN student
ON student.course_id = course.id
"""
print("RIGHT JOIN")
display(pd.read_sql(query, conn))


# 5. FULL OUTER JOIN cũng do sqlite không hỗ trợ nên em kết hợp hai bảng bằng union
query = """
SELECT *
FROM student
LEFT JOIN course
ON student.course_id = course.id

UNION

SELECT *
FROM course
LEFT JOIN student
ON student.course_id = course.id
"""
print("FULL OUTER JOIN")
display(pd.read_sql(query, conn))

DECARTES PRODUCT

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  20     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  24     Tin hoc
3            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
4            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
6            2       Tran Thi Lan   Kinh Te       34.0    9.2  20     Tin hoc
7            2       Tran Thi Lan   Kinh Te       34.0    9.2  24     Tin hoc
8            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
9            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
10           3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
11           3       Pham Van Nam  Toan Tin        NaN    7.9  20     Tin hoc
12           3       Pham Van Nam  Toan Tin        NaN    7.9  24     Tin hoc
13           3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
14           3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
15           4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
16           4     Le Thanh Huyen  Toan Tin       20.0    7.2  20     Tin hoc
17           4     Le Thanh Huyen  Toan Tin       20.0    7.2  24     Tin hoc
18           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
19           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
20           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
21           5        Vu Quoc Anh  May Tinh       24.0    8.0  20     Tin hoc
22           5        Vu Quoc Anh  May Tinh       24.0    8.0  24     Tin hoc
23           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
24           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
25           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
26           6     Dang Thuy Linh  May Tinh       24.0    5.5  20     Tin hoc
27           6     Dang Thuy Linh  May Tinh       24.0    5.5  24     Tin hoc
28           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
29           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
30           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
31           7      Bui Tien Dung   Kinh Te       34.0    9.2  20     Tin hoc
32           7      Bui Tien Dung   Kinh Te       34.0    9.2  24     Tin hoc
33           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
34           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
35           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
36           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  20     Tin hoc
37           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  24     Tin hoc
38           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
39           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
40           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
41           9     Duong Huu Phuc   Kinh Te        NaN    7.2  20     Tin hoc
42           9     Duong Huu Phuc   Kinh Te        NaN    7.2  24     Tin hoc
43           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
44           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
45          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
46          10       Cao Thi Hanh  May Tinh        NaN    7.0  20     Tin hoc
47          10       Cao Thi Hanh  May Tinh        NaN    7.0  24     Tin hoc
48          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
49          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

INNER JOIN

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           4     Le Thanh Huyen  Toan Tin         20    7.2  20     Tin hoc
3           5        Vu Quoc Anh  May Tinh         24    8.0  24     Tin hoc
4           6     Dang Thuy Linh  May Tinh         24    5.5  24     Tin hoc
5           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke
6           8        Ho Ngoc Mai  Toan Tin         20    8.8  20     Tin hoc

LEFT JOIN

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2  20.0     Tin hoc
4           5        Vu Quoc Anh  May Tinh       24.0    8.0  24.0     Tin hoc
5           6     Dang Thuy Linh  May Tinh       24.0    5.5  24.0     Tin hoc
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  20.0     Tin hoc
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

RIGHT JOIN (simulate)

   id course_name  student_id               name     class  course_id  score
0  12   Giai tich         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  20     Tin hoc         8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8
2  20     Tin hoc         4.0     Le Thanh Huyen  Toan Tin       20.0    7.2
3  24     Tin hoc         6.0     Dang Thuy Linh  May Tinh       24.0    5.5
4  24     Tin hoc         5.0        Vu Quoc Anh  May Tinh       24.0    8.0
5  26     Tin hoc         NaN               None      None        NaN    NaN
6  34    Thong ke         7.0      Bui Tien Dung   Kinh Te       34.0    9.2
7  34    Thong ke         2.0       Tran Thi Lan   Kinh Te       34.0    9.2

FULL OUTER JOIN (simulate)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,20.0,Tin hoc
4,5,Vu Quoc Anh,May Tinh,24,8.0,24.0,Tin hoc
5,6,Dang Thuy Linh,May Tinh,24,5.5,24.0,Tin hoc
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,20.0,Tin hoc
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,20,Tin hoc,4,Le Thanh Huyen,Toan Tin,20.0,7.2
12,20,Tin hoc,8,Ho Ngoc Mai,Toan Tin,20.0,8.8
13,24,Tin hoc,5,Vu Quoc Anh,May Tinh,24.0,8.0
14,24,Tin hoc,6,Dang Thuy Linh,May Tinh,24.0,5.5
15,26,Tin hoc,None,None,None,NaN,None
16,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
17,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

kết quả thu được :
+ decartes thì nó sẽ ra cái bảng mà mỗi thành phần của bảng student sẽ kết hợp với tât cả các thành phần của bảng course tạo ra một bảng có số dòng bằng số dòng bảng student nhân với số dòng bảng course
+ left join thì nó sẽ lấy phần chung và phần còn lại của bảng bên trái
+ right join thì cũng tương tự nhưng nó lấy phần chung và phần còn lại của bảng bên phải
+ full outer join là lấy tất

In [ ]:
# loại bỏ bản ghi course không tồn tại
cur.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
AND course_id IS NOT NULL
""")

conn.commit()

# a. Tổng số sinh viên + điểm TB từng lớp
query = """
SELECT class,
COUNT(*) AS total_students,
AVG(score) AS avg_score
FROM student
GROUP BY class
"""
print("Thống kê theo lớp")
display(pd.read_sql(query, conn))


# b. Tổng số sinh viên + điểm TB từng môn
query = """
SELECT course_name,
COUNT(student_id) AS total_students,
AVG(score) AS avg_score
FROM student
JOIN course
ON student.course_id = course.id
GROUP BY course_name
"""
print("Thống kê theo môn")
display(pd.read_sql(query, conn))


# c. Phân loại thi đua
query = """
SELECT student.name,
course.course_name,
score,
CASE
WHEN score >= 9 THEN 'Xuat sac'
WHEN score >= 6 THEN 'Tot'
ELSE 'Kem'
END AS classification
FROM student
JOIN course
ON student.course_id = course.id
"""
print("Phân loại sinh viên")
display(pd.read_sql(query, conn))

Thống kê theo lớp

      class  total_students  avg_score
0   Kinh Te               3   8.533333
1  May Tinh               4   6.800000
2  Toan Tin               3   7.966667

Thống kê theo môn

  course_name  total_students  avg_score
0   Giai tich               1      6.700
1    Thong ke               2      9.200
2     Tin hoc               4      7.375

Phân loại sinh viên

                name course_name  score classification
0  Nguyen Minh Hoang   Giai tich    6.7            Tot
1       Tran Thi Lan    Thong ke    9.2       Xuat sac
2     Le Thanh Huyen     Tin hoc    7.2            Tot
3        Vu Quoc Anh     Tin hoc    8.0            Tot
4     Dang Thuy Linh     Tin hoc    5.5            Kem
5      Bui Tien Dung    Thong ke    9.2       Xuat sac
6        Ho Ngoc Mai     Tin hoc    8.8            Tot

+ phần này dùng hàm gộp , sẽ gộp nhóm và tính toàn bằng các hàm có sẵn để tính theo nhóm , có sửu dụng cả hàm điều kiện

In [ ]:
# a. xếp hạng theo điểm
query = """
SELECT name,
score,
RANK() OVER (ORDER BY score DESC) as rank_score
FROM student
"""
display(pd.read_sql(query, conn))


# b. xếp hạng theo lớp
query = """
SELECT name,
class,
score,
RANK() OVER (PARTITION BY class ORDER BY score DESC) as rank_class
FROM student
"""
display(pd.read_sql(query, conn))


# c. xếp hạng theo môn
query = """
SELECT name,
course_id,
score,
RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as rank_course
FROM student
"""
display(pd.read_sql(query, conn))


# thêm trường graduation_date
cur.execute("""
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
""")

# cập nhật ngày tốt nghiệp dựa trên thứ hạng
cur.execute("""
UPDATE student
SET graduation_date =
datetime('now','+' || score || ' days')
""")

conn.commit()

print("Graduation date updated!")

display(pd.read_sql("SELECT * FROM student", conn))

                name  score  rank_score
0       Tran Thi Lan    9.2           1
1      Bui Tien Dung    9.2           1
2        Ho Ngoc Mai    8.8           3
3        Vu Quoc Anh    8.0           4
4       Pham Van Nam    7.9           5
5     Le Thanh Huyen    7.2           6
6     Duong Huu Phuc    7.2           6
7       Cao Thi Hanh    7.0           8
8  Nguyen Minh Hoang    6.7           9
9     Dang Thuy Linh    5.5          10

                name     class  score  rank_class
0       Tran Thi Lan   Kinh Te    9.2           1
1      Bui Tien Dung   Kinh Te    9.2           1
2     Duong Huu Phuc   Kinh Te    7.2           3
3        Vu Quoc Anh  May Tinh    8.0           1
4       Cao Thi Hanh  May Tinh    7.0           2
5  Nguyen Minh Hoang  May Tinh    6.7           3
6     Dang Thuy Linh  May Tinh    5.5           4
7        Ho Ngoc Mai  Toan Tin    8.8           1
8       Pham Van Nam  Toan Tin    7.9           2
9     Le Thanh Huyen  Toan Tin    7.2           3

                name  course_id  score  rank_course
0       Pham Van Nam        NaN    7.9            1
1     Duong Huu Phuc        NaN    7.2            2
2       Cao Thi Hanh        NaN    7.0            3
3  Nguyen Minh Hoang       12.0    6.7            1
4        Ho Ngoc Mai       20.0    8.8            1
5     Le Thanh Huyen       20.0    7.2            2
6        Vu Quoc Anh       24.0    8.0            1
7     Dang Thuy Linh       24.0    5.5            2
8       Tran Thi Lan       34.0    9.2            1
9      Bui Tien Dung       34.0    9.2            1

Graduation date updated!

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,2026-04-09 17:27:33
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,2026-04-12 05:27:33
2,3,Pham Van Nam,Toan Tin,NaN,7.9,2026-04-10 22:15:33
3,4,Le Thanh Huyen,Toan Tin,20.0,7.2,2026-04-10 05:27:33
4,5,Vu Quoc Anh,May Tinh,24.0,8.0,2026-04-11 00:39:33
5,6,Dang Thuy Linh,May Tinh,24.0,5.5,2026-04-08 12:39:33
6,7,Bui Tien Dung,Kinh Te,34.0,9.2,2026-04-12 05:27:33
7,8,Ho Ngoc Mai,Toan Tin,20.0,8.8,2026-04-11 19:51:33
8,9,Duong Huu Phuc,Kinh Te,NaN,7.2,2026-04-10 05:27:33
9,10,Cao Thi Hanh,May Tinh,NaN,7.0,2026-04-10 00:39:33

+ rank để xếp hạng , những ai bằng điểm sẽ chung một rank nhưgn mức rank dựa trên số lượng , hai người có cùng rank 1 thì người tiếp theo sẽ là rank 3 , hiểu là sẽ nhảy bậc chứ không theo thứ tự liên tiếp