BÀI 1

In [40]:
import sqlite3
import pandas as pd

# Tạo kết nối đến cơ sở dữ liệu SQLite trong bộ nhớ
conn = sqlite3.connect(':memory:')
cursor = conn.cursor()

# Tạo bảng course
cursor.execute('''
CREATE TABLE course (
    id INTEGER PRIMARY KEY,
    course_name TEXT
)''')

# Tạo bảng student
cursor.execute('''
CREATE TABLE student (
    student_id INTEGER PRIMARY KEY,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)''')

# Chèn dữ liệu vào bảng course
courses = [(12, 'Giai tich'), (34, 'Thong ke'), (26, 'Tin hoc')]
cursor.executemany("INSERT INTO course VALUES (?, ?)", courses)

# Chèn dữ liệu vào bảng student 
students = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]
cursor.executemany("INSERT INTO student VALUES (?, ?, ?, ?, ?)", students)
conn.commit()

print("Khởi tạo cơ sở dữ liệu thành công!")

Khởi tạo cơ sở dữ liệu thành công!

In [41]:
print("1. Tích Decartes:")
df_cross = pd.read_sql_query("SELECT * FROM student, course;", conn)
display(df_cross)

1. Tích Decartes:

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
8            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke

In [42]:
print("\n2. INNER JOIN:")
df_inner = pd.read_sql_query("SELECT * FROM student INNER JOIN course ON student.course_id = course.id", conn)
display(df_inner)

2. INNER JOIN:

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

In [43]:
print("\n3. LEFT JOIN:")
df_left = pd.read_sql_query("SELECT * FROM student LEFT JOIN course ON student.course_id = course.id", conn)
display(df_left)

3. LEFT JOIN:

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

In [44]:
print("\n4. RIGHT JOIN:")
df_right = pd.read_sql_query("SELECT * FROM student RIGHT JOIN course ON student.course_id = course.id", conn)
display(df_right)

4. RIGHT JOIN:

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN               None      None        NaN    NaN  26     Tin hoc

In [45]:
print("\n5. FULL OUTER JOIN:")
df_full = pd.read_sql_query("SELECT * FROM student FULL OUTER JOIN course ON student.course_id = course.id", conn)
display(df_full)

5. FULL OUTER JOIN:

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,None
3,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,None
4,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,None
5,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,None
6,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,None
8,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,None
9,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,None
10,NaN,None,None,NaN,NaN,26.0,Tin hoc

Cập nhật làm sạch và thống kê

In [46]:
# Cập nhật course_id 26-Tin học còn thiếu
cursor.execute("UPDATE student SET course_id = 26 WHERE course_id IS NULL")

In [47]:
# Loại bỏ các môn học không tồn tại ở Course
cursor.execute("DELETE FROM student WHERE course_id NOT IN (SELECT id FROM course)")
conn.commit()

In [48]:
# Cập nhật sau khi dọn dẹp
print("Danh sách sau khi cập nhật:")
display(pd.read_sql_query("SELECT * FROM student", conn))

Danh sách sau khi cập nhật:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh         12    6.7
1           2       Tran Thi Lan   Kinh Te         34    9.2
2           3       Pham Van Nam  Toan Tin         26    7.9
3           7      Bui Tien Dung   Kinh Te         34    9.2
4           9     Duong Huu Phuc   Kinh Te         26    7.2
5          10       Cao Thi Hanh  May Tinh         26    7.0

BÀI 2

In [49]:
# 2a. Tổng số sinh viên, điểm trung bình của từng lớp
print("\n2a. Thống kê theo lớp:")
df_2a = pd.read_sql_query('''
    SELECT class, COUNT(student_id) as so_hoc_sinh, AVG(score) as Diem_TB
    FROM student GROUP BY class
''', conn)
df_2a

2a. Thống kê theo lớp:

      class  so_hoc_sinh   Diem_TB
0   Kinh Te            3  8.533333
1  May Tinh            2  6.850000
2  Toan Tin            1  7.900000

In [50]:
# 2b. Tổng số sinh viên, điểm trung bình của từng môn học
print("\n2b. Thống kê theo môn học:")
df_2b = pd.read_sql_query('''
    SELECT course_name as Mon_Hoc, COUNT(student_id) as Tong_SV, ROUND(AVG(s.score), 2) as Diem_TB
    FROM student s JOIN course c ON course_id = id
    GROUP BY course_name
''', conn)
display(df_2b)

2b. Thống kê theo môn học:

     Mon_Hoc  Tong_SV  Diem_TB
0  Giai tich        1     6.70
1   Thong ke        2     9.20
2    Tin hoc        3     7.37

In [51]:
print("\n2c. Phân loại thi đua:")
df_2c = pd.read_sql_query('''
    SELECT Mon_Hoc, 
           Diem_TB,
           CASE 
               WHEN Diem_TB >= 9.0 THEN 'Xuất sắc'
               WHEN Diem_TB >= 6.0 THEN 'Tốt'
               ELSE 'Kém'
           END as Phan_Loai
    FROM (
        SELECT course.course_name as Mon_Hoc, 
               ROUND(AVG(student.score), 2) as Diem_TB
        FROM student, course 
        WHERE student.course_id = course.id
        GROUP BY course.course_name
    )
''', conn)
df_2c

2c. Phân loại thi đua:

     Mon_Hoc  Diem_TB Phan_Loai
0  Giai tich     6.70       Tốt
1   Thong ke     9.20  Xuất sắc
2    Tin hoc     7.37       Tốt

BÀI 3

In [52]:
# 3a. Xếp hạng toàn bộ
df_3a=pd.read_sql_query( "SELECT  student_id,name, class, score, RANK() OVER (ORDER BY score DESC) as Ranked FROM student;",conn)
df_3a

   student_id               name     class  score  Ranked
0           2       Tran Thi Lan   Kinh Te    9.2       1
1           7      Bui Tien Dung   Kinh Te    9.2       1
2           3       Pham Van Nam  Toan Tin    7.9       3
3           9     Duong Huu Phuc   Kinh Te    7.2       4
4          10       Cao Thi Hanh  May Tinh    7.0       5
5           1  Nguyen Minh Hoang  May Tinh    6.7       6

In [53]:
# 3b. Xếp hạng theo lớp
df_3b=pd.read_sql_query("SELECT  student_id,name, class, score, RANK() OVER (PARTITION BY class ORDER BY score DESC) as Ranked FROM student;",conn)
df_3b

   student_id               name     class  score  Ranked
0           2       Tran Thi Lan   Kinh Te    9.2       1
1           7      Bui Tien Dung   Kinh Te    9.2       1
2           9     Duong Huu Phuc   Kinh Te    7.2       3
3          10       Cao Thi Hanh  May Tinh    7.0       1
4           1  Nguyen Minh Hoang  May Tinh    6.7       2
5           3       Pham Van Nam  Toan Tin    7.9       1

In [54]:
# 3c. Xếp hạng theo mã môn học
df_3c=pd.read_sql_query('''
    SELECT s.student_id, s.name, c.course_name, s.score,
           RANK() OVER (PARTITION BY s.course_id ORDER BY s.score DESC) as Ranked
    FROM student s
    JOIN course c ON s.course_id = c.id
''', conn)
df_3c

   student_id               name course_name  score  Ranked
0           1  Nguyen Minh Hoang   Giai tich    6.7       1
1           3       Pham Van Nam     Tin hoc    7.9       1
2           9     Duong Huu Phuc     Tin hoc    7.2       2
3          10       Cao Thi Hanh     Tin hoc    7.0       3
4           2       Tran Thi Lan    Thong ke    9.2       1
5           7      Bui Tien Dung    Thong ke    9.2       1

In [55]:
print("-> TOP 3 CAO NHẤT TOÀN TRƯỜNG:")
display(df_3a[df_3a['Ranked'] <= 3])

print("-> TOP 3 THẤP NHẤT TOÀN TRƯỜNG:")
display(df_3a.sort_values(by='score', ascending=True).head(3))

-> TOP 3 CAO NHẤT TOÀN TRƯỜNG:

   student_id           name     class  score  Ranked
0           2   Tran Thi Lan   Kinh Te    9.2       1
1           7  Bui Tien Dung   Kinh Te    9.2       1
2           3   Pham Van Nam  Toan Tin    7.9       3

-> TOP 3 THẤP NHẤT TOÀN TRƯỜNG:

   student_id               name     class  score  Ranked
5           1  Nguyen Minh Hoang  May Tinh    6.7       6
4          10       Cao Thi Hanh  May Tinh    7.0       5
3           9     Duong Huu Phuc   Kinh Te    7.2       4

In [56]:
print("-> TOP 3 CAO NHẤT TỪNG LỚP:")
display(df_3b[df_3b['Ranked'] <= 3])

print("-> TOP 3 THẤP NHẤT TỪNG LỚP:")
display(df_3b.sort_values(by='score', ascending=True).groupby('class').head(3))

-> TOP 3 CAO NHẤT TỪNG LỚP:

   student_id               name     class  score  Ranked
0           2       Tran Thi Lan   Kinh Te    9.2       1
1           7      Bui Tien Dung   Kinh Te    9.2       1
2           9     Duong Huu Phuc   Kinh Te    7.2       3
3          10       Cao Thi Hanh  May Tinh    7.0       1
4           1  Nguyen Minh Hoang  May Tinh    6.7       2
5           3       Pham Van Nam  Toan Tin    7.9       1

-> TOP 3 THẤP NHẤT TỪNG LỚP:

   student_id               name     class  score  Ranked
4           1  Nguyen Minh Hoang  May Tinh    6.7       2
3          10       Cao Thi Hanh  May Tinh    7.0       1
2           9     Duong Huu Phuc   Kinh Te    7.2       3
5           3       Pham Van Nam  Toan Tin    7.9       1
0           2       Tran Thi Lan   Kinh Te    9.2       1
1           7      Bui Tien Dung   Kinh Te    9.2       1

In [57]:
print("-> TOP 3 CAO NHẤT TỪNG MÔN:")
display(df_3c[df_3c['Ranked'] <= 3])

print("-> TOP 3 THẤP NHẤT TỪNG MÔN:")
display(df_3c.sort_values(by='score', ascending=True).groupby('course_name').head(3))

-> TOP 3 CAO NHẤT TỪNG MÔN:

   student_id               name course_name  score  Ranked
0           1  Nguyen Minh Hoang   Giai tich    6.7       1
1           3       Pham Van Nam     Tin hoc    7.9       1
2           9     Duong Huu Phuc     Tin hoc    7.2       2
3          10       Cao Thi Hanh     Tin hoc    7.0       3
4           2       Tran Thi Lan    Thong ke    9.2       1
5           7      Bui Tien Dung    Thong ke    9.2       1

-> TOP 3 THẤP NHẤT TỪNG MÔN:

   student_id               name course_name  score  Ranked
0           1  Nguyen Minh Hoang   Giai tich    6.7       1
3          10       Cao Thi Hanh     Tin hoc    7.0       3
2           9     Duong Huu Phuc     Tin hoc    7.2       2
1           3       Pham Van Nam     Tin hoc    7.9       1
4           2       Tran Thi Lan    Thong ke    9.2       1
5           7      Bui Tien Dung    Thong ke    9.2       1

BÀI 4

In [58]:
try:
    cursor.execute("ALTER TABLE student ADD COLUMN graduation_date TEXT")
    print("Đã thêm cột graduation_date thành công!")
except sqlite3.OperationalError:
    print("Cột graduation_date đã tồn tại, bỏ qua bước thêm cột.")

conn.execute('''
    UPDATE student 
    SET graduation_date = date('now', 'localtime', '+' || (
        SELECT COUNT(*) + 1 
        FROM student s2 
        WHERE s2.score > student.score
    ) || ' months');
''')
conn.commit()
print("\n=== BẢNG SINH VIÊN SAU KHI CẬP NHẬT NGÀY TỐT NGHIỆP ===")
df_result = pd.read_sql_query("SELECT * FROM student ORDER BY score DESC", conn)
display(df_result)

Đã thêm cột graduation_date thành công!

=== BẢNG SINH VIÊN SAU KHI CẬP NHẬT NGÀY TỐT NGHIỆP ===

   student_id               name     class  course_id  score graduation_date
0           2       Tran Thi Lan   Kinh Te         34    9.2      2026-04-29
1           7      Bui Tien Dung   Kinh Te         34    9.2      2026-04-29
2           3       Pham Van Nam  Toan Tin         26    7.9      2026-06-29
3           9     Duong Huu Phuc   Kinh Te         26    7.2      2026-07-29
4          10       Cao Thi Hanh  May Tinh         26    7.0      2026-08-29
5           1  Nguyen Minh Hoang  May Tinh         12    6.7      2026-09-29