# tạo bảng

In [2]:
import pandas as pd
import numpy as np # Dùng để xử lý các giá trị trống (NaN)
data_student = {
    'student_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'name': [
        'Nguyen Minh Hoang', 'Tran Thi Lan', 'Pham Van Nam', 'Le Thanh Huyen',
        'Vu Quoc Anh', 'Dang Thuy Linh', 'Bui Tien Dung', 'Ho Ngoc Mai',
        'Duong Huu Phuc', 'Cao Thi Hanh'
    ],
    'class': [
        'May Tinh', 'Kinh Te', 'Toan Tin', 'Toan Tin', 'May Tinh',
        'May Tinh', 'Kinh Te', 'Toan Tin', 'Kinh Te', 'May Tinh'
    ],
    'course_id': [12, 34, None, 20, 24, 24, 34, 20, None, None],
    'score': [6.7, 9.2, 7.9, 7.2, 8.0, 5.5, 9.2, 8.8, 7.2, 7.0]
}

df_student = pd.DataFrame(data_student)
print("Bảng Student:")
display(df_student)

data_course = {
    'id': [12, 34, 26],
    'course_name': ['Giai tich', 'Thong ke', 'Tin hoc']
}

df_course = pd.DataFrame(data_course)
print("\nBảng Course:")
display(df_course)

Bảng Student:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin        NaN    7.9
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
4           5        Vu Quoc Anh  May Tinh       24.0    8.0
5           6     Dang Thuy Linh  May Tinh       24.0    5.5
6           7      Bui Tien Dung   Kinh Te       34.0    9.2
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9          10       Cao Thi Hanh  May Tinh        NaN    7.0

Bảng Course:

   id course_name
0  12   Giai tich
1  34    Thong ke
2  26     Tin hoc

# 1. kết nối bảng

In [3]:
# Tích Descartes (Cross Join)
cartesian = df_student.merge(df_course, how='cross')

# Inner Join
inner_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='inner')
inner_join
# Left Join
left_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='left')

# Right Join
right_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='right')

# Full Outer Join
outer_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='outer')

Sử dụng tích Decartes

In [20]:
cartesian = df_student.merge(df_course, how='cross')
cartesian

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin       12.0    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin       12.0    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin       12.0    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te       12.0    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te       12.0    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te       12.0    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh       12.0    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh       12.0    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh       12.0    7.0  26     Tin hoc

Sử dụng JOIN:

INNER JOIN

In [ ]:
inner_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='inner')
inner_join

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

 LEFT JOIN

In [9]:
left_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='left')
left_join

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

RIGHT JOIN

In [10]:
right_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='right')
right_join

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

FULL OUTER JOIN

In [12]:
outer_join = df_student.merge(df_course, left_on='course_id', right_on='id', how='outer')
outer_join

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

# 2. cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL,trong đó các giá trị được điền là những giá trị nằm trong bảng course và loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course. Sau đó cho biết:
a. Tổng số sinh viên, điểm trung bình của từng lớp.

b. Tổng số sinh viên, điểm trung bình của từng môn học.

c. Phân loại thi đua theo số điểm của từng môn học biết:

i. Điểm TB ≥ 9.0: Xuất sắc.

ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt.

iii. Điểm TB < 6.0: Kém.

cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL,
trong đó các giá trị được điền là những giá trị nằm trong bảng course và loại bỏ những
bản ghi tham gia những môn học không tồn tại bảng course

In [ ]:
valid_ids = [12, 34, 26] # Giải tích, Thống kê, Tin học
null_indices = df_student[df_student['course_id'].isna()].index

for i, idx in enumerate(null_indices):
    df_student.loc[idx, 'course_id'] = valid_ids[i % len(valid_ids)]

df_final = df_student[df_student['course_id'].isin(df_course['id'])].merge(df_course, left_on='course_id', right_on='id')
display(df_final)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           3       Pham Van Nam  Toan Tin       12.0    7.9  12   Giai tich
3           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
4           9     Duong Huu Phuc   Kinh Te       34.0    7.2  34    Thong ke
5          10       Cao Thi Hanh  May Tinh       26.0    7.0  26     Tin hoc

a. Tổng số sinh viên, điểm trung bình của từng lớp.

In [46]:

stats_class = df_final.groupby('class').agg(
    total_students=('student_id', 'count'),
    avg_score=('score', 'mean')
).reset_index()

stats_class['avg_score'] = stats_class['avg_score'].round(2)

print("Tổng số sinh viên và điểm trung bình của từng lớp:")
display(stats_class)

Tổng số sinh viên và điểm trung bình của từng lớp:

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

b. Tổng số sinh viên, điểm trung bình của từng môn học.

In [47]:

stats_course = df_final.groupby('course_name').agg(
    total_students=('student_id', 'count'),
    avg_score=('score', 'mean')
).reset_index()


stats_course['avg_score'] = stats_course['avg_score'].round(2)

print("Tổng số sinh viên và điểm trung bình của từng môn học:")
display(stats_course)

Tổng số sinh viên và điểm trung bình của từng môn học:

  course_name  total_students  avg_score
0   Giai tich               2       7.30
1    Thong ke               3       8.53
2     Tin hoc               1       7.00

c.Phân loại thi đua theo số điểm của từng môn học

In [48]:
# 1. Định nghĩa hàm phân loại thi đua
def phan_loai_thi_dua(score):
    if score >= 9.0:
        return 'Xuat sac'
    elif 6.0 <= score <= 8.9:
        return 'Tot'
    else:
        return 'Kem'

# 2. Áp dụng hàm vào cột điểm trung bình (avg_score) của từng môn học
stats_course['Xep loai'] = stats_course['avg_score'].apply(phan_loai_thi_dua)

print("c. Phân loại thi đua theo số điểm của từng môn học:")
display(stats_course)

c. Phân loại thi đua theo số điểm của từng môn học:

  course_name  total_students  avg_score Xep loai
0   Giai tich               2       7.30      Tot
1    Thong ke               3       8.53      Tot
2     Tin hoc               1       7.00      Tot

# 3. xếp hạng sinh viên thông qua:

a. Điểm số.

b. Điểm số theo lớp học.

c. Điểm số theo mã môn học.

a. xếp hạng sinh viên qua Điểm số

In [ ]:
# 3a. Xếp hạng theo điểm số toàn bảng
df_final['rank_global'] = df_final['score'].rank(ascending=False, method='min')

print("=== XẾP HẠNG THEO ĐIỂM SỐ TOÀN BẢNG ===")
display(df_final[['name', 'score', 'rank_global']].sort_values('rank_global'))

top_3_global = df_final.nsmallest(3, 'rank_global').sort_values('rank_global')
bottom_3_global = df_final.nlargest(3, 'rank_global').sort_values('rank_global', ascending=False)

print("Top 3 sinh viên cao nhất:")
display(top_3_global[['name', 'score', 'rank_global']])
print("Top 3 sinh viên thấp nhất:")
display(bottom_3_global[['name', 'score', 'rank_global']])

=== XẾP HẠNG THEO ĐIỂM SỐ TOÀN BẢNG ===

                name  score  rank_global
1       Tran Thi Lan    9.2          1.0
3      Bui Tien Dung    9.2          1.0
2       Pham Van Nam    7.9          3.0
4     Duong Huu Phuc    7.2          4.0
5       Cao Thi Hanh    7.0          5.0
0  Nguyen Minh Hoang    6.7          6.0

Top 3 sinh viên cao nhất:

            name  score  rank_global
1   Tran Thi Lan    9.2          1.0
3  Bui Tien Dung    9.2          1.0
2   Pham Van Nam    7.9          3.0

Top 3 sinh viên thấp nhất:

                name  score  rank_global
0  Nguyen Minh Hoang    6.7          6.0
5       Cao Thi Hanh    7.0          5.0
4     Duong Huu Phuc    7.2          4.0

b. Xếp hạng theo điểm số trong từng lớp học

In [ ]:
# 3b. Xếp hạng theo điểm số trong từng lớp học
df_final['rank_by_class'] = df_final.groupby('class')['score'].rank(ascending=False, method='min')

print("=== XẾP HẠNG THEO LỚP HỌC ===")
display(df_final[['name', 'class', 'score', 'rank_by_class']].sort_values(['class', 'rank_by_class']))

print("Top 3 cao nhất theo từng lớp:")
display(df_final[df_final['rank_by_class'] <= 3].sort_values(['class', 'rank_by_class']))

print("Top 3 thấp nhất theo từng lớp:")
display(df_final.groupby('class').apply(lambda x: x.nsmallest(3, 'score')).reset_index(drop=True))

=== XẾP HẠNG THEO LỚP HỌC ===

                name     class  score  rank_by_class
1       Tran Thi Lan   Kinh Te    9.2            1.0
3      Bui Tien Dung   Kinh Te    9.2            1.0
4     Duong Huu Phuc   Kinh Te    7.2            3.0
5       Cao Thi Hanh  May Tinh    7.0            1.0
0  Nguyen Minh Hoang  May Tinh    6.7            2.0
2       Pham Van Nam  Toan Tin    7.9            1.0

Top 3 cao nhất theo từng lớp:

,student_id,name,class,course_id,score,id,course_name,rank_global,rank_by_class,rank_by_course
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
3,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
4,9,Duong Huu Phuc,Kinh Te,34.0,7.2,34,Thong ke,4.0,3.0,3.0
5,10,Cao Thi Hanh,May Tinh,26.0,7.0,26,Tin hoc,5.0,1.0,1.0
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,6.0,2.0,2.0
2,3,Pham Van Nam,Toan Tin,12.0,7.9,12,Giai tich,3.0,1.0,1.0

Top 3 thấp nhất theo từng lớp:

C:\Users\lenovo thinkpad\AppData\Local\Temp\ipykernel_3192\3510626725.py:13: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  display(df_final.groupby('class').apply(lambda x: x.nsmallest(3, 'score')).reset_index(drop=True))

,student_id,name,class,course_id,score,id,course_name,rank_global,rank_by_class,rank_by_course
0,9,Duong Huu Phuc,Kinh Te,34.0,7.2,34,Thong ke,4.0,3.0,3.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
2,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
3,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,6.0,2.0,2.0
4,10,Cao Thi Hanh,May Tinh,26.0,7.0,26,Tin hoc,5.0,1.0,1.0
5,3,Pham Van Nam,Toan Tin,12.0,7.9,12,Giai tich,3.0,1.0,1.0

c. Xếp hạng theo điểm số trong từng môn học

In [61]:
# 3c. Xếp hạng theo điểm số trong từng môn học
df_final['rank_by_course'] = df_final.groupby('course_name')['score'].rank(ascending=False, method='min')

print("=== XẾP HẠNG THEO MÔN HỌC ===")
display(df_final[['name', 'course_name', 'score', 'rank_by_course']].sort_values(['course_name', 'rank_by_course']))

print("Top 3 sinh viên cao nhất theo môn học:")
display(df_final[df_final['rank_by_course'] <= 3].sort_values(['course_name', 'rank_by_course']))

print("Top 3 sinh viên thấp nhất theo môn học:")
display(df_final.groupby('course_name').apply(lambda x: x.nsmallest(3, 'score')).reset_index(drop=True))

=== XẾP HẠNG THEO MÔN HỌC ===

                name course_name  score  rank_by_course
2       Pham Van Nam   Giai tich    7.9             1.0
0  Nguyen Minh Hoang   Giai tich    6.7             2.0
1       Tran Thi Lan    Thong ke    9.2             1.0
3      Bui Tien Dung    Thong ke    9.2             1.0
4     Duong Huu Phuc    Thong ke    7.2             3.0
5       Cao Thi Hanh     Tin hoc    7.0             1.0

Top 3 sinh viên cao nhất theo môn học:

,student_id,name,class,course_id,score,id,course_name,rank_global,rank_by_class,rank_by_course
2,3,Pham Van Nam,Toan Tin,12.0,7.9,12,Giai tich,3.0,1.0,1.0
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,6.0,2.0,2.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
3,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
4,9,Duong Huu Phuc,Kinh Te,34.0,7.2,34,Thong ke,4.0,3.0,3.0
5,10,Cao Thi Hanh,May Tinh,26.0,7.0,26,Tin hoc,5.0,1.0,1.0

Top 3 sinh viên thấp nhất theo môn học:

C:\Users\lenovo thinkpad\AppData\Local\Temp\ipykernel_3192\3021304926.py:11: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  display(df_final.groupby('course_name').apply(lambda x: x.nsmallest(3, 'score')).reset_index(drop=True))

,student_id,name,class,course_id,score,id,course_name,rank_global,rank_by_class,rank_by_course
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,6.0,2.0,2.0
1,3,Pham Van Nam,Toan Tin,12.0,7.9,12,Giai tich,3.0,1.0,1.0
2,9,Duong Huu Phuc,Kinh Te,34.0,7.2,34,Thong ke,4.0,3.0,3.0
3,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
4,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.0,1.0,1.0
5,10,Cao Thi Hanh,May Tinh,26.0,7.0,26,Tin hoc,5.0,1.0,1.0

# 4. bổ sung thêm một trường graduation_date

In [ ]:
from datetime import datetime, timedelta

current_now = datetime.now()

df_final['graduation_date'] = df_final['rank_global'].apply(
    lambda x: current_now + timedelta(days=int(x))
)

df_final['graduation_date_display'] = df_final['graduation_date'].dt.strftime('%d/%m/%Y %H:%M')

print("4. Bảng danh sách sinh viên với Ngày tốt nghiệp dự kiến:")
display(df_final[['student_id', 'name', 'score', 'rank_global', 'graduation_date_display']])

4. Bảng danh sách sinh viên với Ngày tốt nghiệp dự kiến:

   student_id               name  score  rank_global graduation_date_display
0           1  Nguyen Minh Hoang    6.7          6.0        07/04/2026 21:23
1           2       Tran Thi Lan    9.2          1.0        02/04/2026 21:23
2           3       Pham Van Nam    7.9          3.0        04/04/2026 21:23
3           7      Bui Tien Dung    9.2          1.0        02/04/2026 21:23
4           9     Duong Huu Phuc    7.2          4.0        05/04/2026 21:23
5          10       Cao Thi Hanh    7.0          5.0        06/04/2026 21:23