1. Hãy kết nối hai bảng trên theo những cách sau: 

Sử dụng tích Decartes. 

Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.

In [1]:
import sqlite3

conn = sqlite3.connect(":memory:")
cursor = conn.cursor()
cursor.execute("""
CREATE TABLE student (
    student_id INTEGER,
    name TEXT,
    class TEXT,
    course_id INTEGER,
    score REAL
)
""")


cursor.execute("""
CREATE TABLE course (
    id INTEGER,
    course_name TEXT
)
""")

In [2]:
import pandas as pd
from IPython.display import display

def show(cursor):
    """Hien thi ket qua query dang bang dep voi pandas."""
    rows = cursor.fetchall()
    if not rows:
        print("(Khong co du lieu)")
        return
    cols = [desc[0] for desc in cursor.description]
    df = pd.DataFrame(rows, columns=cols)
    display(df)

In [3]:
# Insert student
students = [
(1,"Nguyen Minh Hoang","May Tinh",12,6.7),
(2,"Tran Thi Lan","Kinh Te",34,9.2),
(3,"Pham Van Nam","Toan Tin",None,7.9),
(4,"Le Thanh Huyen","Toan Tin",20,7.2),
(5,"Vu Quoc Anh","May Tinh",24,8.0),
(6,"Dang Thuy Linh","May Tinh",24,5.5),
(7,"Bui Tien Dung","Kinh Te",34,9.2),
(8,"Ho Ngoc Mai","Toan Tin",20,8.8),
(9,"Duong Huu Phuc","Kinh Te",None,7.2),
(10,"Cao Thi Hanh","May Tinh",None,7.0)
]

cursor.executemany("INSERT INTO student VALUES (?,?,?,?,?)", students)

# Insert course
courses = [
(12,"Giai tich"),
(34,"Thong ke"),
(26,"Tin hoc")
]

cursor.executemany("INSERT INTO course VALUES (?,?)", courses)

conn.commit()

In [4]:
# nối 2 bảng theo tích decarts
cursor.execute("""
SELECT * 
FROM student, course
""")
show(cursor)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

In [5]:
# INNER JOIN
cursor.execute("""
SELECT *
FROM student s
INNER JOIN course c
ON s.course_id = c.id
""")
show(cursor)

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2  34    Thong ke

In [6]:
# LEFT JOIN
cursor.execute("""
SELECT *
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
""")
show(cursor)

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN        None

In [7]:
# Right JOIN
cursor.execute("""
SELECT * 
FROM course c
RIGHT JOIN student s
ON s.course_id = c.id
""")
show(cursor)

     id course_name  student_id               name     class  course_id  score
0  12.0   Giai tich           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1  34.0    Thong ke           2       Tran Thi Lan   Kinh Te       34.0    9.2
2  34.0    Thong ke           7      Bui Tien Dung   Kinh Te       34.0    9.2
3   NaN        None           3       Pham Van Nam  Toan Tin        NaN    7.9
4   NaN        None           4     Le Thanh Huyen  Toan Tin       20.0    7.2
5   NaN        None           5        Vu Quoc Anh  May Tinh       24.0    8.0
6   NaN        None           6     Dang Thuy Linh  May Tinh       24.0    5.5
7   NaN        None           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
8   NaN        None           9     Duong Huu Phuc   Kinh Te        NaN    7.2
9   NaN        None          10       Cao Thi Hanh  May Tinh        NaN    7.0

In [8]:
# FULL OUTER JOIN
cursor.execute("""
SELECT *
FROM student s
LEFT JOIN course c ON s.course_id = c.id

UNION

SELECT *
FROM course c
LEFT JOIN student s ON s.course_id = c.id
""")

show(cursor)

,student_id,name,class,course_id,score,id,course_name
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,12.0,Giai tich
1,2,Tran Thi Lan,Kinh Te,34,9.2,34.0,Thong ke
2,3,Pham Van Nam,Toan Tin,None,7.9,NaN,None
3,4,Le Thanh Huyen,Toan Tin,20,7.2,NaN,None
4,5,Vu Quoc Anh,May Tinh,24,8.0,NaN,None
5,6,Dang Thuy Linh,May Tinh,24,5.5,NaN,None
6,7,Bui Tien Dung,Kinh Te,34,9.2,34.0,Thong ke
7,8,Ho Ngoc Mai,Toan Tin,20,8.8,NaN,None
8,9,Duong Huu Phuc,Kinh Te,None,7.2,NaN,None
9,10,Cao Thi Hanh,May Tinh,None,7.0,NaN,None
10,12,Giai tich,1,Nguyen Minh Hoang,May Tinh,12.0,6.7
11,26,Tin hoc,None,None,None,NaN,None
12,34,Thong ke,2,Tran Thi Lan,Kinh Te,34.0,9.2
13,34,Thong ke,7,Bui Tien Dung,Kinh Te,34.0,9.2

2. Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL, 
trong đó các giá trị được điền là những giá trị nằm trong bảng course  và loại bỏ những 
bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết: 

a. Tổng số sinh viên, điểm trung bình của từng lớp. 

b. Tổng số sinh viên, điểm trung bình của từng môn học. 

c. Phân loại thi đua theo số điểm của từng môn học biết: 

   -i. Điểm TB ≥  9.0: Xuất sắc. 

   -ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt. 

   -iii. Điểm TB < 6.0: Kém.

In [9]:
cursor.execute("""
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
   OR course_id IS NULL
""")

In [10]:
cursor.execute("""
SELECT class,
       COUNT(*) AS total_students,
       AVG(score) AS avg_score
FROM student
GROUP BY class
""")
show(cursor)

      class  total_students  avg_score
0   Kinh Te               2        9.2
1  May Tinh               1        6.7

In [11]:
cursor.execute("""
SELECT c.course_name,
       COUNT(*) AS total_students,
       AVG(s.score) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""")
show(cursor)

  course_name  total_students  avg_score
0   Giai tich               1        6.7
1    Thong ke               2        9.2

In [12]:
cursor.execute("""
SELECT c.course_name,
       AVG(s.score) AS avg_score,
       CASE 
           WHEN AVG(s.score) >= 9 THEN 'Xuat sac'
           WHEN AVG(s.score) >= 6 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
""")
show(cursor)

  course_name  avg_score classification
0   Giai tich        6.7            Tot
1    Thong ke        9.2       Xuat sac

3. Hãy xếp hạng sinh viên thông qua: 

a. Điểm số. 

b. Điểm số theo lớp học. 

c. Điểm số theo mã môn học. 

và cho biết top 3 sinh viện đạt thứ hạng cao nhất, top 3 sinh viên đạt thứ hạng thấp nhất theo 
từng trường hợp trên.

In [13]:
# xếp hạng qua điểm số
cursor.execute("""
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_overall
FROM student
""")

In [14]:
cursor.execute("""
SELECT *,
       RANK() OVER (ORDER BY score DESC) AS rank_all
FROM student
""")
show(cursor)

   student_id               name     class  course_id  score  rank_all
0           2       Tran Thi Lan   Kinh Te         34    9.2         1
1           7      Bui Tien Dung   Kinh Te         34    9.2         1
2           1  Nguyen Minh Hoang  May Tinh         12    6.7         3

In [15]:
cursor.execute("""
SELECT *,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_class
FROM student
""")
show(cursor)

   student_id               name     class  course_id  score  rank_class
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           1  Nguyen Minh Hoang  May Tinh         12    6.7           1

In [16]:
cursor.execute("""
SELECT * FROM (
    SELECT *,
           RANK() OVER (ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
""")
print("top 3 sinh viên đạt thứ hạng thấp nhất theo điểm số")
show(cursor)

top 3 sinh viên đạt thứ hạng thấp nhất theo điểm số

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1           2       Tran Thi Lan   Kinh Te         34    9.2  2
2           7      Bui Tien Dung   Kinh Te         34    9.2  2

In [17]:
cursor.execute("""
SELECT *
FROM (
    SELECT *, RANK() OVER (ORDER BY score DESC) AS r
    FROM student
)
WHERE r <= 3
""")
show(cursor)

   student_id               name     class  course_id  score  r
0           2       Tran Thi Lan   Kinh Te         34    9.2  1
1           7      Bui Tien Dung   Kinh Te         34    9.2  1
2           1  Nguyen Minh Hoang  May Tinh         12    6.7  3

In [18]:
cursor.execute("""
SELECT *
FROM (
    SELECT *, RANK() OVER (ORDER BY score ASC) AS r
    FROM student
)
WHERE r <= 3
""")
show(cursor)

   student_id               name     class  course_id  score  r
0           1  Nguyen Minh Hoang  May Tinh         12    6.7  1
1           2       Tran Thi Lan   Kinh Te         34    9.2  2
2           7      Bui Tien Dung   Kinh Te         34    9.2  2

4. Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng 
student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được 
xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số.

In [19]:
cursor.execute("""
ALTER TABLE student ADD COLUMN graduation_date TEXT
""")

In [20]:
cursor.execute("""
UPDATE student
SET graduation_date = datetime('now', '+' || (
    SELECT r FROM (
        SELECT student_id,
               RANK() OVER (ORDER BY score DESC) AS r
        FROM student
    ) t
    WHERE t.student_id = student.student_id
) || ' days')
""")
conn.commit()
cursor.execute("""
SELECT * FROM student
""")
show(cursor)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-04-05 14:54:24
1,2,Tran Thi Lan,Kinh Te,34,9.2,2026-04-03 14:54:24
2,7,Bui Tien Dung,Kinh Te,34,9.2,2026-04-03 14:54:24

# kết luận/ câu trả lời về kết quả cuối cùng thu được.

- INNER JOIN chỉ giữ dữ liệu hợp lệ giữa 2 bảng

- LEFT JOIN giữ toàn bộ student, kể cả thiếu course

- Sau khi làm sạch, chỉ còn sinh viên học môn hợp lệ

- Có thể phân tích theo lớp, môn học dễ dàng bằng GROUP BY

- Ranking giúp xác định top sinh viên nhanh

- Có thể tạo dữ liệu mới (graduation_date) từ kết quả tính toán