# Load bảng data

In [ ]:
import sqlite3
import pandas as pd

# Tạo database
conn = sqlite3.connect(':memory:')

# Tạo bảng + insert data
conn.executescript("""
CREATE TABLE student (
    student_id INT,
    name TEXT,
    class TEXT,
    course_id INT,
    score FLOAT
);

CREATE TABLE course (
    id INT,
    course_name TEXT
);

INSERT INTO student VALUES
(1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
(2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
(3, 'Pham Van Nam', 'Toan Tin', NULL, 7.9),
(4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
(5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
(6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
(7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
(8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
(9, 'Duong Huu Phuc', 'Kinh Te', NULL, 7.2),
(10, 'Cao Thi Hanh', 'May Tinh', NULL, 7.0);

INSERT INTO course VALUES
(12, 'Giai tich'),
(34, 'Thong ke'),
(26, 'Tin hoc');
""")

## Câu 1

### 1.Tích Descartes (CROSS JOIN)

In [ ]:
query = """
SELECT *
FROM student
CROSS JOIN course
"""
pd.read_sql_query(query, conn)

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

### 2.INNER JOIN

In [ ]:
query = """
SELECT s.*, c.course_name
FROM student s
INNER JOIN course c
ON s.course_id = c.id
"""
pd.read_sql_query(query, conn)

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh         12    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te         34    9.2    Thong ke
2           7      Bui Tien Dung   Kinh Te         34    9.2    Thong ke

### 3.LEFT JOIN

In [ ]:
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id
"""
pd.read_sql_query(query, conn)

   student_id               name     class  course_id  score course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9        None
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2        None
4           5        Vu Quoc Anh  May Tinh       24.0    8.0        None
5           6     Dang Thuy Linh  May Tinh       24.0    5.5        None
6           7      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2        None
9          10       Cao Thi Hanh  May Tinh        NaN    7.0        None

### 4.RIGHT JOIN (SQLite không có → đảo bảng)

In [ ]:
query = """
SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
pd.read_sql_query(query, conn)

   student_id               name     class  course_id  score course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
3         NaN               None      None        NaN    NaN     Tin hoc

### 5.FULL OUTER JOIN (dùng UNION)

In [ ]:
query = """
SELECT s.*, c.course_name
FROM student s
LEFT JOIN course c
ON s.course_id = c.id

UNION

SELECT s.*, c.course_name
FROM course c
LEFT JOIN student s
ON s.course_id = c.id
"""
pd.read_sql_query(query, conn)

    student_id               name     class  course_id  score course_name
0          NaN               None      None        NaN    NaN     Tin hoc
1          1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7   Giai tich
2          2.0       Tran Thi Lan   Kinh Te       34.0    9.2    Thong ke
3          3.0       Pham Van Nam  Toan Tin        NaN    7.9        None
4          4.0     Le Thanh Huyen  Toan Tin       20.0    7.2        None
5          5.0        Vu Quoc Anh  May Tinh       24.0    8.0        None
6          6.0     Dang Thuy Linh  May Tinh       24.0    5.5        None
7          7.0      Bui Tien Dung   Kinh Te       34.0    9.2    Thong ke
8          8.0        Ho Ngoc Mai  Toan Tin       20.0    8.8        None
9          9.0     Duong Huu Phuc   Kinh Te        NaN    7.2        None
10        10.0       Cao Thi Hanh  May Tinh        NaN    7.0        None

## 📝 Nhận xét từng phép JOIN

### 🔹 1. CROSS JOIN
- Kết quả tạo ra tất cả các tổ hợp giữa bảng `student` và `course`.
- Số lượng bản ghi rất lớn (student × course).
- Không có điều kiện nối nên dữ liệu bị lặp nhiều.
- Ít dùng trong thực tế, chủ yếu dùng khi cần sinh tổ hợp dữ liệu.

---

### 🔹 2. INNER JOIN
- Chỉ giữ lại các bản ghi có liên kết hợp lệ giữa hai bảng.
- Các sinh viên không có `course_id` hoặc không khớp sẽ bị loại bỏ.
- Kết quả gọn, chính xác và có ý nghĩa nhất.
- Đây là phép JOIN được sử dụng phổ biến nhất.

---

### 🔹 3. LEFT JOIN
- Giữ toàn bộ dữ liệu từ bảng `student`.
- Những sinh viên không có môn học tương ứng sẽ có giá trị `NULL` ở cột `course_name`.
- Giúp phát hiện các dữ liệu bị thiếu liên kết.
- Phù hợp khi cần giữ đầy đủ danh sách sinh viên.

---

### 🔹 4. RIGHT JOIN (giả lập)
- Do SQLite không hỗ trợ RIGHT JOIN nên thực hiện bằng cách đảo bảng và dùng LEFT JOIN.
- Giữ toàn bộ dữ liệu từ bảng `course`.
- Các môn học không có sinh viên vẫn xuất hiện trong kết quả.
- Cách làm đúng và phù hợp với SQLite.

---

### 🔹 5. FULL OUTER JOIN (dùng UNION)
- Kết hợp toàn bộ dữ liệu từ cả hai bảng.
- Bao gồm:
  - Sinh viên không có môn học
  - Môn học không có sinh viên
- Sử dụng UNION của hai LEFT JOIN để mô phỏng.
- Cho cái nhìn đầy đủ và tổng quát nhất về dữ liệu.

## Câu 2

### 1.Cập nhật course_id + loại bỏ dữ liệu sai

In [ ]:
query = """
UPDATE student
SET course_id = 26
WHERE course_id IS NULL
"""
conn.execute(query)
conn.commit()

In [ ]:
query = """
DELETE FROM student
WHERE course_id NOT IN (SELECT id FROM course)
"""
conn.execute(query)
conn.commit()

#### 🔹Nhận xét Bài 2.1: Làm sạch dữ liệu

- Cập nhật course_id hợp lệ từ bảng course.
- Loại bỏ các bản ghi không tồn tại môn học.
- 👉 Dữ liệu sau xử lý trở nên chính xác và đồng nhất hơn.

### 2a. Tổng số sinh viên & điểm TB theo từng lớp

In [ ]:
query = """
SELECT class,
       COUNT(*) AS total_students,
       ROUND(AVG(score), 2) AS avg_score
FROM student
GROUP BY class
"""
pd.read_sql_query(query, conn)

      class  total_students  avg_score
0   Kinh Te               3       8.53
1  May Tinh               2       6.85
2  Toan Tin               1       7.90

#### 🔹Nhận xét Bài 2.2a: Thống kê theo lớp

- Cho biết số lượng sinh viên từng lớp.
- Tính điểm trung bình của từng lớp.
- 👉 Lớp có điểm cao → học tốt, lớp điểm thấp → cần cải thiện.

### 2b.Tổng số sinh viên & điểm TB theo từng môn

In [ ]:
query = """
SELECT c.course_name,
       COUNT(s.student_id) AS total_students,
       ROUND(AVG(s.score), 2) AS avg_score
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
pd.read_sql_query(query, conn)

  course_name  total_students  avg_score
0   Giai tich               1       6.70
1    Thong ke               2       9.20
2     Tin hoc               3       7.37

#### 🔹Nhận xét Bài 2.2b: Thống kê theo môn học

- Cho biết số sinh viên mỗi môn.
- Tính điểm trung bình từng môn.
- 👉 Giúp đánh giá độ khó và mức độ quan tâm của môn học.

### 2c.Phân loại theo điểm trung bình môn

In [ ]:
query = """
SELECT c.course_name,
       ROUND(AVG(s.score), 2) AS avg_score,
       CASE
           WHEN AVG(s.score) >= 9.0 THEN 'Xuat sac'
           WHEN AVG(s.score) BETWEEN 6.0 AND 8.9 THEN 'Tot'
           ELSE 'Kem'
       END AS classification
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY c.course_name
"""
pd.read_sql_query(query, conn)

  course_name  avg_score classification
0   Giai tich       6.70            Tot
1    Thong ke       9.20       Xuat sac
2     Tin hoc       7.37            Tot

#### 🔹Nhận xét Bài 2.2c: Phân loại theo điểm

- ≥ 9.0 → Xuất sắc
- 6.0 – 8.9 → Tốt
- < 6.0 → Kém

- 👉 Giúp đánh giá tổng quan chất lượng học tập.

#### 🔹 Kết luận Bài 2

- Dữ liệu sau khi làm sạch có độ tin cậy cao hơn.
- Các thống kê giúp hiểu rõ:
  - Chất lượng học tập
  - Sự phân bố sinh viên
- 👉 Đây là bước chuyển từ dữ liệu thô → thông tin có giá trị.

## Câu 3

### 3a.Xếp hạng theo điểm toàn bộ sinh viên

In [ ]:
query = """
SELECT student_id, name, class, course_id, score,
       RANK() OVER (ORDER BY score DESC) AS rank_score
FROM student
"""
pd.read_sql_query(query, conn)

   student_id               name     class  course_id  score  rank_score
0           2       Tran Thi Lan   Kinh Te         34    9.2           1
1           7      Bui Tien Dung   Kinh Te         34    9.2           1
2           3       Pham Van Nam  Toan Tin         26    7.9           3
3           9     Duong Huu Phuc   Kinh Te         26    7.2           4
4          10       Cao Thi Hanh  May Tinh         26    7.0           5
5           1  Nguyen Minh Hoang  May Tinh         12    6.7           6

#### ==> Top 3 sinh viên đạt điểm cao nhất

In [ ]:
query = """
SELECT *
FROM (
    SELECT student_id, name, class, course_id, score,
           RANK() OVER (ORDER BY score DESC) AS rnk
    FROM student
)
WHERE rnk <= 3
"""
pd.read_sql_query(query, conn)

   student_id           name     class  course_id  score  rnk
0           2   Tran Thi Lan   Kinh Te         34    9.2    1
1           7  Bui Tien Dung   Kinh Te         34    9.2    1
2           3   Pham Van Nam  Toan Tin         26    7.9    3

#### ==> Top 3 sinh viên đạt điểm thấp nhất

In [ ]:
query = """
SELECT *
FROM (
    SELECT student_id, name, class, course_id, score,
           RANK() OVER (ORDER BY score ASC) AS rnk
    FROM student
)
WHERE rnk <= 3
"""
pd.read_sql_query(query, conn)

   student_id               name     class  course_id  score  rnk
0           1  Nguyen Minh Hoang  May Tinh         12    6.7    1
1          10       Cao Thi Hanh  May Tinh         26    7.0    2
2           9     Duong Huu Phuc   Kinh Te         26    7.2    3

### 3b.Xếp hạng theo điểm trong từng lớp

In [ ]:
query = """
SELECT student_id, name, class, score,
       RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rank_in_class
FROM student
"""
pd.read_sql_query(query, conn)

   student_id               name     class  score  rank_in_class
0           2       Tran Thi Lan   Kinh Te    9.2              1
1           7      Bui Tien Dung   Kinh Te    9.2              1
2           9     Duong Huu Phuc   Kinh Te    7.2              3
3          10       Cao Thi Hanh  May Tinh    7.0              1
4           1  Nguyen Minh Hoang  May Tinh    6.7              2
5           3       Pham Van Nam  Toan Tin    7.9              1

#### ==> Top 3 mỗi lớp

In [ ]:
query = """
SELECT *
FROM (
    SELECT student_id, name, class, score,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) AS rnk
    FROM student
)
WHERE rnk <= 3
"""
pd.read_sql_query(query, conn)

   student_id               name     class  score  rnk
0           2       Tran Thi Lan   Kinh Te    9.2    1
1           7      Bui Tien Dung   Kinh Te    9.2    1
2           9     Duong Huu Phuc   Kinh Te    7.2    3
3          10       Cao Thi Hanh  May Tinh    7.0    1
4           1  Nguyen Minh Hoang  May Tinh    6.7    2
5           3       Pham Van Nam  Toan Tin    7.9    1

#### ==> Bottom 3 mỗi lớp

In [ ]:
query = """
SELECT *
FROM (
    SELECT student_id, name, class, score,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) AS rnk
    FROM student
)
WHERE rnk <= 3
"""
pd.read_sql_query(query, conn)

   student_id               name     class  score  rnk
0           9     Duong Huu Phuc   Kinh Te    7.2    1
1           2       Tran Thi Lan   Kinh Te    9.2    2
2           7      Bui Tien Dung   Kinh Te    9.2    2
3           1  Nguyen Minh Hoang  May Tinh    6.7    1
4          10       Cao Thi Hanh  May Tinh    7.0    2
5           3       Pham Van Nam  Toan Tin    7.9    1

### 3c.Xếp hạng theo môn học (course_id)

In [ ]:
query = """
SELECT student_id, name, course_id, score,
       RANK() OVER (PARTITION BY course_id ORDER BY score DESC) AS rank_in_course
FROM student
"""
pd.read_sql_query(query, conn)

   student_id               name  course_id  score  rank_in_course
0           1  Nguyen Minh Hoang         12    6.7               1
1           3       Pham Van Nam         26    7.9               1
2           9     Duong Huu Phuc         26    7.2               2
3          10       Cao Thi Hanh         26    7.0               3
4           2       Tran Thi Lan         34    9.2               1
5           7      Bui Tien Dung         34    9.2               1

#### ==> Top 3 mỗi môn

In [ ]:
query = """
SELECT *
FROM (
    SELECT s.student_id, s.name, c.course_name, s.score,
           RANK() OVER (PARTITION BY s.course_id ORDER BY s.score DESC) AS rnk
    FROM student s
    JOIN course c ON s.course_id = c.id
)
WHERE rnk <= 3
"""
pd.read_sql_query(query, conn)

   student_id               name course_name  score  rnk
0           1  Nguyen Minh Hoang   Giai tich    6.7    1
1           3       Pham Van Nam     Tin hoc    7.9    1
2           9     Duong Huu Phuc     Tin hoc    7.2    2
3          10       Cao Thi Hanh     Tin hoc    7.0    3
4           2       Tran Thi Lan    Thong ke    9.2    1
5           7      Bui Tien Dung    Thong ke    9.2    1

#### Bottom 3 mỗi môn

In [ ]:
query = """
SELECT *
FROM (
    SELECT s.student_id, s.name, c.course_name, s.score,
           RANK() OVER (PARTITION BY s.course_id ORDER BY s.score ASC) AS rnk
    FROM student s
    JOIN course c ON s.course_id = c.id
)
WHERE rnk <= 3
"""
pd.read_sql_query(query, conn)

   student_id               name course_name  score  rnk
0           1  Nguyen Minh Hoang   Giai tich    6.7    1
1          10       Cao Thi Hanh     Tin hoc    7.0    1
2           9     Duong Huu Phuc     Tin hoc    7.2    2
3           3       Pham Van Nam     Tin hoc    7.9    3
4           2       Tran Thi Lan    Thong ke    9.2    1
5           7      Bui Tien Dung    Thong ke    9.2    1

## 🔹Nhận xét Bài 3: Xếp hạng sinh viên

- Việc xếp hạng sinh viên được thực hiện dựa trên nhiều tiêu chí khác nhau bao gồm:
  - Điểm tổng
  - Điểm theo lớp
  - Điểm theo từng môn học

- Trước hết, khi xếp hạng theo **điểm tổng**, kết quả phản ánh năng lực học tập tổng thể của từng sinh viên trong toàn hệ thống.
  - Những sinh viên đứng đầu là những người có thành tích học tập xuất sắc và ổn định.
  - Ngược lại, những sinh viên ở cuối bảng xếp hạng là những người có kết quả học tập thấp, cần được hỗ trợ hoặc cải thiện phương pháp học tập.
  - Đây là cơ sở quan trọng để nhà trường đưa ra các quyết định như khen thưởng hoặc cảnh báo học vụ.

- Khi xếp hạng theo **lớp học**, việc đánh giá trở nên công bằng hơn do chỉ so sánh trong phạm vi từng lớp.
  - Điều này giúp loại bỏ sự chênh lệch giữa các lớp (ví dụ: lớp có đầu vào khác nhau).
  - Đồng thời, có thể xác định được sinh viên nổi bật trong từng lớp, phục vụ cho việc đánh giá nội bộ.

- Khi xếp hạng theo **môn học**, kết quả cho thấy năng lực của sinh viên theo từng lĩnh vực cụ thể.
  - Một sinh viên có thể có thứ hạng cao ở môn này nhưng thấp ở môn khác.
  - Điều này phản ánh sự khác biệt về năng lực và sở trường của từng cá nhân.
  - 👉 Từ đó có thể định hướng chuyên ngành hoặc cải thiện kỹ năng còn yếu.

- Việc xác định **top 3 sinh viên cao nhất và thấp nhất** trong từng trường hợp mang lại giá trị thực tiễn cao:
  - Top 3 cao nhất:
    - Đại diện cho nhóm sinh viên xuất sắc.
    - Có thể được xem xét để khen thưởng hoặc phát triển nâng cao.
  - Top 3 thấp nhất:
    - Là nhóm có nguy cơ học kém hoặc không đạt yêu cầu.
    - Cần có biện pháp hỗ trợ kịp thời như phụ đạo hoặc tư vấn học tập.

- Tổng thể, việc xếp hạng không chỉ dừng lại ở việc so sánh điểm số mà còn:
  - Cung cấp góc nhìn đa chiều về năng lực sinh viên.
  - Hỗ trợ quá trình quản lý và ra quyết định trong giáo dục.
  - Là bước nâng cao từ thống kê dữ liệu sang đánh giá và phân tích chuyên sâu.

---

### ✅ Kết luận Bài 3

- Xếp hạng sinh viên là một công cụ quan trọng trong phân tích dữ liệu giáo dục.
- Giúp đánh giá:
  - Năng lực tổng thể
  - Năng lực theo lớp
  - Năng lực theo từng môn học
- 👉 Có thể ứng dụng trực tiếp vào:
  - Khen thưởng
  - Cảnh báo học vụ
  - Định hướng học tập và phát triển sinh viên

## Câu 4

In [ ]:
query = """
ALTER TABLE student
ADD COLUMN graduation_date DATETIME
"""
conn.execute(query)
conn.commit()

In [ ]:
query = """
UPDATE student
SET graduation_date = datetime('now', '+' || rnk || ' days')
FROM (
    SELECT student_id,
           RANK() OVER (ORDER BY score DESC) AS rnk
    FROM student
) AS ranked
WHERE student.student_id = ranked.student_id
"""
conn.execute(query)
conn.commit()

In [ ]:
query = "SELECT * FROM student"
pd.read_sql_query(query, conn)

,student_id,name,class,course_id,score,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12,6.7,2026-04-08 03:46:50
1,2,Tran Thi Lan,Kinh Te,34,9.2,2026-04-03 03:46:50
2,3,Pham Van Nam,Toan Tin,26,7.9,2026-04-05 03:46:50
3,7,Bui Tien Dung,Kinh Te,34,9.2,2026-04-03 03:46:50
4,9,Duong Huu Phuc,Kinh Te,26,7.2,2026-04-06 03:46:50
5,10,Cao Thi Hanh,May Tinh,26,7.0,2026-04-07 03:46:50

# 🔹Nhận xét Bài 4: Kết luận

- Việc bổ sung trường `graduation_date` không chỉ đơn thuần là thêm một thuộc tính mới mà còn giúp dữ liệu trở nên có ý nghĩa thực tế hơn khi gắn với yếu tố thời gian.

- Thông qua việc tính toán thời gian tốt nghiệp dựa trên:
  - Thời điểm hiện tại
  - Thứ hạng hoặc kết quả học tập của sinh viên

→ Dữ liệu đã được mở rộng từ dạng tĩnh (chỉ lưu trữ thông tin) sang dạng động (có khả năng mô phỏng và dự đoán).

- Cụ thể:
  - Sinh viên có kết quả học tập tốt (thứ hạng cao) sẽ có xu hướng tốt nghiệp sớm hơn.
  - Sinh viên có kết quả thấp hơn sẽ có thời gian tốt nghiệp muộn hơn.
  - Điều này phản ánh một mô hình logic gần với thực tế trong quản lý đào tạo.

- Ngoài ra, việc bổ sung trường thời gian còn mang lại nhiều giá trị:
  - Hỗ trợ theo dõi tiến độ học tập của sinh viên.
  - Giúp dự đoán kế hoạch tốt nghiệp.
  - Tăng khả năng phân tích và khai thác dữ liệu trong tương lai.

- 👉 Tổng thể, bài toán đã được nâng cấp từ mức:
  - **Phân tích dữ liệu** → sang **mô phỏng và hỗ trợ ra quyết định**.

---

### ✅ Kết luận tổng quát Bài 4

- Việc mở rộng dữ liệu với yếu tố thời gian giúp:
  - Tăng tính thực tiễn
  - Tăng khả năng ứng dụng của hệ thống

- 👉 Đây là bước quan trọng trong việc:
  - Xây dựng hệ thống quản lý dữ liệu hoàn chỉnh
  - Ứng dụng SQL không chỉ để truy vấn mà còn để phục vụ phân tích và dự đoán

## 🔎 Nhận xét chung

- Toàn bộ bài tập đã thực hiện đầy đủ quy trình xử lý và phân tích dữ liệu trong SQL, bao gồm:
  - Kết nối dữ liệu từ nhiều bảng (JOIN)
  - Làm sạch và chuẩn hóa dữ liệu
  - Thực hiện các phép thống kê (COUNT, AVG, GROUP BY)
  - Xếp hạng dữ liệu (RANK)
  - Mở rộng dữ liệu với yếu tố thời gian

- Qua từng bước, có thể thấy rõ rằng:
  - Dữ liệu ban đầu nếu chưa được xử lý sẽ chứa nhiều sai lệch (thiếu, sai khóa, không đồng nhất).
  - Sau khi làm sạch, dữ liệu trở nên đáng tin cậy và có thể sử dụng cho phân tích.

- Việc sử dụng các phép JOIN khác nhau cho thấy:
  - INNER JOIN phù hợp cho phân tích chính xác.
  - LEFT/RIGHT/FULL JOIN phù hợp cho kiểm tra và phát hiện dữ liệu thiếu.
  - Việc lựa chọn sai loại JOIN có thể dẫn đến kết quả sai lệch nghiêm trọng.

- Các phép thống kê và phân loại dữ liệu giúp:
  - Chuyển dữ liệu thô thành thông tin có ý nghĩa.
  - Đánh giá được chất lượng học tập theo nhiều khía cạnh (lớp, môn học, cá nhân).

- Phần xếp hạng sinh viên thể hiện bước nâng cao:
  - Không chỉ dừng ở mô tả dữ liệu mà còn đi vào đánh giá và so sánh.
  - Giúp xác định rõ các nhóm đối tượng (giỏi, trung bình, yếu).

- Việc bổ sung trường thời gian (`graduation_date`) cho thấy:
  - Khả năng mở rộng dữ liệu từ phân tích sang mô phỏng và dự đoán.
  - Dữ liệu không còn tĩnh mà có thể phục vụ cho các bài toán quản lý thực tế.

---

## 💡 Những điểm rút ra quan trọng

### 1. Dữ liệu cần được làm sạch trước khi phân tích
- Nếu dữ liệu sai hoặc thiếu:
  - Kết quả thống kê sẽ không chính xác.
- 👉 Làm sạch dữ liệu là bước bắt buộc trong mọi bài toán dữ liệu.

---

### 2. Lựa chọn JOIN ảnh hưởng trực tiếp đến kết quả
- INNER JOIN → dùng để phân tích chính
- OUTER JOIN → dùng để kiểm tra dữ liệu
- 👉 Chọn sai JOIN → sai toàn bộ kết quả

---

### 3. SQL không chỉ để truy vấn mà còn để phân tích dữ liệu
- Có thể thực hiện:
  - Thống kê
  - Phân loại
  - Xếp hạng
- 👉 SQL là công cụ mạnh trong Data Analysis.

---

### 4. Xếp hạng giúp chuyển từ “thống kê” sang “đánh giá”
- Không chỉ biết dữ liệu là gì
- Mà còn biết:
  - Ai tốt hơn
  - Ai cần cải thiện
- 👉 Có giá trị thực tế trong quản lý.

---

### 5. Dữ liệu có thể mở rộng để phục vụ dự đoán
- Thêm yếu tố thời gian giúp:
  - Mô phỏng tiến độ học tập
  - Dự đoán kết quả trong tương lai
- 👉 Đây là bước tiến từ phân tích → ứng dụng thực tế.

---

## 🚀 Kết luận cuối cùng

- Bài tập đã thể hiện đầy đủ quy trình xử lý dữ liệu từ cơ bản đến nâng cao.
- Cho thấy rõ vai trò của SQL trong:
  - Quản lý dữ liệu
  - Phân tích dữ liệu
  - Hỗ trợ ra quyết định

- 👉 Qua bài này có thể khẳng định:
  - SQL không chỉ là công cụ truy vấn mà còn là nền tảng quan trọng trong khoa học dữ liệu (Data Analysis).
  - Việc hiểu đúng và sử dụng đúng các thao tác trong SQL sẽ quyết định chất lượng của toàn bộ quá trình phân tích.

- 👉 Đây là nền tảng quan trọng để phát triển các hệ thống:
  - Quản lý sinh viên
  - Phân tích học tập
  - Hỗ trợ ra quyết định trong giáo dục