In [9]:
import pandas as pd

# bảng student
student = pd.DataFrame({
    "student_id": [1,2,3,4,5,6,7,8,9,10],
    "name": [
        "Nguyen Minh Hoang","Tran Thi Lan","Pham Van Nam","Le Thanh Huyen",
        "Vu Quoc Anh","Dang Thuy Linh","Bui Tien Dung","Ho Ngoc Mai",
        "Duong Huu Phuc","Cao Thi Hanh"
    ],
    "class": [
        "May Tinh","Kinh Te","Toan Tin","Toan Tin",
        "May Tinh","May Tinh","Kinh Te","Toan Tin",
        "Kinh Te","May Tinh"
    ],
    "course_id": [12,34,None,20,24,24,34,20,None,None],
    "score": [6.7,9.2,7.9,7.2,8.0,5.5,9.2,8.8,7.2,7.0]
})

# bảng course
course = pd.DataFrame({
    "id": [12,34,26],
    "course_name": ["Giai tich","Thong ke","Tin hoc"]
})

student, course

(   student_id               name     class  course_id  score
 0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
 1           2       Tran Thi Lan   Kinh Te       34.0    9.2
 2           3       Pham Van Nam  Toan Tin        NaN    7.9
 3           4     Le Thanh Huyen  Toan Tin       20.0    7.2
 4           5        Vu Quoc Anh  May Tinh       24.0    8.0
 5           6     Dang Thuy Linh  May Tinh       24.0    5.5
 6           7      Bui Tien Dung   Kinh Te       34.0    9.2
 7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8
 8           9     Duong Huu Phuc   Kinh Te        NaN    7.2
 9          10       Cao Thi Hanh  May Tinh        NaN    7.0,
    id course_name
 0  12   Giai tich
 1  34    Thong ke
 2  26     Tin hoc)

In [10]:
cross_join = student.merge(course, how='cross')
cross_join.head()

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3           2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke

In [11]:
inner_join = student.merge(course, left_on="course_id", right_on="id", how="inner")
inner_join

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

In [12]:
left_join = student.merge(course, left_on="course_id", right_on="id", how="left")
left_join

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

In [13]:
right_join = student.merge(course, left_on="course_id", right_on="id", how="right")
right_join

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

In [14]:
full_join = student.merge(course, left_on="course_id", right_on="id", how="outer")
full_join

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
2,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
3,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
4,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc
6,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
7,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
8,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
9,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
10,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN

In [15]:
clean = student.merge(course, left_on="course_id", right_on="id", how="inner")
clean

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

In [16]:
class_stats = clean.groupby("class").agg(
    so_sinh_vien=("student_id","count"),
    diem_tb=("score","mean")
)
class_stats

          so_sinh_vien  diem_tb
class
Kinh Te              2      9.2
May Tinh             1      6.7

In [17]:
course_stats = clean.groupby("course_name").agg(
    so_sinh_vien=("student_id","count"),
    diem_tb=("score","mean")
)
course_stats

             so_sinh_vien  diem_tb
course_name
Giai tich               1      6.7
Thong ke                2      9.2

In [18]:
def xep_loai(score):
    if score >= 9:
        return "Xuat sac"
    elif score >= 6:
        return "Tot"
    else:
        return "Kem"

course_stats["xep_loai"] = course_stats["diem_tb"].apply(xep_loai)
course_stats

             so_sinh_vien  diem_tb  xep_loai
course_name
Giai tich               1      6.7       Tot
Thong ke                2      9.2  Xuat sac

In [19]:
clean["rank_all"] = clean["score"].rank(ascending=False)
clean.sort_values("rank_all")

,student_id,name,class,course_id,score,id,course_name,rank_all
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.5
2,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.5
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,3.0

In [20]:
clean["rank_class"] = clean.groupby("class")["score"].rank(ascending=False)
clean.sort_values(["class","rank_class"])

,student_id,name,class,course_id,score,id,course_name,rank_all,rank_class
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.5,1.5
2,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.5,1.5
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,3.0,1.0

In [21]:
clean["rank_course"] = clean.groupby("course_name")["score"].rank(ascending=False)
clean.sort_values(["course_name","rank_course"])

,student_id,name,class,course_id,score,id,course_name,rank_all,rank_class,rank_course
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,3.0,1.0,1.0
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.5,1.5,1.5
2,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.5,1.5,1.5

In [22]:
top3 = clean.nlargest(3, "score")
bottom3 = clean.nsmallest(3, "score")

top3, bottom3

(   student_id               name     class  course_id  score  id course_name  \
 1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
 2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
 0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich

    rank_all  rank_class  rank_course
 1       1.5         1.5          1.5
 2       1.5         1.5          1.5
 0       3.0         1.0          1.0  ,
    student_id               name     class  course_id  score  id course_name  \
 0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
 1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
 2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

    rank_all  rank_class  rank_course
 0       3.0         1.0          1.0
 1       1.5         1.5          1.5
 2       1.5         1.5          1.5  )

In [23]:
from datetime import datetime, timedelta

now = datetime.now()

def grad_date(rank):
    return now + timedelta(days=int(rank*30))

clean["graduation_date"] = clean["rank_all"].apply(grad_date)
clean

,student_id,name,class,course_id,score,id,course_name,rank_all,rank_class,rank_course,graduation_date
0,1,Nguyen Minh Hoang,May Tinh,12.0,6.7,12,Giai tich,3.0,1.0,1.0,2026-07-01 18:49:52.686787
1,2,Tran Thi Lan,Kinh Te,34.0,9.2,34,Thong ke,1.5,1.5,1.5,2026-05-17 18:49:52.686787
2,7,Bui Tien Dung,Kinh Te,34.0,9.2,34,Thong ke,1.5,1.5,1.5,2026-05-17 18:49:52.686787