In [12]:
import pandas as pd
import sqlite3
conn = sqlite3.connect(':memory:')

# 1. Khởi tạo dữ liệu cho bảng student
student_data = [
    (1, 'Nguyen Minh Hoang', 'May Tinh', 12, 6.7),
    (2, 'Tran Thi Lan', 'Kinh Te', 34, 9.2),
    (3, 'Pham Van Nam', 'Toan Tin', None, 7.9),
    (4, 'Le Thanh Huyen', 'Toan Tin', 20, 7.2),
    (5, 'Vu Quoc Anh', 'May Tinh', 24, 8.0),
    (6, 'Dang Thuy Linh', 'May Tinh', 24, 5.5),
    (7, 'Bui Tien Dung', 'Kinh Te', 34, 9.2),
    (8, 'Ho Ngoc Mai', 'Toan Tin', 20, 8.8),
    (9, 'Duong Huu Phuc', 'Kinh Te', None, 7.2),
    (10, 'Cao Thi Hanh', 'May Tinh', None, 7.0)
]
student_df = pd.DataFrame(student_data, columns=['student_id', 'name', 'class', 'course_id', 'score'])
student_df.to_sql('student', conn, index=False)

# 2. Khởi tạo dữ liệu cho bảng course
course_data = [
    (12, 'Giai tich'),
    (34, 'Thong ke'),
    (26, 'Tin hoc')
]
course_df = pd.DataFrame(course_data, columns=['id', 'course_name'])
course_df.to_sql('course', conn, index=False)

print("Đã khởi tạo xong bảng 'student' và 'course'.")

Đã khởi tạo xong bảng 'student' và 'course'.

## 1. Hãy kết nối hai bảng trên theo những cách sau:

- Sử dụng tích Decartes.

In [13]:
query_cross = """
SELECT * FROM student 
CROSS JOIN course;
"""
df_cross = pd.read_sql_query(query_cross, conn)
display(df_cross)
print(f"Kết luận: Tích Descartes tạo ra {len(df_cross)} bản ghi (10 sinh viên x 3 môn học).")

    student_id               name     class  course_id  score  id course_name
0            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  34    Thong ke
2            1  Nguyen Minh Hoang  May Tinh       12.0    6.7  26     Tin hoc
3            2       Tran Thi Lan   Kinh Te       34.0    9.2  12   Giai tich
4            2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
5            2       Tran Thi Lan   Kinh Te       34.0    9.2  26     Tin hoc
6            3       Pham Van Nam  Toan Tin        NaN    7.9  12   Giai tich
7            3       Pham Van Nam  Toan Tin        NaN    7.9  34    Thong ke
8            3       Pham Van Nam  Toan Tin        NaN    7.9  26     Tin hoc
9            4     Le Thanh Huyen  Toan Tin       20.0    7.2  12   Giai tich
10           4     Le Thanh Huyen  Toan Tin       20.0    7.2  34    Thong ke
11           4     Le Thanh Huyen  Toan Tin       20.0    7.2  26     Tin hoc
12           5        Vu Quoc Anh  May Tinh       24.0    8.0  12   Giai tich
13           5        Vu Quoc Anh  May Tinh       24.0    8.0  34    Thong ke
14           5        Vu Quoc Anh  May Tinh       24.0    8.0  26     Tin hoc
15           6     Dang Thuy Linh  May Tinh       24.0    5.5  12   Giai tich
16           6     Dang Thuy Linh  May Tinh       24.0    5.5  34    Thong ke
17           6     Dang Thuy Linh  May Tinh       24.0    5.5  26     Tin hoc
18           7      Bui Tien Dung   Kinh Te       34.0    9.2  12   Giai tich
19           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
20           7      Bui Tien Dung   Kinh Te       34.0    9.2  26     Tin hoc
21           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  12   Giai tich
22           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  34    Thong ke
23           8        Ho Ngoc Mai  Toan Tin       20.0    8.8  26     Tin hoc
24           9     Duong Huu Phuc   Kinh Te        NaN    7.2  12   Giai tich
25           9     Duong Huu Phuc   Kinh Te        NaN    7.2  34    Thong ke
26           9     Duong Huu Phuc   Kinh Te        NaN    7.2  26     Tin hoc
27          10       Cao Thi Hanh  May Tinh        NaN    7.0  12   Giai tich
28          10       Cao Thi Hanh  May Tinh        NaN    7.0  34    Thong ke
29          10       Cao Thi Hanh  May Tinh        NaN    7.0  26     Tin hoc

Kết luận: Tích Descartes tạo ra 30 bản ghi (10 sinh viên x 3 môn học).

- Sử dụng JOIN: INNER JOIN, LEFT JOIN, RIGHT JOIN, FULL OUTER JOIN.

In [14]:
# INNER JOIN: 
query_inner = """
SELECT * FROM student 
INNER JOIN course ON student.course_id = course.id;
"""
df_inner = pd.read_sql_query(query_inner, conn)
print("\n--- INNER JOIN ---")
display(df_inner)

# LEFT JOIN:
query_left = """
SELECT * FROM student 
LEFT JOIN course ON student.course_id = course.id;
"""
df_left = pd.read_sql_query(query_left, conn)
print("\n--- LEFT JOIN ---")
display(df_left)

# RIGHT JOIN: 
query_right = """
SELECT * FROM student 
RIGHT JOIN course ON student.course_id = course.id;
"""
df_right = pd.read_sql_query(query_right, conn)
print("\n--- RIGHT JOIN ---")
display(df_right)

# FULL OUTER JOIN:  
query_full = """
SELECT * FROM student 
FULL OUTER JOIN course ON student.course_id = course.id;
"""
df_full = pd.read_sql_query(query_full, conn)
print("\n--- FULL OUTER JOIN ---")
display(df_full)

--- INNER JOIN ---

   student_id               name     class  course_id  score  id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2           7      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke

--- LEFT JOIN ---

   student_id               name     class  course_id  score    id course_name
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7  12.0   Giai tich
1           2       Tran Thi Lan   Kinh Te       34.0    9.2  34.0    Thong ke
2           3       Pham Van Nam  Toan Tin        NaN    7.9   NaN         NaN
3           4     Le Thanh Huyen  Toan Tin       20.0    7.2   NaN         NaN
4           5        Vu Quoc Anh  May Tinh       24.0    8.0   NaN         NaN
5           6     Dang Thuy Linh  May Tinh       24.0    5.5   NaN         NaN
6           7      Bui Tien Dung   Kinh Te       34.0    9.2  34.0    Thong ke
7           8        Ho Ngoc Mai  Toan Tin       20.0    8.8   NaN         NaN
8           9     Duong Huu Phuc   Kinh Te        NaN    7.2   NaN         NaN
9          10       Cao Thi Hanh  May Tinh        NaN    7.0   NaN         NaN

--- RIGHT JOIN ---

   student_id               name     class  course_id  score  id course_name
0         1.0  Nguyen Minh Hoang  May Tinh       12.0    6.7  12   Giai tich
1         2.0       Tran Thi Lan   Kinh Te       34.0    9.2  34    Thong ke
2         7.0      Bui Tien Dung   Kinh Te       34.0    9.2  34    Thong ke
3         NaN                NaN       NaN        NaN    NaN  26     Tin hoc

--- FULL OUTER JOIN ---

,student_id,name,class,course_id,score,id,course_name
0,1.0,Nguyen Minh Hoang,May Tinh,12.0,6.7,12.0,Giai tich
1,2.0,Tran Thi Lan,Kinh Te,34.0,9.2,34.0,Thong ke
2,3.0,Pham Van Nam,Toan Tin,NaN,7.9,NaN,NaN
3,4.0,Le Thanh Huyen,Toan Tin,20.0,7.2,NaN,NaN
4,5.0,Vu Quoc Anh,May Tinh,24.0,8.0,NaN,NaN
5,6.0,Dang Thuy Linh,May Tinh,24.0,5.5,NaN,NaN
6,7.0,Bui Tien Dung,Kinh Te,34.0,9.2,34.0,Thong ke
7,8.0,Ho Ngoc Mai,Toan Tin,20.0,8.8,NaN,NaN
8,9.0,Duong Huu Phuc,Kinh Te,NaN,7.2,NaN,NaN
9,10.0,Cao Thi Hanh,May Tinh,NaN,7.0,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,26.0,Tin hoc

#### 2. Hãy cập nhật những giá trị course_id còn thiếu trong bảng student bằng câu lệnh SQL,trong đó các giá trị được điền là những giá trị nằm trong bảng course  và loại bỏ những bản ghi tham gia những môn học không tồn tại bảng course. Sau đó hãy cho biết:

In [15]:
cursor = conn.cursor()
query_update = """
UPDATE student 
SET course_id = 26 
WHERE course_id IS NULL;
"""
cursor.execute(query_update)

# Loại bỏ những bản ghi có course_id không tồn tại trong bảng course
query_delete = """
DELETE FROM student 
WHERE course_id NOT IN (SELECT id FROM course);
"""
cursor.execute(query_delete)
conn.commit()

# Hiển thị lại bảng student để kiểm tra
df_student_updated = pd.read_sql_query("SELECT * FROM student", conn)
print("Bảng student sau khi được làm sạch:")
display(df_student_updated)
print("Kết luận: Các sinh viên thiếu course_id đã được gán mã 26. Các sinh viên có mã môn học 20 và 24 đã bị xóa.\n")

Bảng student sau khi được làm sạch:

   student_id               name     class  course_id  score
0           1  Nguyen Minh Hoang  May Tinh       12.0    6.7
1           2       Tran Thi Lan   Kinh Te       34.0    9.2
2           3       Pham Van Nam  Toan Tin       26.0    7.9
3           7      Bui Tien Dung   Kinh Te       34.0    9.2
4           9     Duong Huu Phuc   Kinh Te       26.0    7.2
5          10       Cao Thi Hanh  May Tinh       26.0    7.0

Kết luận: Các sinh viên thiếu course_id đã được gán mã 26. Các sinh viên có mã môn học 20 và 24 đã bị xóa.

a. Tổng số sinh viên, điểm trung bình của từng lớp.

In [16]:
query_2a = """
SELECT class, COUNT(student_id) AS tong_sinh_vien, ROUND(AVG(score), 2) AS diem_trung_binh
FROM student
GROUP BY class;
"""
df_2a = pd.read_sql_query(query_2a, conn)
print("\n--- 2a. Thống kê theo Lớp ---")
display(df_2a)

--- 2a. Thống kê theo Lớp ---

      class  tong_sinh_vien  diem_trung_binh
0   Kinh Te               3             8.53
1  May Tinh               2             6.85
2  Toan Tin               1             7.90

b. Tổng số sinh viên, điểm trung bình của từng môn học.

In [17]:
query_2b = """
SELECT c.course_name, s.course_id, COUNT(s.student_id) AS tong_sinh_vien, ROUND(AVG(s.score), 2) AS diem_trung_binh
FROM student s
JOIN course c ON s.course_id = c.id
GROUP BY s.course_id;
"""
df_2b = pd.read_sql_query(query_2b, conn)
print("\n--- 2b. Thống kê theo Môn học ---")
display(df_2b)

--- 2b. Thống kê theo Môn học ---

  course_name  course_id  tong_sinh_vien  diem_trung_binh
0   Giai tich       12.0               1             6.70
1     Tin hoc       26.0               3             7.37
2    Thong ke       34.0               2             9.20

c. Phân loại thi đua theo số điểm của từng môn học biết: 
- i. Điểm TB ≥  9.0: Xuất sắc. 
- ii. 6.0 ≤ Điểm TB ≤ 8.9: Tốt. 
- iii. Điểm TB < 6.0: Kém.

In [18]:
query_2c = """
SELECT student_id, name, course_id, score,
    CASE 
        WHEN score >= 9.0 THEN 'Xuất sắc'
        WHEN score >= 6.0 AND score <= 8.9 THEN 'Tốt'
        ELSE 'Kém'
    END AS phan_loai
FROM student;
"""
df_2c = pd.read_sql_query(query_2c, conn)
print("\n--- 2c. Phân loại thi đua ---")
display(df_2c)
print("Kết luận: Sinh viên Trần Thị Lan và Bùi Tiến Dũng đạt loại Xuất sắc do điểm >= 9.0, các sinh viên còn lại đạt loại Tốt. Không có sinh viên nào loại Kém (điểm < 6.0) trong danh sách hiện tại.")

--- 2c. Phân loại thi đua ---

   student_id               name  course_id  score phan_loai
0           1  Nguyen Minh Hoang       12.0    6.7       Tốt
1           2       Tran Thi Lan       34.0    9.2  Xuất sắc
2           3       Pham Van Nam       26.0    7.9       Tốt
3           7      Bui Tien Dung       34.0    9.2  Xuất sắc
4           9     Duong Huu Phuc       26.0    7.2       Tốt
5          10       Cao Thi Hanh       26.0    7.0       Tốt

Kết luận: Sinh viên Trần Thị Lan và Bùi Tiến Dũng đạt loại Xuất sắc do điểm >= 9.0, các sinh viên còn lại đạt loại Tốt. Không có sinh viên nào loại Kém (điểm < 6.0) trong danh sách hiện tại.

### 3. Hãy xếp hạng sinh viên thông qua: 
- a. Điểm số. 
- b. Điểm số theo lớp học. 
- c. Điểm số theo mã môn học. 

và cho biết top 3 sinh viện đạt thứ hạng cao nhất, top 3 sinh viên đạt thứ hạng thấp nhất theo 
từng trường hợp trên.

In [19]:
# --- 3a. Xếp hạng sinh viên qua ĐIỂM SỐ ---
print("3a. XẾP HẠNG THEO ĐIỂM SỐ")

# Bảng xếp hạng 
query_3a_rank = """
WITH RankedStudents AS (
    SELECT student_id, name, class, course_id, score,
           RANK() OVER (ORDER BY score DESC) as hang_cao_xuong_thap,
           RANK() OVER (ORDER BY score ASC) as hang_thap_len_cao
    FROM student
)
SELECT * FROM RankedStudents;
"""
df_3a_rank = pd.read_sql_query(query_3a_rank, conn)
display(df_3a_rank[['student_id', 'name', 'score', 'hang_cao_xuong_thap']])

# Top 3 cao nhất 
df_3a_top3 = df_3a_rank[df_3a_rank['hang_cao_xuong_thap'] <= 3]
print("\nTop 3 sinh viên điểm CAO NHẤT:")
display(df_3a_top3[['student_id', 'name', 'score', 'hang_cao_xuong_thap']])

# Top 3 thấp nhất 
df_3a_bot3 = df_3a_rank[df_3a_rank['hang_thap_len_cao'] <= 3]
print("\nTop 3 sinh viên điểm THẤP NHẤT:")
display(df_3a_bot3[['student_id', 'name', 'score', 'hang_thap_len_cao']])

3a. XẾP HẠNG THEO ĐIỂM SỐ

   student_id               name  score  hang_cao_xuong_thap
0           2       Tran Thi Lan    9.2                    1
1           7      Bui Tien Dung    9.2                    1
2           3       Pham Van Nam    7.9                    3
3           9     Duong Huu Phuc    7.2                    4
4          10       Cao Thi Hanh    7.0                    5
5           1  Nguyen Minh Hoang    6.7                    6

Top 3 sinh viên điểm CAO NHẤT:

   student_id           name  score  hang_cao_xuong_thap
0           2   Tran Thi Lan    9.2                    1
1           7  Bui Tien Dung    9.2                    1
2           3   Pham Van Nam    7.9                    3

Top 3 sinh viên điểm THẤP NHẤT:

   student_id               name  score  hang_thap_len_cao
3           9     Duong Huu Phuc    7.2                  3
4          10       Cao Thi Hanh    7.0                  2
5           1  Nguyen Minh Hoang    6.7                  1

In [20]:
# --- 3b. Xếp hạng sinh viên theo LỚP HỌC ---
print("3b. XẾP HẠNG THEO LỚP HỌC")

query_3b_rank = """
WITH RankedByClass AS (
    SELECT student_id, name, class, course_id, score,
           RANK() OVER (PARTITION BY class ORDER BY score DESC) as hang_cao_xuong_thap,
           RANK() OVER (PARTITION BY class ORDER BY score ASC) as hang_thap_len_cao
    FROM student
)
SELECT * FROM RankedByClass;
"""
df_3b_rank = pd.read_sql_query(query_3b_rank, conn)
display(df_3b_rank[['student_id', 'name', 'class', 'score', 'hang_cao_xuong_thap']])

# Top 3 cao nhất theo lớp
df_3b_top3 = df_3b_rank[df_3b_rank['hang_cao_xuong_thap'] <= 3]
print("\nTop 3 sinh viên điểm CAO NHẤT trong từng lớp:")
display(df_3b_top3[['student_id', 'name', 'class', 'score', 'hang_cao_xuong_thap']])

# Top 3 thấp nhất theo lớp
df_3b_bot3 = df_3b_rank[df_3b_rank['hang_thap_len_cao'] <= 3]
print("\nTop 3 sinh viên điểm THẤP NHẤT trong từng lớp:")
display(df_3b_bot3[['student_id', 'name', 'class', 'score', 'hang_thap_len_cao']])

3b. XẾP HẠNG THEO LỚP HỌC

   student_id               name     class  score  hang_cao_xuong_thap
0           2       Tran Thi Lan   Kinh Te    9.2                    1
1           7      Bui Tien Dung   Kinh Te    9.2                    1
2           9     Duong Huu Phuc   Kinh Te    7.2                    3
3          10       Cao Thi Hanh  May Tinh    7.0                    1
4           1  Nguyen Minh Hoang  May Tinh    6.7                    2
5           3       Pham Van Nam  Toan Tin    7.9                    1

Top 3 sinh viên điểm CAO NHẤT trong từng lớp:

   student_id               name     class  score  hang_cao_xuong_thap
0           2       Tran Thi Lan   Kinh Te    9.2                    1
1           7      Bui Tien Dung   Kinh Te    9.2                    1
2           9     Duong Huu Phuc   Kinh Te    7.2                    3
3          10       Cao Thi Hanh  May Tinh    7.0                    1
4           1  Nguyen Minh Hoang  May Tinh    6.7                    2
5           3       Pham Van Nam  Toan Tin    7.9                    1

Top 3 sinh viên điểm THẤP NHẤT trong từng lớp:

   student_id               name     class  score  hang_thap_len_cao
0           2       Tran Thi Lan   Kinh Te    9.2                  2
1           7      Bui Tien Dung   Kinh Te    9.2                  2
2           9     Duong Huu Phuc   Kinh Te    7.2                  1
3          10       Cao Thi Hanh  May Tinh    7.0                  2
4           1  Nguyen Minh Hoang  May Tinh    6.7                  1
5           3       Pham Van Nam  Toan Tin    7.9                  1

In [21]:
# --- 3c. Xếp hạng sinh viên theo MÃ MÔN HỌC ---
print("3c. XẾP HẠNG THEO MÃ MÔN HỌC")

query_3c_rank = """
WITH RankedByCourse AS (
    SELECT student_id, name, class, course_id, score,
           RANK() OVER (PARTITION BY course_id ORDER BY score DESC) as hang_cao_xuong_thap,
           RANK() OVER (PARTITION BY course_id ORDER BY score ASC) as hang_thap_len_cao
    FROM student
)
SELECT * FROM RankedByCourse;
"""
df_3c_rank = pd.read_sql_query(query_3c_rank, conn)
display(df_3c_rank[['student_id', 'name', 'course_id', 'score', 'hang_cao_xuong_thap']])

# Top 3 cao nhất theo môn
df_3c_top3 = df_3c_rank[df_3c_rank['hang_cao_xuong_thap'] <= 3]
print("\nTop 3 sinh viên điểm CAO NHẤT trong từng môn học:")
display(df_3c_top3[['student_id', 'name', 'course_id', 'score', 'hang_cao_xuong_thap']])

# Top 3 thấp nhất theo môn
df_3c_bot3 = df_3c_rank[df_3c_rank['hang_thap_len_cao'] <= 3]
print("\nTop 3 sinh viên điểm THẤP NHẤT trong từng môn học:")
display(df_3c_bot3[['student_id', 'name', 'course_id', 'score', 'hang_thap_len_cao']])

3c. XẾP HẠNG THEO MÃ MÔN HỌC

   student_id               name  course_id  score  hang_cao_xuong_thap
0           1  Nguyen Minh Hoang       12.0    6.7                    1
1           3       Pham Van Nam       26.0    7.9                    1
2           9     Duong Huu Phuc       26.0    7.2                    2
3          10       Cao Thi Hanh       26.0    7.0                    3
4           2       Tran Thi Lan       34.0    9.2                    1
5           7      Bui Tien Dung       34.0    9.2                    1

Top 3 sinh viên điểm CAO NHẤT trong từng môn học:

   student_id               name  course_id  score  hang_cao_xuong_thap
0           1  Nguyen Minh Hoang       12.0    6.7                    1
1           3       Pham Van Nam       26.0    7.9                    1
2           9     Duong Huu Phuc       26.0    7.2                    2
3          10       Cao Thi Hanh       26.0    7.0                    3
4           2       Tran Thi Lan       34.0    9.2                    1
5           7      Bui Tien Dung       34.0    9.2                    1

Top 3 sinh viên điểm THẤP NHẤT trong từng môn học:

   student_id               name  course_id  score  hang_thap_len_cao
0           1  Nguyen Minh Hoang       12.0    6.7                  1
1           3       Pham Van Nam       26.0    7.9                  3
2           9     Duong Huu Phuc       26.0    7.2                  2
3          10       Cao Thi Hanh       26.0    7.0                  1
4           2       Tran Thi Lan       34.0    9.2                  1
5           7      Bui Tien Dung       34.0    9.2                  1

#### 4. Hãy bổ sung thêm một trường graduation_date có kiểu dữ liệu là DATETIME vào bảng student để xác định thời gian tốt nghiệp của từng bạn, trong đó thời gian tốt nghiệp được xác định bởi thời gian hiện tại cộng với số hạng tương ứng của bạn đó tính theo điểm số.

In [ ]:
# --- 4. Bổ sung trường graduation_date và cập nhật thời gian tốt nghiệp ---
print("4. BỔ SUNG TRƯỜNG GRADUATION_DATE")

cursor = conn.cursor()
try:
    cursor.execute("ALTER TABLE student ADD COLUMN graduation_date DATETIME;")
except sqlite3.OperationalError:
    pass 
query_update_date = """
WITH Ranked AS (
    SELECT student_id, DENSE_RANK() OVER (ORDER BY score DESC) as thu_hang
    FROM student
)
UPDATE student
SET graduation_date = datetime('now', 'localtime', '+' || (SELECT thu_hang FROM Ranked WHERE Ranked.student_id = student.student_id) || ' days');
"""
cursor.execute(query_update_date)
conn.commit()
query_final = """
SELECT student_id, name, score, 
       DENSE_RANK() OVER (ORDER BY score DESC) as thu_hang,
       graduation_date 
FROM student 
ORDER BY score DESC;
"""
df_final = pd.read_sql_query(query_final, conn)
display(df_final)

4. BỔ SUNG TRƯỜNG GRADUATION_DATE

   student_id               name  score  thu_hang      graduation_date
0           2       Tran Thi Lan    9.2         1  2026-04-03 22:04:43
1           7      Bui Tien Dung    9.2         1  2026-04-03 22:04:43
2           3       Pham Van Nam    7.9         2  2026-04-04 22:04:43
3           9     Duong Huu Phuc    7.2         3  2026-04-05 22:04:43
4          10       Cao Thi Hanh    7.0         4  2026-04-06 22:04:43
5           1  Nguyen Minh Hoang    6.7         5  2026-04-07 22:04:43